
SUBROUTINE CPG_PT_ULP_EXPL (YDMODEL, YDGEOMETRY, YDCPG_SL1, YDVARS, YGFL, KSTART, &
                          & KPROF, LDGET, PGFLPT, PGFLT1, PGFL)

! -----------------------------------------------------------------------------
!     --------------------------------------------
!**** *CPG_PT_ULP_EXPL*  physics tendencies written to or extracted from GFLPT
!     --------------------------------------------

!     Purpose.
!     --------
!       Copy the physics tendencies calculated (for ex in predictor)
!       to GFLPT to be retrieved and used during corrector
!       Designed for unlagged physics packages (LAGPHY=F).
!       May be used for non advected GFL too.

!       This routine is called for lpc_full=true only.

!**   Interface.
!     ----------
!        CALL CPG_PT_ULP_EXPL(...)

!     Input arguments
!     ------------------
!       KSTART  : start of horizontal loop
!       KPROF   : end of horizontal loop
!       LDGET   : T = get tendencies from buffers.
!                 F = save tendencies in buffers.
!       KFLDN,KFLDX: for second dimension of PTENDEXT.

!     Input or Output according to LDGET
!     ----------------------------------
!       PTEND[X]: tendency of X variable from phy (advected variables).
!       PGFLPT  : buffer for tendency of GFL variable from phy.
!       PGFLT1  : tendency of X variable from phy (not advected variables).
!       PGFL    : GFL variables.
!       PGMV    : upper air GMV variables at time t.
!       PGMVS   : surface GMV variables at time t.

!     Implicit arguments
!     --------------------

!     Author.
!     -------
!      Martina Tudor + Karim Yessad
!      Original : Jan 2011 (from CPG_PT)

!     Modifications.
!     --------------
! -----------------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE YOM_YGFL     , ONLY : TYPE_GFLD
USE YOMCT0       , ONLY : LNHDYN
USE FIELD_VARIABLES_MOD     , ONLY : FIELD_VARIABLES
USE CPG_TYPE_MOD            , ONLY : CPG_SL1_TYPE
USE TYPE_MODEL              , ONLY : MODEL
USE MF_PHYS_NEXT_STATE_TYPE_MOD &
                            , ONLY : MF_PHYS_NEXT_STATE_TYPE

! -----------------------------------------------------------------------------

IMPLICIT NONE

TYPE(MODEL)             ,INTENT(INOUT)  :: YDMODEL
TYPE(GEOMETRY)          ,INTENT(IN)     :: YDGEOMETRY
TYPE(CPG_SL1_TYPE)      ,INTENT(INOUT)  :: YDCPG_SL1
TYPE(FIELD_VARIABLES)   ,INTENT(INOUT)  :: YDVARS
TYPE(TYPE_GFLD)         ,INTENT(IN)    :: YGFL
INTEGER(KIND=JPIM)      ,INTENT(IN)    :: KSTART
INTEGER(KIND=JPIM)      ,INTENT(IN)    :: KPROF
LOGICAL                 ,INTENT(IN)    :: LDGET
REAL(KIND=JPRB)         ,INTENT(INOUT) :: PGFLPT(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIMPT)
REAL(KIND=JPRB)         ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM1)
REAL(KIND=JPRB)         ,INTENT(IN)    :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YGFL%NDIM)
! -----------------------------------------------------------------------------

#include "cp_ptrslb1.intfb.h"

TYPE (MF_PHYS_NEXT_STATE_TYPE) :: YLMF_PHYS_NEXT_STATE

REAL(KIND=JPRB), POINTER :: ZTENDGFL (:,:)

INTEGER(KIND=JPIM) :: JGFL,IPT
INTEGER(KIND=JPIM) :: ISLB1GFL9,ISLB1T9,ISLB1V9,ISLB1U9,ISLB1VD9

REAL(KIND=JPRB) :: ZHOOK_HANDLE

! -----------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CPG_PT_ULP_EXPL',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV)
ASSOCIATE(NUMFLDS=>YGFL%NUMFLDS, YCOMP=>YGFL%YCOMP, YCPF=>YGFL%YCPF,   NFLEVG=>YDDIMV%NFLEVG)
! -----------------------------------------------------------------------------

CALL YLMF_PHYS_NEXT_STATE%INIT (YDCPG_SL1, YDGEOMETRY, YDVARS, YDMODEL)

CALL CP_PTRSLB1(YDMODEL%YRML_DYN%YRDYN, YDMODEL%YRML_DYN%YRPTRSLB1, &
              & ISLB1U9, ISLB1V9, ISLB1T9, ISLB1VD9, ISLB1GFL9)

ZTENDGFL (1:,0:) => YDCPG_SL1%ZVIEW(:, ISLB1GFL9:)

!*       1.  PREDICTOR FOR LPC_FULL.
!        ---------------------------

IF (.NOT.LDGET) THEN

  ! * GMV:
  YDVARS%CUPT%T9(KSTART:KPROF,1:NFLEVG)=YLMF_PHYS_NEXT_STATE%U(KSTART:KPROF,1:NFLEVG)
  YDVARS%CVPT%T9(KSTART:KPROF,1:NFLEVG)=YLMF_PHYS_NEXT_STATE%V(KSTART:KPROF,1:NFLEVG)
  YDVARS%CTPT%T9(KSTART:KPROF,1:NFLEVG)=YLMF_PHYS_NEXT_STATE%T(KSTART:KPROF,1:NFLEVG)
  IF (LNHDYN) THEN
    YDVARS%CSVDPT%T9(KSTART:KPROF,1:NFLEVG)=YLMF_PHYS_NEXT_STATE%SVD(KSTART:KPROF,1:NFLEVG)
  ENDIF

  ! * GMVS:
  YDVARS%CSPPT%T9(KSTART:KPROF)=YDCPG_SL1%SP9%P(KSTART:KPROF)

  ! * GFL:
  IF (YGFL%YQ%LT1 .AND. YGFL%YQ%LPT) THEN
    IF (YGFL%YQ%LADV) THEN
      IPT=YGFL%YQ%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MPPT) = YDCPG_SL1%Q%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MPPT) = YDVARS%Q%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YI%LT1 .AND. YGFL%YI%LPT) THEN
    IF (YGFL%YI%LADV) THEN
      IPT=YGFL%YI%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YI%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YI%MPPT) = YDCPG_SL1%I%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YI%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YI%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YI%MPPT) = YDVARS%I%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YL%LT1 .AND. YGFL%YL%LPT) THEN
    IF (YGFL%YL%LADV) THEN
      IPT=YGFL%YL%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YL%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YL%MPPT) = YDCPG_SL1%L%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YL%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YL%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YL%MPPT) = YDVARS%L%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YLCONV%LT1 .AND. YGFL%YLCONV%LPT) THEN
    IF (YGFL%YLCONV%LADV) THEN
      IPT=YGFL%YLCONV%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MPPT) = YDCPG_SL1%LCONV%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MPPT) = YDVARS%LCONV%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YICONV%LT1 .AND. YGFL%YICONV%LPT) THEN
    IF (YGFL%YICONV%LADV) THEN
      IPT=YGFL%YICONV%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MPPT) = YDCPG_SL1%ICONV%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MPPT) = YDVARS%ICONV%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YRCONV%LT1 .AND. YGFL%YRCONV%LPT) THEN
    IF (YGFL%YRCONV%LADV) THEN
      IPT=YGFL%YRCONV%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MPPT) = YDCPG_SL1%RCONV%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MPPT) = YDVARS%RCONV%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YSCONV%LT1 .AND. YGFL%YSCONV%LPT) THEN
    IF (YGFL%YSCONV%LADV) THEN
      IPT=YGFL%YSCONV%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MPPT) = YDCPG_SL1%SCONV%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MPPT) = YDVARS%SCONV%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YIRAD%LT1 .AND. YGFL%YIRAD%LPT) THEN
    IF (YGFL%YIRAD%LADV) THEN
      IPT=YGFL%YIRAD%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MPPT) = YDCPG_SL1%IRAD%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MPPT) = YDVARS%IRAD%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YLRAD%LT1 .AND. YGFL%YLRAD%LPT) THEN
    IF (YGFL%YLRAD%LADV) THEN
      IPT=YGFL%YLRAD%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MPPT) = YDCPG_SL1%LRAD%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MPPT) = YDVARS%LRAD%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YS%LT1 .AND. YGFL%YS%LPT) THEN
    IF (YGFL%YS%LADV) THEN
      IPT=YGFL%YS%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YS%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YS%MPPT) = YDCPG_SL1%S%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YS%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YS%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YS%MPPT) = YDVARS%S%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YR%LT1 .AND. YGFL%YR%LPT) THEN
    IF (YGFL%YR%LADV) THEN
      IPT=YGFL%YR%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YR%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YR%MPPT) = YDCPG_SL1%R%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YR%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YR%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YR%MPPT) = YDVARS%R%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YG%LT1 .AND. YGFL%YG%LPT) THEN
    IF (YGFL%YG%LADV) THEN
      IPT=YGFL%YG%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YG%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YG%MPPT) = YDCPG_SL1%G%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YG%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YG%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YG%MPPT) = YDVARS%G%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YH%LT1 .AND. YGFL%YH%LPT) THEN
    IF (YGFL%YH%LADV) THEN
      IPT=YGFL%YH%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YH%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YH%MPPT) = YDCPG_SL1%H%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YH%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YH%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YH%MPPT) = YDVARS%H%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YTKE%LT1 .AND. YGFL%YTKE%LPT) THEN
    IF (YGFL%YTKE%LADV) THEN
      IPT=YGFL%YTKE%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MPPT) = YDCPG_SL1%TKE%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MPPT) = YDVARS%TKE%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YTTE%LT1 .AND. YGFL%YTTE%LPT) THEN
    IF (YGFL%YTTE%LADV) THEN
      IPT=YGFL%YTTE%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MPPT) = YDCPG_SL1%TTE%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MPPT) = YDVARS%TTE%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YEFB1%LT1 .AND. YGFL%YEFB1%LPT) THEN
    IF (YGFL%YEFB1%LADV) THEN
      IPT=YGFL%YEFB1%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MPPT) = YDCPG_SL1%EFB1%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MPPT) = YDVARS%EFB1%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YEFB2%LT1 .AND. YGFL%YEFB2%LPT) THEN
    IF (YGFL%YEFB2%LADV) THEN
      IPT=YGFL%YEFB2%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MPPT) = YDCPG_SL1%EFB2%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MPPT) = YDVARS%EFB2%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YEFB3%LT1 .AND. YGFL%YEFB3%LPT) THEN
    IF (YGFL%YEFB3%LADV) THEN
      IPT=YGFL%YEFB3%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MPPT) = YDCPG_SL1%EFB3%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MPPT) = YDVARS%EFB3%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YA%LT1 .AND. YGFL%YA%LPT) THEN
    IF (YGFL%YA%LADV) THEN
      IPT=YGFL%YA%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YA%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YA%MPPT) = YDCPG_SL1%A%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YA%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YA%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YA%MPPT) = YDVARS%A%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YO3%LT1 .AND. YGFL%YO3%LPT) THEN
    IF (YGFL%YO3%LADV) THEN
      IPT=YGFL%YO3%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MPPT) = YDCPG_SL1%O3%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MPPT) = YDVARS%O3%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YSRC%LT1 .AND. YGFL%YSRC%LPT) THEN
    IF (YGFL%YSRC%LADV) THEN
      IPT=YGFL%YSRC%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MPPT) = YDCPG_SL1%SRC%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MPPT) = YDVARS%SRC%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YMXL%LT1 .AND. YGFL%YMXL%LPT) THEN
    IF (YGFL%YMXL%LADV) THEN
      IPT=YGFL%YMXL%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MPPT) = YDCPG_SL1%MXL%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MPPT) = YDVARS%MXL%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YSHTUR%LT1 .AND. YGFL%YSHTUR%LPT) THEN
    IF (YGFL%YSHTUR%LADV) THEN
      IPT=YGFL%YSHTUR%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MPPT) = YDCPG_SL1%SHTUR%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MPPT) = YDVARS%SHTUR%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YFQTUR%LT1 .AND. YGFL%YFQTUR%LPT) THEN
    IF (YGFL%YFQTUR%LADV) THEN
      IPT=YGFL%YFQTUR%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MPPT) = YDCPG_SL1%FQTUR%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MPPT) = YDVARS%FQTUR%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YFSTUR%LT1 .AND. YGFL%YFSTUR%LPT) THEN
    IF (YGFL%YFSTUR%LADV) THEN
      IPT=YGFL%YFSTUR%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MPPT) = YDCPG_SL1%FSTUR%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MPPT) = YDVARS%FSTUR%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YCPF%LT1 .AND. YGFL%YCPF%LPT) THEN
    IF (YGFL%YCPF%LADV) THEN
      IPT=YGFL%YCPF%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MPPT) = YDCPG_SL1%CPF%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MPPT) = YDVARS%CPF%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YSPF%LT1 .AND. YGFL%YSPF%LPT) THEN
    IF (YGFL%YSPF%LADV) THEN
      IPT=YGFL%YSPF%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MPPT) = YDCPG_SL1%SPF%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MPPT) = YDVARS%SPF%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YCVGQ%LT1 .AND. YGFL%YCVGQ%LPT) THEN
    IF (YGFL%YCVGQ%LADV) THEN
      IPT=YGFL%YCVGQ%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MPPT) = YDCPG_SL1%CVGQ%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MPPT) = YDVARS%CVGQ%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YQVA%LT1 .AND. YGFL%YQVA%LPT) THEN
    IF (YGFL%YQVA%LADV) THEN
      IPT=YGFL%YQVA%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MPPT) = YDCPG_SL1%QVA%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MPPT) = YDVARS%QVA%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%GHG)
    IF (YGFL%YGHG(JGFL)%LT1 .AND. YGFL%YGHG(JGFL)%LPT) THEN
      IF (YGFL%YGHG(JGFL)%LADV) THEN
        IPT=YGFL%YGHG(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT) = YDCPG_SL1%GHG(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT) = YDVARS%GHG(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%CHEM)
    IF (YGFL%YCHEM(JGFL)%LT1 .AND. YGFL%YCHEM(JGFL)%LPT) THEN
      IF (YGFL%YCHEM(JGFL)%LADV) THEN
        IPT=YGFL%YCHEM(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT) = YDCPG_SL1%CHEM(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT) = YDVARS%CHEM(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERO)
    IF (YGFL%YAERO(JGFL)%LT1 .AND. YGFL%YAERO(JGFL)%LPT) THEN
      IF (YGFL%YAERO(JGFL)%LADV) THEN
        IPT=YGFL%YAERO(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT) = YDCPG_SL1%AERO(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT) = YDVARS%AERO(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  IF (YGFL%YLRCH4%LT1 .AND. YGFL%YLRCH4%LPT) THEN
    IF (YGFL%YLRCH4%LADV) THEN
      IPT=YGFL%YLRCH4%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MPPT) = YDCPG_SL1%LRCH4%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MPPT) = YDVARS%LRCH4%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%FORC)
    IF (YGFL%YFORC(JGFL)%LT1 .AND. YGFL%YFORC(JGFL)%LPT) THEN
      IF (YGFL%YFORC(JGFL)%LADV) THEN
        IPT=YGFL%YFORC(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT) = YDCPG_SL1%FORC(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT) = YDVARS%FORC(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%EZDIAG)
    IF (YGFL%YEZDIAG(JGFL)%LT1 .AND. YGFL%YEZDIAG(JGFL)%LPT) THEN
      IF (YGFL%YEZDIAG(JGFL)%LADV) THEN
        IPT=YGFL%YEZDIAG(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT) = YDCPG_SL1%EZDIAG(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT) = YDVARS%EZDIAG(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%ERA40)
    IF (YGFL%YERA40(JGFL)%LT1 .AND. YGFL%YERA40(JGFL)%LPT) THEN
      IF (YGFL%YERA40(JGFL)%LADV) THEN
        IPT=YGFL%YERA40(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT) = YDCPG_SL1%ERA40(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT) = YDVARS%ERA40(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%NOGW)
    IF (YGFL%YNOGW(JGFL)%LT1 .AND. YGFL%YNOGW(JGFL)%LPT) THEN
      IF (YGFL%YNOGW(JGFL)%LADV) THEN
        IPT=YGFL%YNOGW(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT) = YDCPG_SL1%NOGW(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT) = YDVARS%NOGW(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%EDRP)
    IF (YGFL%YEDRP(JGFL)%LT1 .AND. YGFL%YEDRP(JGFL)%LPT) THEN
      IF (YGFL%YEDRP(JGFL)%LADV) THEN
        IPT=YGFL%YEDRP(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT) = YDCPG_SL1%EDRP(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT) = YDVARS%EDRP(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%SLDIA)
    IF (YGFL%YSLDIA(JGFL)%LT1 .AND. YGFL%YSLDIA(JGFL)%LPT) THEN
      IF (YGFL%YSLDIA(JGFL)%LADV) THEN
        IPT=YGFL%YSLDIA(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT) = YDCPG_SL1%SLDIA(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT) = YDVARS%SLDIA(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERAOT)
    IF (YGFL%YAERAOT(JGFL)%LT1 .AND. YGFL%YAERAOT(JGFL)%LPT) THEN
      IF (YGFL%YAERAOT(JGFL)%LADV) THEN
        IPT=YGFL%YAERAOT(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT) = YDCPG_SL1%AERAOT(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT) = YDVARS%AERAOT(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERLISI)
    IF (YGFL%YAERLISI(JGFL)%LT1 .AND. YGFL%YAERLISI(JGFL)%LPT) THEN
      IF (YGFL%YAERLISI(JGFL)%LADV) THEN
        IPT=YGFL%YAERLISI(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT) = YDCPG_SL1%AERLISI(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT) = YDVARS%AERLISI(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AEROUT)
    IF (YGFL%YAEROUT(JGFL)%LT1 .AND. YGFL%YAEROUT(JGFL)%LPT) THEN
      IF (YGFL%YAEROUT(JGFL)%LADV) THEN
        IPT=YGFL%YAEROUT(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT) = YDCPG_SL1%AEROUT(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT) = YDVARS%AEROUT(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AEROCLIM)
    IF (YGFL%YAEROCLIM(JGFL)%LT1 .AND. YGFL%YAEROCLIM(JGFL)%LPT) THEN
      IF (YGFL%YAEROCLIM(JGFL)%LADV) THEN
        IPT=YGFL%YAEROCLIM(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT) = YDCPG_SL1%AEROCLIM(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT) = YDVARS%AEROCLIM(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%UVP)
    IF (YGFL%YUVP(JGFL)%LT1 .AND. YGFL%YUVP(JGFL)%LPT) THEN
      IF (YGFL%YUVP(JGFL)%LADV) THEN
        IPT=YGFL%YUVP(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT) = YDCPG_SL1%UVP(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT) = YDVARS%UVP(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%PHYS)
    IF (YGFL%YPHYS(JGFL)%LT1 .AND. YGFL%YPHYS(JGFL)%LPT) THEN
      IF (YGFL%YPHYS(JGFL)%LADV) THEN
        IPT=YGFL%YPHYS(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT) = YDCPG_SL1%PHYS(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT) = YDVARS%PHYS(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  IF (YGFL%YPHYCTY%LT1 .AND. YGFL%YPHYCTY%LPT) THEN
    IF (YGFL%YPHYCTY%LADV) THEN
      IPT=YGFL%YPHYCTY%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MPPT) = YDCPG_SL1%PHYCTY%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MPPT) = YDVARS%PHYCTY%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YRSPEC%LT1 .AND. YGFL%YRSPEC%LPT) THEN
    IF (YGFL%YRSPEC%LADV) THEN
      IPT=YGFL%YRSPEC%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MPPT) = YDCPG_SL1%RSPEC%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MPPT) = YDVARS%RSPEC%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YSDSAT%LT1 .AND. YGFL%YSDSAT%LPT) THEN
    IF (YGFL%YSDSAT%LADV) THEN
      IPT=YGFL%YSDSAT%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MPPT) = YDCPG_SL1%SDSAT%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MPPT) = YDVARS%SDSAT%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YCVV%LT1 .AND. YGFL%YCVV%LPT) THEN
    IF (YGFL%YCVV%LADV) THEN
      IPT=YGFL%YCVV%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MPPT) = YDCPG_SL1%CVV%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MPPT) = YDVARS%CVV%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YRKTH%LT1 .AND. YGFL%YRKTH%LPT) THEN
    IF (YGFL%YRKTH%LADV) THEN
      IPT=YGFL%YRKTH%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MPPT) = YDCPG_SL1%RKTH%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MPPT) = YDVARS%RKTH%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YRKTQV%LT1 .AND. YGFL%YRKTQV%LPT) THEN
    IF (YGFL%YRKTQV%LADV) THEN
      IPT=YGFL%YRKTQV%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MPPT) = YDCPG_SL1%RKTQV%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MPPT) = YDVARS%RKTQV%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YRKTQC%LT1 .AND. YGFL%YRKTQC%LPT) THEN
    IF (YGFL%YRKTQC%LADV) THEN
      IPT=YGFL%YRKTQC%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MPPT) = YDCPG_SL1%RKTQC%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MPPT) = YDVARS%RKTQC%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YUOM%LT1 .AND. YGFL%YUOM%LPT) THEN
    IF (YGFL%YUOM%LADV) THEN
      IPT=YGFL%YUOM%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MPPT) = YDCPG_SL1%UOM%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MPPT) = YDVARS%UOM%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YUAL%LT1 .AND. YGFL%YUAL%LPT) THEN
    IF (YGFL%YUAL%LADV) THEN
      IPT=YGFL%YUAL%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MPPT) = YDCPG_SL1%UAL%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MPPT) = YDVARS%UAL%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YDOM%LT1 .AND. YGFL%YDOM%LPT) THEN
    IF (YGFL%YDOM%LADV) THEN
      IPT=YGFL%YDOM%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MPPT) = YDCPG_SL1%DOM%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MPPT) = YDVARS%DOM%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YDAL%LT1 .AND. YGFL%YDAL%LPT) THEN
    IF (YGFL%YDAL%LADV) THEN
      IPT=YGFL%YDAL%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MPPT) = YDCPG_SL1%DAL%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MPPT) = YDVARS%DAL%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YUEN%LT1 .AND. YGFL%YUEN%LPT) THEN
    IF (YGFL%YUEN%LADV) THEN
      IPT=YGFL%YUEN%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MPPT) = YDCPG_SL1%UEN%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MPPT) = YDVARS%UEN%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  IF (YGFL%YUNEBH%LT1 .AND. YGFL%YUNEBH%LPT) THEN
    IF (YGFL%YUNEBH%LADV) THEN
      IPT=YGFL%YUNEBH%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MPPT) = YDCPG_SL1%UNEBH%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MPPT) = YDVARS%UNEBH%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%CRM)
    IF (YGFL%YCRM(JGFL)%LT1 .AND. YGFL%YCRM(JGFL)%LPT) THEN
      IF (YGFL%YCRM(JGFL)%LADV) THEN
        IPT=YGFL%YCRM(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT) = YDCPG_SL1%CRM(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT) = YDVARS%CRM(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%LIMA)
    IF (YGFL%YLIMA(JGFL)%LT1 .AND. YGFL%YLIMA(JGFL)%LPT) THEN
      IF (YGFL%YLIMA(JGFL)%LADV) THEN
        IPT=YGFL%YLIMA(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT) = YDCPG_SL1%LIMA(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT) = YDVARS%LIMA(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO

  IF (YGFL%YFSD%LT1 .AND. YGFL%YFSD%LPT) THEN
    IF (YGFL%YFSD%LADV) THEN
      IPT=YGFL%YFSD%MP_SLX
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MPPT) = YDCPG_SL1%FSD%P_X(KSTART:KPROF,1:NFLEVG)
    ELSE
      PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MP1)
!     PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MPPT) = YDVARS%FSD%T1(KSTART:KPROF,1:NFLEVG)
    ENDIF
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%EXT)
    IF (YGFL%YEXT(JGFL)%LT1 .AND. YGFL%YEXT(JGFL)%LPT) THEN
      IF (YGFL%YEXT(JGFL)%LADV) THEN
        IPT=YGFL%YEXT(JGFL)%MP_SLX
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT) = YDCPG_SL1%EXT(JGFL)%P_X(KSTART:KPROF,1:NFLEVG)
      ELSE
        PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MP1)
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT) = YDVARS%EXT(JGFL)%T1(KSTART:KPROF,1:NFLEVG)
      ENDIF
    ENDIF
  ENDDO


! DO JGFL=1,NUMFLDS
!   IF (YCOMP(JGFL)%LT1 .AND. YCOMP(JGFL)%LPT) THEN
!     IF (YCOMP(JGFL)%LADV) THEN
!       IPT=YCOMP(JGFL)%MP_SLX
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YCOMP(JGFL)%MPPT)=ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)
!     ELSE
!       PGFLPT(KSTART:KPROF,1:NFLEVG,YCOMP(JGFL)%MPPT)=PGFLT1(KSTART:KPROF,1:NFLEVG,YCOMP(JGFL)%MP1)
!     ENDIF
!   ENDIF
! ENDDO

ENDIF

! -----------------------------------------------------------------------------

!*       2.  CORRECTOR FOR LPC_FULL.
!        ---------------------------

IF (LDGET) THEN

  ! * GMV:
  YLMF_PHYS_NEXT_STATE%U(KSTART:KPROF,1:NFLEVG)=YDVARS%CUPT%T9(KSTART:KPROF,1:NFLEVG)
  YLMF_PHYS_NEXT_STATE%V(KSTART:KPROF,1:NFLEVG)=YDVARS%CVPT%T9(KSTART:KPROF,1:NFLEVG)
  YLMF_PHYS_NEXT_STATE%T(KSTART:KPROF,1:NFLEVG)=YDVARS%CTPT%T9(KSTART:KPROF,1:NFLEVG)
  IF (LNHDYN) THEN
    YLMF_PHYS_NEXT_STATE%SVD(KSTART:KPROF,1:NFLEVG)=YDVARS%CSVDPT%T9(KSTART:KPROF,1:NFLEVG)
  ENDIF

  ! * GMVS:
  YDCPG_SL1%SP9%P(KSTART:KPROF)=YDVARS%CSPPT%T9(KSTART:KPROF)

  ! * GFL:
  IF (YGFL%YQ%LT1 .AND. YGFL%YQ%LPT) THEN
    IF (YGFL%YQ%LADV) THEN
      IPT=YGFL%YQ%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MPPT)
!     YDCPG_SL1%Q%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MPPT)
!     YDVARS%Q%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQ%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YI%LT1 .AND. YGFL%YI%LPT) THEN
    IF (YGFL%YI%LADV) THEN
      IPT=YGFL%YI%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YI%MPPT)
!     YDCPG_SL1%I%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YI%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YI%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YI%MPPT)
!     YDVARS%I%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YI%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YL%LT1 .AND. YGFL%YL%LPT) THEN
    IF (YGFL%YL%LADV) THEN
      IPT=YGFL%YL%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YL%MPPT)
!     YDCPG_SL1%L%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YL%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YL%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YL%MPPT)
!     YDVARS%L%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YL%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YLCONV%LT1 .AND. YGFL%YLCONV%LPT) THEN
    IF (YGFL%YLCONV%LADV) THEN
      IPT=YGFL%YLCONV%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MPPT)
!     YDCPG_SL1%LCONV%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MPPT)
!     YDVARS%LCONV%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLCONV%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YICONV%LT1 .AND. YGFL%YICONV%LPT) THEN
    IF (YGFL%YICONV%LADV) THEN
      IPT=YGFL%YICONV%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MPPT)
!     YDCPG_SL1%ICONV%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MPPT)
!     YDVARS%ICONV%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YICONV%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YRCONV%LT1 .AND. YGFL%YRCONV%LPT) THEN
    IF (YGFL%YRCONV%LADV) THEN
      IPT=YGFL%YRCONV%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MPPT)
!     YDCPG_SL1%RCONV%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MPPT)
!     YDVARS%RCONV%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRCONV%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YSCONV%LT1 .AND. YGFL%YSCONV%LPT) THEN
    IF (YGFL%YSCONV%LADV) THEN
      IPT=YGFL%YSCONV%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MPPT)
!     YDCPG_SL1%SCONV%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MPPT)
!     YDVARS%SCONV%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSCONV%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YIRAD%LT1 .AND. YGFL%YIRAD%LPT) THEN
    IF (YGFL%YIRAD%LADV) THEN
      IPT=YGFL%YIRAD%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MPPT)
!     YDCPG_SL1%IRAD%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MPPT)
!     YDVARS%IRAD%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YIRAD%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YLRAD%LT1 .AND. YGFL%YLRAD%LPT) THEN
    IF (YGFL%YLRAD%LADV) THEN
      IPT=YGFL%YLRAD%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MPPT)
!     YDCPG_SL1%LRAD%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MPPT)
!     YDVARS%LRAD%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRAD%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YS%LT1 .AND. YGFL%YS%LPT) THEN
    IF (YGFL%YS%LADV) THEN
      IPT=YGFL%YS%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YS%MPPT)
!     YDCPG_SL1%S%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YS%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YS%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YS%MPPT)
!     YDVARS%S%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YS%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YR%LT1 .AND. YGFL%YR%LPT) THEN
    IF (YGFL%YR%LADV) THEN
      IPT=YGFL%YR%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YR%MPPT)
!     YDCPG_SL1%R%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YR%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YR%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YR%MPPT)
!     YDVARS%R%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YR%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YG%LT1 .AND. YGFL%YG%LPT) THEN
    IF (YGFL%YG%LADV) THEN
      IPT=YGFL%YG%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YG%MPPT)
!     YDCPG_SL1%G%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YG%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YG%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YG%MPPT)
!     YDVARS%G%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YG%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YH%LT1 .AND. YGFL%YH%LPT) THEN
    IF (YGFL%YH%LADV) THEN
      IPT=YGFL%YH%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YH%MPPT)
!     YDCPG_SL1%H%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YH%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YH%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YH%MPPT)
!     YDVARS%H%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YH%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YTKE%LT1 .AND. YGFL%YTKE%LPT) THEN
    IF (YGFL%YTKE%LADV) THEN
      IPT=YGFL%YTKE%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MPPT)
!     YDCPG_SL1%TKE%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MPPT)
!     YDVARS%TKE%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTKE%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YTTE%LT1 .AND. YGFL%YTTE%LPT) THEN
    IF (YGFL%YTTE%LADV) THEN
      IPT=YGFL%YTTE%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MPPT)
!     YDCPG_SL1%TTE%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MPPT)
!     YDVARS%TTE%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YTTE%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YEFB1%LT1 .AND. YGFL%YEFB1%LPT) THEN
    IF (YGFL%YEFB1%LADV) THEN
      IPT=YGFL%YEFB1%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MPPT)
!     YDCPG_SL1%EFB1%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MPPT)
!     YDVARS%EFB1%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB1%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YEFB2%LT1 .AND. YGFL%YEFB2%LPT) THEN
    IF (YGFL%YEFB2%LADV) THEN
      IPT=YGFL%YEFB2%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MPPT)
!     YDCPG_SL1%EFB2%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MPPT)
!     YDVARS%EFB2%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB2%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YEFB3%LT1 .AND. YGFL%YEFB3%LPT) THEN
    IF (YGFL%YEFB3%LADV) THEN
      IPT=YGFL%YEFB3%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MPPT)
!     YDCPG_SL1%EFB3%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MPPT)
!     YDVARS%EFB3%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEFB3%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YA%LT1 .AND. YGFL%YA%LPT) THEN
    IF (YGFL%YA%LADV) THEN
      IPT=YGFL%YA%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YA%MPPT)
!     YDCPG_SL1%A%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YA%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YA%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YA%MPPT)
!     YDVARS%A%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YA%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YO3%LT1 .AND. YGFL%YO3%LPT) THEN
    IF (YGFL%YO3%LADV) THEN
      IPT=YGFL%YO3%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MPPT)
!     YDCPG_SL1%O3%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MPPT)
!     YDVARS%O3%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YO3%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YSRC%LT1 .AND. YGFL%YSRC%LPT) THEN
    IF (YGFL%YSRC%LADV) THEN
      IPT=YGFL%YSRC%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MPPT)
!     YDCPG_SL1%SRC%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MPPT)
!     YDVARS%SRC%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSRC%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YMXL%LT1 .AND. YGFL%YMXL%LPT) THEN
    IF (YGFL%YMXL%LADV) THEN
      IPT=YGFL%YMXL%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MPPT)
!     YDCPG_SL1%MXL%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MPPT)
!     YDVARS%MXL%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YMXL%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YSHTUR%LT1 .AND. YGFL%YSHTUR%LPT) THEN
    IF (YGFL%YSHTUR%LADV) THEN
      IPT=YGFL%YSHTUR%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MPPT)
!     YDCPG_SL1%SHTUR%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MPPT)
!     YDVARS%SHTUR%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSHTUR%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YFQTUR%LT1 .AND. YGFL%YFQTUR%LPT) THEN
    IF (YGFL%YFQTUR%LADV) THEN
      IPT=YGFL%YFQTUR%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MPPT)
!     YDCPG_SL1%FQTUR%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MPPT)
!     YDVARS%FQTUR%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFQTUR%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YFSTUR%LT1 .AND. YGFL%YFSTUR%LPT) THEN
    IF (YGFL%YFSTUR%LADV) THEN
      IPT=YGFL%YFSTUR%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MPPT)
!     YDCPG_SL1%FSTUR%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MPPT)
!     YDVARS%FSTUR%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSTUR%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YCPF%LT1 .AND. YGFL%YCPF%LPT) THEN
    IF (YGFL%YCPF%LADV) THEN
      IPT=YGFL%YCPF%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MPPT)
!     YDCPG_SL1%CPF%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MPPT)
!     YDVARS%CPF%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCPF%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YSPF%LT1 .AND. YGFL%YSPF%LPT) THEN
    IF (YGFL%YSPF%LADV) THEN
      IPT=YGFL%YSPF%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MPPT)
!     YDCPG_SL1%SPF%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MPPT)
!     YDVARS%SPF%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSPF%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YCVGQ%LT1 .AND. YGFL%YCVGQ%LPT) THEN
    IF (YGFL%YCVGQ%LADV) THEN
      IPT=YGFL%YCVGQ%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MPPT)
!     YDCPG_SL1%CVGQ%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MPPT)
!     YDVARS%CVGQ%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVGQ%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YQVA%LT1 .AND. YGFL%YQVA%LPT) THEN
    IF (YGFL%YQVA%LADV) THEN
      IPT=YGFL%YQVA%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MPPT)
!     YDCPG_SL1%QVA%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MPPT)
!     YDVARS%QVA%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YQVA%MPPT) 
    ENDIF
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%GHG)
    IF (YGFL%YGHG(JGFL)%LT1 .AND. YGFL%YGHG(JGFL)%LPT) THEN
      IF (YGFL%YGHG(JGFL)%LADV) THEN
        IPT=YGFL%YGHG(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT)
!       YDCPG_SL1%GHG(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT)
!       YDVARS%GHG(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%CHEM)
    IF (YGFL%YCHEM(JGFL)%LT1 .AND. YGFL%YCHEM(JGFL)%LPT) THEN
      IF (YGFL%YCHEM(JGFL)%LADV) THEN
        IPT=YGFL%YCHEM(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT)
!       YDCPG_SL1%CHEM(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT)
!       YDVARS%CHEM(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERO)
    IF (YGFL%YAERO(JGFL)%LT1 .AND. YGFL%YAERO(JGFL)%LPT) THEN
      IF (YGFL%YAERO(JGFL)%LADV) THEN
        IPT=YGFL%YAERO(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT)
!       YDCPG_SL1%AERO(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT)
!       YDVARS%AERO(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  IF (YGFL%YLRCH4%LT1 .AND. YGFL%YLRCH4%LPT) THEN
    IF (YGFL%YLRCH4%LADV) THEN
      IPT=YGFL%YLRCH4%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MPPT)
!     YDCPG_SL1%LRCH4%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MPPT)
!     YDVARS%LRCH4%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLRCH4%MPPT) 
    ENDIF
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%FORC)
    IF (YGFL%YFORC(JGFL)%LT1 .AND. YGFL%YFORC(JGFL)%LPT) THEN
      IF (YGFL%YFORC(JGFL)%LADV) THEN
        IPT=YGFL%YFORC(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT)
!       YDCPG_SL1%FORC(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT)
!       YDVARS%FORC(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%EZDIAG)
    IF (YGFL%YEZDIAG(JGFL)%LT1 .AND. YGFL%YEZDIAG(JGFL)%LPT) THEN
      IF (YGFL%YEZDIAG(JGFL)%LADV) THEN
        IPT=YGFL%YEZDIAG(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT)
!       YDCPG_SL1%EZDIAG(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT)
!       YDVARS%EZDIAG(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%ERA40)
    IF (YGFL%YERA40(JGFL)%LT1 .AND. YGFL%YERA40(JGFL)%LPT) THEN
      IF (YGFL%YERA40(JGFL)%LADV) THEN
        IPT=YGFL%YERA40(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT)
!       YDCPG_SL1%ERA40(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT)
!       YDVARS%ERA40(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%NOGW)
    IF (YGFL%YNOGW(JGFL)%LT1 .AND. YGFL%YNOGW(JGFL)%LPT) THEN
      IF (YGFL%YNOGW(JGFL)%LADV) THEN
        IPT=YGFL%YNOGW(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT)
!       YDCPG_SL1%NOGW(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT)
!       YDVARS%NOGW(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%EDRP)
    IF (YGFL%YEDRP(JGFL)%LT1 .AND. YGFL%YEDRP(JGFL)%LPT) THEN
      IF (YGFL%YEDRP(JGFL)%LADV) THEN
        IPT=YGFL%YEDRP(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT)
!       YDCPG_SL1%EDRP(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT)
!       YDVARS%EDRP(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%SLDIA)
    IF (YGFL%YSLDIA(JGFL)%LT1 .AND. YGFL%YSLDIA(JGFL)%LPT) THEN
      IF (YGFL%YSLDIA(JGFL)%LADV) THEN
        IPT=YGFL%YSLDIA(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT)
!       YDCPG_SL1%SLDIA(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT)
!       YDVARS%SLDIA(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERAOT)
    IF (YGFL%YAERAOT(JGFL)%LT1 .AND. YGFL%YAERAOT(JGFL)%LPT) THEN
      IF (YGFL%YAERAOT(JGFL)%LADV) THEN
        IPT=YGFL%YAERAOT(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT)
!       YDCPG_SL1%AERAOT(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT)
!       YDVARS%AERAOT(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERLISI)
    IF (YGFL%YAERLISI(JGFL)%LT1 .AND. YGFL%YAERLISI(JGFL)%LPT) THEN
      IF (YGFL%YAERLISI(JGFL)%LADV) THEN
        IPT=YGFL%YAERLISI(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT)
!       YDCPG_SL1%AERLISI(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT)
!       YDVARS%AERLISI(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AEROUT)
    IF (YGFL%YAEROUT(JGFL)%LT1 .AND. YGFL%YAEROUT(JGFL)%LPT) THEN
      IF (YGFL%YAEROUT(JGFL)%LADV) THEN
        IPT=YGFL%YAEROUT(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT)
!       YDCPG_SL1%AEROUT(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT)
!       YDVARS%AEROUT(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AEROCLIM)
    IF (YGFL%YAEROCLIM(JGFL)%LT1 .AND. YGFL%YAEROCLIM(JGFL)%LPT) THEN
      IF (YGFL%YAEROCLIM(JGFL)%LADV) THEN
        IPT=YGFL%YAEROCLIM(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT)
!       YDCPG_SL1%AEROCLIM(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT)
!       YDVARS%AEROCLIM(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%UVP)
    IF (YGFL%YUVP(JGFL)%LT1 .AND. YGFL%YUVP(JGFL)%LPT) THEN
      IF (YGFL%YUVP(JGFL)%LADV) THEN
        IPT=YGFL%YUVP(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT)
!       YDCPG_SL1%UVP(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT)
!       YDVARS%UVP(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%PHYS)
    IF (YGFL%YPHYS(JGFL)%LT1 .AND. YGFL%YPHYS(JGFL)%LPT) THEN
      IF (YGFL%YPHYS(JGFL)%LADV) THEN
        IPT=YGFL%YPHYS(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT)
!       YDCPG_SL1%PHYS(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT)
!       YDVARS%PHYS(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  IF (YGFL%YPHYCTY%LT1 .AND. YGFL%YPHYCTY%LPT) THEN
    IF (YGFL%YPHYCTY%LADV) THEN
      IPT=YGFL%YPHYCTY%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MPPT)
!     YDCPG_SL1%PHYCTY%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MPPT)
!     YDVARS%PHYCTY%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YPHYCTY%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YRSPEC%LT1 .AND. YGFL%YRSPEC%LPT) THEN
    IF (YGFL%YRSPEC%LADV) THEN
      IPT=YGFL%YRSPEC%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MPPT)
!     YDCPG_SL1%RSPEC%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MPPT)
!     YDVARS%RSPEC%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRSPEC%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YSDSAT%LT1 .AND. YGFL%YSDSAT%LPT) THEN
    IF (YGFL%YSDSAT%LADV) THEN
      IPT=YGFL%YSDSAT%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MPPT)
!     YDCPG_SL1%SDSAT%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MPPT)
!     YDVARS%SDSAT%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YSDSAT%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YCVV%LT1 .AND. YGFL%YCVV%LPT) THEN
    IF (YGFL%YCVV%LADV) THEN
      IPT=YGFL%YCVV%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MPPT)
!     YDCPG_SL1%CVV%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MPPT)
!     YDVARS%CVV%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCVV%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YRKTH%LT1 .AND. YGFL%YRKTH%LPT) THEN
    IF (YGFL%YRKTH%LADV) THEN
      IPT=YGFL%YRKTH%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MPPT)
!     YDCPG_SL1%RKTH%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MPPT)
!     YDVARS%RKTH%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTH%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YRKTQV%LT1 .AND. YGFL%YRKTQV%LPT) THEN
    IF (YGFL%YRKTQV%LADV) THEN
      IPT=YGFL%YRKTQV%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MPPT)
!     YDCPG_SL1%RKTQV%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MPPT)
!     YDVARS%RKTQV%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQV%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YRKTQC%LT1 .AND. YGFL%YRKTQC%LPT) THEN
    IF (YGFL%YRKTQC%LADV) THEN
      IPT=YGFL%YRKTQC%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MPPT)
!     YDCPG_SL1%RKTQC%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MPPT)
!     YDVARS%RKTQC%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YRKTQC%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YUOM%LT1 .AND. YGFL%YUOM%LPT) THEN
    IF (YGFL%YUOM%LADV) THEN
      IPT=YGFL%YUOM%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MPPT)
!     YDCPG_SL1%UOM%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MPPT)
!     YDVARS%UOM%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUOM%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YUAL%LT1 .AND. YGFL%YUAL%LPT) THEN
    IF (YGFL%YUAL%LADV) THEN
      IPT=YGFL%YUAL%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MPPT)
!     YDCPG_SL1%UAL%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MPPT)
!     YDVARS%UAL%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUAL%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YDOM%LT1 .AND. YGFL%YDOM%LPT) THEN
    IF (YGFL%YDOM%LADV) THEN
      IPT=YGFL%YDOM%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MPPT)
!     YDCPG_SL1%DOM%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MPPT)
!     YDVARS%DOM%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDOM%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YDAL%LT1 .AND. YGFL%YDAL%LPT) THEN
    IF (YGFL%YDAL%LADV) THEN
      IPT=YGFL%YDAL%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MPPT)
!     YDCPG_SL1%DAL%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MPPT)
!     YDVARS%DAL%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YDAL%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YUEN%LT1 .AND. YGFL%YUEN%LPT) THEN
    IF (YGFL%YUEN%LADV) THEN
      IPT=YGFL%YUEN%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MPPT)
!     YDCPG_SL1%UEN%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MPPT)
!     YDVARS%UEN%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUEN%MPPT) 
    ENDIF
  ENDIF

  IF (YGFL%YUNEBH%LT1 .AND. YGFL%YUNEBH%LPT) THEN
    IF (YGFL%YUNEBH%LADV) THEN
      IPT=YGFL%YUNEBH%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MPPT)
!     YDCPG_SL1%UNEBH%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MPPT)
!     YDVARS%UNEBH%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YUNEBH%MPPT) 
    ENDIF
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%CRM)
    IF (YGFL%YCRM(JGFL)%LT1 .AND. YGFL%YCRM(JGFL)%LPT) THEN
      IF (YGFL%YCRM(JGFL)%LADV) THEN
        IPT=YGFL%YCRM(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT)
!       YDCPG_SL1%CRM(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT)
!       YDVARS%CRM(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%LIMA)
    IF (YGFL%YLIMA(JGFL)%LT1 .AND. YGFL%YLIMA(JGFL)%LPT) THEN
      IF (YGFL%YLIMA(JGFL)%LADV) THEN
        IPT=YGFL%YLIMA(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT)
!       YDCPG_SL1%LIMA(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT)
!       YDVARS%LIMA(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO

  IF (YGFL%YFSD%LT1 .AND. YGFL%YFSD%LPT) THEN
    IF (YGFL%YFSD%LADV) THEN
      IPT=YGFL%YFSD%MP_SLX
      ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MPPT)
!     YDCPG_SL1%FSD%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MPPT) 
    ELSE
      PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MPPT)
!     YDVARS%FSD%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YFSD%MPPT) 
    ENDIF
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%EXT)
    IF (YGFL%YEXT(JGFL)%LT1 .AND. YGFL%YEXT(JGFL)%LPT) THEN
      IF (YGFL%YEXT(JGFL)%LADV) THEN
        IPT=YGFL%YEXT(JGFL)%MP_SLX
        ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT)
!       YDCPG_SL1%EXT(JGFL)%P_X(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT)
      ELSE
        PGFLT1(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT)
!       YDVARS%EXT(JGFL)%T1(KSTART:KPROF,1:NFLEVG) = PGFLPT(KSTART:KPROF,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT) 
      ENDIF
    ENDIF
  ENDDO


! DO JGFL=1,NUMFLDS
!   IF (YCOMP(JGFL)%LT1 .AND. YCOMP(JGFL)%LPT) THEN
!     IF (YCOMP(JGFL)%LADV) THEN
!       IPT=YCOMP(JGFL)%MP_SLX
!       ZTENDGFL(KSTART:KPROF,IPT+1:IPT+NFLEVG)=PGFLPT(KSTART:KPROF,1:NFLEVG,YCOMP(JGFL)%MPPT)
!     ELSE
!       PGFLT1(KSTART:KPROF,1:NFLEVG,YCOMP(JGFL)%MP1)=PGFLPT(KSTART:KPROF,1:NFLEVG,YCOMP(JGFL)%MPPT)
!     ENDIF
!   ENDIF
! ENDDO

  IF (YCPF%LACTIVE) THEN
    YDVARS%CPF%T1(KSTART:KPROF,1:NFLEVG)=YDVARS%CPF%T0(KSTART:KPROF,1:NFLEVG)
  ENDIF

ENDIF

! -----------------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('CPG_PT_ULP_EXPL',1,ZHOOK_HANDLE)

END SUBROUTINE CPG_PT_ULP_EXPL
