MODULE MF_PHYS_NEXT_STATE_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_DIMS_VARS_TYPE
IMPLICIT NONE

TYPE MF_PHYS_NEXT_STATE_TYPE

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: U (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: U (NPROMA,YDCPG_OPTS%YRVARS%U%ILEVT1I:YDCPG_OPTS%YRVARS%U%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_U => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: V (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: V (NPROMA,YDCPG_OPTS%YRVARS%V%ILEVT1I:YDCPG_OPTS%YRVARS%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_V => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: T (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: T (NPROMA,YDCPG_OPTS%YRVARS%T%ILEVT1I:YDCPG_OPTS%YRVARS%T%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_T => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SVD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: SVD (NPROMA,YDCPG_OPTS%YRVARS%SVD%ILEVT1I:YDCPG_OPTS%YRVARS%SVD%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_SVD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SP (:) => NULL ()
!>REAL (KIND=JPRB)                      :: SP (NPROMA)
  TYPE (FIELD_2D), POINTER :: F_SP => NULL ()

  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: Q (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: Q (NPROMA,YDCPG_OPTS%YRVARS%Q%ILEVT1I:YDCPG_OPTS%YRVARS%Q%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_Q => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: I (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: I (NPROMA,YDCPG_OPTS%YRVARS%I%ILEVT1I:YDCPG_OPTS%YRVARS%I%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_I => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: L (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: L (NPROMA,YDCPG_OPTS%YRVARS%L%ILEVT1I:YDCPG_OPTS%YRVARS%L%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_L => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LCONV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LCONV (NPROMA,YDCPG_OPTS%YRVARS%LCONV%ILEVT1I:YDCPG_OPTS%YRVARS%LCONV%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_LCONV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: ICONV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: ICONV (NPROMA,YDCPG_OPTS%YRVARS%ICONV%ILEVT1I:YDCPG_OPTS%YRVARS%ICONV%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_ICONV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RCONV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RCONV (NPROMA,YDCPG_OPTS%YRVARS%RCONV%ILEVT1I:YDCPG_OPTS%YRVARS%RCONV%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_RCONV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SCONV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: SCONV (NPROMA,YDCPG_OPTS%YRVARS%SCONV%ILEVT1I:YDCPG_OPTS%YRVARS%SCONV%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_SCONV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: IRAD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: IRAD (NPROMA,YDCPG_OPTS%YRVARS%IRAD%ILEVT1I:YDCPG_OPTS%YRVARS%IRAD%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_IRAD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LRAD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LRAD (NPROMA,YDCPG_OPTS%YRVARS%LRAD%ILEVT1I:YDCPG_OPTS%YRVARS%LRAD%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_LRAD => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: S (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: S (NPROMA,YDCPG_OPTS%YRVARS%S%ILEVT1I:YDCPG_OPTS%YRVARS%S%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_S => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: R (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: R (NPROMA,YDCPG_OPTS%YRVARS%R%ILEVT1I:YDCPG_OPTS%YRVARS%R%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_R => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: G (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: G (NPROMA,YDCPG_OPTS%YRVARS%G%ILEVT1I:YDCPG_OPTS%YRVARS%G%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_G => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: H (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: H (NPROMA,YDCPG_OPTS%YRVARS%H%ILEVT1I:YDCPG_OPTS%YRVARS%H%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_H => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TKE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TKE (NPROMA,YDCPG_OPTS%YRVARS%TKE%ILEVT1I:YDCPG_OPTS%YRVARS%TKE%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_TKE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: TTE (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: TTE (NPROMA,YDCPG_OPTS%YRVARS%TTE%ILEVT1I:YDCPG_OPTS%YRVARS%TTE%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_TTE => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB1 (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: EFB1 (NPROMA,YDCPG_OPTS%YRVARS%EFB1%ILEVT1I:YDCPG_OPTS%YRVARS%EFB1%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_EFB1 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB2 (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: EFB2 (NPROMA,YDCPG_OPTS%YRVARS%EFB2%ILEVT1I:YDCPG_OPTS%YRVARS%EFB2%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_EFB2 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: EFB3 (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: EFB3 (NPROMA,YDCPG_OPTS%YRVARS%EFB3%ILEVT1I:YDCPG_OPTS%YRVARS%EFB3%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_EFB3 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: A (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: A (NPROMA,YDCPG_OPTS%YRVARS%A%ILEVT1I:YDCPG_OPTS%YRVARS%A%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_A => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: O3 (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: O3 (NPROMA,YDCPG_OPTS%YRVARS%O3%ILEVT1I:YDCPG_OPTS%YRVARS%O3%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_O3 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SRC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: SRC (NPROMA,YDCPG_OPTS%YRVARS%SRC%ILEVT1I:YDCPG_OPTS%YRVARS%SRC%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_SRC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: MXL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: MXL (NPROMA,YDCPG_OPTS%YRVARS%MXL%ILEVT1I:YDCPG_OPTS%YRVARS%MXL%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_MXL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SHTUR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: SHTUR (NPROMA,YDCPG_OPTS%YRVARS%SHTUR%ILEVT1I:YDCPG_OPTS%YRVARS%SHTUR%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_SHTUR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FQTUR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FQTUR (NPROMA,YDCPG_OPTS%YRVARS%FQTUR%ILEVT1I:YDCPG_OPTS%YRVARS%FQTUR%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_FQTUR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FSTUR (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FSTUR (NPROMA,YDCPG_OPTS%YRVARS%FSTUR%ILEVT1I:YDCPG_OPTS%YRVARS%FSTUR%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_FSTUR => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CPF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: CPF (NPROMA,YDCPG_OPTS%YRVARS%CPF%ILEVT1I:YDCPG_OPTS%YRVARS%CPF%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_CPF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SPF (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: SPF (NPROMA,YDCPG_OPTS%YRVARS%SPF%ILEVT1I:YDCPG_OPTS%YRVARS%SPF%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_SPF => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CVGQ (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: CVGQ (NPROMA,YDCPG_OPTS%YRVARS%CVGQ%ILEVT1I:YDCPG_OPTS%YRVARS%CVGQ%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_CVGQ => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: QVA (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: QVA (NPROMA,YDCPG_OPTS%YRVARS%QVA%ILEVT1I:YDCPG_OPTS%YRVARS%QVA%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_QVA => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: LRCH4 (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: LRCH4 (NPROMA,YDCPG_OPTS%YRVARS%LRCH4%ILEVT1I:YDCPG_OPTS%YRVARS%LRCH4%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_LRCH4 => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: PHYCTY (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: PHYCTY (NPROMA,YDCPG_OPTS%YRVARS%PHYCTY%ILEVT1I:YDCPG_OPTS%YRVARS%PHYCTY%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_PHYCTY => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RSPEC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RSPEC (NPROMA,YDCPG_OPTS%YRVARS%RSPEC%ILEVT1I:YDCPG_OPTS%YRVARS%RSPEC%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_RSPEC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: SDSAT (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: SDSAT (NPROMA,YDCPG_OPTS%YRVARS%SDSAT%ILEVT1I:YDCPG_OPTS%YRVARS%SDSAT%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_SDSAT => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: CVV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: CVV (NPROMA,YDCPG_OPTS%YRVARS%CVV%ILEVT1I:YDCPG_OPTS%YRVARS%CVV%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_CVV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RKTH (NPROMA,YDCPG_OPTS%YRVARS%RKTH%ILEVT1I:YDCPG_OPTS%YRVARS%RKTH%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_RKTH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTQV (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RKTQV (NPROMA,YDCPG_OPTS%YRVARS%RKTQV%ILEVT1I:YDCPG_OPTS%YRVARS%RKTQV%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_RKTQV => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: RKTQC (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: RKTQC (NPROMA,YDCPG_OPTS%YRVARS%RKTQC%ILEVT1I:YDCPG_OPTS%YRVARS%RKTQC%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_RKTQC => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UOM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: UOM (NPROMA,YDCPG_OPTS%YRVARS%UOM%ILEVT1I:YDCPG_OPTS%YRVARS%UOM%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_UOM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UAL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: UAL (NPROMA,YDCPG_OPTS%YRVARS%UAL%ILEVT1I:YDCPG_OPTS%YRVARS%UAL%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_UAL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DOM (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DOM (NPROMA,YDCPG_OPTS%YRVARS%DOM%ILEVT1I:YDCPG_OPTS%YRVARS%DOM%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_DOM => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: DAL (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: DAL (NPROMA,YDCPG_OPTS%YRVARS%DAL%ILEVT1I:YDCPG_OPTS%YRVARS%DAL%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_DAL => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UEN (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: UEN (NPROMA,YDCPG_OPTS%YRVARS%UEN%ILEVT1I:YDCPG_OPTS%YRVARS%UEN%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_UEN => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: UNEBH (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: UNEBH (NPROMA,YDCPG_OPTS%YRVARS%UNEBH%ILEVT1I:YDCPG_OPTS%YRVARS%UNEBH%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_UNEBH => NULL ()
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: FSD (:, :) => NULL ()
!>REAL (KIND=JPRB)                      :: FSD (NPROMA,YDCPG_OPTS%YRVARS%FSD%ILEVT1I:YDCPG_OPTS%YRVARS%FSD%ILEVT1F)
  TYPE (FIELD_3D), POINTER :: F_FSD => NULL ()


  TYPE (CPG_DIMS_VARS_TYPE) :: DIMS

CONTAINS

  PROCEDURE :: INIT => MF_PHYS_NEXT_STATE_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW

END TYPE MF_PHYS_NEXT_STATE_TYPE

CONTAINS

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT (SELF, YDCPG_SL1, YDGEOMETRY, YDVARS, YDMODEL)

USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMCT0, ONLY : LSLAG, LTWOTL
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
USE CPG_TYPE_MOD, ONLY : CPG_SL1_TYPE
USE TYPE_MODEL  , ONLY : MODEL

CLASS (MF_PHYS_NEXT_STATE_TYPE)     :: SELF
TYPE (CPG_SL1_TYPE),    INTENT (IN) :: YDCPG_SL1
TYPE(GEOMETRY),         INTENT (IN) :: YDGEOMETRY
TYPE (FIELD_VARIABLES), INTENT (IN) :: YDVARS
TYPE(MODEL),            INTENT (IN) :: YDMODEL

ASSOCIATE (YDDYN => YDMODEL%YRML_DYN%YRDYN)

CALL SELF%DIMS%INIT (YDGEOMETRY, YDMODEL, YDVARS)

IF (LSLAG) THEN

  ! Taken from cp_ptrslb1.F90
  
  IF (YDDYN%NWLAG == 4) THEN
    SELF%U   => YDCPG_SL1%U0%P 
    SELF%F_U => YDCPG_SL1%U0%F_P
    SELF%V   => YDCPG_SL1%V0%P 
    SELF%F_V => YDCPG_SL1%V0%F_P
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%U   => YDCPG_SL1%UF9%P 
      SELF%F_U => YDCPG_SL1%UF9%F_P
      SELF%V   => YDCPG_SL1%VF9%P 
      SELF%F_V => YDCPG_SL1%VF9%F_P
    ELSE
      SELF%U   => YDCPG_SL1%U9%P 
      SELF%F_U => YDCPG_SL1%U9%F_P
      SELF%V   => YDCPG_SL1%V9%P 
      SELF%F_V => YDCPG_SL1%V9%F_P
    ENDIF
  ENDIF
  ! * temperature
  IF (YDDYN%NTLAG == 4) THEN
    SELF%T   => YDCPG_SL1%T0%P 
    SELF%F_T => YDCPG_SL1%T0%F_P
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%T   => YDCPG_SL1%TF9%P 
      SELF%F_T => YDCPG_SL1%TF9%F_P
    ELSE
      SELF%T   => YDCPG_SL1%T9%P 
      SELF%F_T => YDCPG_SL1%T9%F_P
    ENDIF
  ENDIF
  ! * vertical divergence
  IF (YDDYN%NSVDLAG == 4) THEN
    SELF%SVD   => YDCPG_SL1%VD0%P
    SELF%F_SVD => YDCPG_SL1%VD0%F_P
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%SVD   => YDCPG_SL1%VDF9%P
      SELF%F_SVD => YDCPG_SL1%VDF9%F_P
    ELSE
      SELF%SVD   => YDCPG_SL1%VD9%P
      SELF%F_SVD => YDCPG_SL1%VD9%F_P
    ENDIF
  ENDIF

  SELF%SP   => YDCPG_SL1%SP9%P
  SELF%F_SP => YDCPG_SL1%SP9%F_P

  ! * GFL arrays
  IF (YDDYN%LSPLTHOIGFL.OR.(YDDYN%NSPLTHOI /= 0)) THEN
    IF (YDVARS%Q%LADV) THEN
      SELF%Q   => YDCPG_SL1%Q%P_F
      SELF%F_Q => YDCPG_SL1%Q%F_P_F
    ELSE
      SELF%Q   => YDVARS%Q%T1
      SELF%F_Q => YDVARS%Q%FT1
    ENDIF
    IF (YDVARS%I%LADV) THEN
      SELF%I   => YDCPG_SL1%I%P_F
      SELF%F_I => YDCPG_SL1%I%F_P_F
    ELSE
      SELF%I   => YDVARS%I%T1
      SELF%F_I => YDVARS%I%FT1
    ENDIF
    IF (YDVARS%L%LADV) THEN
      SELF%L   => YDCPG_SL1%L%P_F
      SELF%F_L => YDCPG_SL1%L%F_P_F
    ELSE
      SELF%L   => YDVARS%L%T1
      SELF%F_L => YDVARS%L%FT1
    ENDIF
    IF (YDVARS%LCONV%LADV) THEN
      SELF%LCONV   => YDCPG_SL1%LCONV%P_F
      SELF%F_LCONV => YDCPG_SL1%LCONV%F_P_F
    ELSE
      SELF%LCONV   => YDVARS%LCONV%T1
      SELF%F_LCONV => YDVARS%LCONV%FT1
    ENDIF
    IF (YDVARS%ICONV%LADV) THEN
      SELF%ICONV   => YDCPG_SL1%ICONV%P_F
      SELF%F_ICONV => YDCPG_SL1%ICONV%F_P_F
    ELSE
      SELF%ICONV   => YDVARS%ICONV%T1
      SELF%F_ICONV => YDVARS%ICONV%FT1
    ENDIF
    IF (YDVARS%RCONV%LADV) THEN
      SELF%RCONV   => YDCPG_SL1%RCONV%P_F
      SELF%F_RCONV => YDCPG_SL1%RCONV%F_P_F
    ELSE
      SELF%RCONV   => YDVARS%RCONV%T1
      SELF%F_RCONV => YDVARS%RCONV%FT1
    ENDIF
    IF (YDVARS%SCONV%LADV) THEN
      SELF%SCONV   => YDCPG_SL1%SCONV%P_F
      SELF%F_SCONV => YDCPG_SL1%SCONV%F_P_F
    ELSE
      SELF%SCONV   => YDVARS%SCONV%T1
      SELF%F_SCONV => YDVARS%SCONV%FT1
    ENDIF
    IF (YDVARS%IRAD%LADV) THEN
      SELF%IRAD   => YDCPG_SL1%IRAD%P_F
      SELF%F_IRAD => YDCPG_SL1%IRAD%F_P_F
    ELSE
      SELF%IRAD   => YDVARS%IRAD%T1
      SELF%F_IRAD => YDVARS%IRAD%FT1
    ENDIF
    IF (YDVARS%LRAD%LADV) THEN
      SELF%LRAD   => YDCPG_SL1%LRAD%P_F
      SELF%F_LRAD => YDCPG_SL1%LRAD%F_P_F
    ELSE
      SELF%LRAD   => YDVARS%LRAD%T1
      SELF%F_LRAD => YDVARS%LRAD%FT1
    ENDIF
    IF (YDVARS%S%LADV) THEN
      SELF%S   => YDCPG_SL1%S%P_F
      SELF%F_S => YDCPG_SL1%S%F_P_F
    ELSE
      SELF%S   => YDVARS%S%T1
      SELF%F_S => YDVARS%S%FT1
    ENDIF
    IF (YDVARS%R%LADV) THEN
      SELF%R   => YDCPG_SL1%R%P_F
      SELF%F_R => YDCPG_SL1%R%F_P_F
    ELSE
      SELF%R   => YDVARS%R%T1
      SELF%F_R => YDVARS%R%FT1
    ENDIF
    IF (YDVARS%G%LADV) THEN
      SELF%G   => YDCPG_SL1%G%P_F
      SELF%F_G => YDCPG_SL1%G%F_P_F
    ELSE
      SELF%G   => YDVARS%G%T1
      SELF%F_G => YDVARS%G%FT1
    ENDIF
    IF (YDVARS%H%LADV) THEN
      SELF%H   => YDCPG_SL1%H%P_F
      SELF%F_H => YDCPG_SL1%H%F_P_F
    ELSE
      SELF%H   => YDVARS%H%T1
      SELF%F_H => YDVARS%H%FT1
    ENDIF
    IF (YDVARS%TKE%LADV) THEN
      SELF%TKE   => YDCPG_SL1%TKE%P_F
      SELF%F_TKE => YDCPG_SL1%TKE%F_P_F
    ELSE
      SELF%TKE   => YDVARS%TKE%T1
      SELF%F_TKE => YDVARS%TKE%FT1
    ENDIF
    IF (YDVARS%TTE%LADV) THEN
      SELF%TTE   => YDCPG_SL1%TTE%P_F
      SELF%F_TTE => YDCPG_SL1%TTE%F_P_F
    ELSE
      SELF%TTE   => YDVARS%TTE%T1
      SELF%F_TTE => YDVARS%TTE%FT1
    ENDIF
    IF (YDVARS%EFB1%LADV) THEN
      SELF%EFB1   => YDCPG_SL1%EFB1%P_F
      SELF%F_EFB1 => YDCPG_SL1%EFB1%F_P_F
    ELSE
      SELF%EFB1   => YDVARS%EFB1%T1
      SELF%F_EFB1 => YDVARS%EFB1%FT1
    ENDIF
    IF (YDVARS%EFB2%LADV) THEN
      SELF%EFB2   => YDCPG_SL1%EFB2%P_F
      SELF%F_EFB2 => YDCPG_SL1%EFB2%F_P_F
    ELSE
      SELF%EFB2   => YDVARS%EFB2%T1
      SELF%F_EFB2 => YDVARS%EFB2%FT1
    ENDIF
    IF (YDVARS%EFB3%LADV) THEN
      SELF%EFB3   => YDCPG_SL1%EFB3%P_F
      SELF%F_EFB3 => YDCPG_SL1%EFB3%F_P_F
    ELSE
      SELF%EFB3   => YDVARS%EFB3%T1
      SELF%F_EFB3 => YDVARS%EFB3%FT1
    ENDIF
    IF (YDVARS%A%LADV) THEN
      SELF%A   => YDCPG_SL1%A%P_F
      SELF%F_A => YDCPG_SL1%A%F_P_F
    ELSE
      SELF%A   => YDVARS%A%T1
      SELF%F_A => YDVARS%A%FT1
    ENDIF
    IF (YDVARS%O3%LADV) THEN
      SELF%O3   => YDCPG_SL1%O3%P_F
      SELF%F_O3 => YDCPG_SL1%O3%F_P_F
    ELSE
      SELF%O3   => YDVARS%O3%T1
      SELF%F_O3 => YDVARS%O3%FT1
    ENDIF
    IF (YDVARS%SRC%LADV) THEN
      SELF%SRC   => YDCPG_SL1%SRC%P_F
      SELF%F_SRC => YDCPG_SL1%SRC%F_P_F
    ELSE
      SELF%SRC   => YDVARS%SRC%T1
      SELF%F_SRC => YDVARS%SRC%FT1
    ENDIF
    IF (YDVARS%MXL%LADV) THEN
      SELF%MXL   => YDCPG_SL1%MXL%P_F
      SELF%F_MXL => YDCPG_SL1%MXL%F_P_F
    ELSE
      SELF%MXL   => YDVARS%MXL%T1
      SELF%F_MXL => YDVARS%MXL%FT1
    ENDIF
    IF (YDVARS%SHTUR%LADV) THEN
      SELF%SHTUR   => YDCPG_SL1%SHTUR%P_F
      SELF%F_SHTUR => YDCPG_SL1%SHTUR%F_P_F
    ELSE
      SELF%SHTUR   => YDVARS%SHTUR%T1
      SELF%F_SHTUR => YDVARS%SHTUR%FT1
    ENDIF
    IF (YDVARS%FQTUR%LADV) THEN
      SELF%FQTUR   => YDCPG_SL1%FQTUR%P_F
      SELF%F_FQTUR => YDCPG_SL1%FQTUR%F_P_F
    ELSE
      SELF%FQTUR   => YDVARS%FQTUR%T1
      SELF%F_FQTUR => YDVARS%FQTUR%FT1
    ENDIF
    IF (YDVARS%FSTUR%LADV) THEN
      SELF%FSTUR   => YDCPG_SL1%FSTUR%P_F
      SELF%F_FSTUR => YDCPG_SL1%FSTUR%F_P_F
    ELSE
      SELF%FSTUR   => YDVARS%FSTUR%T1
      SELF%F_FSTUR => YDVARS%FSTUR%FT1
    ENDIF
    IF (YDVARS%CPF%LADV) THEN
      SELF%CPF   => YDCPG_SL1%CPF%P_F
      SELF%F_CPF => YDCPG_SL1%CPF%F_P_F
    ELSE
      SELF%CPF   => YDVARS%CPF%T1
      SELF%F_CPF => YDVARS%CPF%FT1
    ENDIF
    IF (YDVARS%SPF%LADV) THEN
      SELF%SPF   => YDCPG_SL1%SPF%P_F
      SELF%F_SPF => YDCPG_SL1%SPF%F_P_F
    ELSE
      SELF%SPF   => YDVARS%SPF%T1
      SELF%F_SPF => YDVARS%SPF%FT1
    ENDIF
    IF (YDVARS%CVGQ%LADV) THEN
      SELF%CVGQ   => YDCPG_SL1%CVGQ%P_F
      SELF%F_CVGQ => YDCPG_SL1%CVGQ%F_P_F
    ELSE
      SELF%CVGQ   => YDVARS%CVGQ%T1
      SELF%F_CVGQ => YDVARS%CVGQ%FT1
    ENDIF
    IF (YDVARS%QVA%LADV) THEN
      SELF%QVA   => YDCPG_SL1%QVA%P_F
      SELF%F_QVA => YDCPG_SL1%QVA%F_P_F
    ELSE
      SELF%QVA   => YDVARS%QVA%T1
      SELF%F_QVA => YDVARS%QVA%FT1
    ENDIF
    IF (YDVARS%LRCH4%LADV) THEN
      SELF%LRCH4   => YDCPG_SL1%LRCH4%P_F
      SELF%F_LRCH4 => YDCPG_SL1%LRCH4%F_P_F
    ELSE
      SELF%LRCH4   => YDVARS%LRCH4%T1
      SELF%F_LRCH4 => YDVARS%LRCH4%FT1
    ENDIF
    IF (YDVARS%PHYCTY%LADV) THEN
      SELF%PHYCTY   => YDCPG_SL1%PHYCTY%P_F
      SELF%F_PHYCTY => YDCPG_SL1%PHYCTY%F_P_F
    ELSE
      SELF%PHYCTY   => YDVARS%PHYCTY%T1
      SELF%F_PHYCTY => YDVARS%PHYCTY%FT1
    ENDIF
    IF (YDVARS%RSPEC%LADV) THEN
      SELF%RSPEC   => YDCPG_SL1%RSPEC%P_F
      SELF%F_RSPEC => YDCPG_SL1%RSPEC%F_P_F
    ELSE
      SELF%RSPEC   => YDVARS%RSPEC%T1
      SELF%F_RSPEC => YDVARS%RSPEC%FT1
    ENDIF
    IF (YDVARS%SDSAT%LADV) THEN
      SELF%SDSAT   => YDCPG_SL1%SDSAT%P_F
      SELF%F_SDSAT => YDCPG_SL1%SDSAT%F_P_F
    ELSE
      SELF%SDSAT   => YDVARS%SDSAT%T1
      SELF%F_SDSAT => YDVARS%SDSAT%FT1
    ENDIF
    IF (YDVARS%CVV%LADV) THEN
      SELF%CVV   => YDCPG_SL1%CVV%P_F
      SELF%F_CVV => YDCPG_SL1%CVV%F_P_F
    ELSE
      SELF%CVV   => YDVARS%CVV%T1
      SELF%F_CVV => YDVARS%CVV%FT1
    ENDIF
    IF (YDVARS%RKTH%LADV) THEN
      SELF%RKTH   => YDCPG_SL1%RKTH%P_F
      SELF%F_RKTH => YDCPG_SL1%RKTH%F_P_F
    ELSE
      SELF%RKTH   => YDVARS%RKTH%T1
      SELF%F_RKTH => YDVARS%RKTH%FT1
    ENDIF
    IF (YDVARS%RKTQV%LADV) THEN
      SELF%RKTQV   => YDCPG_SL1%RKTQV%P_F
      SELF%F_RKTQV => YDCPG_SL1%RKTQV%F_P_F
    ELSE
      SELF%RKTQV   => YDVARS%RKTQV%T1
      SELF%F_RKTQV => YDVARS%RKTQV%FT1
    ENDIF
    IF (YDVARS%RKTQC%LADV) THEN
      SELF%RKTQC   => YDCPG_SL1%RKTQC%P_F
      SELF%F_RKTQC => YDCPG_SL1%RKTQC%F_P_F
    ELSE
      SELF%RKTQC   => YDVARS%RKTQC%T1
      SELF%F_RKTQC => YDVARS%RKTQC%FT1
    ENDIF
    IF (YDVARS%UOM%LADV) THEN
      SELF%UOM   => YDCPG_SL1%UOM%P_F
      SELF%F_UOM => YDCPG_SL1%UOM%F_P_F
    ELSE
      SELF%UOM   => YDVARS%UOM%T1
      SELF%F_UOM => YDVARS%UOM%FT1
    ENDIF
    IF (YDVARS%UAL%LADV) THEN
      SELF%UAL   => YDCPG_SL1%UAL%P_F
      SELF%F_UAL => YDCPG_SL1%UAL%F_P_F
    ELSE
      SELF%UAL   => YDVARS%UAL%T1
      SELF%F_UAL => YDVARS%UAL%FT1
    ENDIF
    IF (YDVARS%DOM%LADV) THEN
      SELF%DOM   => YDCPG_SL1%DOM%P_F
      SELF%F_DOM => YDCPG_SL1%DOM%F_P_F
    ELSE
      SELF%DOM   => YDVARS%DOM%T1
      SELF%F_DOM => YDVARS%DOM%FT1
    ENDIF
    IF (YDVARS%DAL%LADV) THEN
      SELF%DAL   => YDCPG_SL1%DAL%P_F
      SELF%F_DAL => YDCPG_SL1%DAL%F_P_F
    ELSE
      SELF%DAL   => YDVARS%DAL%T1
      SELF%F_DAL => YDVARS%DAL%FT1
    ENDIF
    IF (YDVARS%UEN%LADV) THEN
      SELF%UEN   => YDCPG_SL1%UEN%P_F
      SELF%F_UEN => YDCPG_SL1%UEN%F_P_F
    ELSE
      SELF%UEN   => YDVARS%UEN%T1
      SELF%F_UEN => YDVARS%UEN%FT1
    ENDIF
    IF (YDVARS%UNEBH%LADV) THEN
      SELF%UNEBH   => YDCPG_SL1%UNEBH%P_F
      SELF%F_UNEBH => YDCPG_SL1%UNEBH%F_P_F
    ELSE
      SELF%UNEBH   => YDVARS%UNEBH%T1
      SELF%F_UNEBH => YDVARS%UNEBH%FT1
    ENDIF
    IF (YDVARS%FSD%LADV) THEN
      SELF%FSD   => YDCPG_SL1%FSD%P_F
      SELF%F_FSD => YDCPG_SL1%FSD%F_P_F
    ELSE
      SELF%FSD   => YDVARS%FSD%T1
      SELF%F_FSD => YDVARS%FSD%FT1
    ENDIF
  ELSE
    IF (YDVARS%Q%LADV) THEN
      SELF%Q   => YDCPG_SL1%Q%P
      SELF%F_Q => YDCPG_SL1%Q%F_P
    ELSE
      SELF%Q   => YDVARS%Q%T1
      SELF%F_Q => YDVARS%Q%FT1
    ENDIF
    IF (YDVARS%I%LADV) THEN
      SELF%I   => YDCPG_SL1%I%P
      SELF%F_I => YDCPG_SL1%I%F_P
    ELSE
      SELF%I   => YDVARS%I%T1
      SELF%F_I => YDVARS%I%FT1
    ENDIF
    IF (YDVARS%L%LADV) THEN
      SELF%L   => YDCPG_SL1%L%P
      SELF%F_L => YDCPG_SL1%L%F_P
    ELSE
      SELF%L   => YDVARS%L%T1
      SELF%F_L => YDVARS%L%FT1
    ENDIF
    IF (YDVARS%LCONV%LADV) THEN
      SELF%LCONV   => YDCPG_SL1%LCONV%P
      SELF%F_LCONV => YDCPG_SL1%LCONV%F_P
    ELSE
      SELF%LCONV   => YDVARS%LCONV%T1
      SELF%F_LCONV => YDVARS%LCONV%FT1
    ENDIF
    IF (YDVARS%ICONV%LADV) THEN
      SELF%ICONV   => YDCPG_SL1%ICONV%P
      SELF%F_ICONV => YDCPG_SL1%ICONV%F_P
    ELSE
      SELF%ICONV   => YDVARS%ICONV%T1
      SELF%F_ICONV => YDVARS%ICONV%FT1
    ENDIF
    IF (YDVARS%RCONV%LADV) THEN
      SELF%RCONV   => YDCPG_SL1%RCONV%P
      SELF%F_RCONV => YDCPG_SL1%RCONV%F_P
    ELSE
      SELF%RCONV   => YDVARS%RCONV%T1
      SELF%F_RCONV => YDVARS%RCONV%FT1
    ENDIF
    IF (YDVARS%SCONV%LADV) THEN
      SELF%SCONV   => YDCPG_SL1%SCONV%P
      SELF%F_SCONV => YDCPG_SL1%SCONV%F_P
    ELSE
      SELF%SCONV   => YDVARS%SCONV%T1
      SELF%F_SCONV => YDVARS%SCONV%FT1
    ENDIF
    IF (YDVARS%IRAD%LADV) THEN
      SELF%IRAD   => YDCPG_SL1%IRAD%P
      SELF%F_IRAD => YDCPG_SL1%IRAD%F_P
    ELSE
      SELF%IRAD   => YDVARS%IRAD%T1
      SELF%F_IRAD => YDVARS%IRAD%FT1
    ENDIF
    IF (YDVARS%LRAD%LADV) THEN
      SELF%LRAD   => YDCPG_SL1%LRAD%P
      SELF%F_LRAD => YDCPG_SL1%LRAD%F_P
    ELSE
      SELF%LRAD   => YDVARS%LRAD%T1
      SELF%F_LRAD => YDVARS%LRAD%FT1
    ENDIF
    IF (YDVARS%S%LADV) THEN
      SELF%S   => YDCPG_SL1%S%P
      SELF%F_S => YDCPG_SL1%S%F_P
    ELSE
      SELF%S   => YDVARS%S%T1
      SELF%F_S => YDVARS%S%FT1
    ENDIF
    IF (YDVARS%R%LADV) THEN
      SELF%R   => YDCPG_SL1%R%P
      SELF%F_R => YDCPG_SL1%R%F_P
    ELSE
      SELF%R   => YDVARS%R%T1
      SELF%F_R => YDVARS%R%FT1
    ENDIF
    IF (YDVARS%G%LADV) THEN
      SELF%G   => YDCPG_SL1%G%P
      SELF%F_G => YDCPG_SL1%G%F_P
    ELSE
      SELF%G   => YDVARS%G%T1
      SELF%F_G => YDVARS%G%FT1
    ENDIF
    IF (YDVARS%H%LADV) THEN
      SELF%H   => YDCPG_SL1%H%P
      SELF%F_H => YDCPG_SL1%H%F_P
    ELSE
      SELF%H   => YDVARS%H%T1
      SELF%F_H => YDVARS%H%FT1
    ENDIF
    IF (YDVARS%TKE%LADV) THEN
      SELF%TKE   => YDCPG_SL1%TKE%P
      SELF%F_TKE => YDCPG_SL1%TKE%F_P
    ELSE
      SELF%TKE   => YDVARS%TKE%T1
      SELF%F_TKE => YDVARS%TKE%FT1
    ENDIF
    IF (YDVARS%TTE%LADV) THEN
      SELF%TTE   => YDCPG_SL1%TTE%P
      SELF%F_TTE => YDCPG_SL1%TTE%F_P
    ELSE
      SELF%TTE   => YDVARS%TTE%T1
      SELF%F_TTE => YDVARS%TTE%FT1
    ENDIF
    IF (YDVARS%EFB1%LADV) THEN
      SELF%EFB1   => YDCPG_SL1%EFB1%P
      SELF%F_EFB1 => YDCPG_SL1%EFB1%F_P
    ELSE
      SELF%EFB1   => YDVARS%EFB1%T1
      SELF%F_EFB1 => YDVARS%EFB1%FT1
    ENDIF
    IF (YDVARS%EFB2%LADV) THEN
      SELF%EFB2   => YDCPG_SL1%EFB2%P
      SELF%F_EFB2 => YDCPG_SL1%EFB2%F_P
    ELSE
      SELF%EFB2   => YDVARS%EFB2%T1
      SELF%F_EFB2 => YDVARS%EFB2%FT1
    ENDIF
    IF (YDVARS%EFB3%LADV) THEN
      SELF%EFB3   => YDCPG_SL1%EFB3%P
      SELF%F_EFB3 => YDCPG_SL1%EFB3%F_P
    ELSE
      SELF%EFB3   => YDVARS%EFB3%T1
      SELF%F_EFB3 => YDVARS%EFB3%FT1
    ENDIF
    IF (YDVARS%A%LADV) THEN
      SELF%A   => YDCPG_SL1%A%P
      SELF%F_A => YDCPG_SL1%A%F_P
    ELSE
      SELF%A   => YDVARS%A%T1
      SELF%F_A => YDVARS%A%FT1
    ENDIF
    IF (YDVARS%O3%LADV) THEN
      SELF%O3   => YDCPG_SL1%O3%P
      SELF%F_O3 => YDCPG_SL1%O3%F_P
    ELSE
      SELF%O3   => YDVARS%O3%T1
      SELF%F_O3 => YDVARS%O3%FT1
    ENDIF
    IF (YDVARS%SRC%LADV) THEN
      SELF%SRC   => YDCPG_SL1%SRC%P
      SELF%F_SRC => YDCPG_SL1%SRC%F_P
    ELSE
      SELF%SRC   => YDVARS%SRC%T1
      SELF%F_SRC => YDVARS%SRC%FT1
    ENDIF
    IF (YDVARS%MXL%LADV) THEN
      SELF%MXL   => YDCPG_SL1%MXL%P
      SELF%F_MXL => YDCPG_SL1%MXL%F_P
    ELSE
      SELF%MXL   => YDVARS%MXL%T1
      SELF%F_MXL => YDVARS%MXL%FT1
    ENDIF
    IF (YDVARS%SHTUR%LADV) THEN
      SELF%SHTUR   => YDCPG_SL1%SHTUR%P
      SELF%F_SHTUR => YDCPG_SL1%SHTUR%F_P
    ELSE
      SELF%SHTUR   => YDVARS%SHTUR%T1
      SELF%F_SHTUR => YDVARS%SHTUR%FT1
    ENDIF
    IF (YDVARS%FQTUR%LADV) THEN
      SELF%FQTUR   => YDCPG_SL1%FQTUR%P
      SELF%F_FQTUR => YDCPG_SL1%FQTUR%F_P
    ELSE
      SELF%FQTUR   => YDVARS%FQTUR%T1
      SELF%F_FQTUR => YDVARS%FQTUR%FT1
    ENDIF
    IF (YDVARS%FSTUR%LADV) THEN
      SELF%FSTUR   => YDCPG_SL1%FSTUR%P
      SELF%F_FSTUR => YDCPG_SL1%FSTUR%F_P
    ELSE
      SELF%FSTUR   => YDVARS%FSTUR%T1
      SELF%F_FSTUR => YDVARS%FSTUR%FT1
    ENDIF
    IF (YDVARS%CPF%LADV) THEN
      SELF%CPF   => YDCPG_SL1%CPF%P
      SELF%F_CPF => YDCPG_SL1%CPF%F_P
    ELSE
      SELF%CPF   => YDVARS%CPF%T1
      SELF%F_CPF => YDVARS%CPF%FT1
    ENDIF
    IF (YDVARS%SPF%LADV) THEN
      SELF%SPF   => YDCPG_SL1%SPF%P
      SELF%F_SPF => YDCPG_SL1%SPF%F_P
    ELSE
      SELF%SPF   => YDVARS%SPF%T1
      SELF%F_SPF => YDVARS%SPF%FT1
    ENDIF
    IF (YDVARS%CVGQ%LADV) THEN
      SELF%CVGQ   => YDCPG_SL1%CVGQ%P
      SELF%F_CVGQ => YDCPG_SL1%CVGQ%F_P
    ELSE
      SELF%CVGQ   => YDVARS%CVGQ%T1
      SELF%F_CVGQ => YDVARS%CVGQ%FT1
    ENDIF
    IF (YDVARS%QVA%LADV) THEN
      SELF%QVA   => YDCPG_SL1%QVA%P
      SELF%F_QVA => YDCPG_SL1%QVA%F_P
    ELSE
      SELF%QVA   => YDVARS%QVA%T1
      SELF%F_QVA => YDVARS%QVA%FT1
    ENDIF
    IF (YDVARS%LRCH4%LADV) THEN
      SELF%LRCH4   => YDCPG_SL1%LRCH4%P
      SELF%F_LRCH4 => YDCPG_SL1%LRCH4%F_P
    ELSE
      SELF%LRCH4   => YDVARS%LRCH4%T1
      SELF%F_LRCH4 => YDVARS%LRCH4%FT1
    ENDIF
    IF (YDVARS%PHYCTY%LADV) THEN
      SELF%PHYCTY   => YDCPG_SL1%PHYCTY%P
      SELF%F_PHYCTY => YDCPG_SL1%PHYCTY%F_P
    ELSE
      SELF%PHYCTY   => YDVARS%PHYCTY%T1
      SELF%F_PHYCTY => YDVARS%PHYCTY%FT1
    ENDIF
    IF (YDVARS%RSPEC%LADV) THEN
      SELF%RSPEC   => YDCPG_SL1%RSPEC%P
      SELF%F_RSPEC => YDCPG_SL1%RSPEC%F_P
    ELSE
      SELF%RSPEC   => YDVARS%RSPEC%T1
      SELF%F_RSPEC => YDVARS%RSPEC%FT1
    ENDIF
    IF (YDVARS%SDSAT%LADV) THEN
      SELF%SDSAT   => YDCPG_SL1%SDSAT%P
      SELF%F_SDSAT => YDCPG_SL1%SDSAT%F_P
    ELSE
      SELF%SDSAT   => YDVARS%SDSAT%T1
      SELF%F_SDSAT => YDVARS%SDSAT%FT1
    ENDIF
    IF (YDVARS%CVV%LADV) THEN
      SELF%CVV   => YDCPG_SL1%CVV%P
      SELF%F_CVV => YDCPG_SL1%CVV%F_P
    ELSE
      SELF%CVV   => YDVARS%CVV%T1
      SELF%F_CVV => YDVARS%CVV%FT1
    ENDIF
    IF (YDVARS%RKTH%LADV) THEN
      SELF%RKTH   => YDCPG_SL1%RKTH%P
      SELF%F_RKTH => YDCPG_SL1%RKTH%F_P
    ELSE
      SELF%RKTH   => YDVARS%RKTH%T1
      SELF%F_RKTH => YDVARS%RKTH%FT1
    ENDIF
    IF (YDVARS%RKTQV%LADV) THEN
      SELF%RKTQV   => YDCPG_SL1%RKTQV%P
      SELF%F_RKTQV => YDCPG_SL1%RKTQV%F_P
    ELSE
      SELF%RKTQV   => YDVARS%RKTQV%T1
      SELF%F_RKTQV => YDVARS%RKTQV%FT1
    ENDIF
    IF (YDVARS%RKTQC%LADV) THEN
      SELF%RKTQC   => YDCPG_SL1%RKTQC%P
      SELF%F_RKTQC => YDCPG_SL1%RKTQC%F_P
    ELSE
      SELF%RKTQC   => YDVARS%RKTQC%T1
      SELF%F_RKTQC => YDVARS%RKTQC%FT1
    ENDIF
    IF (YDVARS%UOM%LADV) THEN
      SELF%UOM   => YDCPG_SL1%UOM%P
      SELF%F_UOM => YDCPG_SL1%UOM%F_P
    ELSE
      SELF%UOM   => YDVARS%UOM%T1
      SELF%F_UOM => YDVARS%UOM%FT1
    ENDIF
    IF (YDVARS%UAL%LADV) THEN
      SELF%UAL   => YDCPG_SL1%UAL%P
      SELF%F_UAL => YDCPG_SL1%UAL%F_P
    ELSE
      SELF%UAL   => YDVARS%UAL%T1
      SELF%F_UAL => YDVARS%UAL%FT1
    ENDIF
    IF (YDVARS%DOM%LADV) THEN
      SELF%DOM   => YDCPG_SL1%DOM%P
      SELF%F_DOM => YDCPG_SL1%DOM%F_P
    ELSE
      SELF%DOM   => YDVARS%DOM%T1
      SELF%F_DOM => YDVARS%DOM%FT1
    ENDIF
    IF (YDVARS%DAL%LADV) THEN
      SELF%DAL   => YDCPG_SL1%DAL%P
      SELF%F_DAL => YDCPG_SL1%DAL%F_P
    ELSE
      SELF%DAL   => YDVARS%DAL%T1
      SELF%F_DAL => YDVARS%DAL%FT1
    ENDIF
    IF (YDVARS%UEN%LADV) THEN
      SELF%UEN   => YDCPG_SL1%UEN%P
      SELF%F_UEN => YDCPG_SL1%UEN%F_P
    ELSE
      SELF%UEN   => YDVARS%UEN%T1
      SELF%F_UEN => YDVARS%UEN%FT1
    ENDIF
    IF (YDVARS%UNEBH%LADV) THEN
      SELF%UNEBH   => YDCPG_SL1%UNEBH%P
      SELF%F_UNEBH => YDCPG_SL1%UNEBH%F_P
    ELSE
      SELF%UNEBH   => YDVARS%UNEBH%T1
      SELF%F_UNEBH => YDVARS%UNEBH%FT1
    ENDIF
    IF (YDVARS%FSD%LADV) THEN
      SELF%FSD   => YDCPG_SL1%FSD%P
      SELF%F_FSD => YDCPG_SL1%FSD%F_P
    ELSE
      SELF%FSD   => YDVARS%FSD%T1
      SELF%F_FSD => YDVARS%FSD%FT1
    ENDIF
  ENDIF  

ELSE

  SELF%U     => YDVARS%U%T1
  SELF%F_U   => YDVARS%U%FT1
  SELF%V     => YDVARS%V%T1
  SELF%F_V   => YDVARS%V%FT1
  SELF%T     => YDVARS%T%T1
  SELF%F_T   => YDVARS%T%FT1
  SELF%SVD   => YDVARS%SVD%T1
  SELF%F_SVD => YDVARS%SVD%FT1
  SELF%SP    => YDVARS%SP%T1
  SELF%F_SP  => YDVARS%SP%FT1

  SELF%Q   => YDVARS%Q%T1
  SELF%F_Q => YDVARS%Q%FT1
  SELF%I   => YDVARS%I%T1
  SELF%F_I => YDVARS%I%FT1
  SELF%L   => YDVARS%L%T1
  SELF%F_L => YDVARS%L%FT1
  SELF%LCONV   => YDVARS%LCONV%T1
  SELF%F_LCONV => YDVARS%LCONV%FT1
  SELF%ICONV   => YDVARS%ICONV%T1
  SELF%F_ICONV => YDVARS%ICONV%FT1
  SELF%RCONV   => YDVARS%RCONV%T1
  SELF%F_RCONV => YDVARS%RCONV%FT1
  SELF%SCONV   => YDVARS%SCONV%T1
  SELF%F_SCONV => YDVARS%SCONV%FT1
  SELF%IRAD   => YDVARS%IRAD%T1
  SELF%F_IRAD => YDVARS%IRAD%FT1
  SELF%LRAD   => YDVARS%LRAD%T1
  SELF%F_LRAD => YDVARS%LRAD%FT1
  SELF%S   => YDVARS%S%T1
  SELF%F_S => YDVARS%S%FT1
  SELF%R   => YDVARS%R%T1
  SELF%F_R => YDVARS%R%FT1
  SELF%G   => YDVARS%G%T1
  SELF%F_G => YDVARS%G%FT1
  SELF%H   => YDVARS%H%T1
  SELF%F_H => YDVARS%H%FT1
  SELF%TKE   => YDVARS%TKE%T1
  SELF%F_TKE => YDVARS%TKE%FT1
  SELF%TTE   => YDVARS%TTE%T1
  SELF%F_TTE => YDVARS%TTE%FT1
  SELF%EFB1   => YDVARS%EFB1%T1
  SELF%F_EFB1 => YDVARS%EFB1%FT1
  SELF%EFB2   => YDVARS%EFB2%T1
  SELF%F_EFB2 => YDVARS%EFB2%FT1
  SELF%EFB3   => YDVARS%EFB3%T1
  SELF%F_EFB3 => YDVARS%EFB3%FT1
  SELF%A   => YDVARS%A%T1
  SELF%F_A => YDVARS%A%FT1
  SELF%O3   => YDVARS%O3%T1
  SELF%F_O3 => YDVARS%O3%FT1
  SELF%SRC   => YDVARS%SRC%T1
  SELF%F_SRC => YDVARS%SRC%FT1
  SELF%MXL   => YDVARS%MXL%T1
  SELF%F_MXL => YDVARS%MXL%FT1
  SELF%SHTUR   => YDVARS%SHTUR%T1
  SELF%F_SHTUR => YDVARS%SHTUR%FT1
  SELF%FQTUR   => YDVARS%FQTUR%T1
  SELF%F_FQTUR => YDVARS%FQTUR%FT1
  SELF%FSTUR   => YDVARS%FSTUR%T1
  SELF%F_FSTUR => YDVARS%FSTUR%FT1
  SELF%CPF   => YDVARS%CPF%T1
  SELF%F_CPF => YDVARS%CPF%FT1
  SELF%SPF   => YDVARS%SPF%T1
  SELF%F_SPF => YDVARS%SPF%FT1
  SELF%CVGQ   => YDVARS%CVGQ%T1
  SELF%F_CVGQ => YDVARS%CVGQ%FT1
  SELF%QVA   => YDVARS%QVA%T1
  SELF%F_QVA => YDVARS%QVA%FT1
  SELF%LRCH4   => YDVARS%LRCH4%T1
  SELF%F_LRCH4 => YDVARS%LRCH4%FT1
  SELF%PHYCTY   => YDVARS%PHYCTY%T1
  SELF%F_PHYCTY => YDVARS%PHYCTY%FT1
  SELF%RSPEC   => YDVARS%RSPEC%T1
  SELF%F_RSPEC => YDVARS%RSPEC%FT1
  SELF%SDSAT   => YDVARS%SDSAT%T1
  SELF%F_SDSAT => YDVARS%SDSAT%FT1
  SELF%CVV   => YDVARS%CVV%T1
  SELF%F_CVV => YDVARS%CVV%FT1
  SELF%RKTH   => YDVARS%RKTH%T1
  SELF%F_RKTH => YDVARS%RKTH%FT1
  SELF%RKTQV   => YDVARS%RKTQV%T1
  SELF%F_RKTQV => YDVARS%RKTQV%FT1
  SELF%RKTQC   => YDVARS%RKTQC%T1
  SELF%F_RKTQC => YDVARS%RKTQC%FT1
  SELF%UOM   => YDVARS%UOM%T1
  SELF%F_UOM => YDVARS%UOM%FT1
  SELF%UAL   => YDVARS%UAL%T1
  SELF%F_UAL => YDVARS%UAL%FT1
  SELF%DOM   => YDVARS%DOM%T1
  SELF%F_DOM => YDVARS%DOM%FT1
  SELF%DAL   => YDVARS%DAL%T1
  SELF%F_DAL => YDVARS%DAL%FT1
  SELF%UEN   => YDVARS%UEN%T1
  SELF%F_UEN => YDVARS%UEN%FT1
  SELF%UNEBH   => YDVARS%UNEBH%T1
  SELF%F_UNEBH => YDVARS%UNEBH%FT1
  SELF%FSD   => YDVARS%FSD%T1
  SELF%F_FSD => YDVARS%FSD%FT1

ENDIF

END ASSOCIATE

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)
CLASS (MF_PHYS_NEXT_STATE_TYPE)              :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

IF (ASSOCIATED (SELF%F_U)) THEN
  SELF%U (1:, SELF%DIMS%U%ILEVT1I:) => SELF%F_U%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_V)) THEN
  SELF%V (1:, SELF%DIMS%V%ILEVT1I:) => SELF%F_V%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_T)) THEN
  SELF%T (1:, SELF%DIMS%T%ILEVT1I:) => SELF%F_T%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_SVD)) THEN
  SELF%SVD (1:, SELF%DIMS%SVD%ILEVT1I:) => SELF%F_SVD%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%F_Q)) THEN
  SELF%Q (1:, SELF%DIMS%Q%ILEVT1I:) => SELF%F_Q%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_I)) THEN
  SELF%I (1:, SELF%DIMS%I%ILEVT1I:) => SELF%F_I%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_L)) THEN
  SELF%L (1:, SELF%DIMS%L%ILEVT1I:) => SELF%F_L%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_LCONV)) THEN
  SELF%LCONV (1:, SELF%DIMS%LCONV%ILEVT1I:) => SELF%F_LCONV%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_ICONV)) THEN
  SELF%ICONV (1:, SELF%DIMS%ICONV%ILEVT1I:) => SELF%F_ICONV%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_RCONV)) THEN
  SELF%RCONV (1:, SELF%DIMS%RCONV%ILEVT1I:) => SELF%F_RCONV%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_SCONV)) THEN
  SELF%SCONV (1:, SELF%DIMS%SCONV%ILEVT1I:) => SELF%F_SCONV%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_IRAD)) THEN
  SELF%IRAD (1:, SELF%DIMS%IRAD%ILEVT1I:) => SELF%F_IRAD%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_LRAD)) THEN
  SELF%LRAD (1:, SELF%DIMS%LRAD%ILEVT1I:) => SELF%F_LRAD%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_S)) THEN
  SELF%S (1:, SELF%DIMS%S%ILEVT1I:) => SELF%F_S%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_R)) THEN
  SELF%R (1:, SELF%DIMS%R%ILEVT1I:) => SELF%F_R%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_G)) THEN
  SELF%G (1:, SELF%DIMS%G%ILEVT1I:) => SELF%F_G%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_H)) THEN
  SELF%H (1:, SELF%DIMS%H%ILEVT1I:) => SELF%F_H%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_TKE)) THEN
  SELF%TKE (1:, SELF%DIMS%TKE%ILEVT1I:) => SELF%F_TKE%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_TTE)) THEN
  SELF%TTE (1:, SELF%DIMS%TTE%ILEVT1I:) => SELF%F_TTE%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_EFB1)) THEN
  SELF%EFB1 (1:, SELF%DIMS%EFB1%ILEVT1I:) => SELF%F_EFB1%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_EFB2)) THEN
  SELF%EFB2 (1:, SELF%DIMS%EFB2%ILEVT1I:) => SELF%F_EFB2%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_EFB3)) THEN
  SELF%EFB3 (1:, SELF%DIMS%EFB3%ILEVT1I:) => SELF%F_EFB3%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_A)) THEN
  SELF%A (1:, SELF%DIMS%A%ILEVT1I:) => SELF%F_A%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_O3)) THEN
  SELF%O3 (1:, SELF%DIMS%O3%ILEVT1I:) => SELF%F_O3%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_SRC)) THEN
  SELF%SRC (1:, SELF%DIMS%SRC%ILEVT1I:) => SELF%F_SRC%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_MXL)) THEN
  SELF%MXL (1:, SELF%DIMS%MXL%ILEVT1I:) => SELF%F_MXL%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_SHTUR)) THEN
  SELF%SHTUR (1:, SELF%DIMS%SHTUR%ILEVT1I:) => SELF%F_SHTUR%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_FQTUR)) THEN
  SELF%FQTUR (1:, SELF%DIMS%FQTUR%ILEVT1I:) => SELF%F_FQTUR%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_FSTUR)) THEN
  SELF%FSTUR (1:, SELF%DIMS%FSTUR%ILEVT1I:) => SELF%F_FSTUR%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_CPF)) THEN
  SELF%CPF (1:, SELF%DIMS%CPF%ILEVT1I:) => SELF%F_CPF%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_SPF)) THEN
  SELF%SPF (1:, SELF%DIMS%SPF%ILEVT1I:) => SELF%F_SPF%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_CVGQ)) THEN
  SELF%CVGQ (1:, SELF%DIMS%CVGQ%ILEVT1I:) => SELF%F_CVGQ%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_QVA)) THEN
  SELF%QVA (1:, SELF%DIMS%QVA%ILEVT1I:) => SELF%F_QVA%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_LRCH4)) THEN
  SELF%LRCH4 (1:, SELF%DIMS%LRCH4%ILEVT1I:) => SELF%F_LRCH4%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_PHYCTY)) THEN
  SELF%PHYCTY (1:, SELF%DIMS%PHYCTY%ILEVT1I:) => SELF%F_PHYCTY%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_RSPEC)) THEN
  SELF%RSPEC (1:, SELF%DIMS%RSPEC%ILEVT1I:) => SELF%F_RSPEC%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_SDSAT)) THEN
  SELF%SDSAT (1:, SELF%DIMS%SDSAT%ILEVT1I:) => SELF%F_SDSAT%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_CVV)) THEN
  SELF%CVV (1:, SELF%DIMS%CVV%ILEVT1I:) => SELF%F_CVV%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_RKTH)) THEN
  SELF%RKTH (1:, SELF%DIMS%RKTH%ILEVT1I:) => SELF%F_RKTH%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_RKTQV)) THEN
  SELF%RKTQV (1:, SELF%DIMS%RKTQV%ILEVT1I:) => SELF%F_RKTQV%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_RKTQC)) THEN
  SELF%RKTQC (1:, SELF%DIMS%RKTQC%ILEVT1I:) => SELF%F_RKTQC%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_UOM)) THEN
  SELF%UOM (1:, SELF%DIMS%UOM%ILEVT1I:) => SELF%F_UOM%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_UAL)) THEN
  SELF%UAL (1:, SELF%DIMS%UAL%ILEVT1I:) => SELF%F_UAL%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_DOM)) THEN
  SELF%DOM (1:, SELF%DIMS%DOM%ILEVT1I:) => SELF%F_DOM%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_DAL)) THEN
  SELF%DAL (1:, SELF%DIMS%DAL%ILEVT1I:) => SELF%F_DAL%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_UEN)) THEN
  SELF%UEN (1:, SELF%DIMS%UEN%ILEVT1I:) => SELF%F_UEN%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_UNEBH)) THEN
  SELF%UNEBH (1:, SELF%DIMS%UNEBH%ILEVT1I:) => SELF%F_UNEBH%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%F_FSD)) THEN
  SELF%FSD (1:, SELF%DIMS%FSD%ILEVT1I:) => SELF%F_FSD%GET_VIEW (BLOCK_INDEX)
ENDIF

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW 

END MODULE MF_PHYS_NEXT_STATE_TYPE_MOD



