MODULE MF_PHYS_NEXT_STATE_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE FIELD_MODULE
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_DIMS_VARS_TYPE
IMPLICIT NONE

TYPE MF_PHYS_NEXT_STATE_2D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:) => NULL ()
  TYPE (FIELD_2D), POINTER :: F_P => NULL ()
END TYPE MF_PHYS_NEXT_STATE_2D_TYPE

TYPE MF_PHYS_NEXT_STATE_3D_TYPE
  REAL (KIND=JPRB), POINTER, CONTIGUOUS :: P (:, :) => NULL ()
  TYPE (FIELD_3D), POINTER :: F_P => NULL ()
END TYPE MF_PHYS_NEXT_STATE_3D_TYPE

TYPE MF_PHYS_NEXT_STATE_TYPE

  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: U
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: V
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: T
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SVD
  TYPE (MF_PHYS_NEXT_STATE_2D_TYPE) :: SP

  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: Q
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: I
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: L
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: LCONV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: ICONV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RCONV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SCONV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: IRAD
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: LRAD
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: S
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: R
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: G
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: H
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: TKE
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: TTE
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: EFB1
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: EFB2
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: EFB3
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: A
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: O3
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SRC
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: MXL
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SHTUR
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: FQTUR
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: FSTUR
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: CPF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SPF
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: CVGQ
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: QVA
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: GHG (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: CHEM (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AERO (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: LRCH4
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: FORC (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: EZDIAG (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: ERA40 (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: NOGW (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: EDRP (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: SLDIA (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AERAOT (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AERLISI (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AEROUT (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: AEROCLIM (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: UVP (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: PHYS (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: PHYCTY
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RSPEC
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: SDSAT
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: CVV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RKTH
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RKTQV
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: RKTQC
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: UOM
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: UAL
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: DOM
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: DAL
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: UEN
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: UNEBH
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: CRM (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: LIMA (:)
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE) :: FSD
  TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), ALLOCATABLE :: EXT (:)


  TYPE (CPG_DIMS_VARS_TYPE) :: DIMS

CONTAINS

  PROCEDURE :: INIT => MF_PHYS_NEXT_STATE_TYPE_INIT
  PROCEDURE :: UPDATE_VIEW => MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW

END TYPE MF_PHYS_NEXT_STATE_TYPE

CONTAINS

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT (SELF, YDCPG_SL1, YDGEOMETRY, YDVARS, YDMODEL)

USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMCT0, ONLY : LSLAG, LTWOTL
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
USE CPG_TYPE_MOD, ONLY : CPG_SL1_TYPE
USE TYPE_MODEL  , ONLY : MODEL

CLASS (MF_PHYS_NEXT_STATE_TYPE)     :: SELF
TYPE (CPG_SL1_TYPE),    INTENT (IN) :: YDCPG_SL1
TYPE(GEOMETRY),         INTENT (IN) :: YDGEOMETRY
TYPE (FIELD_VARIABLES), INTENT (IN) :: YDVARS
TYPE(MODEL),            INTENT (IN) :: YDMODEL

INTEGER (KIND=JPIM) :: JGFL

ASSOCIATE (YDDYN => YDMODEL%YRML_DYN%YRDYN)

CALL SELF%DIMS%INIT (YDGEOMETRY, YDMODEL, YDVARS)

IF (LSLAG) THEN

  ! Taken from cp_ptrslb1.F90
  
  IF (YDDYN%NWLAG == 4) THEN
    SELF%U%P   => YDCPG_SL1%U0%P 
    SELF%U%F_P => YDCPG_SL1%U0%F_P
    SELF%V%P   => YDCPG_SL1%V0%P 
    SELF%V%F_P => YDCPG_SL1%V0%F_P
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%U%P   => YDCPG_SL1%UF9%P 
      SELF%U%F_P => YDCPG_SL1%UF9%F_P
      SELF%V%P   => YDCPG_SL1%VF9%P 
      SELF%V%F_P => YDCPG_SL1%VF9%F_P
    ELSE
      SELF%U%P   => YDCPG_SL1%U9%P 
      SELF%U%F_P => YDCPG_SL1%U9%F_P
      SELF%V%P   => YDCPG_SL1%V9%P 
      SELF%V%F_P => YDCPG_SL1%V9%F_P
    ENDIF
  ENDIF
  ! * temperature
  IF (YDDYN%NTLAG == 4) THEN
    SELF%T%P   => YDCPG_SL1%T0%P 
    SELF%T%F_P => YDCPG_SL1%T0%F_P
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%T%P   => YDCPG_SL1%TF9%P 
      SELF%T%F_P => YDCPG_SL1%TF9%F_P
    ELSE
      SELF%T%P   => YDCPG_SL1%T9%P 
      SELF%T%F_P => YDCPG_SL1%T9%F_P
    ENDIF
  ENDIF
  ! * vertical divergence
  IF (YDDYN%NSVDLAG == 4) THEN
    SELF%SVD%P   => YDCPG_SL1%VD0%P
    SELF%SVD%F_P => YDCPG_SL1%VD0%F_P
  ELSE
    IF (YDDYN%NSPLTHOI /= 0) THEN
      SELF%SVD%P   => YDCPG_SL1%VDF9%P
      SELF%SVD%F_P => YDCPG_SL1%VDF9%F_P
    ELSE
      SELF%SVD%P   => YDCPG_SL1%VD9%P
      SELF%SVD%F_P => YDCPG_SL1%VD9%F_P
    ENDIF
  ENDIF

  SELF%SP%P   => YDCPG_SL1%SP9%P
  SELF%SP%F_P => YDCPG_SL1%SP9%F_P

  ! * GFL arrays
  IF (YDDYN%LSPLTHOIGFL.OR.(YDDYN%NSPLTHOI /= 0)) THEN
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%Q, SELF%Q, YDCPG_SL1%Q)
!   IF (YDVARS%Q%LADV) THEN
!     SELF%Q%P   => YDCPG_SL1%Q%P_F
!     SELF%Q%F_P => YDCPG_SL1%Q%F_P_F
!   ELSE
!     SELF%Q%P   => YDVARS%Q%T1
!     SELF%Q%F_P => YDVARS%Q%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%I, SELF%I, YDCPG_SL1%I)
!   IF (YDVARS%I%LADV) THEN
!     SELF%I%P   => YDCPG_SL1%I%P_F
!     SELF%I%F_P => YDCPG_SL1%I%F_P_F
!   ELSE
!     SELF%I%P   => YDVARS%I%T1
!     SELF%I%F_P => YDVARS%I%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%L, SELF%L, YDCPG_SL1%L)
!   IF (YDVARS%L%LADV) THEN
!     SELF%L%P   => YDCPG_SL1%L%P_F
!     SELF%L%F_P => YDCPG_SL1%L%F_P_F
!   ELSE
!     SELF%L%P   => YDVARS%L%T1
!     SELF%L%F_P => YDVARS%L%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%LCONV, SELF%LCONV, YDCPG_SL1%LCONV)
!   IF (YDVARS%LCONV%LADV) THEN
!     SELF%LCONV%P   => YDCPG_SL1%LCONV%P_F
!     SELF%LCONV%F_P => YDCPG_SL1%LCONV%F_P_F
!   ELSE
!     SELF%LCONV%P   => YDVARS%LCONV%T1
!     SELF%LCONV%F_P => YDVARS%LCONV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%ICONV, SELF%ICONV, YDCPG_SL1%ICONV)
!   IF (YDVARS%ICONV%LADV) THEN
!     SELF%ICONV%P   => YDCPG_SL1%ICONV%P_F
!     SELF%ICONV%F_P => YDCPG_SL1%ICONV%F_P_F
!   ELSE
!     SELF%ICONV%P   => YDVARS%ICONV%T1
!     SELF%ICONV%F_P => YDVARS%ICONV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%RCONV, SELF%RCONV, YDCPG_SL1%RCONV)
!   IF (YDVARS%RCONV%LADV) THEN
!     SELF%RCONV%P   => YDCPG_SL1%RCONV%P_F
!     SELF%RCONV%F_P => YDCPG_SL1%RCONV%F_P_F
!   ELSE
!     SELF%RCONV%P   => YDVARS%RCONV%T1
!     SELF%RCONV%F_P => YDVARS%RCONV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%SCONV, SELF%SCONV, YDCPG_SL1%SCONV)
!   IF (YDVARS%SCONV%LADV) THEN
!     SELF%SCONV%P   => YDCPG_SL1%SCONV%P_F
!     SELF%SCONV%F_P => YDCPG_SL1%SCONV%F_P_F
!   ELSE
!     SELF%SCONV%P   => YDVARS%SCONV%T1
!     SELF%SCONV%F_P => YDVARS%SCONV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%IRAD, SELF%IRAD, YDCPG_SL1%IRAD)
!   IF (YDVARS%IRAD%LADV) THEN
!     SELF%IRAD%P   => YDCPG_SL1%IRAD%P_F
!     SELF%IRAD%F_P => YDCPG_SL1%IRAD%F_P_F
!   ELSE
!     SELF%IRAD%P   => YDVARS%IRAD%T1
!     SELF%IRAD%F_P => YDVARS%IRAD%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%LRAD, SELF%LRAD, YDCPG_SL1%LRAD)
!   IF (YDVARS%LRAD%LADV) THEN
!     SELF%LRAD%P   => YDCPG_SL1%LRAD%P_F
!     SELF%LRAD%F_P => YDCPG_SL1%LRAD%F_P_F
!   ELSE
!     SELF%LRAD%P   => YDVARS%LRAD%T1
!     SELF%LRAD%F_P => YDVARS%LRAD%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%S, SELF%S, YDCPG_SL1%S)
!   IF (YDVARS%S%LADV) THEN
!     SELF%S%P   => YDCPG_SL1%S%P_F
!     SELF%S%F_P => YDCPG_SL1%S%F_P_F
!   ELSE
!     SELF%S%P   => YDVARS%S%T1
!     SELF%S%F_P => YDVARS%S%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%R, SELF%R, YDCPG_SL1%R)
!   IF (YDVARS%R%LADV) THEN
!     SELF%R%P   => YDCPG_SL1%R%P_F
!     SELF%R%F_P => YDCPG_SL1%R%F_P_F
!   ELSE
!     SELF%R%P   => YDVARS%R%T1
!     SELF%R%F_P => YDVARS%R%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%G, SELF%G, YDCPG_SL1%G)
!   IF (YDVARS%G%LADV) THEN
!     SELF%G%P   => YDCPG_SL1%G%P_F
!     SELF%G%F_P => YDCPG_SL1%G%F_P_F
!   ELSE
!     SELF%G%P   => YDVARS%G%T1
!     SELF%G%F_P => YDVARS%G%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%H, SELF%H, YDCPG_SL1%H)
!   IF (YDVARS%H%LADV) THEN
!     SELF%H%P   => YDCPG_SL1%H%P_F
!     SELF%H%F_P => YDCPG_SL1%H%F_P_F
!   ELSE
!     SELF%H%P   => YDVARS%H%T1
!     SELF%H%F_P => YDVARS%H%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%TKE, SELF%TKE, YDCPG_SL1%TKE)
!   IF (YDVARS%TKE%LADV) THEN
!     SELF%TKE%P   => YDCPG_SL1%TKE%P_F
!     SELF%TKE%F_P => YDCPG_SL1%TKE%F_P_F
!   ELSE
!     SELF%TKE%P   => YDVARS%TKE%T1
!     SELF%TKE%F_P => YDVARS%TKE%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%TTE, SELF%TTE, YDCPG_SL1%TTE)
!   IF (YDVARS%TTE%LADV) THEN
!     SELF%TTE%P   => YDCPG_SL1%TTE%P_F
!     SELF%TTE%F_P => YDCPG_SL1%TTE%F_P_F
!   ELSE
!     SELF%TTE%P   => YDVARS%TTE%T1
!     SELF%TTE%F_P => YDVARS%TTE%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%EFB1, SELF%EFB1, YDCPG_SL1%EFB1)
!   IF (YDVARS%EFB1%LADV) THEN
!     SELF%EFB1%P   => YDCPG_SL1%EFB1%P_F
!     SELF%EFB1%F_P => YDCPG_SL1%EFB1%F_P_F
!   ELSE
!     SELF%EFB1%P   => YDVARS%EFB1%T1
!     SELF%EFB1%F_P => YDVARS%EFB1%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%EFB2, SELF%EFB2, YDCPG_SL1%EFB2)
!   IF (YDVARS%EFB2%LADV) THEN
!     SELF%EFB2%P   => YDCPG_SL1%EFB2%P_F
!     SELF%EFB2%F_P => YDCPG_SL1%EFB2%F_P_F
!   ELSE
!     SELF%EFB2%P   => YDVARS%EFB2%T1
!     SELF%EFB2%F_P => YDVARS%EFB2%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%EFB3, SELF%EFB3, YDCPG_SL1%EFB3)
!   IF (YDVARS%EFB3%LADV) THEN
!     SELF%EFB3%P   => YDCPG_SL1%EFB3%P_F
!     SELF%EFB3%F_P => YDCPG_SL1%EFB3%F_P_F
!   ELSE
!     SELF%EFB3%P   => YDVARS%EFB3%T1
!     SELF%EFB3%F_P => YDVARS%EFB3%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%A, SELF%A, YDCPG_SL1%A)
!   IF (YDVARS%A%LADV) THEN
!     SELF%A%P   => YDCPG_SL1%A%P_F
!     SELF%A%F_P => YDCPG_SL1%A%F_P_F
!   ELSE
!     SELF%A%P   => YDVARS%A%T1
!     SELF%A%F_P => YDVARS%A%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%O3, SELF%O3, YDCPG_SL1%O3)
!   IF (YDVARS%O3%LADV) THEN
!     SELF%O3%P   => YDCPG_SL1%O3%P_F
!     SELF%O3%F_P => YDCPG_SL1%O3%F_P_F
!   ELSE
!     SELF%O3%P   => YDVARS%O3%T1
!     SELF%O3%F_P => YDVARS%O3%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%SRC, SELF%SRC, YDCPG_SL1%SRC)
!   IF (YDVARS%SRC%LADV) THEN
!     SELF%SRC%P   => YDCPG_SL1%SRC%P_F
!     SELF%SRC%F_P => YDCPG_SL1%SRC%F_P_F
!   ELSE
!     SELF%SRC%P   => YDVARS%SRC%T1
!     SELF%SRC%F_P => YDVARS%SRC%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%MXL, SELF%MXL, YDCPG_SL1%MXL)
!   IF (YDVARS%MXL%LADV) THEN
!     SELF%MXL%P   => YDCPG_SL1%MXL%P_F
!     SELF%MXL%F_P => YDCPG_SL1%MXL%F_P_F
!   ELSE
!     SELF%MXL%P   => YDVARS%MXL%T1
!     SELF%MXL%F_P => YDVARS%MXL%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%SHTUR, SELF%SHTUR, YDCPG_SL1%SHTUR)
!   IF (YDVARS%SHTUR%LADV) THEN
!     SELF%SHTUR%P   => YDCPG_SL1%SHTUR%P_F
!     SELF%SHTUR%F_P => YDCPG_SL1%SHTUR%F_P_F
!   ELSE
!     SELF%SHTUR%P   => YDVARS%SHTUR%T1
!     SELF%SHTUR%F_P => YDVARS%SHTUR%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%FQTUR, SELF%FQTUR, YDCPG_SL1%FQTUR)
!   IF (YDVARS%FQTUR%LADV) THEN
!     SELF%FQTUR%P   => YDCPG_SL1%FQTUR%P_F
!     SELF%FQTUR%F_P => YDCPG_SL1%FQTUR%F_P_F
!   ELSE
!     SELF%FQTUR%P   => YDVARS%FQTUR%T1
!     SELF%FQTUR%F_P => YDVARS%FQTUR%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%FSTUR, SELF%FSTUR, YDCPG_SL1%FSTUR)
!   IF (YDVARS%FSTUR%LADV) THEN
!     SELF%FSTUR%P   => YDCPG_SL1%FSTUR%P_F
!     SELF%FSTUR%F_P => YDCPG_SL1%FSTUR%F_P_F
!   ELSE
!     SELF%FSTUR%P   => YDVARS%FSTUR%T1
!     SELF%FSTUR%F_P => YDVARS%FSTUR%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%CPF, SELF%CPF, YDCPG_SL1%CPF)
!   IF (YDVARS%CPF%LADV) THEN
!     SELF%CPF%P   => YDCPG_SL1%CPF%P_F
!     SELF%CPF%F_P => YDCPG_SL1%CPF%F_P_F
!   ELSE
!     SELF%CPF%P   => YDVARS%CPF%T1
!     SELF%CPF%F_P => YDVARS%CPF%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%SPF, SELF%SPF, YDCPG_SL1%SPF)
!   IF (YDVARS%SPF%LADV) THEN
!     SELF%SPF%P   => YDCPG_SL1%SPF%P_F
!     SELF%SPF%F_P => YDCPG_SL1%SPF%F_P_F
!   ELSE
!     SELF%SPF%P   => YDVARS%SPF%T1
!     SELF%SPF%F_P => YDVARS%SPF%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%CVGQ, SELF%CVGQ, YDCPG_SL1%CVGQ)
!   IF (YDVARS%CVGQ%LADV) THEN
!     SELF%CVGQ%P   => YDCPG_SL1%CVGQ%P_F
!     SELF%CVGQ%F_P => YDCPG_SL1%CVGQ%F_P_F
!   ELSE
!     SELF%CVGQ%P   => YDVARS%CVGQ%T1
!     SELF%CVGQ%F_P => YDVARS%CVGQ%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%QVA, SELF%QVA, YDCPG_SL1%QVA)
!   IF (YDVARS%QVA%LADV) THEN
!     SELF%QVA%P   => YDCPG_SL1%QVA%P_F
!     SELF%QVA%F_P => YDCPG_SL1%QVA%F_P_F
!   ELSE
!     SELF%QVA%P   => YDVARS%QVA%T1
!     SELF%QVA%F_P => YDVARS%QVA%FT1
!   ENDIF
    ALLOCATE (SELF%GHG (SIZE (YDVARS%GHG)))
    DO JGFL = 1, SIZE (YDVARS%GHG)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%GHG(JGFL), SELF%GHG(JGFL), YDCPG_SL1%GHG(JGFL))
    ENDDO
    ALLOCATE (SELF%CHEM (SIZE (YDVARS%CHEM)))
    DO JGFL = 1, SIZE (YDVARS%CHEM)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%CHEM(JGFL), SELF%CHEM(JGFL), YDCPG_SL1%CHEM(JGFL))
    ENDDO
    ALLOCATE (SELF%AERO (SIZE (YDVARS%AERO)))
    DO JGFL = 1, SIZE (YDVARS%AERO)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%AERO(JGFL), SELF%AERO(JGFL), YDCPG_SL1%AERO(JGFL))
    ENDDO
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%LRCH4, SELF%LRCH4, YDCPG_SL1%LRCH4)
!   IF (YDVARS%LRCH4%LADV) THEN
!     SELF%LRCH4%P   => YDCPG_SL1%LRCH4%P_F
!     SELF%LRCH4%F_P => YDCPG_SL1%LRCH4%F_P_F
!   ELSE
!     SELF%LRCH4%P   => YDVARS%LRCH4%T1
!     SELF%LRCH4%F_P => YDVARS%LRCH4%FT1
!   ENDIF
    ALLOCATE (SELF%FORC (SIZE (YDVARS%FORC)))
    DO JGFL = 1, SIZE (YDVARS%FORC)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%FORC(JGFL), SELF%FORC(JGFL), YDCPG_SL1%FORC(JGFL))
    ENDDO
    ALLOCATE (SELF%EZDIAG (SIZE (YDVARS%EZDIAG)))
    DO JGFL = 1, SIZE (YDVARS%EZDIAG)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%EZDIAG(JGFL), SELF%EZDIAG(JGFL), YDCPG_SL1%EZDIAG(JGFL))
    ENDDO
    ALLOCATE (SELF%ERA40 (SIZE (YDVARS%ERA40)))
    DO JGFL = 1, SIZE (YDVARS%ERA40)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%ERA40(JGFL), SELF%ERA40(JGFL), YDCPG_SL1%ERA40(JGFL))
    ENDDO
    ALLOCATE (SELF%NOGW (SIZE (YDVARS%NOGW)))
    DO JGFL = 1, SIZE (YDVARS%NOGW)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%NOGW(JGFL), SELF%NOGW(JGFL), YDCPG_SL1%NOGW(JGFL))
    ENDDO
    ALLOCATE (SELF%EDRP (SIZE (YDVARS%EDRP)))
    DO JGFL = 1, SIZE (YDVARS%EDRP)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%EDRP(JGFL), SELF%EDRP(JGFL), YDCPG_SL1%EDRP(JGFL))
    ENDDO
    ALLOCATE (SELF%SLDIA (SIZE (YDVARS%SLDIA)))
    DO JGFL = 1, SIZE (YDVARS%SLDIA)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%SLDIA(JGFL), SELF%SLDIA(JGFL), YDCPG_SL1%SLDIA(JGFL))
    ENDDO
    ALLOCATE (SELF%AERAOT (SIZE (YDVARS%AERAOT)))
    DO JGFL = 1, SIZE (YDVARS%AERAOT)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%AERAOT(JGFL), SELF%AERAOT(JGFL), YDCPG_SL1%AERAOT(JGFL))
    ENDDO
    ALLOCATE (SELF%AERLISI (SIZE (YDVARS%AERLISI)))
    DO JGFL = 1, SIZE (YDVARS%AERLISI)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%AERLISI(JGFL), SELF%AERLISI(JGFL), YDCPG_SL1%AERLISI(JGFL))
    ENDDO
    ALLOCATE (SELF%AEROUT (SIZE (YDVARS%AEROUT)))
    DO JGFL = 1, SIZE (YDVARS%AEROUT)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%AEROUT(JGFL), SELF%AEROUT(JGFL), YDCPG_SL1%AEROUT(JGFL))
    ENDDO
    ALLOCATE (SELF%AEROCLIM (SIZE (YDVARS%AEROCLIM)))
    DO JGFL = 1, SIZE (YDVARS%AEROCLIM)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%AEROCLIM(JGFL), SELF%AEROCLIM(JGFL), YDCPG_SL1%AEROCLIM(JGFL))
    ENDDO
    ALLOCATE (SELF%UVP (SIZE (YDVARS%UVP)))
    DO JGFL = 1, SIZE (YDVARS%UVP)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%UVP(JGFL), SELF%UVP(JGFL), YDCPG_SL1%UVP(JGFL))
    ENDDO
    ALLOCATE (SELF%PHYS (SIZE (YDVARS%PHYS)))
    DO JGFL = 1, SIZE (YDVARS%PHYS)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%PHYS(JGFL), SELF%PHYS(JGFL), YDCPG_SL1%PHYS(JGFL))
    ENDDO
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%PHYCTY, SELF%PHYCTY, YDCPG_SL1%PHYCTY)
!   IF (YDVARS%PHYCTY%LADV) THEN
!     SELF%PHYCTY%P   => YDCPG_SL1%PHYCTY%P_F
!     SELF%PHYCTY%F_P => YDCPG_SL1%PHYCTY%F_P_F
!   ELSE
!     SELF%PHYCTY%P   => YDVARS%PHYCTY%T1
!     SELF%PHYCTY%F_P => YDVARS%PHYCTY%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%RSPEC, SELF%RSPEC, YDCPG_SL1%RSPEC)
!   IF (YDVARS%RSPEC%LADV) THEN
!     SELF%RSPEC%P   => YDCPG_SL1%RSPEC%P_F
!     SELF%RSPEC%F_P => YDCPG_SL1%RSPEC%F_P_F
!   ELSE
!     SELF%RSPEC%P   => YDVARS%RSPEC%T1
!     SELF%RSPEC%F_P => YDVARS%RSPEC%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%SDSAT, SELF%SDSAT, YDCPG_SL1%SDSAT)
!   IF (YDVARS%SDSAT%LADV) THEN
!     SELF%SDSAT%P   => YDCPG_SL1%SDSAT%P_F
!     SELF%SDSAT%F_P => YDCPG_SL1%SDSAT%F_P_F
!   ELSE
!     SELF%SDSAT%P   => YDVARS%SDSAT%T1
!     SELF%SDSAT%F_P => YDVARS%SDSAT%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%CVV, SELF%CVV, YDCPG_SL1%CVV)
!   IF (YDVARS%CVV%LADV) THEN
!     SELF%CVV%P   => YDCPG_SL1%CVV%P_F
!     SELF%CVV%F_P => YDCPG_SL1%CVV%F_P_F
!   ELSE
!     SELF%CVV%P   => YDVARS%CVV%T1
!     SELF%CVV%F_P => YDVARS%CVV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%RKTH, SELF%RKTH, YDCPG_SL1%RKTH)
!   IF (YDVARS%RKTH%LADV) THEN
!     SELF%RKTH%P   => YDCPG_SL1%RKTH%P_F
!     SELF%RKTH%F_P => YDCPG_SL1%RKTH%F_P_F
!   ELSE
!     SELF%RKTH%P   => YDVARS%RKTH%T1
!     SELF%RKTH%F_P => YDVARS%RKTH%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%RKTQV, SELF%RKTQV, YDCPG_SL1%RKTQV)
!   IF (YDVARS%RKTQV%LADV) THEN
!     SELF%RKTQV%P   => YDCPG_SL1%RKTQV%P_F
!     SELF%RKTQV%F_P => YDCPG_SL1%RKTQV%F_P_F
!   ELSE
!     SELF%RKTQV%P   => YDVARS%RKTQV%T1
!     SELF%RKTQV%F_P => YDVARS%RKTQV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%RKTQC, SELF%RKTQC, YDCPG_SL1%RKTQC)
!   IF (YDVARS%RKTQC%LADV) THEN
!     SELF%RKTQC%P   => YDCPG_SL1%RKTQC%P_F
!     SELF%RKTQC%F_P => YDCPG_SL1%RKTQC%F_P_F
!   ELSE
!     SELF%RKTQC%P   => YDVARS%RKTQC%T1
!     SELF%RKTQC%F_P => YDVARS%RKTQC%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%UOM, SELF%UOM, YDCPG_SL1%UOM)
!   IF (YDVARS%UOM%LADV) THEN
!     SELF%UOM%P   => YDCPG_SL1%UOM%P_F
!     SELF%UOM%F_P => YDCPG_SL1%UOM%F_P_F
!   ELSE
!     SELF%UOM%P   => YDVARS%UOM%T1
!     SELF%UOM%F_P => YDVARS%UOM%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%UAL, SELF%UAL, YDCPG_SL1%UAL)
!   IF (YDVARS%UAL%LADV) THEN
!     SELF%UAL%P   => YDCPG_SL1%UAL%P_F
!     SELF%UAL%F_P => YDCPG_SL1%UAL%F_P_F
!   ELSE
!     SELF%UAL%P   => YDVARS%UAL%T1
!     SELF%UAL%F_P => YDVARS%UAL%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%DOM, SELF%DOM, YDCPG_SL1%DOM)
!   IF (YDVARS%DOM%LADV) THEN
!     SELF%DOM%P   => YDCPG_SL1%DOM%P_F
!     SELF%DOM%F_P => YDCPG_SL1%DOM%F_P_F
!   ELSE
!     SELF%DOM%P   => YDVARS%DOM%T1
!     SELF%DOM%F_P => YDVARS%DOM%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%DAL, SELF%DAL, YDCPG_SL1%DAL)
!   IF (YDVARS%DAL%LADV) THEN
!     SELF%DAL%P   => YDCPG_SL1%DAL%P_F
!     SELF%DAL%F_P => YDCPG_SL1%DAL%F_P_F
!   ELSE
!     SELF%DAL%P   => YDVARS%DAL%T1
!     SELF%DAL%F_P => YDVARS%DAL%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%UEN, SELF%UEN, YDCPG_SL1%UEN)
!   IF (YDVARS%UEN%LADV) THEN
!     SELF%UEN%P   => YDCPG_SL1%UEN%P_F
!     SELF%UEN%F_P => YDCPG_SL1%UEN%F_P_F
!   ELSE
!     SELF%UEN%P   => YDVARS%UEN%T1
!     SELF%UEN%F_P => YDVARS%UEN%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%UNEBH, SELF%UNEBH, YDCPG_SL1%UNEBH)
!   IF (YDVARS%UNEBH%LADV) THEN
!     SELF%UNEBH%P   => YDCPG_SL1%UNEBH%P_F
!     SELF%UNEBH%F_P => YDCPG_SL1%UNEBH%F_P_F
!   ELSE
!     SELF%UNEBH%P   => YDVARS%UNEBH%T1
!     SELF%UNEBH%F_P => YDVARS%UNEBH%FT1
!   ENDIF
    ALLOCATE (SELF%CRM (SIZE (YDVARS%CRM)))
    DO JGFL = 1, SIZE (YDVARS%CRM)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%CRM(JGFL), SELF%CRM(JGFL), YDCPG_SL1%CRM(JGFL))
    ENDDO
    ALLOCATE (SELF%LIMA (SIZE (YDVARS%LIMA)))
    DO JGFL = 1, SIZE (YDVARS%LIMA)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%LIMA(JGFL), SELF%LIMA(JGFL), YDCPG_SL1%LIMA(JGFL))
    ENDDO
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%FSD, SELF%FSD, YDCPG_SL1%FSD)
!   IF (YDVARS%FSD%LADV) THEN
!     SELF%FSD%P   => YDCPG_SL1%FSD%P_F
!     SELF%FSD%F_P => YDCPG_SL1%FSD%F_P_F
!   ELSE
!     SELF%FSD%P   => YDVARS%FSD%T1
!     SELF%FSD%F_P => YDVARS%FSD%FT1
!   ENDIF
    ALLOCATE (SELF%EXT (SIZE (YDVARS%EXT)))
    DO JGFL = 1, SIZE (YDVARS%EXT)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDVARS%EXT(JGFL), SELF%EXT(JGFL), YDCPG_SL1%EXT(JGFL))
    ENDDO
  ELSE
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%Q, SELF%Q, YDCPG_SL1%Q)
!   IF (YDVARS%Q%LADV) THEN
!     SELF%Q%P   => YDCPG_SL1%Q%P
!     SELF%Q%F_P => YDCPG_SL1%Q%F_P
!   ELSE
!     SELF%Q%P   => YDVARS%Q%T1
!     SELF%Q%F_P => YDVARS%Q%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%I, SELF%I, YDCPG_SL1%I)
!   IF (YDVARS%I%LADV) THEN
!     SELF%I%P   => YDCPG_SL1%I%P
!     SELF%I%F_P => YDCPG_SL1%I%F_P
!   ELSE
!     SELF%I%P   => YDVARS%I%T1
!     SELF%I%F_P => YDVARS%I%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%L, SELF%L, YDCPG_SL1%L)
!   IF (YDVARS%L%LADV) THEN
!     SELF%L%P   => YDCPG_SL1%L%P
!     SELF%L%F_P => YDCPG_SL1%L%F_P
!   ELSE
!     SELF%L%P   => YDVARS%L%T1
!     SELF%L%F_P => YDVARS%L%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%LCONV, SELF%LCONV, YDCPG_SL1%LCONV)
!   IF (YDVARS%LCONV%LADV) THEN
!     SELF%LCONV%P   => YDCPG_SL1%LCONV%P
!     SELF%LCONV%F_P => YDCPG_SL1%LCONV%F_P
!   ELSE
!     SELF%LCONV%P   => YDVARS%LCONV%T1
!     SELF%LCONV%F_P => YDVARS%LCONV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%ICONV, SELF%ICONV, YDCPG_SL1%ICONV)
!   IF (YDVARS%ICONV%LADV) THEN
!     SELF%ICONV%P   => YDCPG_SL1%ICONV%P
!     SELF%ICONV%F_P => YDCPG_SL1%ICONV%F_P
!   ELSE
!     SELF%ICONV%P   => YDVARS%ICONV%T1
!     SELF%ICONV%F_P => YDVARS%ICONV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%RCONV, SELF%RCONV, YDCPG_SL1%RCONV)
!   IF (YDVARS%RCONV%LADV) THEN
!     SELF%RCONV%P   => YDCPG_SL1%RCONV%P
!     SELF%RCONV%F_P => YDCPG_SL1%RCONV%F_P
!   ELSE
!     SELF%RCONV%P   => YDVARS%RCONV%T1
!     SELF%RCONV%F_P => YDVARS%RCONV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%SCONV, SELF%SCONV, YDCPG_SL1%SCONV)
!   IF (YDVARS%SCONV%LADV) THEN
!     SELF%SCONV%P   => YDCPG_SL1%SCONV%P
!     SELF%SCONV%F_P => YDCPG_SL1%SCONV%F_P
!   ELSE
!     SELF%SCONV%P   => YDVARS%SCONV%T1
!     SELF%SCONV%F_P => YDVARS%SCONV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%IRAD, SELF%IRAD, YDCPG_SL1%IRAD)
!   IF (YDVARS%IRAD%LADV) THEN
!     SELF%IRAD%P   => YDCPG_SL1%IRAD%P
!     SELF%IRAD%F_P => YDCPG_SL1%IRAD%F_P
!   ELSE
!     SELF%IRAD%P   => YDVARS%IRAD%T1
!     SELF%IRAD%F_P => YDVARS%IRAD%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%LRAD, SELF%LRAD, YDCPG_SL1%LRAD)
!   IF (YDVARS%LRAD%LADV) THEN
!     SELF%LRAD%P   => YDCPG_SL1%LRAD%P
!     SELF%LRAD%F_P => YDCPG_SL1%LRAD%F_P
!   ELSE
!     SELF%LRAD%P   => YDVARS%LRAD%T1
!     SELF%LRAD%F_P => YDVARS%LRAD%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%S, SELF%S, YDCPG_SL1%S)
!   IF (YDVARS%S%LADV) THEN
!     SELF%S%P   => YDCPG_SL1%S%P
!     SELF%S%F_P => YDCPG_SL1%S%F_P
!   ELSE
!     SELF%S%P   => YDVARS%S%T1
!     SELF%S%F_P => YDVARS%S%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%R, SELF%R, YDCPG_SL1%R)
!   IF (YDVARS%R%LADV) THEN
!     SELF%R%P   => YDCPG_SL1%R%P
!     SELF%R%F_P => YDCPG_SL1%R%F_P
!   ELSE
!     SELF%R%P   => YDVARS%R%T1
!     SELF%R%F_P => YDVARS%R%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%G, SELF%G, YDCPG_SL1%G)
!   IF (YDVARS%G%LADV) THEN
!     SELF%G%P   => YDCPG_SL1%G%P
!     SELF%G%F_P => YDCPG_SL1%G%F_P
!   ELSE
!     SELF%G%P   => YDVARS%G%T1
!     SELF%G%F_P => YDVARS%G%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%H, SELF%H, YDCPG_SL1%H)
!   IF (YDVARS%H%LADV) THEN
!     SELF%H%P   => YDCPG_SL1%H%P
!     SELF%H%F_P => YDCPG_SL1%H%F_P
!   ELSE
!     SELF%H%P   => YDVARS%H%T1
!     SELF%H%F_P => YDVARS%H%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%TKE, SELF%TKE, YDCPG_SL1%TKE)
!   IF (YDVARS%TKE%LADV) THEN
!     SELF%TKE%P   => YDCPG_SL1%TKE%P
!     SELF%TKE%F_P => YDCPG_SL1%TKE%F_P
!   ELSE
!     SELF%TKE%P   => YDVARS%TKE%T1
!     SELF%TKE%F_P => YDVARS%TKE%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%TTE, SELF%TTE, YDCPG_SL1%TTE)
!   IF (YDVARS%TTE%LADV) THEN
!     SELF%TTE%P   => YDCPG_SL1%TTE%P
!     SELF%TTE%F_P => YDCPG_SL1%TTE%F_P
!   ELSE
!     SELF%TTE%P   => YDVARS%TTE%T1
!     SELF%TTE%F_P => YDVARS%TTE%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%EFB1, SELF%EFB1, YDCPG_SL1%EFB1)
!   IF (YDVARS%EFB1%LADV) THEN
!     SELF%EFB1%P   => YDCPG_SL1%EFB1%P
!     SELF%EFB1%F_P => YDCPG_SL1%EFB1%F_P
!   ELSE
!     SELF%EFB1%P   => YDVARS%EFB1%T1
!     SELF%EFB1%F_P => YDVARS%EFB1%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%EFB2, SELF%EFB2, YDCPG_SL1%EFB2)
!   IF (YDVARS%EFB2%LADV) THEN
!     SELF%EFB2%P   => YDCPG_SL1%EFB2%P
!     SELF%EFB2%F_P => YDCPG_SL1%EFB2%F_P
!   ELSE
!     SELF%EFB2%P   => YDVARS%EFB2%T1
!     SELF%EFB2%F_P => YDVARS%EFB2%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%EFB3, SELF%EFB3, YDCPG_SL1%EFB3)
!   IF (YDVARS%EFB3%LADV) THEN
!     SELF%EFB3%P   => YDCPG_SL1%EFB3%P
!     SELF%EFB3%F_P => YDCPG_SL1%EFB3%F_P
!   ELSE
!     SELF%EFB3%P   => YDVARS%EFB3%T1
!     SELF%EFB3%F_P => YDVARS%EFB3%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%A, SELF%A, YDCPG_SL1%A)
!   IF (YDVARS%A%LADV) THEN
!     SELF%A%P   => YDCPG_SL1%A%P
!     SELF%A%F_P => YDCPG_SL1%A%F_P
!   ELSE
!     SELF%A%P   => YDVARS%A%T1
!     SELF%A%F_P => YDVARS%A%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%O3, SELF%O3, YDCPG_SL1%O3)
!   IF (YDVARS%O3%LADV) THEN
!     SELF%O3%P   => YDCPG_SL1%O3%P
!     SELF%O3%F_P => YDCPG_SL1%O3%F_P
!   ELSE
!     SELF%O3%P   => YDVARS%O3%T1
!     SELF%O3%F_P => YDVARS%O3%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%SRC, SELF%SRC, YDCPG_SL1%SRC)
!   IF (YDVARS%SRC%LADV) THEN
!     SELF%SRC%P   => YDCPG_SL1%SRC%P
!     SELF%SRC%F_P => YDCPG_SL1%SRC%F_P
!   ELSE
!     SELF%SRC%P   => YDVARS%SRC%T1
!     SELF%SRC%F_P => YDVARS%SRC%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%MXL, SELF%MXL, YDCPG_SL1%MXL)
!   IF (YDVARS%MXL%LADV) THEN
!     SELF%MXL%P   => YDCPG_SL1%MXL%P
!     SELF%MXL%F_P => YDCPG_SL1%MXL%F_P
!   ELSE
!     SELF%MXL%P   => YDVARS%MXL%T1
!     SELF%MXL%F_P => YDVARS%MXL%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%SHTUR, SELF%SHTUR, YDCPG_SL1%SHTUR)
!   IF (YDVARS%SHTUR%LADV) THEN
!     SELF%SHTUR%P   => YDCPG_SL1%SHTUR%P
!     SELF%SHTUR%F_P => YDCPG_SL1%SHTUR%F_P
!   ELSE
!     SELF%SHTUR%P   => YDVARS%SHTUR%T1
!     SELF%SHTUR%F_P => YDVARS%SHTUR%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%FQTUR, SELF%FQTUR, YDCPG_SL1%FQTUR)
!   IF (YDVARS%FQTUR%LADV) THEN
!     SELF%FQTUR%P   => YDCPG_SL1%FQTUR%P
!     SELF%FQTUR%F_P => YDCPG_SL1%FQTUR%F_P
!   ELSE
!     SELF%FQTUR%P   => YDVARS%FQTUR%T1
!     SELF%FQTUR%F_P => YDVARS%FQTUR%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%FSTUR, SELF%FSTUR, YDCPG_SL1%FSTUR)
!   IF (YDVARS%FSTUR%LADV) THEN
!     SELF%FSTUR%P   => YDCPG_SL1%FSTUR%P
!     SELF%FSTUR%F_P => YDCPG_SL1%FSTUR%F_P
!   ELSE
!     SELF%FSTUR%P   => YDVARS%FSTUR%T1
!     SELF%FSTUR%F_P => YDVARS%FSTUR%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%CPF, SELF%CPF, YDCPG_SL1%CPF)
!   IF (YDVARS%CPF%LADV) THEN
!     SELF%CPF%P   => YDCPG_SL1%CPF%P
!     SELF%CPF%F_P => YDCPG_SL1%CPF%F_P
!   ELSE
!     SELF%CPF%P   => YDVARS%CPF%T1
!     SELF%CPF%F_P => YDVARS%CPF%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%SPF, SELF%SPF, YDCPG_SL1%SPF)
!   IF (YDVARS%SPF%LADV) THEN
!     SELF%SPF%P   => YDCPG_SL1%SPF%P
!     SELF%SPF%F_P => YDCPG_SL1%SPF%F_P
!   ELSE
!     SELF%SPF%P   => YDVARS%SPF%T1
!     SELF%SPF%F_P => YDVARS%SPF%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%CVGQ, SELF%CVGQ, YDCPG_SL1%CVGQ)
!   IF (YDVARS%CVGQ%LADV) THEN
!     SELF%CVGQ%P   => YDCPG_SL1%CVGQ%P
!     SELF%CVGQ%F_P => YDCPG_SL1%CVGQ%F_P
!   ELSE
!     SELF%CVGQ%P   => YDVARS%CVGQ%T1
!     SELF%CVGQ%F_P => YDVARS%CVGQ%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%QVA, SELF%QVA, YDCPG_SL1%QVA)
!   IF (YDVARS%QVA%LADV) THEN
!     SELF%QVA%P   => YDCPG_SL1%QVA%P
!     SELF%QVA%F_P => YDCPG_SL1%QVA%F_P
!   ELSE
!     SELF%QVA%P   => YDVARS%QVA%T1
!     SELF%QVA%F_P => YDVARS%QVA%FT1
!   ENDIF
    ALLOCATE (SELF%GHG (SIZE (YDVARS%GHG)))
    DO JGFL = 1, SIZE (YDVARS%GHG)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%GHG(JGFL), SELF%GHG(JGFL), YDCPG_SL1%GHG(JGFL))
    ENDDO
    ALLOCATE (SELF%CHEM (SIZE (YDVARS%CHEM)))
    DO JGFL = 1, SIZE (YDVARS%CHEM)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%CHEM(JGFL), SELF%CHEM(JGFL), YDCPG_SL1%CHEM(JGFL))
    ENDDO
    ALLOCATE (SELF%AERO (SIZE (YDVARS%AERO)))
    DO JGFL = 1, SIZE (YDVARS%AERO)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%AERO(JGFL), SELF%AERO(JGFL), YDCPG_SL1%AERO(JGFL))
    ENDDO
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%LRCH4, SELF%LRCH4, YDCPG_SL1%LRCH4)
!   IF (YDVARS%LRCH4%LADV) THEN
!     SELF%LRCH4%P   => YDCPG_SL1%LRCH4%P
!     SELF%LRCH4%F_P => YDCPG_SL1%LRCH4%F_P
!   ELSE
!     SELF%LRCH4%P   => YDVARS%LRCH4%T1
!     SELF%LRCH4%F_P => YDVARS%LRCH4%FT1
!   ENDIF
    ALLOCATE (SELF%FORC (SIZE (YDVARS%FORC)))
    DO JGFL = 1, SIZE (YDVARS%FORC)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%FORC(JGFL), SELF%FORC(JGFL), YDCPG_SL1%FORC(JGFL))
    ENDDO
    ALLOCATE (SELF%EZDIAG (SIZE (YDVARS%EZDIAG)))
    DO JGFL = 1, SIZE (YDVARS%EZDIAG)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%EZDIAG(JGFL), SELF%EZDIAG(JGFL), YDCPG_SL1%EZDIAG(JGFL))
    ENDDO
    ALLOCATE (SELF%ERA40 (SIZE (YDVARS%ERA40)))
    DO JGFL = 1, SIZE (YDVARS%ERA40)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%ERA40(JGFL), SELF%ERA40(JGFL), YDCPG_SL1%ERA40(JGFL))
    ENDDO
    ALLOCATE (SELF%NOGW (SIZE (YDVARS%NOGW)))
    DO JGFL = 1, SIZE (YDVARS%NOGW)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%NOGW(JGFL), SELF%NOGW(JGFL), YDCPG_SL1%NOGW(JGFL))
    ENDDO
    ALLOCATE (SELF%EDRP (SIZE (YDVARS%EDRP)))
    DO JGFL = 1, SIZE (YDVARS%EDRP)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%EDRP(JGFL), SELF%EDRP(JGFL), YDCPG_SL1%EDRP(JGFL))
    ENDDO
    ALLOCATE (SELF%SLDIA (SIZE (YDVARS%SLDIA)))
    DO JGFL = 1, SIZE (YDVARS%SLDIA)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%SLDIA(JGFL), SELF%SLDIA(JGFL), YDCPG_SL1%SLDIA(JGFL))
    ENDDO
    ALLOCATE (SELF%AERAOT (SIZE (YDVARS%AERAOT)))
    DO JGFL = 1, SIZE (YDVARS%AERAOT)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%AERAOT(JGFL), SELF%AERAOT(JGFL), YDCPG_SL1%AERAOT(JGFL))
    ENDDO
    ALLOCATE (SELF%AERLISI (SIZE (YDVARS%AERLISI)))
    DO JGFL = 1, SIZE (YDVARS%AERLISI)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%AERLISI(JGFL), SELF%AERLISI(JGFL), YDCPG_SL1%AERLISI(JGFL))
    ENDDO
    ALLOCATE (SELF%AEROUT (SIZE (YDVARS%AEROUT)))
    DO JGFL = 1, SIZE (YDVARS%AEROUT)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%AEROUT(JGFL), SELF%AEROUT(JGFL), YDCPG_SL1%AEROUT(JGFL))
    ENDDO
    ALLOCATE (SELF%AEROCLIM (SIZE (YDVARS%AEROCLIM)))
    DO JGFL = 1, SIZE (YDVARS%AEROCLIM)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%AEROCLIM(JGFL), SELF%AEROCLIM(JGFL), YDCPG_SL1%AEROCLIM(JGFL))
    ENDDO
    ALLOCATE (SELF%UVP (SIZE (YDVARS%UVP)))
    DO JGFL = 1, SIZE (YDVARS%UVP)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%UVP(JGFL), SELF%UVP(JGFL), YDCPG_SL1%UVP(JGFL))
    ENDDO
    ALLOCATE (SELF%PHYS (SIZE (YDVARS%PHYS)))
    DO JGFL = 1, SIZE (YDVARS%PHYS)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%PHYS(JGFL), SELF%PHYS(JGFL), YDCPG_SL1%PHYS(JGFL))
    ENDDO
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%PHYCTY, SELF%PHYCTY, YDCPG_SL1%PHYCTY)
!   IF (YDVARS%PHYCTY%LADV) THEN
!     SELF%PHYCTY%P   => YDCPG_SL1%PHYCTY%P
!     SELF%PHYCTY%F_P => YDCPG_SL1%PHYCTY%F_P
!   ELSE
!     SELF%PHYCTY%P   => YDVARS%PHYCTY%T1
!     SELF%PHYCTY%F_P => YDVARS%PHYCTY%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%RSPEC, SELF%RSPEC, YDCPG_SL1%RSPEC)
!   IF (YDVARS%RSPEC%LADV) THEN
!     SELF%RSPEC%P   => YDCPG_SL1%RSPEC%P
!     SELF%RSPEC%F_P => YDCPG_SL1%RSPEC%F_P
!   ELSE
!     SELF%RSPEC%P   => YDVARS%RSPEC%T1
!     SELF%RSPEC%F_P => YDVARS%RSPEC%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%SDSAT, SELF%SDSAT, YDCPG_SL1%SDSAT)
!   IF (YDVARS%SDSAT%LADV) THEN
!     SELF%SDSAT%P   => YDCPG_SL1%SDSAT%P
!     SELF%SDSAT%F_P => YDCPG_SL1%SDSAT%F_P
!   ELSE
!     SELF%SDSAT%P   => YDVARS%SDSAT%T1
!     SELF%SDSAT%F_P => YDVARS%SDSAT%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%CVV, SELF%CVV, YDCPG_SL1%CVV)
!   IF (YDVARS%CVV%LADV) THEN
!     SELF%CVV%P   => YDCPG_SL1%CVV%P
!     SELF%CVV%F_P => YDCPG_SL1%CVV%F_P
!   ELSE
!     SELF%CVV%P   => YDVARS%CVV%T1
!     SELF%CVV%F_P => YDVARS%CVV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%RKTH, SELF%RKTH, YDCPG_SL1%RKTH)
!   IF (YDVARS%RKTH%LADV) THEN
!     SELF%RKTH%P   => YDCPG_SL1%RKTH%P
!     SELF%RKTH%F_P => YDCPG_SL1%RKTH%F_P
!   ELSE
!     SELF%RKTH%P   => YDVARS%RKTH%T1
!     SELF%RKTH%F_P => YDVARS%RKTH%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%RKTQV, SELF%RKTQV, YDCPG_SL1%RKTQV)
!   IF (YDVARS%RKTQV%LADV) THEN
!     SELF%RKTQV%P   => YDCPG_SL1%RKTQV%P
!     SELF%RKTQV%F_P => YDCPG_SL1%RKTQV%F_P
!   ELSE
!     SELF%RKTQV%P   => YDVARS%RKTQV%T1
!     SELF%RKTQV%F_P => YDVARS%RKTQV%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%RKTQC, SELF%RKTQC, YDCPG_SL1%RKTQC)
!   IF (YDVARS%RKTQC%LADV) THEN
!     SELF%RKTQC%P   => YDCPG_SL1%RKTQC%P
!     SELF%RKTQC%F_P => YDCPG_SL1%RKTQC%F_P
!   ELSE
!     SELF%RKTQC%P   => YDVARS%RKTQC%T1
!     SELF%RKTQC%F_P => YDVARS%RKTQC%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%UOM, SELF%UOM, YDCPG_SL1%UOM)
!   IF (YDVARS%UOM%LADV) THEN
!     SELF%UOM%P   => YDCPG_SL1%UOM%P
!     SELF%UOM%F_P => YDCPG_SL1%UOM%F_P
!   ELSE
!     SELF%UOM%P   => YDVARS%UOM%T1
!     SELF%UOM%F_P => YDVARS%UOM%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%UAL, SELF%UAL, YDCPG_SL1%UAL)
!   IF (YDVARS%UAL%LADV) THEN
!     SELF%UAL%P   => YDCPG_SL1%UAL%P
!     SELF%UAL%F_P => YDCPG_SL1%UAL%F_P
!   ELSE
!     SELF%UAL%P   => YDVARS%UAL%T1
!     SELF%UAL%F_P => YDVARS%UAL%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%DOM, SELF%DOM, YDCPG_SL1%DOM)
!   IF (YDVARS%DOM%LADV) THEN
!     SELF%DOM%P   => YDCPG_SL1%DOM%P
!     SELF%DOM%F_P => YDCPG_SL1%DOM%F_P
!   ELSE
!     SELF%DOM%P   => YDVARS%DOM%T1
!     SELF%DOM%F_P => YDVARS%DOM%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%DAL, SELF%DAL, YDCPG_SL1%DAL)
!   IF (YDVARS%DAL%LADV) THEN
!     SELF%DAL%P   => YDCPG_SL1%DAL%P
!     SELF%DAL%F_P => YDCPG_SL1%DAL%F_P
!   ELSE
!     SELF%DAL%P   => YDVARS%DAL%T1
!     SELF%DAL%F_P => YDVARS%DAL%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%UEN, SELF%UEN, YDCPG_SL1%UEN)
!   IF (YDVARS%UEN%LADV) THEN
!     SELF%UEN%P   => YDCPG_SL1%UEN%P
!     SELF%UEN%F_P => YDCPG_SL1%UEN%F_P
!   ELSE
!     SELF%UEN%P   => YDVARS%UEN%T1
!     SELF%UEN%F_P => YDVARS%UEN%FT1
!   ENDIF
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%UNEBH, SELF%UNEBH, YDCPG_SL1%UNEBH)
!   IF (YDVARS%UNEBH%LADV) THEN
!     SELF%UNEBH%P   => YDCPG_SL1%UNEBH%P
!     SELF%UNEBH%F_P => YDCPG_SL1%UNEBH%F_P
!   ELSE
!     SELF%UNEBH%P   => YDVARS%UNEBH%T1
!     SELF%UNEBH%F_P => YDVARS%UNEBH%FT1
!   ENDIF
    ALLOCATE (SELF%CRM (SIZE (YDVARS%CRM)))
    DO JGFL = 1, SIZE (YDVARS%CRM)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%CRM(JGFL), SELF%CRM(JGFL), YDCPG_SL1%CRM(JGFL))
    ENDDO
    ALLOCATE (SELF%LIMA (SIZE (YDVARS%LIMA)))
    DO JGFL = 1, SIZE (YDVARS%LIMA)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%LIMA(JGFL), SELF%LIMA(JGFL), YDCPG_SL1%LIMA(JGFL))
    ENDDO
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%FSD, SELF%FSD, YDCPG_SL1%FSD)
!   IF (YDVARS%FSD%LADV) THEN
!     SELF%FSD%P   => YDCPG_SL1%FSD%P
!     SELF%FSD%F_P => YDCPG_SL1%FSD%F_P
!   ELSE
!     SELF%FSD%P   => YDVARS%FSD%T1
!     SELF%FSD%F_P => YDVARS%FSD%FT1
!   ENDIF
    ALLOCATE (SELF%EXT (SIZE (YDVARS%EXT)))
    DO JGFL = 1, SIZE (YDVARS%EXT)
      CALL MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDVARS%EXT(JGFL), SELF%EXT(JGFL), YDCPG_SL1%EXT(JGFL))
    ENDDO
  ENDIF  

ELSE

  SELF%U%P     => YDVARS%U%T1
  SELF%U%F_P   => YDVARS%U%FT1
  SELF%V%P     => YDVARS%V%T1
  SELF%V%F_P   => YDVARS%V%FT1
  SELF%T%P     => YDVARS%T%T1
  SELF%T%F_P   => YDVARS%T%FT1
  SELF%SVD%P   => YDVARS%SVD%T1
  SELF%SVD%F_P => YDVARS%SVD%FT1
  SELF%SP%P    => YDVARS%SP%T1
  SELF%SP%F_P  => YDVARS%SP%FT1

  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%Q, SELF%Q)
! SELF%Q%P   => YDVARS%Q%T1
! SELF%Q%F_P => YDVARS%Q%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%I, SELF%I)
! SELF%I%P   => YDVARS%I%T1
! SELF%I%F_P => YDVARS%I%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%L, SELF%L)
! SELF%L%P   => YDVARS%L%T1
! SELF%L%F_P => YDVARS%L%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%LCONV, SELF%LCONV)
! SELF%LCONV%P   => YDVARS%LCONV%T1
! SELF%LCONV%F_P => YDVARS%LCONV%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%ICONV, SELF%ICONV)
! SELF%ICONV%P   => YDVARS%ICONV%T1
! SELF%ICONV%F_P => YDVARS%ICONV%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%RCONV, SELF%RCONV)
! SELF%RCONV%P   => YDVARS%RCONV%T1
! SELF%RCONV%F_P => YDVARS%RCONV%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%SCONV, SELF%SCONV)
! SELF%SCONV%P   => YDVARS%SCONV%T1
! SELF%SCONV%F_P => YDVARS%SCONV%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%IRAD, SELF%IRAD)
! SELF%IRAD%P   => YDVARS%IRAD%T1
! SELF%IRAD%F_P => YDVARS%IRAD%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%LRAD, SELF%LRAD)
! SELF%LRAD%P   => YDVARS%LRAD%T1
! SELF%LRAD%F_P => YDVARS%LRAD%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%S, SELF%S)
! SELF%S%P   => YDVARS%S%T1
! SELF%S%F_P => YDVARS%S%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%R, SELF%R)
! SELF%R%P   => YDVARS%R%T1
! SELF%R%F_P => YDVARS%R%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%G, SELF%G)
! SELF%G%P   => YDVARS%G%T1
! SELF%G%F_P => YDVARS%G%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%H, SELF%H)
! SELF%H%P   => YDVARS%H%T1
! SELF%H%F_P => YDVARS%H%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%TKE, SELF%TKE)
! SELF%TKE%P   => YDVARS%TKE%T1
! SELF%TKE%F_P => YDVARS%TKE%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%TTE, SELF%TTE)
! SELF%TTE%P   => YDVARS%TTE%T1
! SELF%TTE%F_P => YDVARS%TTE%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%EFB1, SELF%EFB1)
! SELF%EFB1%P   => YDVARS%EFB1%T1
! SELF%EFB1%F_P => YDVARS%EFB1%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%EFB2, SELF%EFB2)
! SELF%EFB2%P   => YDVARS%EFB2%T1
! SELF%EFB2%F_P => YDVARS%EFB2%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%EFB3, SELF%EFB3)
! SELF%EFB3%P   => YDVARS%EFB3%T1
! SELF%EFB3%F_P => YDVARS%EFB3%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%A, SELF%A)
! SELF%A%P   => YDVARS%A%T1
! SELF%A%F_P => YDVARS%A%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%O3, SELF%O3)
! SELF%O3%P   => YDVARS%O3%T1
! SELF%O3%F_P => YDVARS%O3%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%SRC, SELF%SRC)
! SELF%SRC%P   => YDVARS%SRC%T1
! SELF%SRC%F_P => YDVARS%SRC%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%MXL, SELF%MXL)
! SELF%MXL%P   => YDVARS%MXL%T1
! SELF%MXL%F_P => YDVARS%MXL%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%SHTUR, SELF%SHTUR)
! SELF%SHTUR%P   => YDVARS%SHTUR%T1
! SELF%SHTUR%F_P => YDVARS%SHTUR%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%FQTUR, SELF%FQTUR)
! SELF%FQTUR%P   => YDVARS%FQTUR%T1
! SELF%FQTUR%F_P => YDVARS%FQTUR%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%FSTUR, SELF%FSTUR)
! SELF%FSTUR%P   => YDVARS%FSTUR%T1
! SELF%FSTUR%F_P => YDVARS%FSTUR%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%CPF, SELF%CPF)
! SELF%CPF%P   => YDVARS%CPF%T1
! SELF%CPF%F_P => YDVARS%CPF%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%SPF, SELF%SPF)
! SELF%SPF%P   => YDVARS%SPF%T1
! SELF%SPF%F_P => YDVARS%SPF%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%CVGQ, SELF%CVGQ)
! SELF%CVGQ%P   => YDVARS%CVGQ%T1
! SELF%CVGQ%F_P => YDVARS%CVGQ%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%QVA, SELF%QVA)
! SELF%QVA%P   => YDVARS%QVA%T1
! SELF%QVA%F_P => YDVARS%QVA%FT1
  ALLOCATE (SELF%GHG (SIZE (YDVARS%GHG)))
  DO JGFL = 1, SIZE (YDVARS%GHG)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%GHG(JGFL), SELF%GHG(JGFL))
  ENDDO
  ALLOCATE (SELF%CHEM (SIZE (YDVARS%CHEM)))
  DO JGFL = 1, SIZE (YDVARS%CHEM)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%CHEM(JGFL), SELF%CHEM(JGFL))
  ENDDO
  ALLOCATE (SELF%AERO (SIZE (YDVARS%AERO)))
  DO JGFL = 1, SIZE (YDVARS%AERO)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%AERO(JGFL), SELF%AERO(JGFL))
  ENDDO
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%LRCH4, SELF%LRCH4)
! SELF%LRCH4%P   => YDVARS%LRCH4%T1
! SELF%LRCH4%F_P => YDVARS%LRCH4%FT1
  ALLOCATE (SELF%FORC (SIZE (YDVARS%FORC)))
  DO JGFL = 1, SIZE (YDVARS%FORC)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%FORC(JGFL), SELF%FORC(JGFL))
  ENDDO
  ALLOCATE (SELF%EZDIAG (SIZE (YDVARS%EZDIAG)))
  DO JGFL = 1, SIZE (YDVARS%EZDIAG)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%EZDIAG(JGFL), SELF%EZDIAG(JGFL))
  ENDDO
  ALLOCATE (SELF%ERA40 (SIZE (YDVARS%ERA40)))
  DO JGFL = 1, SIZE (YDVARS%ERA40)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%ERA40(JGFL), SELF%ERA40(JGFL))
  ENDDO
  ALLOCATE (SELF%NOGW (SIZE (YDVARS%NOGW)))
  DO JGFL = 1, SIZE (YDVARS%NOGW)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%NOGW(JGFL), SELF%NOGW(JGFL))
  ENDDO
  ALLOCATE (SELF%EDRP (SIZE (YDVARS%EDRP)))
  DO JGFL = 1, SIZE (YDVARS%EDRP)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%EDRP(JGFL), SELF%EDRP(JGFL))
  ENDDO
  ALLOCATE (SELF%SLDIA (SIZE (YDVARS%SLDIA)))
  DO JGFL = 1, SIZE (YDVARS%SLDIA)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%SLDIA(JGFL), SELF%SLDIA(JGFL))
  ENDDO
  ALLOCATE (SELF%AERAOT (SIZE (YDVARS%AERAOT)))
  DO JGFL = 1, SIZE (YDVARS%AERAOT)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%AERAOT(JGFL), SELF%AERAOT(JGFL))
  ENDDO
  ALLOCATE (SELF%AERLISI (SIZE (YDVARS%AERLISI)))
  DO JGFL = 1, SIZE (YDVARS%AERLISI)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%AERLISI(JGFL), SELF%AERLISI(JGFL))
  ENDDO
  ALLOCATE (SELF%AEROUT (SIZE (YDVARS%AEROUT)))
  DO JGFL = 1, SIZE (YDVARS%AEROUT)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%AEROUT(JGFL), SELF%AEROUT(JGFL))
  ENDDO
  ALLOCATE (SELF%AEROCLIM (SIZE (YDVARS%AEROCLIM)))
  DO JGFL = 1, SIZE (YDVARS%AEROCLIM)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%AEROCLIM(JGFL), SELF%AEROCLIM(JGFL))
  ENDDO
  ALLOCATE (SELF%UVP (SIZE (YDVARS%UVP)))
  DO JGFL = 1, SIZE (YDVARS%UVP)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%UVP(JGFL), SELF%UVP(JGFL))
  ENDDO
  ALLOCATE (SELF%PHYS (SIZE (YDVARS%PHYS)))
  DO JGFL = 1, SIZE (YDVARS%PHYS)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%PHYS(JGFL), SELF%PHYS(JGFL))
  ENDDO
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%PHYCTY, SELF%PHYCTY)
! SELF%PHYCTY%P   => YDVARS%PHYCTY%T1
! SELF%PHYCTY%F_P => YDVARS%PHYCTY%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%RSPEC, SELF%RSPEC)
! SELF%RSPEC%P   => YDVARS%RSPEC%T1
! SELF%RSPEC%F_P => YDVARS%RSPEC%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%SDSAT, SELF%SDSAT)
! SELF%SDSAT%P   => YDVARS%SDSAT%T1
! SELF%SDSAT%F_P => YDVARS%SDSAT%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%CVV, SELF%CVV)
! SELF%CVV%P   => YDVARS%CVV%T1
! SELF%CVV%F_P => YDVARS%CVV%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%RKTH, SELF%RKTH)
! SELF%RKTH%P   => YDVARS%RKTH%T1
! SELF%RKTH%F_P => YDVARS%RKTH%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%RKTQV, SELF%RKTQV)
! SELF%RKTQV%P   => YDVARS%RKTQV%T1
! SELF%RKTQV%F_P => YDVARS%RKTQV%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%RKTQC, SELF%RKTQC)
! SELF%RKTQC%P   => YDVARS%RKTQC%T1
! SELF%RKTQC%F_P => YDVARS%RKTQC%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%UOM, SELF%UOM)
! SELF%UOM%P   => YDVARS%UOM%T1
! SELF%UOM%F_P => YDVARS%UOM%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%UAL, SELF%UAL)
! SELF%UAL%P   => YDVARS%UAL%T1
! SELF%UAL%F_P => YDVARS%UAL%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%DOM, SELF%DOM)
! SELF%DOM%P   => YDVARS%DOM%T1
! SELF%DOM%F_P => YDVARS%DOM%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%DAL, SELF%DAL)
! SELF%DAL%P   => YDVARS%DAL%T1
! SELF%DAL%F_P => YDVARS%DAL%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%UEN, SELF%UEN)
! SELF%UEN%P   => YDVARS%UEN%T1
! SELF%UEN%F_P => YDVARS%UEN%FT1
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%UNEBH, SELF%UNEBH)
! SELF%UNEBH%P   => YDVARS%UNEBH%T1
! SELF%UNEBH%F_P => YDVARS%UNEBH%FT1
  ALLOCATE (SELF%CRM (SIZE (YDVARS%CRM)))
  DO JGFL = 1, SIZE (YDVARS%CRM)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%CRM(JGFL), SELF%CRM(JGFL))
  ENDDO
  ALLOCATE (SELF%LIMA (SIZE (YDVARS%LIMA)))
  DO JGFL = 1, SIZE (YDVARS%LIMA)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%LIMA(JGFL), SELF%LIMA(JGFL))
  ENDDO
  CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%FSD, SELF%FSD)
! SELF%FSD%P   => YDVARS%FSD%T1
! SELF%FSD%F_P => YDVARS%FSD%FT1
  ALLOCATE (SELF%EXT (SIZE (YDVARS%EXT)))
  DO JGFL = 1, SIZE (YDVARS%EXT)
    CALL MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDVARS%EXT(JGFL), SELF%EXT(JGFL))
  ENDDO

ENDIF

END ASSOCIATE

CONTAINS

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_EUL_3D (YDV3D, YDN3D)

USE VARIABLE_MODULE, ONLY: VARIABLE_3D

TYPE (VARIABLE_3D),                INTENT (IN)    :: YDV3D
TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), INTENT (INOUT) :: YDN3D

YDN3D%P   => YDV3D%T1
YDN3D%F_P => YDV3D%FT1

END SUBROUTINE 

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_3D (YDV3D, YDN3D, YDF3D)

USE CPG_TYPE_MOD, ONLY : CPG_SL1_3D_TYPE
USE VARIABLE_MODULE, ONLY: VARIABLE_3D

TYPE (VARIABLE_3D),                INTENT (IN)    :: YDV3D
TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), INTENT (INOUT) :: YDN3D
TYPE (CPG_SL1_3D_TYPE),            INTENT (IN)    :: YDF3D

IF (YDV3D%LADV) THEN
  YDN3D%P   => YDF3D%P
  YDN3D%F_P => YDF3D%F_P
ELSE
  YDN3D%P   => YDV3D%T1
  YDN3D%F_P => YDV3D%FT1
ENDIF

END SUBROUTINE 

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT_SPLTHOI_3D (YDV3D, YDN3D, YDF3D)

USE CPG_TYPE_MOD, ONLY : CPG_SL1_3D_TYPE
USE VARIABLE_MODULE, ONLY: VARIABLE_3D

TYPE (VARIABLE_3D),                INTENT (IN)    :: YDV3D
TYPE (MF_PHYS_NEXT_STATE_3D_TYPE), INTENT (INOUT) :: YDN3D
TYPE (CPG_SL1_3D_TYPE),            INTENT (IN)    :: YDF3D

IF (YDV3D%LADV) THEN
  YDN3D%P   => YDF3D%P_F
  YDN3D%F_P => YDF3D%F_P_F
ELSE
  YDN3D%P   => YDV3D%T1
  YDN3D%F_P => YDV3D%FT1
ENDIF

END SUBROUTINE

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_INIT

SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW (SELF, BLOCK_INDEX)
CLASS (MF_PHYS_NEXT_STATE_TYPE)              :: SELF
INTEGER(KIND=JPIM), INTENT (IN)   :: BLOCK_INDEX

INTEGER (KIND=JPIM) :: JGFL

IF (ASSOCIATED (SELF%U%F_P)) THEN
  SELF%U%P => SELF%U%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%V%F_P)) THEN
  SELF%V%P => SELF%V%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%T%F_P)) THEN
  SELF%T%P => SELF%T%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%SVD%F_P)) THEN
  SELF%SVD%P => SELF%SVD%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%SP%F_P)) THEN
  SELF%SP%P => SELF%SP%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF

IF (ASSOCIATED (SELF%Q%F_P)) THEN
  SELF%Q%P => SELF%Q%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%I%F_P)) THEN
  SELF%I%P => SELF%I%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%L%F_P)) THEN
  SELF%L%P => SELF%L%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%LCONV%F_P)) THEN
  SELF%LCONV%P => SELF%LCONV%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%ICONV%F_P)) THEN
  SELF%ICONV%P => SELF%ICONV%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%RCONV%F_P)) THEN
  SELF%RCONV%P => SELF%RCONV%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%SCONV%F_P)) THEN
  SELF%SCONV%P => SELF%SCONV%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%IRAD%F_P)) THEN
  SELF%IRAD%P => SELF%IRAD%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%LRAD%F_P)) THEN
  SELF%LRAD%P => SELF%LRAD%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%S%F_P)) THEN
  SELF%S%P => SELF%S%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%R%F_P)) THEN
  SELF%R%P => SELF%R%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%G%F_P)) THEN
  SELF%G%P => SELF%G%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%H%F_P)) THEN
  SELF%H%P => SELF%H%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%TKE%F_P)) THEN
  SELF%TKE%P => SELF%TKE%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%TTE%F_P)) THEN
  SELF%TTE%P => SELF%TTE%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%EFB1%F_P)) THEN
  SELF%EFB1%P => SELF%EFB1%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%EFB2%F_P)) THEN
  SELF%EFB2%P => SELF%EFB2%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%EFB3%F_P)) THEN
  SELF%EFB3%P => SELF%EFB3%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%A%F_P)) THEN
  SELF%A%P => SELF%A%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%O3%F_P)) THEN
  SELF%O3%P => SELF%O3%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%SRC%F_P)) THEN
  SELF%SRC%P => SELF%SRC%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%MXL%F_P)) THEN
  SELF%MXL%P => SELF%MXL%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%SHTUR%F_P)) THEN
  SELF%SHTUR%P => SELF%SHTUR%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%FQTUR%F_P)) THEN
  SELF%FQTUR%P => SELF%FQTUR%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%FSTUR%F_P)) THEN
  SELF%FSTUR%P => SELF%FSTUR%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%CPF%F_P)) THEN
  SELF%CPF%P => SELF%CPF%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%SPF%F_P)) THEN
  SELF%SPF%P => SELF%SPF%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%CVGQ%F_P)) THEN
  SELF%CVGQ%P => SELF%CVGQ%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%QVA%F_P)) THEN
  SELF%QVA%P => SELF%QVA%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
DO JGFL = 1, SIZE (SELF%GHG)
  IF (ASSOCIATED (SELF%GHG(JGFL)%F_P)) THEN
    SELF%GHG(JGFL)%P => SELF%GHG(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%CHEM)
  IF (ASSOCIATED (SELF%CHEM(JGFL)%F_P)) THEN
    SELF%CHEM(JGFL)%P => SELF%CHEM(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%AERO)
  IF (ASSOCIATED (SELF%AERO(JGFL)%F_P)) THEN
    SELF%AERO(JGFL)%P => SELF%AERO(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
IF (ASSOCIATED (SELF%LRCH4%F_P)) THEN
  SELF%LRCH4%P => SELF%LRCH4%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
DO JGFL = 1, SIZE (SELF%FORC)
  IF (ASSOCIATED (SELF%FORC(JGFL)%F_P)) THEN
    SELF%FORC(JGFL)%P => SELF%FORC(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%EZDIAG)
  IF (ASSOCIATED (SELF%EZDIAG(JGFL)%F_P)) THEN
    SELF%EZDIAG(JGFL)%P => SELF%EZDIAG(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%ERA40)
  IF (ASSOCIATED (SELF%ERA40(JGFL)%F_P)) THEN
    SELF%ERA40(JGFL)%P => SELF%ERA40(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%NOGW)
  IF (ASSOCIATED (SELF%NOGW(JGFL)%F_P)) THEN
    SELF%NOGW(JGFL)%P => SELF%NOGW(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%EDRP)
  IF (ASSOCIATED (SELF%EDRP(JGFL)%F_P)) THEN
    SELF%EDRP(JGFL)%P => SELF%EDRP(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%SLDIA)
  IF (ASSOCIATED (SELF%SLDIA(JGFL)%F_P)) THEN
    SELF%SLDIA(JGFL)%P => SELF%SLDIA(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%AERAOT)
  IF (ASSOCIATED (SELF%AERAOT(JGFL)%F_P)) THEN
    SELF%AERAOT(JGFL)%P => SELF%AERAOT(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%AERLISI)
  IF (ASSOCIATED (SELF%AERLISI(JGFL)%F_P)) THEN
    SELF%AERLISI(JGFL)%P => SELF%AERLISI(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%AEROUT)
  IF (ASSOCIATED (SELF%AEROUT(JGFL)%F_P)) THEN
    SELF%AEROUT(JGFL)%P => SELF%AEROUT(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%AEROCLIM)
  IF (ASSOCIATED (SELF%AEROCLIM(JGFL)%F_P)) THEN
    SELF%AEROCLIM(JGFL)%P => SELF%AEROCLIM(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%UVP)
  IF (ASSOCIATED (SELF%UVP(JGFL)%F_P)) THEN
    SELF%UVP(JGFL)%P => SELF%UVP(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%PHYS)
  IF (ASSOCIATED (SELF%PHYS(JGFL)%F_P)) THEN
    SELF%PHYS(JGFL)%P => SELF%PHYS(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
IF (ASSOCIATED (SELF%PHYCTY%F_P)) THEN
  SELF%PHYCTY%P => SELF%PHYCTY%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%RSPEC%F_P)) THEN
  SELF%RSPEC%P => SELF%RSPEC%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%SDSAT%F_P)) THEN
  SELF%SDSAT%P => SELF%SDSAT%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%CVV%F_P)) THEN
  SELF%CVV%P => SELF%CVV%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%RKTH%F_P)) THEN
  SELF%RKTH%P => SELF%RKTH%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%RKTQV%F_P)) THEN
  SELF%RKTQV%P => SELF%RKTQV%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%RKTQC%F_P)) THEN
  SELF%RKTQC%P => SELF%RKTQC%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%UOM%F_P)) THEN
  SELF%UOM%P => SELF%UOM%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%UAL%F_P)) THEN
  SELF%UAL%P => SELF%UAL%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%DOM%F_P)) THEN
  SELF%DOM%P => SELF%DOM%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%DAL%F_P)) THEN
  SELF%DAL%P => SELF%DAL%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%UEN%F_P)) THEN
  SELF%UEN%P => SELF%UEN%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
IF (ASSOCIATED (SELF%UNEBH%F_P)) THEN
  SELF%UNEBH%P => SELF%UNEBH%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
DO JGFL = 1, SIZE (SELF%CRM)
  IF (ASSOCIATED (SELF%CRM(JGFL)%F_P)) THEN
    SELF%CRM(JGFL)%P => SELF%CRM(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
DO JGFL = 1, SIZE (SELF%LIMA)
  IF (ASSOCIATED (SELF%LIMA(JGFL)%F_P)) THEN
    SELF%LIMA(JGFL)%P => SELF%LIMA(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO
IF (ASSOCIATED (SELF%FSD%F_P)) THEN
  SELF%FSD%P => SELF%FSD%F_P%GET_VIEW (BLOCK_INDEX)
ENDIF
DO JGFL = 1, SIZE (SELF%EXT)
  IF (ASSOCIATED (SELF%EXT(JGFL)%F_P)) THEN
    SELF%EXT(JGFL)%P => SELF%EXT(JGFL)%F_P%GET_VIEW (BLOCK_INDEX)
  ENDIF
ENDDO

END SUBROUTINE MF_PHYS_NEXT_STATE_TYPE_UPDATE_VIEW 

END MODULE MF_PHYS_NEXT_STATE_TYPE_MOD



