
SUBROUTINE GPTF2_EXPL_3TL_PART2 (YDGEOMETRY, YDDYN, KST, KEN, LDFSTEP, YDVARS)

USE PARKIND1, ONLY : JPIM, JPRB

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE FIELD_VARIABLES_MOD    , ONLY : FIELD_VARIABLES
USE YOMDYN       , ONLY : TDYN


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KEN
LOGICAL           ,INTENT(IN)    :: LDFSTEP
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS

INTEGER (KIND=JPIM) :: JK
INTEGER (KIND=JPIM) :: JL

IF (LDFSTEP) THEN

  IF(YDVARS%Q%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%Q%T9 (JL,JK) = YDVARS%Q%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%I%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%I%T9 (JL,JK) = YDVARS%I%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%L%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%L%T9 (JL,JK) = YDVARS%L%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%LCONV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%LCONV%T9 (JL,JK) = YDVARS%LCONV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%ICONV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%ICONV%T9 (JL,JK) = YDVARS%ICONV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RCONV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RCONV%T9 (JL,JK) = YDVARS%RCONV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SCONV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SCONV%T9 (JL,JK) = YDVARS%SCONV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%IRAD%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%IRAD%T9 (JL,JK) = YDVARS%IRAD%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%LRAD%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%LRAD%T9 (JL,JK) = YDVARS%LRAD%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%S%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%S%T9 (JL,JK) = YDVARS%S%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%R%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%R%T9 (JL,JK) = YDVARS%R%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%G%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%G%T9 (JL,JK) = YDVARS%G%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%H%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%H%T9 (JL,JK) = YDVARS%H%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%TKE%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%TKE%T9 (JL,JK) = YDVARS%TKE%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%TTE%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%TTE%T9 (JL,JK) = YDVARS%TTE%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%EFB1%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%EFB1%T9 (JL,JK) = YDVARS%EFB1%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%EFB2%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%EFB2%T9 (JL,JK) = YDVARS%EFB2%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%EFB3%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%EFB3%T9 (JL,JK) = YDVARS%EFB3%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%A%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%A%T9 (JL,JK) = YDVARS%A%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%O3%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%O3%T9 (JL,JK) = YDVARS%O3%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SRC%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SRC%T9 (JL,JK) = YDVARS%SRC%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%MXL%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%MXL%T9 (JL,JK) = YDVARS%MXL%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SHTUR%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SHTUR%T9 (JL,JK) = YDVARS%SHTUR%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%FQTUR%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%FQTUR%T9 (JL,JK) = YDVARS%FQTUR%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%FSTUR%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%FSTUR%T9 (JL,JK) = YDVARS%FSTUR%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%CPF%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%CPF%T9 (JL,JK) = YDVARS%CPF%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SPF%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SPF%T9 (JL,JK) = YDVARS%SPF%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%CVGQ%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%CVGQ%T9 (JL,JK) = YDVARS%CVGQ%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%QVA%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%QVA%T9 (JL,JK) = YDVARS%QVA%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%LRCH4%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%LRCH4%T9 (JL,JK) = YDVARS%LRCH4%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%PHYCTY%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%PHYCTY%T9 (JL,JK) = YDVARS%PHYCTY%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RSPEC%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RSPEC%T9 (JL,JK) = YDVARS%RSPEC%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SDSAT%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SDSAT%T9 (JL,JK) = YDVARS%SDSAT%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%CVV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%CVV%T9 (JL,JK) = YDVARS%CVV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RKTH%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RKTH%T9 (JL,JK) = YDVARS%RKTH%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RKTQV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RKTQV%T9 (JL,JK) = YDVARS%RKTQV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RKTQC%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RKTQC%T9 (JL,JK) = YDVARS%RKTQC%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%UOM%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%UOM%T9 (JL,JK) = YDVARS%UOM%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%UAL%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%UAL%T9 (JL,JK) = YDVARS%UAL%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%DOM%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%DOM%T9 (JL,JK) = YDVARS%DOM%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%DAL%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%DAL%T9 (JL,JK) = YDVARS%DAL%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%UEN%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%UEN%T9 (JL,JK) = YDVARS%UEN%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%UNEBH%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%UNEBH%T9 (JL,JK) = YDVARS%UNEBH%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%FSD%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%FSD%T9 (JL,JK) = YDVARS%FSD%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF

ELSE

  IF(YDVARS%Q%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%Q%T9 (JL,JK) = YDVARS%Q%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%Q%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%I%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%I%T9 (JL,JK) = YDVARS%I%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%I%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%L%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%L%T9 (JL,JK) = YDVARS%L%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%L%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%LCONV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%LCONV%T9 (JL,JK) = YDVARS%LCONV%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%LCONV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%ICONV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%ICONV%T9 (JL,JK) = YDVARS%ICONV%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%ICONV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RCONV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RCONV%T9 (JL,JK) = YDVARS%RCONV%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%RCONV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SCONV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SCONV%T9 (JL,JK) = YDVARS%SCONV%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%SCONV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%IRAD%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%IRAD%T9 (JL,JK) = YDVARS%IRAD%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%IRAD%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%LRAD%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%LRAD%T9 (JL,JK) = YDVARS%LRAD%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%LRAD%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%S%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%S%T9 (JL,JK) = YDVARS%S%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%S%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%R%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%R%T9 (JL,JK) = YDVARS%R%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%R%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%G%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%G%T9 (JL,JK) = YDVARS%G%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%G%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%H%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%H%T9 (JL,JK) = YDVARS%H%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%H%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%TKE%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%TKE%T9 (JL,JK) = YDVARS%TKE%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%TKE%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%TTE%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%TTE%T9 (JL,JK) = YDVARS%TTE%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%TTE%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%EFB1%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%EFB1%T9 (JL,JK) = YDVARS%EFB1%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%EFB1%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%EFB2%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%EFB2%T9 (JL,JK) = YDVARS%EFB2%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%EFB2%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%EFB3%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%EFB3%T9 (JL,JK) = YDVARS%EFB3%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%EFB3%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%A%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%A%T9 (JL,JK) = YDVARS%A%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%A%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%O3%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%O3%T9 (JL,JK) = YDVARS%O3%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%O3%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SRC%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SRC%T9 (JL,JK) = YDVARS%SRC%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%SRC%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%MXL%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%MXL%T9 (JL,JK) = YDVARS%MXL%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%MXL%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SHTUR%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SHTUR%T9 (JL,JK) = YDVARS%SHTUR%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%SHTUR%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%FQTUR%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%FQTUR%T9 (JL,JK) = YDVARS%FQTUR%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%FQTUR%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%FSTUR%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%FSTUR%T9 (JL,JK) = YDVARS%FSTUR%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%FSTUR%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%CPF%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%CPF%T9 (JL,JK) = YDVARS%CPF%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%CPF%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SPF%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SPF%T9 (JL,JK) = YDVARS%SPF%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%SPF%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%CVGQ%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%CVGQ%T9 (JL,JK) = YDVARS%CVGQ%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%CVGQ%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%QVA%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%QVA%T9 (JL,JK) = YDVARS%QVA%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%QVA%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%LRCH4%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%LRCH4%T9 (JL,JK) = YDVARS%LRCH4%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%LRCH4%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%PHYCTY%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%PHYCTY%T9 (JL,JK) = YDVARS%PHYCTY%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%PHYCTY%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RSPEC%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RSPEC%T9 (JL,JK) = YDVARS%RSPEC%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%RSPEC%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%SDSAT%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%SDSAT%T9 (JL,JK) = YDVARS%SDSAT%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%SDSAT%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%CVV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%CVV%T9 (JL,JK) = YDVARS%CVV%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%CVV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RKTH%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RKTH%T9 (JL,JK) = YDVARS%RKTH%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%RKTH%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RKTQV%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RKTQV%T9 (JL,JK) = YDVARS%RKTQV%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%RKTQV%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%RKTQC%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%RKTQC%T9 (JL,JK) = YDVARS%RKTQC%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%RKTQC%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%UOM%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%UOM%T9 (JL,JK) = YDVARS%UOM%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%UOM%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%UAL%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%UAL%T9 (JL,JK) = YDVARS%UAL%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%UAL%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%DOM%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%DOM%T9 (JL,JK) = YDVARS%DOM%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%DOM%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%DAL%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%DAL%T9 (JL,JK) = YDVARS%DAL%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%DAL%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%UEN%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%UEN%T9 (JL,JK) = YDVARS%UEN%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%UEN%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%UNEBH%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%UNEBH%T9 (JL,JK) = YDVARS%UNEBH%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%UNEBH%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF
  IF(YDVARS%FSD%LT9) THEN
    DO JK=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JL=KST,KEN
        YDVARS%FSD%T9 (JL,JK) = YDVARS%FSD%T9 (JL,JK) + YDDYN%REPSM2 * YDVARS%FSD%T0 (JL,JK)
      ENDDO
    ENDDO
  ENDIF

ENDIF

END SUBROUTINE
