
SUBROUTINE LATTEX_EXPL_3TL (YDGEOMETRY, YDCPG_BNDS, YDML_GCONF, YDML_DYN, YDCPG_SL1, YDVARS)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK

USE GEOMETRY_MOD           , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE MODEL_DYNAMICS_MOD     , ONLY : MODEL_DYNAMICS_TYPE
USE CPG_TYPE_MOD           , ONLY : CPG_SL1_TYPE
USE FIELD_VARIABLES_MOD,ONLY : FIELD_VARIABLES


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)   ,INTENT(IN)   :: YDCPG_BNDS
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN):: YDML_GCONF
TYPE(MODEL_DYNAMICS_TYPE),INTENT(IN):: YDML_DYN
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS


LOGICAL :: LLTDIABLIN
INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF
INTEGER (KIND=JPIM) :: JGFL

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('LATTEX_EXPL_3TL',0,ZHOOK_HANDLE)

CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YQ%LADV, YDML_GCONF%YGFL%YQ%LTDIABLIN, &
                      & YDCPG_SL1%Q%P, YDCPG_SL1%Q%P_F, YDVARS%Q%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YI%LADV, YDML_GCONF%YGFL%YI%LTDIABLIN, &
                      & YDCPG_SL1%I%P, YDCPG_SL1%I%P_F, YDVARS%I%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YL%LADV, YDML_GCONF%YGFL%YL%LTDIABLIN, &
                      & YDCPG_SL1%L%P, YDCPG_SL1%L%P_F, YDVARS%L%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YLCONV%LADV, YDML_GCONF%YGFL%YLCONV%LTDIABLIN, &
                      & YDCPG_SL1%LCONV%P, YDCPG_SL1%LCONV%P_F, YDVARS%LCONV%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YICONV%LADV, YDML_GCONF%YGFL%YICONV%LTDIABLIN, &
                      & YDCPG_SL1%ICONV%P, YDCPG_SL1%ICONV%P_F, YDVARS%ICONV%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YRCONV%LADV, YDML_GCONF%YGFL%YRCONV%LTDIABLIN, &
                      & YDCPG_SL1%RCONV%P, YDCPG_SL1%RCONV%P_F, YDVARS%RCONV%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YSCONV%LADV, YDML_GCONF%YGFL%YSCONV%LTDIABLIN, &
                      & YDCPG_SL1%SCONV%P, YDCPG_SL1%SCONV%P_F, YDVARS%SCONV%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YIRAD%LADV, YDML_GCONF%YGFL%YIRAD%LTDIABLIN, &
                      & YDCPG_SL1%IRAD%P, YDCPG_SL1%IRAD%P_F, YDVARS%IRAD%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YLRAD%LADV, YDML_GCONF%YGFL%YLRAD%LTDIABLIN, &
                      & YDCPG_SL1%LRAD%P, YDCPG_SL1%LRAD%P_F, YDVARS%LRAD%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YS%LADV, YDML_GCONF%YGFL%YS%LTDIABLIN, &
                      & YDCPG_SL1%S%P, YDCPG_SL1%S%P_F, YDVARS%S%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YR%LADV, YDML_GCONF%YGFL%YR%LTDIABLIN, &
                      & YDCPG_SL1%R%P, YDCPG_SL1%R%P_F, YDVARS%R%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YG%LADV, YDML_GCONF%YGFL%YG%LTDIABLIN, &
                      & YDCPG_SL1%G%P, YDCPG_SL1%G%P_F, YDVARS%G%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YH%LADV, YDML_GCONF%YGFL%YH%LTDIABLIN, &
                      & YDCPG_SL1%H%P, YDCPG_SL1%H%P_F, YDVARS%H%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YTKE%LADV, YDML_GCONF%YGFL%YTKE%LTDIABLIN, &
                      & YDCPG_SL1%TKE%P, YDCPG_SL1%TKE%P_F, YDVARS%TKE%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YTTE%LADV, YDML_GCONF%YGFL%YTTE%LTDIABLIN, &
                      & YDCPG_SL1%TTE%P, YDCPG_SL1%TTE%P_F, YDVARS%TTE%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YEFB1%LADV, YDML_GCONF%YGFL%YEFB1%LTDIABLIN, &
                      & YDCPG_SL1%EFB1%P, YDCPG_SL1%EFB1%P_F, YDVARS%EFB1%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YEFB2%LADV, YDML_GCONF%YGFL%YEFB2%LTDIABLIN, &
                      & YDCPG_SL1%EFB2%P, YDCPG_SL1%EFB2%P_F, YDVARS%EFB2%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YEFB3%LADV, YDML_GCONF%YGFL%YEFB3%LTDIABLIN, &
                      & YDCPG_SL1%EFB3%P, YDCPG_SL1%EFB3%P_F, YDVARS%EFB3%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YA%LADV, YDML_GCONF%YGFL%YA%LTDIABLIN, &
                      & YDCPG_SL1%A%P, YDCPG_SL1%A%P_F, YDVARS%A%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YO3%LADV, YDML_GCONF%YGFL%YO3%LTDIABLIN, &
                      & YDCPG_SL1%O3%P, YDCPG_SL1%O3%P_F, YDVARS%O3%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YSRC%LADV, YDML_GCONF%YGFL%YSRC%LTDIABLIN, &
                      & YDCPG_SL1%SRC%P, YDCPG_SL1%SRC%P_F, YDVARS%SRC%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YMXL%LADV, YDML_GCONF%YGFL%YMXL%LTDIABLIN, &
                      & YDCPG_SL1%MXL%P, YDCPG_SL1%MXL%P_F, YDVARS%MXL%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YSHTUR%LADV, YDML_GCONF%YGFL%YSHTUR%LTDIABLIN, &
                      & YDCPG_SL1%SHTUR%P, YDCPG_SL1%SHTUR%P_F, YDVARS%SHTUR%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YFQTUR%LADV, YDML_GCONF%YGFL%YFQTUR%LTDIABLIN, &
                      & YDCPG_SL1%FQTUR%P, YDCPG_SL1%FQTUR%P_F, YDVARS%FQTUR%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YFSTUR%LADV, YDML_GCONF%YGFL%YFSTUR%LTDIABLIN, &
                      & YDCPG_SL1%FSTUR%P, YDCPG_SL1%FSTUR%P_F, YDVARS%FSTUR%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YCPF%LADV, YDML_GCONF%YGFL%YCPF%LTDIABLIN, &
                      & YDCPG_SL1%CPF%P, YDCPG_SL1%CPF%P_F, YDVARS%CPF%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YSPF%LADV, YDML_GCONF%YGFL%YSPF%LTDIABLIN, &
                      & YDCPG_SL1%SPF%P, YDCPG_SL1%SPF%P_F, YDVARS%SPF%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YCVGQ%LADV, YDML_GCONF%YGFL%YCVGQ%LTDIABLIN, &
                      & YDCPG_SL1%CVGQ%P, YDCPG_SL1%CVGQ%P_F, YDVARS%CVGQ%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YQVA%LADV, YDML_GCONF%YGFL%YQVA%LTDIABLIN, &
                      & YDCPG_SL1%QVA%P, YDCPG_SL1%QVA%P_F, YDVARS%QVA%T9)
DO JGFL = 1, SIZE (YDCPG_SL1%GHG)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YGHG(JGFL)%LADV, YDML_GCONF%YGFL%YGHG(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%GHG(JGFL)%P, YDCPG_SL1%GHG(JGFL)%P_F, YDVARS%GHG(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%CHEM)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YCHEM(JGFL)%LADV, YDML_GCONF%YGFL%YCHEM(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%CHEM(JGFL)%P, YDCPG_SL1%CHEM(JGFL)%P_F, YDVARS%CHEM(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERO)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YAERO(JGFL)%LADV, YDML_GCONF%YGFL%YAERO(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%AERO(JGFL)%P, YDCPG_SL1%AERO(JGFL)%P_F, YDVARS%AERO(JGFL)%T9)
ENDDO
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YLRCH4%LADV, YDML_GCONF%YGFL%YLRCH4%LTDIABLIN, &
                      & YDCPG_SL1%LRCH4%P, YDCPG_SL1%LRCH4%P_F, YDVARS%LRCH4%T9)
DO JGFL = 1, SIZE (YDCPG_SL1%FORC)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YFORC(JGFL)%LADV, YDML_GCONF%YGFL%YFORC(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%FORC(JGFL)%P, YDCPG_SL1%FORC(JGFL)%P_F, YDVARS%FORC(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%EZDIAG)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YEZDIAG(JGFL)%LADV, YDML_GCONF%YGFL%YEZDIAG(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%EZDIAG(JGFL)%P, YDCPG_SL1%EZDIAG(JGFL)%P_F, YDVARS%EZDIAG(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%ERA40)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YERA40(JGFL)%LADV, YDML_GCONF%YGFL%YERA40(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%ERA40(JGFL)%P, YDCPG_SL1%ERA40(JGFL)%P_F, YDVARS%ERA40(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%NOGW)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YNOGW(JGFL)%LADV, YDML_GCONF%YGFL%YNOGW(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%NOGW(JGFL)%P, YDCPG_SL1%NOGW(JGFL)%P_F, YDVARS%NOGW(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%EDRP)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YEDRP(JGFL)%LADV, YDML_GCONF%YGFL%YEDRP(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%EDRP(JGFL)%P, YDCPG_SL1%EDRP(JGFL)%P_F, YDVARS%EDRP(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%SLDIA)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YSLDIA(JGFL)%LADV, YDML_GCONF%YGFL%YSLDIA(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%SLDIA(JGFL)%P, YDCPG_SL1%SLDIA(JGFL)%P_F, YDVARS%SLDIA(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERAOT)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YAERAOT(JGFL)%LADV, YDML_GCONF%YGFL%YAERAOT(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%AERAOT(JGFL)%P, YDCPG_SL1%AERAOT(JGFL)%P_F, YDVARS%AERAOT(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERLISI)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YAERLISI(JGFL)%LADV, YDML_GCONF%YGFL%YAERLISI(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%AERLISI(JGFL)%P, YDCPG_SL1%AERLISI(JGFL)%P_F, YDVARS%AERLISI(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AEROUT)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YAEROUT(JGFL)%LADV, YDML_GCONF%YGFL%YAEROUT(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%AEROUT(JGFL)%P, YDCPG_SL1%AEROUT(JGFL)%P_F, YDVARS%AEROUT(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AEROCLIM)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YAEROCLIM(JGFL)%LADV, YDML_GCONF%YGFL%YAEROCLIM(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%AEROCLIM(JGFL)%P, YDCPG_SL1%AEROCLIM(JGFL)%P_F, YDVARS%AEROCLIM(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%UVP)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YUVP(JGFL)%LADV, YDML_GCONF%YGFL%YUVP(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%UVP(JGFL)%P, YDCPG_SL1%UVP(JGFL)%P_F, YDVARS%UVP(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%PHYS)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YPHYS(JGFL)%LADV, YDML_GCONF%YGFL%YPHYS(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%PHYS(JGFL)%P, YDCPG_SL1%PHYS(JGFL)%P_F, YDVARS%PHYS(JGFL)%T9)
ENDDO
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YPHYCTY%LADV, YDML_GCONF%YGFL%YPHYCTY%LTDIABLIN, &
                      & YDCPG_SL1%PHYCTY%P, YDCPG_SL1%PHYCTY%P_F, YDVARS%PHYCTY%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YRSPEC%LADV, YDML_GCONF%YGFL%YRSPEC%LTDIABLIN, &
                      & YDCPG_SL1%RSPEC%P, YDCPG_SL1%RSPEC%P_F, YDVARS%RSPEC%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YSDSAT%LADV, YDML_GCONF%YGFL%YSDSAT%LTDIABLIN, &
                      & YDCPG_SL1%SDSAT%P, YDCPG_SL1%SDSAT%P_F, YDVARS%SDSAT%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YCVV%LADV, YDML_GCONF%YGFL%YCVV%LTDIABLIN, &
                      & YDCPG_SL1%CVV%P, YDCPG_SL1%CVV%P_F, YDVARS%CVV%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YRKTH%LADV, YDML_GCONF%YGFL%YRKTH%LTDIABLIN, &
                      & YDCPG_SL1%RKTH%P, YDCPG_SL1%RKTH%P_F, YDVARS%RKTH%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YRKTQV%LADV, YDML_GCONF%YGFL%YRKTQV%LTDIABLIN, &
                      & YDCPG_SL1%RKTQV%P, YDCPG_SL1%RKTQV%P_F, YDVARS%RKTQV%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YRKTQC%LADV, YDML_GCONF%YGFL%YRKTQC%LTDIABLIN, &
                      & YDCPG_SL1%RKTQC%P, YDCPG_SL1%RKTQC%P_F, YDVARS%RKTQC%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YUOM%LADV, YDML_GCONF%YGFL%YUOM%LTDIABLIN, &
                      & YDCPG_SL1%UOM%P, YDCPG_SL1%UOM%P_F, YDVARS%UOM%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YUAL%LADV, YDML_GCONF%YGFL%YUAL%LTDIABLIN, &
                      & YDCPG_SL1%UAL%P, YDCPG_SL1%UAL%P_F, YDVARS%UAL%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YDOM%LADV, YDML_GCONF%YGFL%YDOM%LTDIABLIN, &
                      & YDCPG_SL1%DOM%P, YDCPG_SL1%DOM%P_F, YDVARS%DOM%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YDAL%LADV, YDML_GCONF%YGFL%YDAL%LTDIABLIN, &
                      & YDCPG_SL1%DAL%P, YDCPG_SL1%DAL%P_F, YDVARS%DAL%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YUEN%LADV, YDML_GCONF%YGFL%YUEN%LTDIABLIN, &
                      & YDCPG_SL1%UEN%P, YDCPG_SL1%UEN%P_F, YDVARS%UEN%T9)
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YUNEBH%LADV, YDML_GCONF%YGFL%YUNEBH%LTDIABLIN, &
                      & YDCPG_SL1%UNEBH%P, YDCPG_SL1%UNEBH%P_F, YDVARS%UNEBH%T9)
DO JGFL = 1, SIZE (YDCPG_SL1%CRM)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YCRM(JGFL)%LADV, YDML_GCONF%YGFL%YCRM(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%CRM(JGFL)%P, YDCPG_SL1%CRM(JGFL)%P_F, YDVARS%CRM(JGFL)%T9)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%LIMA)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YLIMA(JGFL)%LADV, YDML_GCONF%YGFL%YLIMA(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%LIMA(JGFL)%P, YDCPG_SL1%LIMA(JGFL)%P_F, YDVARS%LIMA(JGFL)%T9)
ENDDO
CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YFSD%LADV, YDML_GCONF%YGFL%YFSD%LTDIABLIN, &
                      & YDCPG_SL1%FSD%P, YDCPG_SL1%FSD%P_F, YDVARS%FSD%T9)
DO JGFL = 1, SIZE (YDCPG_SL1%EXT)
  CALL LATTEX_EXPL_3TL_V (YDML_GCONF%YGFL%YEXT(JGFL)%LADV, YDML_GCONF%YGFL%YEXT(JGFL)%LTDIABLIN, &
                        & YDCPG_SL1%EXT(JGFL)%P, YDCPG_SL1%EXT(JGFL)%P_F, YDVARS%EXT(JGFL)%T9)
ENDDO

IF (LHOOK) CALL DR_HOOK('LATTEX_EXPL_3TL',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE LATTEX_EXPL_3TL_V (LDADV, LDTDIABLIN, PSL1, PSL1_F, PT9)

LOGICAL         , INTENT (IN)    :: LDADV
LOGICAL         , INTENT (IN)    :: LDTDIABLIN
REAL (KIND=JPRB), INTENT (INOUT) :: PSL1   (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB), INTENT (IN)    :: PSL1_F (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB), INTENT (IN)    :: PT9    (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)

IF (LDADV) THEN
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      PSL1(JROF,JLEV)=PSL1(JROF,JLEV)+PT9(JROF,JLEV)
    ENDDO
  ENDDO
  LLTDIABLIN=LDTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        PSL1(JROF,JLEV)=PSL1(JROF,JLEV)+PSL1_F(JROF,JLEV)
      ENDDO
    ENDDO
  ENDIF
ENDIF

END SUBROUTINE LATTEX_EXPL_3TL_V

END SUBROUTINE
