
SUBROUTINE LAVABO_EXPL_LPHY (YDGEOMETRY, KST, KPROF, YGFL, YDCPG_SL1)

! ** NEVER TESTED **

USE PARKIND1     , ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE CPG_TYPE_MOD , ONLY : CPG_SL1_TYPE
USE YOM_YGFL     , ONLY : TYPE_GFLD

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF
TYPE(TYPE_GFLD)   ,INTENT(IN)    :: YGFL
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1

INTEGER (KIND=JPIM) :: JGFL

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('LAVABO_EXPL_LPHY',0,ZHOOK_HANDLE)

IF (YGFL%YQ%LPHY) THEN
  YDCPG_SL1%Q%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%Q%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YI%LPHY) THEN
  YDCPG_SL1%I%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%I%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YL%LPHY) THEN
  YDCPG_SL1%L%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%L%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YLCONV%LPHY) THEN
  YDCPG_SL1%LCONV%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LCONV%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YICONV%LPHY) THEN
  YDCPG_SL1%ICONV%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%ICONV%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YRCONV%LPHY) THEN
  YDCPG_SL1%RCONV%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RCONV%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YSCONV%LPHY) THEN
  YDCPG_SL1%SCONV%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SCONV%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YIRAD%LPHY) THEN
  YDCPG_SL1%IRAD%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%IRAD%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YLRAD%LPHY) THEN
  YDCPG_SL1%LRAD%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LRAD%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YS%LPHY) THEN
  YDCPG_SL1%S%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%S%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YR%LPHY) THEN
  YDCPG_SL1%R%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%R%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YG%LPHY) THEN
  YDCPG_SL1%G%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%G%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YH%LPHY) THEN
  YDCPG_SL1%H%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%H%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YTKE%LPHY) THEN
  YDCPG_SL1%TKE%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%TKE%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YTTE%LPHY) THEN
  YDCPG_SL1%TTE%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%TTE%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YEFB1%LPHY) THEN
  YDCPG_SL1%EFB1%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB1%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YEFB2%LPHY) THEN
  YDCPG_SL1%EFB2%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB2%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YEFB3%LPHY) THEN
  YDCPG_SL1%EFB3%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB3%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YA%LPHY) THEN
  YDCPG_SL1%A%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%A%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YO3%LPHY) THEN
  YDCPG_SL1%O3%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%O3%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YSRC%LPHY) THEN
  YDCPG_SL1%SRC%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SRC%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YMXL%LPHY) THEN
  YDCPG_SL1%MXL%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%MXL%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YSHTUR%LPHY) THEN
  YDCPG_SL1%SHTUR%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SHTUR%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YFQTUR%LPHY) THEN
  YDCPG_SL1%FQTUR%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FQTUR%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YFSTUR%LPHY) THEN
  YDCPG_SL1%FSTUR%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FSTUR%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YCPF%LPHY) THEN
  YDCPG_SL1%CPF%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CPF%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YSPF%LPHY) THEN
  YDCPG_SL1%SPF%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SPF%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YCVGQ%LPHY) THEN
  YDCPG_SL1%CVGQ%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CVGQ%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YQVA%LPHY) THEN
  YDCPG_SL1%QVA%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%QVA%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

DO JGFL = 1, SIZE (YDCPG_SL1%GHG)
  IF (YGFL%YGHG(JGFL)%LPHY) THEN
    YDCPG_SL1%GHG(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%GHG(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%CHEM)
  IF (YGFL%YCHEM(JGFL)%LPHY) THEN
    YDCPG_SL1%CHEM(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%CHEM(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERO)
  IF (YGFL%YAERO(JGFL)%LPHY) THEN
    YDCPG_SL1%AERO(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AERO(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
IF (YGFL%YLRCH4%LPHY) THEN
  YDCPG_SL1%LRCH4%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LRCH4%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

DO JGFL = 1, SIZE (YDCPG_SL1%FORC)
  IF (YGFL%YFORC(JGFL)%LPHY) THEN
    YDCPG_SL1%FORC(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%FORC(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%EZDIAG)
  IF (YGFL%YEZDIAG(JGFL)%LPHY) THEN
    YDCPG_SL1%EZDIAG(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%EZDIAG(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%ERA40)
  IF (YGFL%YERA40(JGFL)%LPHY) THEN
    YDCPG_SL1%ERA40(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%ERA40(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%NOGW)
  IF (YGFL%YNOGW(JGFL)%LPHY) THEN
    YDCPG_SL1%NOGW(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%NOGW(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%EDRP)
  IF (YGFL%YEDRP(JGFL)%LPHY) THEN
    YDCPG_SL1%EDRP(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%EDRP(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%SLDIA)
  IF (YGFL%YSLDIA(JGFL)%LPHY) THEN
    YDCPG_SL1%SLDIA(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%SLDIA(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERAOT)
  IF (YGFL%YAERAOT(JGFL)%LPHY) THEN
    YDCPG_SL1%AERAOT(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AERAOT(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERLISI)
  IF (YGFL%YAERLISI(JGFL)%LPHY) THEN
    YDCPG_SL1%AERLISI(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AERLISI(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AEROUT)
  IF (YGFL%YAEROUT(JGFL)%LPHY) THEN
    YDCPG_SL1%AEROUT(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AEROUT(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AEROCLIM)
  IF (YGFL%YAEROCLIM(JGFL)%LPHY) THEN
    YDCPG_SL1%AEROCLIM(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AEROCLIM(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%UVP)
  IF (YGFL%YUVP(JGFL)%LPHY) THEN
    YDCPG_SL1%UVP(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%UVP(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%PHYS)
  IF (YGFL%YPHYS(JGFL)%LPHY) THEN
    YDCPG_SL1%PHYS(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%PHYS(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
IF (YGFL%YPHYCTY%LPHY) THEN
  YDCPG_SL1%PHYCTY%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%PHYCTY%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YRSPEC%LPHY) THEN
  YDCPG_SL1%RSPEC%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RSPEC%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YSDSAT%LPHY) THEN
  YDCPG_SL1%SDSAT%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SDSAT%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YCVV%LPHY) THEN
  YDCPG_SL1%CVV%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CVV%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YRKTH%LPHY) THEN
  YDCPG_SL1%RKTH%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTH%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YRKTQV%LPHY) THEN
  YDCPG_SL1%RKTQV%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTQV%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YRKTQC%LPHY) THEN
  YDCPG_SL1%RKTQC%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTQC%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YUOM%LPHY) THEN
  YDCPG_SL1%UOM%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UOM%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YUAL%LPHY) THEN
  YDCPG_SL1%UAL%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UAL%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YDOM%LPHY) THEN
  YDCPG_SL1%DOM%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%DOM%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YDAL%LPHY) THEN
  YDCPG_SL1%DAL%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%DAL%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YUEN%LPHY) THEN
  YDCPG_SL1%UEN%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UEN%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF (YGFL%YUNEBH%LPHY) THEN
  YDCPG_SL1%UNEBH%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UNEBH%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

DO JGFL = 1, SIZE (YDCPG_SL1%CRM)
  IF (YGFL%YCRM(JGFL)%LPHY) THEN
    YDCPG_SL1%CRM(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%CRM(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%LIMA)
  IF (YGFL%YLIMA(JGFL)%LPHY) THEN
    YDCPG_SL1%LIMA(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%LIMA(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
IF (YGFL%YFSD%LPHY) THEN
  YDCPG_SL1%FSD%P_P(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FSD%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

DO JGFL = 1, SIZE (YDCPG_SL1%EXT)
  IF (YGFL%YEXT(JGFL)%LPHY) THEN
    YDCPG_SL1%EXT(JGFL)%P_P(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%EXT(JGFL)%P_P(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO

! DO JGFL=1,YGFL%NUMFLDS
!   IF(YGFL%YCOMP(JGFL)%LPHY) THEN
!     ISLB1GFLP9=YDPTRSLB1%MSLB1GFLP9+(JGFL-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
!     YDCPG_SL1%ZVIEW(KST:KPROF,ISLB1GFLP9)=0.0_JPRB
!     YDCPG_SL1%ZVIEW(KST:KPROF,ISLB1GFLP9+YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
!   ENDIF
! ENDDO

IF (LHOOK) CALL DR_HOOK('LAVABO_EXPL_LPHY',1,ZHOOK_HANDLE)

END SUBROUTINE
