
SUBROUTINE LAVABO_EXPL_LAITVSPCQM_PART2 (YDGEOMETRY, YGFL, KST, KPROF, YDCPG_SL1)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOM_YGFL     , ONLY : TYPE_GFLD
USE CPG_TYPE_MOD , ONLY : CPG_SL1_TYPE


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TYPE_GFLD)   ,INTENT(IN)    :: YGFL
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF
TYPE(CPG_SL1_TYPE),INTENT(INOUT) :: YDCPG_SL1

INTEGER (KIND=JPIM) :: JGFL

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('LAVABO_EXPL_LAITVSPCQM_PART2',0,ZHOOK_HANDLE)

IF ((YGFL%YQ%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YQ%LADV) THEN
  YDCPG_SL1%Q%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%Q%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YI%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YI%LADV) THEN
  YDCPG_SL1%I%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%I%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YL%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YL%LADV) THEN
  YDCPG_SL1%L%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%L%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YLCONV%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YLCONV%LADV) THEN
  YDCPG_SL1%LCONV%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LCONV%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YICONV%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YICONV%LADV) THEN
  YDCPG_SL1%ICONV%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%ICONV%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YRCONV%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YRCONV%LADV) THEN
  YDCPG_SL1%RCONV%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RCONV%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YSCONV%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YSCONV%LADV) THEN
  YDCPG_SL1%SCONV%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SCONV%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YIRAD%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YIRAD%LADV) THEN
  YDCPG_SL1%IRAD%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%IRAD%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YLRAD%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YLRAD%LADV) THEN
  YDCPG_SL1%LRAD%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LRAD%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YS%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YS%LADV) THEN
  YDCPG_SL1%S%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%S%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YR%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YR%LADV) THEN
  YDCPG_SL1%R%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%R%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YG%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YG%LADV) THEN
  YDCPG_SL1%G%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%G%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YH%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YH%LADV) THEN
  YDCPG_SL1%H%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%H%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YTKE%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YTKE%LADV) THEN
  YDCPG_SL1%TKE%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%TKE%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YTTE%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YTTE%LADV) THEN
  YDCPG_SL1%TTE%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%TTE%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YEFB1%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YEFB1%LADV) THEN
  YDCPG_SL1%EFB1%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB1%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YEFB2%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YEFB2%LADV) THEN
  YDCPG_SL1%EFB2%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB2%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YEFB3%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YEFB3%LADV) THEN
  YDCPG_SL1%EFB3%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%EFB3%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YA%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YA%LADV) THEN
  YDCPG_SL1%A%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%A%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YO3%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YO3%LADV) THEN
  YDCPG_SL1%O3%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%O3%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YSRC%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YSRC%LADV) THEN
  YDCPG_SL1%SRC%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SRC%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YMXL%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YMXL%LADV) THEN
  YDCPG_SL1%MXL%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%MXL%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YSHTUR%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YSHTUR%LADV) THEN
  YDCPG_SL1%SHTUR%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SHTUR%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YFQTUR%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YFQTUR%LADV) THEN
  YDCPG_SL1%FQTUR%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FQTUR%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YFSTUR%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YFSTUR%LADV) THEN
  YDCPG_SL1%FSTUR%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FSTUR%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YCPF%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YCPF%LADV) THEN
  YDCPG_SL1%CPF%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CPF%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YSPF%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YSPF%LADV) THEN
  YDCPG_SL1%SPF%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SPF%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YCVGQ%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YCVGQ%LADV) THEN
  YDCPG_SL1%CVGQ%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CVGQ%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YQVA%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YQVA%LADV) THEN
  YDCPG_SL1%QVA%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%QVA%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

DO JGFL = 1, SIZE (YDCPG_SL1%GHG)
  IF ((YGFL%YGHG(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YGHG(JGFL)%LADV) THEN
    YDCPG_SL1%GHG(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%GHG(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%CHEM)
  IF ((YGFL%YCHEM(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YCHEM(JGFL)%LADV) THEN
    YDCPG_SL1%CHEM(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%CHEM(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERO)
  IF ((YGFL%YAERO(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YAERO(JGFL)%LADV) THEN
    YDCPG_SL1%AERO(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AERO(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
IF ((YGFL%YLRCH4%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YLRCH4%LADV) THEN
  YDCPG_SL1%LRCH4%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%LRCH4%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

DO JGFL = 1, SIZE (YDCPG_SL1%FORC)
  IF ((YGFL%YFORC(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YFORC(JGFL)%LADV) THEN
    YDCPG_SL1%FORC(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%FORC(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%EZDIAG)
  IF ((YGFL%YEZDIAG(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YEZDIAG(JGFL)%LADV) THEN
    YDCPG_SL1%EZDIAG(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%EZDIAG(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%ERA40)
  IF ((YGFL%YERA40(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YERA40(JGFL)%LADV) THEN
    YDCPG_SL1%ERA40(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%ERA40(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%NOGW)
  IF ((YGFL%YNOGW(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YNOGW(JGFL)%LADV) THEN
    YDCPG_SL1%NOGW(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%NOGW(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%EDRP)
  IF ((YGFL%YEDRP(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YEDRP(JGFL)%LADV) THEN
    YDCPG_SL1%EDRP(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%EDRP(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%SLDIA)
  IF ((YGFL%YSLDIA(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YSLDIA(JGFL)%LADV) THEN
    YDCPG_SL1%SLDIA(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%SLDIA(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERAOT)
  IF ((YGFL%YAERAOT(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YAERAOT(JGFL)%LADV) THEN
    YDCPG_SL1%AERAOT(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AERAOT(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERLISI)
  IF ((YGFL%YAERLISI(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YAERLISI(JGFL)%LADV) THEN
    YDCPG_SL1%AERLISI(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AERLISI(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AEROUT)
  IF ((YGFL%YAEROUT(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YAEROUT(JGFL)%LADV) THEN
    YDCPG_SL1%AEROUT(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AEROUT(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AEROCLIM)
  IF ((YGFL%YAEROCLIM(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YAEROCLIM(JGFL)%LADV) THEN
    YDCPG_SL1%AEROCLIM(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%AEROCLIM(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%UVP)
  IF ((YGFL%YUVP(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YUVP(JGFL)%LADV) THEN
    YDCPG_SL1%UVP(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%UVP(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%PHYS)
  IF ((YGFL%YPHYS(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YPHYS(JGFL)%LADV) THEN
    YDCPG_SL1%PHYS(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%PHYS(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
IF ((YGFL%YPHYCTY%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YPHYCTY%LADV) THEN
  YDCPG_SL1%PHYCTY%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%PHYCTY%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YRSPEC%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YRSPEC%LADV) THEN
  YDCPG_SL1%RSPEC%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RSPEC%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YSDSAT%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YSDSAT%LADV) THEN
  YDCPG_SL1%SDSAT%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%SDSAT%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YCVV%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YCVV%LADV) THEN
  YDCPG_SL1%CVV%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%CVV%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YRKTH%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YRKTH%LADV) THEN
  YDCPG_SL1%RKTH%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTH%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YRKTQV%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YRKTQV%LADV) THEN
  YDCPG_SL1%RKTQV%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTQV%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YRKTQC%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YRKTQC%LADV) THEN
  YDCPG_SL1%RKTQC%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%RKTQC%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YUOM%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YUOM%LADV) THEN
  YDCPG_SL1%UOM%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UOM%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YUAL%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YUAL%LADV) THEN
  YDCPG_SL1%UAL%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UAL%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YDOM%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YDOM%LADV) THEN
  YDCPG_SL1%DOM%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%DOM%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YDAL%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YDAL%LADV) THEN
  YDCPG_SL1%DAL%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%DAL%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YUEN%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YUEN%LADV) THEN
  YDCPG_SL1%UEN%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UEN%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

IF ((YGFL%YUNEBH%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YUNEBH%LADV) THEN
  YDCPG_SL1%UNEBH%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%UNEBH%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

DO JGFL = 1, SIZE (YDCPG_SL1%CRM)
  IF ((YGFL%YCRM(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YCRM(JGFL)%LADV) THEN
    YDCPG_SL1%CRM(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%CRM(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%LIMA)
  IF ((YGFL%YLIMA(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YLIMA(JGFL)%LADV) THEN
    YDCPG_SL1%LIMA(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%LIMA(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO
IF ((YGFL%YFSD%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YFSD%LADV) THEN
  YDCPG_SL1%FSD%P_F(KST:KPROF,0)=0.0_JPRB
  YDCPG_SL1%FSD%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
ENDIF

DO JGFL = 1, SIZE (YDCPG_SL1%EXT)
  IF ((YGFL%YEXT(JGFL)%CSLINT /= 'LAITVSPCQM  ') .AND. YGFL%YEXT(JGFL)%LADV) THEN
    YDCPG_SL1%EXT(JGFL)%P_F(KST:KPROF,0)=0.0_JPRB
    YDCPG_SL1%EXT(JGFL)%P_F(KST:KPROF,YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
  ENDIF
ENDDO

! DO JGFL=1,YGFL%NUMFLDS
!   IF( (YGFL%YCOMP(JGFL)%CSLINT /= 'LAITVSPCQM  ').AND.YGFL%YCOMP(JGFL)%LADV ) THEN
!     ISLB1GFL9=YDPTRSLB1%MSLB1GFLF9+(YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
!     YDCPG_SL1%ZVIEW(KST:KPROF,ISLB1GFL9)=0.0_JPRB
!     YDCPG_SL1%ZVIEW(KST:KPROF,ISLB1GFL9+YDGEOMETRY%YRDIMV%NFLEVG+1)=0.0_JPRB
!   ENDIF
! ENDDO

IF (LHOOK) CALL DR_HOOK('LAVABO_EXPL_LAITVSPCQM_PART2',1,ZHOOK_HANDLE)

END SUBROUTINE
