SUBROUTINE CPG_PT_ULP_EXPL (YDMODEL, YDGEOMETRY, YDMF_PHYS_NEXT_STATE, YDCPG_SL1, YDVARS, YDCPG_BNDS, LDGET, PGFLPT)

! -----------------------------------------------------------------------------
!     --------------------------------------------
!**** *CPG_PT_ULP_EXPL*  physics tendencies written to or extracted from GFLPT
!     --------------------------------------------

!     Purpose.
!     --------
!       Copy the physics tendencies calculated (for ex in predictor)
!       to GFLPT to be retrieved and used during corrector
!       Designed for unlagged physics packages (LAGPHY=F).
!       May be used for non advected GFL too.

!       This routine is called for lpc_full=true only.

!**   Interface.
!     ----------
!        CALL CPG_PT_ULP_EXPL(...)

!     Input arguments
!     ------------------
!       YDCPG_BNDS%KIDIA  : start of horizontal loop
!       YDCPG_BNDS%KFDIA   : end of horizontal loop
!       LDGET   : T = get tendencies from buffers.
!                 F = save tendencies in buffers.
!       KFLDN,KFLDX: for second dimension of PTENDEXT.

!     Input or Output according to LDGET
!     ----------------------------------
!       PTEND[X]: tendency of X variable from phy (advected variables).
!       PGFLPT  : buffer for tendency of GFL variable from phy.
!       PGFLT1  : tendency of X variable from phy (not advected variables).
!       PGFL    : GFL variables.
!       PGMV    : upper air GMV variables at time t.
!       PGMVS   : surface GMV variables at time t.

!     Implicit arguments
!     --------------------

!     Author.
!     -------
!      Martina Tudor + Karim Yessad
!      Original : Jan 2011 (from CPG_PT)

!     Modifications.
!     --------------
! -----------------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK
USE YOMCT0       , ONLY : LNHDYN
USE CPG_OPTS_TYPE_MOD       , ONLY : CPG_BNDS_TYPE
USE FIELD_VARIABLES_MOD     , ONLY : FIELD_VARIABLES
USE CPG_TYPE_MOD            , ONLY : CPG_SL1_TYPE
USE TYPE_MODEL              , ONLY : MODEL
USE MF_PHYS_NEXT_STATE_TYPE_MOD &
                            , ONLY : MF_PHYS_NEXT_STATE_TYPE


! -----------------------------------------------------------------------------

IMPLICIT NONE

TYPE(MODEL)                    ,INTENT(IN)     :: YDMODEL
TYPE(GEOMETRY)                 ,INTENT(IN)     :: YDGEOMETRY
TYPE (MF_PHYS_NEXT_STATE_TYPE), INTENT(INOUT)  :: YDMF_PHYS_NEXT_STATE
TYPE(CPG_SL1_TYPE)             ,INTENT(INOUT)  :: YDCPG_SL1
TYPE(FIELD_VARIABLES)          ,INTENT(INOUT)  :: YDVARS
TYPE(CPG_BNDS_TYPE)            ,INTENT(IN)     :: YDCPG_BNDS
LOGICAL                        ,INTENT(IN)     :: LDGET
REAL(KIND=JPRB)                ,INTENT(INOUT)  :: PGFLPT(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIMPT)
! -----------------------------------------------------------------------------

INTEGER(KIND=JPIM) :: JGFL

REAL(KIND=JPRB) :: ZHOOK_HANDLE

! -----------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CPG_PT_ULP_EXPL',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YGFL=>YDMODEL%YRML_GCONF%YGFL)
ASSOCIATE(YCPF=>YDMODEL%YRML_GCONF%YGFL%YCPF,   NFLEVG=>YDDIMV%NFLEVG)

! -----------------------------------------------------------------------------

!*       1.  PREDICTOR FOR LPC_FULL.
!        ---------------------------

IF (.NOT.LDGET) THEN

  ! * GMV:
  YDVARS%CUPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDMF_PHYS_NEXT_STATE%U%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  YDVARS%CVPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDMF_PHYS_NEXT_STATE%V%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  YDVARS%CTPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDMF_PHYS_NEXT_STATE%T%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  IF (LNHDYN) THEN
    YDVARS%CSVDPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDMF_PHYS_NEXT_STATE%SVD%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  ENDIF

  ! * GMVS:
  YDVARS%CSPPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDCPG_SL1%SP9%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)

  ! * GFL:
  IF (YGFL%YQ%LT1 .AND. YGFL%YQ%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YQ%MPPT) = YDMF_PHYS_NEXT_STATE%Q%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:&
        &NFLEVG)
  ENDIF

  IF (YGFL%YI%LT1 .AND. YGFL%YI%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YI%MPPT) = YDMF_PHYS_NEXT_STATE%I%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:&
        &NFLEVG)
  ENDIF

  IF (YGFL%YL%LT1 .AND. YGFL%YL%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YL%MPPT) = YDMF_PHYS_NEXT_STATE%L%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:&
        &NFLEVG)
  ENDIF

  IF (YGFL%YLCONV%LT1 .AND. YGFL%YLCONV%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YLCONV%MPPT) = YDMF_PHYS_NEXT_STATE%LCONV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YICONV%LT1 .AND. YGFL%YICONV%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YICONV%MPPT) = YDMF_PHYS_NEXT_STATE%ICONV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YRCONV%LT1 .AND. YGFL%YRCONV%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YRCONV%MPPT) = YDMF_PHYS_NEXT_STATE%RCONV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YSCONV%LT1 .AND. YGFL%YSCONV%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YSCONV%MPPT) = YDMF_PHYS_NEXT_STATE%SCONV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YIRAD%LT1 .AND. YGFL%YIRAD%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YIRAD%MPPT) = YDMF_PHYS_NEXT_STATE%IRAD%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KF&
        &DIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YLRAD%LT1 .AND. YGFL%YLRAD%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YLRAD%MPPT) = YDMF_PHYS_NEXT_STATE%LRAD%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KF&
        &DIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YS%LT1 .AND. YGFL%YS%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YS%MPPT) = YDMF_PHYS_NEXT_STATE%S%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:&
        &NFLEVG)
  ENDIF

  IF (YGFL%YR%LT1 .AND. YGFL%YR%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YR%MPPT) = YDMF_PHYS_NEXT_STATE%R%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:&
        &NFLEVG)
  ENDIF

  IF (YGFL%YG%LT1 .AND. YGFL%YG%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YG%MPPT) = YDMF_PHYS_NEXT_STATE%G%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:&
        &NFLEVG)
  ENDIF

  IF (YGFL%YH%LT1 .AND. YGFL%YH%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YH%MPPT) = YDMF_PHYS_NEXT_STATE%H%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:&
        &NFLEVG)
  ENDIF

  IF (YGFL%YTKE%LT1 .AND. YGFL%YTKE%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YTKE%MPPT) = YDMF_PHYS_NEXT_STATE%TKE%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YTTE%LT1 .AND. YGFL%YTTE%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YTTE%MPPT) = YDMF_PHYS_NEXT_STATE%TTE%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YEFB1%LT1 .AND. YGFL%YEFB1%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YEFB1%MPPT) = YDMF_PHYS_NEXT_STATE%EFB1%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KF&
        &DIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YEFB2%LT1 .AND. YGFL%YEFB2%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YEFB2%MPPT) = YDMF_PHYS_NEXT_STATE%EFB2%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KF&
        &DIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YEFB3%LT1 .AND. YGFL%YEFB3%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YEFB3%MPPT) = YDMF_PHYS_NEXT_STATE%EFB3%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KF&
        &DIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YA%LT1 .AND. YGFL%YA%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YA%MPPT) = YDMF_PHYS_NEXT_STATE%A%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:&
        &NFLEVG)
  ENDIF

  IF (YGFL%YO3%LT1 .AND. YGFL%YO3%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YO3%MPPT) = YDMF_PHYS_NEXT_STATE%O3%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,&
        &1:NFLEVG)
  ENDIF

  IF (YGFL%YSRC%LT1 .AND. YGFL%YSRC%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YSRC%MPPT) = YDMF_PHYS_NEXT_STATE%SRC%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YMXL%LT1 .AND. YGFL%YMXL%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YMXL%MPPT) = YDMF_PHYS_NEXT_STATE%MXL%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YSHTUR%LT1 .AND. YGFL%YSHTUR%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YSHTUR%MPPT) = YDMF_PHYS_NEXT_STATE%SHTUR%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YFQTUR%LT1 .AND. YGFL%YFQTUR%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YFQTUR%MPPT) = YDMF_PHYS_NEXT_STATE%FQTUR%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YFSTUR%LT1 .AND. YGFL%YFSTUR%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YFSTUR%MPPT) = YDMF_PHYS_NEXT_STATE%FSTUR%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YCPF%LT1 .AND. YGFL%YCPF%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YCPF%MPPT) = YDMF_PHYS_NEXT_STATE%CPF%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YSPF%LT1 .AND. YGFL%YSPF%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YSPF%MPPT) = YDMF_PHYS_NEXT_STATE%SPF%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YCVGQ%LT1 .AND. YGFL%YCVGQ%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YCVGQ%MPPT) = YDMF_PHYS_NEXT_STATE%CVGQ%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KF&
        &DIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YQVA%LT1 .AND. YGFL%YQVA%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YQVA%MPPT) = YDMF_PHYS_NEXT_STATE%QVA%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%GHG)
    IF (YGFL%YGHG(JGFL)%LT1 .AND. YGFL%YGHG(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YGHG(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%GHG(JGFL)%P(YDCPG_BNDS%KIDIA:Y&
          &DCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%CHEM)
    IF (YGFL%YCHEM(JGFL)%LT1 .AND. YGFL%YCHEM(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YCHEM(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%CHEM(JGFL)%P(YDCPG_BNDS%KIDIA&
          &:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERO)
    IF (YGFL%YAERO(JGFL)%LT1 .AND. YGFL%YAERO(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAERO(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%AERO(JGFL)%P(YDCPG_BNDS%KIDIA&
          &:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  IF (YGFL%YLRCH4%LT1 .AND. YGFL%YLRCH4%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YLRCH4%MPPT) = YDMF_PHYS_NEXT_STATE%LRCH4%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%FORC)
    IF (YGFL%YFORC(JGFL)%LT1 .AND. YGFL%YFORC(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YFORC(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%FORC(JGFL)%P(YDCPG_BNDS%KIDIA&
          &:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%EZDIAG)
    IF (YGFL%YEZDIAG(JGFL)%LT1 .AND. YGFL%YEZDIAG(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%EZDIAG(JGFL)%P(YDCPG_BNDS%K&
          &IDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%ERA40)
    IF (YGFL%YERA40(JGFL)%LT1 .AND. YGFL%YERA40(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YERA40(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%ERA40(JGFL)%P(YDCPG_BNDS%KID&
          &IA:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%NOGW)
    IF (YGFL%YNOGW(JGFL)%LT1 .AND. YGFL%YNOGW(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YNOGW(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%NOGW(JGFL)%P(YDCPG_BNDS%KIDIA&
          &:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%EDRP)
    IF (YGFL%YEDRP(JGFL)%LT1 .AND. YGFL%YEDRP(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YEDRP(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%EDRP(JGFL)%P(YDCPG_BNDS%KIDIA&
          &:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%SLDIA)
    IF (YGFL%YSLDIA(JGFL)%LT1 .AND. YGFL%YSLDIA(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YSLDIA(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%SLDIA(JGFL)%P(YDCPG_BNDS%KID&
          &IA:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERAOT)
    IF (YGFL%YAERAOT(JGFL)%LT1 .AND. YGFL%YAERAOT(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%AERAOT(JGFL)%P(YDCPG_BNDS%K&
          &IDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERLISI)
    IF (YGFL%YAERLISI(JGFL)%LT1 .AND. YGFL%YAERLISI(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%AERLISI(JGFL)%P(YDCPG_BNDS&
          &%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AEROUT)
    IF (YGFL%YAEROUT(JGFL)%LT1 .AND. YGFL%YAEROUT(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%AEROUT(JGFL)%P(YDCPG_BNDS%K&
          &IDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AEROCLIM)
    IF (YGFL%YAEROCLIM(JGFL)%LT1 .AND. YGFL%YAEROCLIM(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%AEROCLIM(JGFL)%P(YDCPG_BN&
          &DS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%UVP)
    IF (YGFL%YUVP(JGFL)%LT1 .AND. YGFL%YUVP(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YUVP(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%UVP(JGFL)%P(YDCPG_BNDS%KIDIA:Y&
          &DCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%PHYS)
    IF (YGFL%YPHYS(JGFL)%LT1 .AND. YGFL%YPHYS(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YPHYS(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%PHYS(JGFL)%P(YDCPG_BNDS%KIDIA&
          &:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  IF (YGFL%YPHYCTY%LT1 .AND. YGFL%YPHYCTY%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YPHYCTY%MPPT) = YDMF_PHYS_NEXT_STATE%PHYCTY%P(YDCPG_BNDS%KIDIA:YDCPG_BND&
        &S%KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YRSPEC%LT1 .AND. YGFL%YRSPEC%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YRSPEC%MPPT) = YDMF_PHYS_NEXT_STATE%RSPEC%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YSDSAT%LT1 .AND. YGFL%YSDSAT%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YSDSAT%MPPT) = YDMF_PHYS_NEXT_STATE%SDSAT%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YCVV%LT1 .AND. YGFL%YCVV%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YCVV%MPPT) = YDMF_PHYS_NEXT_STATE%CVV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YRKTH%LT1 .AND. YGFL%YRKTH%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YRKTH%MPPT) = YDMF_PHYS_NEXT_STATE%RKTH%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KF&
        &DIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YRKTQV%LT1 .AND. YGFL%YRKTQV%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YRKTQV%MPPT) = YDMF_PHYS_NEXT_STATE%RKTQV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YRKTQC%LT1 .AND. YGFL%YRKTQC%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YRKTQC%MPPT) = YDMF_PHYS_NEXT_STATE%RKTQC%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  IF (YGFL%YUOM%LT1 .AND. YGFL%YUOM%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YUOM%MPPT) = YDMF_PHYS_NEXT_STATE%UOM%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YUAL%LT1 .AND. YGFL%YUAL%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YUAL%MPPT) = YDMF_PHYS_NEXT_STATE%UAL%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YDOM%LT1 .AND. YGFL%YDOM%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YDOM%MPPT) = YDMF_PHYS_NEXT_STATE%DOM%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YDAL%LT1 .AND. YGFL%YDAL%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YDAL%MPPT) = YDMF_PHYS_NEXT_STATE%DAL%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YUEN%LT1 .AND. YGFL%YUEN%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YUEN%MPPT) = YDMF_PHYS_NEXT_STATE%UEN%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  IF (YGFL%YUNEBH%LT1 .AND. YGFL%YUNEBH%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YUNEBH%MPPT) = YDMF_PHYS_NEXT_STATE%UNEBH%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%&
        &KFDIA,1:NFLEVG)
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%CRM)
    IF (YGFL%YCRM(JGFL)%LT1 .AND. YGFL%YCRM(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YCRM(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%CRM(JGFL)%P(YDCPG_BNDS%KIDIA:Y&
          &DCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%LIMA)
    IF (YGFL%YLIMA(JGFL)%LT1 .AND. YGFL%YLIMA(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YLIMA(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%LIMA(JGFL)%P(YDCPG_BNDS%KIDIA&
          &:YDCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO

  IF (YGFL%YFSD%LT1 .AND. YGFL%YFSD%LPT) THEN
    PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YFSD%MPPT) = YDMF_PHYS_NEXT_STATE%FSD%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDI&
        &A,1:NFLEVG)
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%EXT)
    IF (YGFL%YEXT(JGFL)%LT1 .AND. YGFL%YEXT(JGFL)%LPT) THEN
      PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YEXT(JGFL)%MPPT) = YDMF_PHYS_NEXT_STATE%EXT(JGFL)%P(YDCPG_BNDS%KIDIA:Y&
          &DCPG_BNDS%KFDIA,1:NFLEVG)
    ENDIF
  ENDDO


ENDIF

! -----------------------------------------------------------------------------

!*       2.  CORRECTOR FOR LPC_FULL.
!        ---------------------------

IF (LDGET) THEN

  ! * GMV:
  YDMF_PHYS_NEXT_STATE%U%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDVARS%CUPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  YDMF_PHYS_NEXT_STATE%V%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDVARS%CVPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  YDMF_PHYS_NEXT_STATE%T%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDVARS%CTPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  IF (LNHDYN) THEN
    YDMF_PHYS_NEXT_STATE%SVD%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDVARS%CSVDPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  ENDIF

  ! * GMVS:
  YDCPG_SL1%SP9%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)=YDVARS%CSPPT%T9(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA)

  ! * GFL:
  IF (YGFL%YQ%LT1 .AND. YGFL%YQ%LPT) THEN
    YDMF_PHYS_NEXT_STATE%Q%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%Y&
        &Q%MPPT)
  ENDIF

  IF (YGFL%YI%LT1 .AND. YGFL%YI%LPT) THEN
    YDMF_PHYS_NEXT_STATE%I%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%Y&
        &I%MPPT)
  ENDIF

  IF (YGFL%YL%LT1 .AND. YGFL%YL%LPT) THEN
    YDMF_PHYS_NEXT_STATE%L%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%Y&
        &L%MPPT)
  ENDIF

  IF (YGFL%YLCONV%LT1 .AND. YGFL%YLCONV%LPT) THEN
    YDMF_PHYS_NEXT_STATE%LCONV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YLCONV%MPPT)
  ENDIF

  IF (YGFL%YICONV%LT1 .AND. YGFL%YICONV%LPT) THEN
    YDMF_PHYS_NEXT_STATE%ICONV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YICONV%MPPT)
  ENDIF

  IF (YGFL%YRCONV%LT1 .AND. YGFL%YRCONV%LPT) THEN
    YDMF_PHYS_NEXT_STATE%RCONV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YRCONV%MPPT)
  ENDIF

  IF (YGFL%YSCONV%LT1 .AND. YGFL%YSCONV%LPT) THEN
    YDMF_PHYS_NEXT_STATE%SCONV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YSCONV%MPPT)
  ENDIF

  IF (YGFL%YIRAD%LT1 .AND. YGFL%YIRAD%LPT) THEN
    YDMF_PHYS_NEXT_STATE%IRAD%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGF&
        &L%YIRAD%MPPT)
  ENDIF

  IF (YGFL%YLRAD%LT1 .AND. YGFL%YLRAD%LPT) THEN
    YDMF_PHYS_NEXT_STATE%LRAD%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGF&
        &L%YLRAD%MPPT)
  ENDIF

  IF (YGFL%YS%LT1 .AND. YGFL%YS%LPT) THEN
    YDMF_PHYS_NEXT_STATE%S%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%Y&
        &S%MPPT)
  ENDIF

  IF (YGFL%YR%LT1 .AND. YGFL%YR%LPT) THEN
    YDMF_PHYS_NEXT_STATE%R%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%Y&
        &R%MPPT)
  ENDIF

  IF (YGFL%YG%LT1 .AND. YGFL%YG%LPT) THEN
    YDMF_PHYS_NEXT_STATE%G%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%Y&
        &G%MPPT)
  ENDIF

  IF (YGFL%YH%LT1 .AND. YGFL%YH%LPT) THEN
    YDMF_PHYS_NEXT_STATE%H%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%Y&
        &H%MPPT)
  ENDIF

  IF (YGFL%YTKE%LT1 .AND. YGFL%YTKE%LPT) THEN
    YDMF_PHYS_NEXT_STATE%TKE%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YTKE%MPPT)
  ENDIF

  IF (YGFL%YTTE%LT1 .AND. YGFL%YTTE%LPT) THEN
    YDMF_PHYS_NEXT_STATE%TTE%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YTTE%MPPT)
  ENDIF

  IF (YGFL%YEFB1%LT1 .AND. YGFL%YEFB1%LPT) THEN
    YDMF_PHYS_NEXT_STATE%EFB1%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGF&
        &L%YEFB1%MPPT)
  ENDIF

  IF (YGFL%YEFB2%LT1 .AND. YGFL%YEFB2%LPT) THEN
    YDMF_PHYS_NEXT_STATE%EFB2%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGF&
        &L%YEFB2%MPPT)
  ENDIF

  IF (YGFL%YEFB3%LT1 .AND. YGFL%YEFB3%LPT) THEN
    YDMF_PHYS_NEXT_STATE%EFB3%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGF&
        &L%YEFB3%MPPT)
  ENDIF

  IF (YGFL%YA%LT1 .AND. YGFL%YA%LPT) THEN
    YDMF_PHYS_NEXT_STATE%A%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%Y&
        &A%MPPT)
  ENDIF

  IF (YGFL%YO3%LT1 .AND. YGFL%YO3%LPT) THEN
    YDMF_PHYS_NEXT_STATE%O3%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%&
        &YO3%MPPT)
  ENDIF

  IF (YGFL%YSRC%LT1 .AND. YGFL%YSRC%LPT) THEN
    YDMF_PHYS_NEXT_STATE%SRC%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YSRC%MPPT)
  ENDIF

  IF (YGFL%YMXL%LT1 .AND. YGFL%YMXL%LPT) THEN
    YDMF_PHYS_NEXT_STATE%MXL%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YMXL%MPPT)
  ENDIF

  IF (YGFL%YSHTUR%LT1 .AND. YGFL%YSHTUR%LPT) THEN
    YDMF_PHYS_NEXT_STATE%SHTUR%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YSHTUR%MPPT)
  ENDIF

  IF (YGFL%YFQTUR%LT1 .AND. YGFL%YFQTUR%LPT) THEN
    YDMF_PHYS_NEXT_STATE%FQTUR%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YFQTUR%MPPT)
  ENDIF

  IF (YGFL%YFSTUR%LT1 .AND. YGFL%YFSTUR%LPT) THEN
    YDMF_PHYS_NEXT_STATE%FSTUR%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YFSTUR%MPPT)
  ENDIF

  IF (YGFL%YCPF%LT1 .AND. YGFL%YCPF%LPT) THEN
    YDMF_PHYS_NEXT_STATE%CPF%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YCPF%MPPT)
  ENDIF

  IF (YGFL%YSPF%LT1 .AND. YGFL%YSPF%LPT) THEN
    YDMF_PHYS_NEXT_STATE%SPF%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YSPF%MPPT)
  ENDIF

  IF (YGFL%YCVGQ%LT1 .AND. YGFL%YCVGQ%LPT) THEN
    YDMF_PHYS_NEXT_STATE%CVGQ%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGF&
        &L%YCVGQ%MPPT)
  ENDIF

  IF (YGFL%YQVA%LT1 .AND. YGFL%YQVA%LPT) THEN
    YDMF_PHYS_NEXT_STATE%QVA%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YQVA%MPPT)
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%GHG)
    IF (YGFL%YGHG(JGFL)%LT1 .AND. YGFL%YGHG(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%GHG(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFL&
          &EVG,YGFL%YGHG(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%CHEM)
    IF (YGFL%YCHEM(JGFL)%LT1 .AND. YGFL%YCHEM(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%CHEM(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NF&
          &LEVG,YGFL%YCHEM(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERO)
    IF (YGFL%YAERO(JGFL)%LT1 .AND. YGFL%YAERO(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%AERO(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NF&
          &LEVG,YGFL%YAERO(JGFL)%MPPT)
    ENDIF
  ENDDO

  IF (YGFL%YLRCH4%LT1 .AND. YGFL%YLRCH4%LPT) THEN
    YDMF_PHYS_NEXT_STATE%LRCH4%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YLRCH4%MPPT)
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%FORC)
    IF (YGFL%YFORC(JGFL)%LT1 .AND. YGFL%YFORC(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%FORC(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NF&
          &LEVG,YGFL%YFORC(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%EZDIAG)
    IF (YGFL%YEZDIAG(JGFL)%LT1 .AND. YGFL%YEZDIAG(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%EZDIAG(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) =&
          & PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YEZDIAG(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%ERA40)
    IF (YGFL%YERA40(JGFL)%LT1 .AND. YGFL%YERA40(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%ERA40(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:N&
          &FLEVG,YGFL%YERA40(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%NOGW)
    IF (YGFL%YNOGW(JGFL)%LT1 .AND. YGFL%YNOGW(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%NOGW(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NF&
          &LEVG,YGFL%YNOGW(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%EDRP)
    IF (YGFL%YEDRP(JGFL)%LT1 .AND. YGFL%YEDRP(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%EDRP(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NF&
          &LEVG,YGFL%YEDRP(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%SLDIA)
    IF (YGFL%YSLDIA(JGFL)%LT1 .AND. YGFL%YSLDIA(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%SLDIA(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:N&
          &FLEVG,YGFL%YSLDIA(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERAOT)
    IF (YGFL%YAERAOT(JGFL)%LT1 .AND. YGFL%YAERAOT(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%AERAOT(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) =&
          & PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAERAOT(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AERLISI)
    IF (YGFL%YAERLISI(JGFL)%LT1 .AND. YGFL%YAERLISI(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%AERLISI(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) =&
          & PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAERLISI(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AEROUT)
    IF (YGFL%YAEROUT(JGFL)%LT1 .AND. YGFL%YAEROUT(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%AEROUT(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) =&
          & PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAEROUT(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%AEROCLIM)
    IF (YGFL%YAEROCLIM(JGFL)%LT1 .AND. YGFL%YAEROCLIM(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%AEROCLIM(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) =&
          & PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL%YAEROCLIM(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%UVP)
    IF (YGFL%YUVP(JGFL)%LT1 .AND. YGFL%YUVP(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%UVP(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFL&
          &EVG,YGFL%YUVP(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%PHYS)
    IF (YGFL%YPHYS(JGFL)%LT1 .AND. YGFL%YPHYS(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%PHYS(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NF&
          &LEVG,YGFL%YPHYS(JGFL)%MPPT)
    ENDIF
  ENDDO

  IF (YGFL%YPHYCTY%LT1 .AND. YGFL%YPHYCTY%LPT) THEN
    YDMF_PHYS_NEXT_STATE%PHYCTY%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,Y&
        &GFL%YPHYCTY%MPPT)
  ENDIF

  IF (YGFL%YRSPEC%LT1 .AND. YGFL%YRSPEC%LPT) THEN
    YDMF_PHYS_NEXT_STATE%RSPEC%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YRSPEC%MPPT)
  ENDIF

  IF (YGFL%YSDSAT%LT1 .AND. YGFL%YSDSAT%LPT) THEN
    YDMF_PHYS_NEXT_STATE%SDSAT%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YSDSAT%MPPT)
  ENDIF

  IF (YGFL%YCVV%LT1 .AND. YGFL%YCVV%LPT) THEN
    YDMF_PHYS_NEXT_STATE%CVV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YCVV%MPPT)
  ENDIF

  IF (YGFL%YRKTH%LT1 .AND. YGFL%YRKTH%LPT) THEN
    YDMF_PHYS_NEXT_STATE%RKTH%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGF&
        &L%YRKTH%MPPT)
  ENDIF

  IF (YGFL%YRKTQV%LT1 .AND. YGFL%YRKTQV%LPT) THEN
    YDMF_PHYS_NEXT_STATE%RKTQV%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YRKTQV%MPPT)
  ENDIF

  IF (YGFL%YRKTQC%LT1 .AND. YGFL%YRKTQC%LPT) THEN
    YDMF_PHYS_NEXT_STATE%RKTQC%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YRKTQC%MPPT)
  ENDIF

  IF (YGFL%YUOM%LT1 .AND. YGFL%YUOM%LPT) THEN
    YDMF_PHYS_NEXT_STATE%UOM%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YUOM%MPPT)
  ENDIF

  IF (YGFL%YUAL%LT1 .AND. YGFL%YUAL%LPT) THEN
    YDMF_PHYS_NEXT_STATE%UAL%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YUAL%MPPT)
  ENDIF

  IF (YGFL%YDOM%LT1 .AND. YGFL%YDOM%LPT) THEN
    YDMF_PHYS_NEXT_STATE%DOM%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YDOM%MPPT)
  ENDIF

  IF (YGFL%YDAL%LT1 .AND. YGFL%YDAL%LPT) THEN
    YDMF_PHYS_NEXT_STATE%DAL%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YDAL%MPPT)
  ENDIF

  IF (YGFL%YUEN%LT1 .AND. YGFL%YUEN%LPT) THEN
    YDMF_PHYS_NEXT_STATE%UEN%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YUEN%MPPT)
  ENDIF

  IF (YGFL%YUNEBH%LT1 .AND. YGFL%YUNEBH%LPT) THEN
    YDMF_PHYS_NEXT_STATE%UNEBH%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YG&
        &FL%YUNEBH%MPPT)
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%CRM)
    IF (YGFL%YCRM(JGFL)%LT1 .AND. YGFL%YCRM(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%CRM(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFL&
          &EVG,YGFL%YCRM(JGFL)%MPPT)
    ENDIF
  ENDDO

  DO JGFL = 1, SIZE (YDCPG_SL1%LIMA)
    IF (YGFL%YLIMA(JGFL)%LT1 .AND. YGFL%YLIMA(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%LIMA(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NF&
          &LEVG,YGFL%YLIMA(JGFL)%MPPT)
    ENDIF
  ENDDO

  IF (YGFL%YFSD%LT1 .AND. YGFL%YFSD%LPT) THEN
    YDMF_PHYS_NEXT_STATE%FSD%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG,YGFL&
        &%YFSD%MPPT)
  ENDIF

  DO JGFL = 1, SIZE (YDCPG_SL1%EXT)
    IF (YGFL%YEXT(JGFL)%LT1 .AND. YGFL%YEXT(JGFL)%LPT) THEN
      YDMF_PHYS_NEXT_STATE%EXT(JGFL)%P(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG) = PGFLPT(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFL&
          &EVG,YGFL%YEXT(JGFL)%MPPT)
    ENDIF
  ENDDO


  IF (YCPF%LACTIVE) THEN
    YDVARS%CPF%T1(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)=YDVARS%CPF%T0(YDCPG_BNDS%KIDIA:YDCPG_BNDS%KFDIA,1:NFLEVG)
  ENDIF

ENDIF

! -----------------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('CPG_PT_ULP_EXPL',1,ZHOOK_HANDLE)

END SUBROUTINE CPG_PT_ULP_EXPL
