
SUBROUTINE GPINISLB_PART2_EXPL (LDSLAG, LDTWOTL, YDDYN, KST, KEN, PTE, YDVARS)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK

USE YOMDYN, ONLY : TDYN
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES

IMPLICIT NONE

LOGICAL                ,INTENT(IN)    :: LDSLAG
LOGICAL                ,INTENT(IN)    :: LDTWOTL
TYPE(TDYN)             ,INTENT(IN)    :: YDDYN
INTEGER(KIND=JPIM)     ,INTENT(IN)    :: KST
INTEGER(KIND=JPIM)     ,INTENT(IN)    :: KEN
REAL(KIND=JPRB)        ,INTENT(IN)    :: PTE
TYPE(FIELD_VARIABLES)  ,INTENT(INOUT) :: YDVARS

INTEGER (KIND=JPIM) :: JFLD

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('GPINISLB_PART2_EXPL',0,ZHOOK_HANDLE)

IF (LDSLAG) THEN
  IF (LDTWOTL) THEN
    CALL SLG_2TL (YDVARS%Q)
    CALL SLG_2TL (YDVARS%I)
    CALL SLG_2TL (YDVARS%L)
    CALL SLG_2TL (YDVARS%LCONV)
    CALL SLG_2TL (YDVARS%ICONV)
    CALL SLG_2TL (YDVARS%RCONV)
    CALL SLG_2TL (YDVARS%SCONV)
    CALL SLG_2TL (YDVARS%IRAD)
    CALL SLG_2TL (YDVARS%LRAD)
    CALL SLG_2TL (YDVARS%S)
    CALL SLG_2TL (YDVARS%R)
    CALL SLG_2TL (YDVARS%G)
    CALL SLG_2TL (YDVARS%H)
    CALL SLG_2TL (YDVARS%TKE)
    CALL SLG_2TL (YDVARS%TTE)
    CALL SLG_2TL (YDVARS%EFB1)
    CALL SLG_2TL (YDVARS%EFB2)
    CALL SLG_2TL (YDVARS%EFB3)
    CALL SLG_2TL (YDVARS%A)
    CALL SLG_2TL (YDVARS%O3)
    CALL SLG_2TL (YDVARS%SRC)
    CALL SLG_2TL (YDVARS%MXL)
    CALL SLG_2TL (YDVARS%SHTUR)
    CALL SLG_2TL (YDVARS%FQTUR)
    CALL SLG_2TL (YDVARS%FSTUR)
    CALL SLG_2TL (YDVARS%CPF)
    CALL SLG_2TL (YDVARS%SPF)
    CALL SLG_2TL (YDVARS%CVGQ)
    CALL SLG_2TL (YDVARS%QVA)
    DO JFLD = 1, SIZE (YDVARS%GHG)
      CALL SLG_2TL (YDVARS%GHG (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%CHEM)
      CALL SLG_2TL (YDVARS%CHEM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERO)
      CALL SLG_2TL (YDVARS%AERO (JFLD))
    ENDDO
    CALL SLG_2TL (YDVARS%LRCH4)
    DO JFLD = 1, SIZE (YDVARS%FORC)
      CALL SLG_2TL (YDVARS%FORC (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%EZDIAG)
      CALL SLG_2TL (YDVARS%EZDIAG (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%ERA40)
      CALL SLG_2TL (YDVARS%ERA40 (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%NOGW)
      CALL SLG_2TL (YDVARS%NOGW (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%EDRP)
      CALL SLG_2TL (YDVARS%EDRP (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%SLDIA)
      CALL SLG_2TL (YDVARS%SLDIA (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERAOT)
      CALL SLG_2TL (YDVARS%AERAOT (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERLISI)
      CALL SLG_2TL (YDVARS%AERLISI (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AEROUT)
      CALL SLG_2TL (YDVARS%AEROUT (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
      CALL SLG_2TL (YDVARS%AEROCLIM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%UVP)
      CALL SLG_2TL (YDVARS%UVP (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%PHYS)
      CALL SLG_2TL (YDVARS%PHYS (JFLD))
    ENDDO
    CALL SLG_2TL (YDVARS%PHYCTY)
    CALL SLG_2TL (YDVARS%RSPEC)
    CALL SLG_2TL (YDVARS%SDSAT)
    CALL SLG_2TL (YDVARS%CVV)
    CALL SLG_2TL (YDVARS%RKTH)
    CALL SLG_2TL (YDVARS%RKTQV)
    CALL SLG_2TL (YDVARS%RKTQC)
    CALL SLG_2TL (YDVARS%UOM)
    CALL SLG_2TL (YDVARS%UAL)
    CALL SLG_2TL (YDVARS%DOM)
    CALL SLG_2TL (YDVARS%DAL)
    CALL SLG_2TL (YDVARS%UEN)
    CALL SLG_2TL (YDVARS%UNEBH)
    DO JFLD = 1, SIZE (YDVARS%CRM)
      CALL SLG_2TL (YDVARS%CRM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%LIMA)
      CALL SLG_2TL (YDVARS%LIMA (JFLD))
    ENDDO
    CALL SLG_2TL (YDVARS%FSD)
    DO JFLD = 1, SIZE (YDVARS%EXT)
      CALL SLG_2TL (YDVARS%EXT (JFLD))
    ENDDO
  ELSE
    CALL SLG_3TL (YDVARS%Q)
    CALL SLG_3TL (YDVARS%I)
    CALL SLG_3TL (YDVARS%L)
    CALL SLG_3TL (YDVARS%LCONV)
    CALL SLG_3TL (YDVARS%ICONV)
    CALL SLG_3TL (YDVARS%RCONV)
    CALL SLG_3TL (YDVARS%SCONV)
    CALL SLG_3TL (YDVARS%IRAD)
    CALL SLG_3TL (YDVARS%LRAD)
    CALL SLG_3TL (YDVARS%S)
    CALL SLG_3TL (YDVARS%R)
    CALL SLG_3TL (YDVARS%G)
    CALL SLG_3TL (YDVARS%H)
    CALL SLG_3TL (YDVARS%TKE)
    CALL SLG_3TL (YDVARS%TTE)
    CALL SLG_3TL (YDVARS%EFB1)
    CALL SLG_3TL (YDVARS%EFB2)
    CALL SLG_3TL (YDVARS%EFB3)
    CALL SLG_3TL (YDVARS%A)
    CALL SLG_3TL (YDVARS%O3)
    CALL SLG_3TL (YDVARS%SRC)
    CALL SLG_3TL (YDVARS%MXL)
    CALL SLG_3TL (YDVARS%SHTUR)
    CALL SLG_3TL (YDVARS%FQTUR)
    CALL SLG_3TL (YDVARS%FSTUR)
    CALL SLG_3TL (YDVARS%CPF)
    CALL SLG_3TL (YDVARS%SPF)
    CALL SLG_3TL (YDVARS%CVGQ)
    CALL SLG_3TL (YDVARS%QVA)
    DO JFLD = 1, SIZE (YDVARS%GHG)
      CALL SLG_3TL (YDVARS%GHG (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%CHEM)
      CALL SLG_3TL (YDVARS%CHEM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERO)
      CALL SLG_3TL (YDVARS%AERO (JFLD))
    ENDDO
    CALL SLG_3TL (YDVARS%LRCH4)
    DO JFLD = 1, SIZE (YDVARS%FORC)
      CALL SLG_3TL (YDVARS%FORC (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%EZDIAG)
      CALL SLG_3TL (YDVARS%EZDIAG (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%ERA40)
      CALL SLG_3TL (YDVARS%ERA40 (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%NOGW)
      CALL SLG_3TL (YDVARS%NOGW (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%EDRP)
      CALL SLG_3TL (YDVARS%EDRP (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%SLDIA)
      CALL SLG_3TL (YDVARS%SLDIA (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERAOT)
      CALL SLG_3TL (YDVARS%AERAOT (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERLISI)
      CALL SLG_3TL (YDVARS%AERLISI (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AEROUT)
      CALL SLG_3TL (YDVARS%AEROUT (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
      CALL SLG_3TL (YDVARS%AEROCLIM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%UVP)
      CALL SLG_3TL (YDVARS%UVP (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%PHYS)
      CALL SLG_3TL (YDVARS%PHYS (JFLD))
    ENDDO
    CALL SLG_3TL (YDVARS%PHYCTY)
    CALL SLG_3TL (YDVARS%RSPEC)
    CALL SLG_3TL (YDVARS%SDSAT)
    CALL SLG_3TL (YDVARS%CVV)
    CALL SLG_3TL (YDVARS%RKTH)
    CALL SLG_3TL (YDVARS%RKTQV)
    CALL SLG_3TL (YDVARS%RKTQC)
    CALL SLG_3TL (YDVARS%UOM)
    CALL SLG_3TL (YDVARS%UAL)
    CALL SLG_3TL (YDVARS%DOM)
    CALL SLG_3TL (YDVARS%DAL)
    CALL SLG_3TL (YDVARS%UEN)
    CALL SLG_3TL (YDVARS%UNEBH)
    DO JFLD = 1, SIZE (YDVARS%CRM)
      CALL SLG_3TL (YDVARS%CRM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%LIMA)
      CALL SLG_3TL (YDVARS%LIMA (JFLD))
    ENDDO
    CALL SLG_3TL (YDVARS%FSD)
    DO JFLD = 1, SIZE (YDVARS%EXT)
      CALL SLG_3TL (YDVARS%EXT (JFLD))
    ENDDO
  ENDIF
ELSE 
  IF (YDDYN%NCURRENT_ITER == 0) THEN
    CALL EUL_IT0 (YDVARS%Q)
    CALL EUL_IT0 (YDVARS%I)
    CALL EUL_IT0 (YDVARS%L)
    CALL EUL_IT0 (YDVARS%LCONV)
    CALL EUL_IT0 (YDVARS%ICONV)
    CALL EUL_IT0 (YDVARS%RCONV)
    CALL EUL_IT0 (YDVARS%SCONV)
    CALL EUL_IT0 (YDVARS%IRAD)
    CALL EUL_IT0 (YDVARS%LRAD)
    CALL EUL_IT0 (YDVARS%S)
    CALL EUL_IT0 (YDVARS%R)
    CALL EUL_IT0 (YDVARS%G)
    CALL EUL_IT0 (YDVARS%H)
    CALL EUL_IT0 (YDVARS%TKE)
    CALL EUL_IT0 (YDVARS%TTE)
    CALL EUL_IT0 (YDVARS%EFB1)
    CALL EUL_IT0 (YDVARS%EFB2)
    CALL EUL_IT0 (YDVARS%EFB3)
    CALL EUL_IT0 (YDVARS%A)
    CALL EUL_IT0 (YDVARS%O3)
    CALL EUL_IT0 (YDVARS%SRC)
    CALL EUL_IT0 (YDVARS%MXL)
    CALL EUL_IT0 (YDVARS%SHTUR)
    CALL EUL_IT0 (YDVARS%FQTUR)
    CALL EUL_IT0 (YDVARS%FSTUR)
    CALL EUL_IT0 (YDVARS%CPF)
    CALL EUL_IT0 (YDVARS%SPF)
    CALL EUL_IT0 (YDVARS%CVGQ)
    CALL EUL_IT0 (YDVARS%QVA)
    DO JFLD = 1, SIZE (YDVARS%GHG)
      CALL EUL_IT0 (YDVARS%GHG (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%CHEM)
      CALL EUL_IT0 (YDVARS%CHEM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERO)
      CALL EUL_IT0 (YDVARS%AERO (JFLD))
    ENDDO
    CALL EUL_IT0 (YDVARS%LRCH4)
    DO JFLD = 1, SIZE (YDVARS%FORC)
      CALL EUL_IT0 (YDVARS%FORC (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%EZDIAG)
      CALL EUL_IT0 (YDVARS%EZDIAG (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%ERA40)
      CALL EUL_IT0 (YDVARS%ERA40 (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%NOGW)
      CALL EUL_IT0 (YDVARS%NOGW (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%EDRP)
      CALL EUL_IT0 (YDVARS%EDRP (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%SLDIA)
      CALL EUL_IT0 (YDVARS%SLDIA (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERAOT)
      CALL EUL_IT0 (YDVARS%AERAOT (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERLISI)
      CALL EUL_IT0 (YDVARS%AERLISI (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AEROUT)
      CALL EUL_IT0 (YDVARS%AEROUT (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
      CALL EUL_IT0 (YDVARS%AEROCLIM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%UVP)
      CALL EUL_IT0 (YDVARS%UVP (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%PHYS)
      CALL EUL_IT0 (YDVARS%PHYS (JFLD))
    ENDDO
    CALL EUL_IT0 (YDVARS%PHYCTY)
    CALL EUL_IT0 (YDVARS%RSPEC)
    CALL EUL_IT0 (YDVARS%SDSAT)
    CALL EUL_IT0 (YDVARS%CVV)
    CALL EUL_IT0 (YDVARS%RKTH)
    CALL EUL_IT0 (YDVARS%RKTQV)
    CALL EUL_IT0 (YDVARS%RKTQC)
    CALL EUL_IT0 (YDVARS%UOM)
    CALL EUL_IT0 (YDVARS%UAL)
    CALL EUL_IT0 (YDVARS%DOM)
    CALL EUL_IT0 (YDVARS%DAL)
    CALL EUL_IT0 (YDVARS%UEN)
    CALL EUL_IT0 (YDVARS%UNEBH)
    DO JFLD = 1, SIZE (YDVARS%CRM)
      CALL EUL_IT0 (YDVARS%CRM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%LIMA)
      CALL EUL_IT0 (YDVARS%LIMA (JFLD))
    ENDDO
    CALL EUL_IT0 (YDVARS%FSD)
    DO JFLD = 1, SIZE (YDVARS%EXT)
      CALL EUL_IT0 (YDVARS%EXT (JFLD))
    ENDDO
  ELSE
    CALL EUL_ITX (YDVARS%Q)
    CALL EUL_ITX (YDVARS%I)
    CALL EUL_ITX (YDVARS%L)
    CALL EUL_ITX (YDVARS%LCONV)
    CALL EUL_ITX (YDVARS%ICONV)
    CALL EUL_ITX (YDVARS%RCONV)
    CALL EUL_ITX (YDVARS%SCONV)
    CALL EUL_ITX (YDVARS%IRAD)
    CALL EUL_ITX (YDVARS%LRAD)
    CALL EUL_ITX (YDVARS%S)
    CALL EUL_ITX (YDVARS%R)
    CALL EUL_ITX (YDVARS%G)
    CALL EUL_ITX (YDVARS%H)
    CALL EUL_ITX (YDVARS%TKE)
    CALL EUL_ITX (YDVARS%TTE)
    CALL EUL_ITX (YDVARS%EFB1)
    CALL EUL_ITX (YDVARS%EFB2)
    CALL EUL_ITX (YDVARS%EFB3)
    CALL EUL_ITX (YDVARS%A)
    CALL EUL_ITX (YDVARS%O3)
    CALL EUL_ITX (YDVARS%SRC)
    CALL EUL_ITX (YDVARS%MXL)
    CALL EUL_ITX (YDVARS%SHTUR)
    CALL EUL_ITX (YDVARS%FQTUR)
    CALL EUL_ITX (YDVARS%FSTUR)
    CALL EUL_ITX (YDVARS%CPF)
    CALL EUL_ITX (YDVARS%SPF)
    CALL EUL_ITX (YDVARS%CVGQ)
    CALL EUL_ITX (YDVARS%QVA)
    DO JFLD = 1, SIZE (YDVARS%GHG)
      CALL EUL_ITX (YDVARS%GHG (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%CHEM)
      CALL EUL_ITX (YDVARS%CHEM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERO)
      CALL EUL_ITX (YDVARS%AERO (JFLD))
    ENDDO
    CALL EUL_ITX (YDVARS%LRCH4)
    DO JFLD = 1, SIZE (YDVARS%FORC)
      CALL EUL_ITX (YDVARS%FORC (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%EZDIAG)
      CALL EUL_ITX (YDVARS%EZDIAG (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%ERA40)
      CALL EUL_ITX (YDVARS%ERA40 (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%NOGW)
      CALL EUL_ITX (YDVARS%NOGW (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%EDRP)
      CALL EUL_ITX (YDVARS%EDRP (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%SLDIA)
      CALL EUL_ITX (YDVARS%SLDIA (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERAOT)
      CALL EUL_ITX (YDVARS%AERAOT (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AERLISI)
      CALL EUL_ITX (YDVARS%AERLISI (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AEROUT)
      CALL EUL_ITX (YDVARS%AEROUT (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
      CALL EUL_ITX (YDVARS%AEROCLIM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%UVP)
      CALL EUL_ITX (YDVARS%UVP (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%PHYS)
      CALL EUL_ITX (YDVARS%PHYS (JFLD))
    ENDDO
    CALL EUL_ITX (YDVARS%PHYCTY)
    CALL EUL_ITX (YDVARS%RSPEC)
    CALL EUL_ITX (YDVARS%SDSAT)
    CALL EUL_ITX (YDVARS%CVV)
    CALL EUL_ITX (YDVARS%RKTH)
    CALL EUL_ITX (YDVARS%RKTQV)
    CALL EUL_ITX (YDVARS%RKTQC)
    CALL EUL_ITX (YDVARS%UOM)
    CALL EUL_ITX (YDVARS%UAL)
    CALL EUL_ITX (YDVARS%DOM)
    CALL EUL_ITX (YDVARS%DAL)
    CALL EUL_ITX (YDVARS%UEN)
    CALL EUL_ITX (YDVARS%UNEBH)
    DO JFLD = 1, SIZE (YDVARS%CRM)
      CALL EUL_ITX (YDVARS%CRM (JFLD))
    ENDDO
    DO JFLD = 1, SIZE (YDVARS%LIMA)
      CALL EUL_ITX (YDVARS%LIMA (JFLD))
    ENDDO
    CALL EUL_ITX (YDVARS%FSD)
    DO JFLD = 1, SIZE (YDVARS%EXT)
      CALL EUL_ITX (YDVARS%EXT (JFLD))
    ENDDO
  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('GPINISLB_PART2_EXPL',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE EUL_IT0 (YDVAR)
USE VARIABLE_MODULE, ONLY : VARIABLE_3D
TYPE (VARIABLE_3D) :: YDVAR
IF(YDVAR%LT1) THEN
  CALL TPTE (YDVAR%T1, YDVAR%T9)
ENDIF
END SUBROUTINE

SUBROUTINE EUL_ITX (YDVAR)
USE VARIABLE_MODULE, ONLY : VARIABLE_3D
TYPE (VARIABLE_3D) :: YDVAR
IF(YDVAR%LT1) THEN
  CALL ZERO (YDVAR%T1)
ENDIF
END SUBROUTINE

SUBROUTINE SLG_2TL (YDVAR)
USE VARIABLE_MODULE, ONLY : VARIABLE_3D
TYPE (VARIABLE_3D) :: YDVAR
IF(YDVAR%LADV) THEN
  CALL ZERO (YDVAR%T1)
ELSEIF(YDVAR%LT1) THEN
  CALL TPTE (YDVAR%T1, YDVAR%T0)
ENDIF
END SUBROUTINE

SUBROUTINE SLG_3TL (YDVAR)
USE VARIABLE_MODULE, ONLY : VARIABLE_3D
TYPE (VARIABLE_3D) :: YDVAR
IF(YDVAR%LADV) THEN
  CALL ZERO (YDVAR%T1)
ELSEIF(YDVAR%LT1) THEN
  CALL TPTE (YDVAR%T1, YDVAR%T9)
ENDIF
END SUBROUTINE

SUBROUTINE ZERO (P1)
REAL (KIND=JPRB), INTENT (OUT) :: P1 (:,:)
P1 (KST:KEN,:) = 0._JPRB
END SUBROUTINE

SUBROUTINE TPTE (P1, PX)
REAL (KIND=JPRB), INTENT (OUT) :: P1 (:,:)
REAL (KIND=JPRB), INTENT (IN)  :: PX (:,:)
P1 (KST:KEN,:) = PX (KST:KEN,:) * PTE
END SUBROUTINE

END SUBROUTINE
