
SUBROUTINE GPMPFC_EXPL_PART2 (YDVARS, KPROMA, KFLEV, KST, KEN, PGM)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK

USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE FIELD_VARIABLES_MOD    , ONLY : FIELD_VARIABLES

IMPLICIT NONE

TYPE(FIELD_VARIABLES), INTENT(INOUT) :: YDVARS
INTEGER(KIND=JPIM)   , INTENT(IN)    :: KPROMA
INTEGER(KIND=JPIM)   , INTENT(IN)    :: KFLEV
INTEGER(KIND=JPIM)   , INTENT(IN)    :: KST
INTEGER(KIND=JPIM)   , INTENT(IN)    :: KEN
REAL(KIND=JPRB)      , INTENT(IN)    :: PGM (KPROMA)

INTEGER (KIND=JPIM) :: JFLD
INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

REAL(KIND=JPRB) :: ZHOOK

IF (LHOOK) CALL DR_HOOK("GPMPFC_EXPL_PART2",0,ZHOOK)

CALL GPMPFC_EXPL_PART2_V (YDVARS%Q%LCDERS, YDVARS%Q%DM, YDVARS%Q%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%I%LCDERS, YDVARS%I%DM, YDVARS%I%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%L%LCDERS, YDVARS%L%DM, YDVARS%L%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%LCONV%LCDERS, YDVARS%LCONV%DM, YDVARS%LCONV%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%ICONV%LCDERS, YDVARS%ICONV%DM, YDVARS%ICONV%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%RCONV%LCDERS, YDVARS%RCONV%DM, YDVARS%RCONV%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%SCONV%LCDERS, YDVARS%SCONV%DM, YDVARS%SCONV%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%IRAD%LCDERS, YDVARS%IRAD%DM, YDVARS%IRAD%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%LRAD%LCDERS, YDVARS%LRAD%DM, YDVARS%LRAD%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%S%LCDERS, YDVARS%S%DM, YDVARS%S%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%R%LCDERS, YDVARS%R%DM, YDVARS%R%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%G%LCDERS, YDVARS%G%DM, YDVARS%G%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%H%LCDERS, YDVARS%H%DM, YDVARS%H%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%TKE%LCDERS, YDVARS%TKE%DM, YDVARS%TKE%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%TTE%LCDERS, YDVARS%TTE%DM, YDVARS%TTE%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%EFB1%LCDERS, YDVARS%EFB1%DM, YDVARS%EFB1%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%EFB2%LCDERS, YDVARS%EFB2%DM, YDVARS%EFB2%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%EFB3%LCDERS, YDVARS%EFB3%DM, YDVARS%EFB3%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%A%LCDERS, YDVARS%A%DM, YDVARS%A%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%O3%LCDERS, YDVARS%O3%DM, YDVARS%O3%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%SRC%LCDERS, YDVARS%SRC%DM, YDVARS%SRC%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%MXL%LCDERS, YDVARS%MXL%DM, YDVARS%MXL%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%SHTUR%LCDERS, YDVARS%SHTUR%DM, YDVARS%SHTUR%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%FQTUR%LCDERS, YDVARS%FQTUR%DM, YDVARS%FQTUR%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%FSTUR%LCDERS, YDVARS%FSTUR%DM, YDVARS%FSTUR%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%CPF%LCDERS, YDVARS%CPF%DM, YDVARS%CPF%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%SPF%LCDERS, YDVARS%SPF%DM, YDVARS%SPF%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%CVGQ%LCDERS, YDVARS%CVGQ%DM, YDVARS%CVGQ%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%QVA%LCDERS, YDVARS%QVA%DM, YDVARS%QVA%DL)
DO JFLD = 1, SIZE (YDVARS%GHG)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%GHG(JFLD)%LCDERS, YDVARS%GHG(JFLD)%DM, YDVARS%GHG(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%CHEM)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%CHEM(JFLD)%LCDERS, YDVARS%CHEM(JFLD)%DM, YDVARS%CHEM(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%AERO)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%AERO(JFLD)%LCDERS, YDVARS%AERO(JFLD)%DM, YDVARS%AERO(JFLD)%DL)
ENDDO
CALL GPMPFC_EXPL_PART2_V (YDVARS%LRCH4%LCDERS, YDVARS%LRCH4%DM, YDVARS%LRCH4%DL)
DO JFLD = 1, SIZE (YDVARS%FORC)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%FORC(JFLD)%LCDERS, YDVARS%FORC(JFLD)%DM, YDVARS%FORC(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%EZDIAG)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%EZDIAG(JFLD)%LCDERS, YDVARS%EZDIAG(JFLD)%DM, YDVARS%EZDIAG(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%ERA40)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%ERA40(JFLD)%LCDERS, YDVARS%ERA40(JFLD)%DM, YDVARS%ERA40(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%NOGW)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%NOGW(JFLD)%LCDERS, YDVARS%NOGW(JFLD)%DM, YDVARS%NOGW(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%EDRP)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%EDRP(JFLD)%LCDERS, YDVARS%EDRP(JFLD)%DM, YDVARS%EDRP(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%SLDIA)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%SLDIA(JFLD)%LCDERS, YDVARS%SLDIA(JFLD)%DM, YDVARS%SLDIA(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%AERAOT)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%AERAOT(JFLD)%LCDERS, YDVARS%AERAOT(JFLD)%DM, YDVARS%AERAOT(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%AERLISI)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%AERLISI(JFLD)%LCDERS, YDVARS%AERLISI(JFLD)%DM, YDVARS%AERLISI(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%AEROUT)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%AEROUT(JFLD)%LCDERS, YDVARS%AEROUT(JFLD)%DM, YDVARS%AEROUT(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%AEROCLIM(JFLD)%LCDERS, YDVARS%AEROCLIM(JFLD)%DM, YDVARS%AEROCLIM(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%UVP)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%UVP(JFLD)%LCDERS, YDVARS%UVP(JFLD)%DM, YDVARS%UVP(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%PHYS)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%PHYS(JFLD)%LCDERS, YDVARS%PHYS(JFLD)%DM, YDVARS%PHYS(JFLD)%DL)
ENDDO
CALL GPMPFC_EXPL_PART2_V (YDVARS%PHYCTY%LCDERS, YDVARS%PHYCTY%DM, YDVARS%PHYCTY%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%RSPEC%LCDERS, YDVARS%RSPEC%DM, YDVARS%RSPEC%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%SDSAT%LCDERS, YDVARS%SDSAT%DM, YDVARS%SDSAT%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%CVV%LCDERS, YDVARS%CVV%DM, YDVARS%CVV%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%RKTH%LCDERS, YDVARS%RKTH%DM, YDVARS%RKTH%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%RKTQV%LCDERS, YDVARS%RKTQV%DM, YDVARS%RKTQV%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%RKTQC%LCDERS, YDVARS%RKTQC%DM, YDVARS%RKTQC%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%UOM%LCDERS, YDVARS%UOM%DM, YDVARS%UOM%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%UAL%LCDERS, YDVARS%UAL%DM, YDVARS%UAL%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%DOM%LCDERS, YDVARS%DOM%DM, YDVARS%DOM%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%DAL%LCDERS, YDVARS%DAL%DM, YDVARS%DAL%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%UEN%LCDERS, YDVARS%UEN%DM, YDVARS%UEN%DL)
CALL GPMPFC_EXPL_PART2_V (YDVARS%UNEBH%LCDERS, YDVARS%UNEBH%DM, YDVARS%UNEBH%DL)
DO JFLD = 1, SIZE (YDVARS%CRM)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%CRM(JFLD)%LCDERS, YDVARS%CRM(JFLD)%DM, YDVARS%CRM(JFLD)%DL)
ENDDO
DO JFLD = 1, SIZE (YDVARS%LIMA)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%LIMA(JFLD)%LCDERS, YDVARS%LIMA(JFLD)%DM, YDVARS%LIMA(JFLD)%DL)
ENDDO
CALL GPMPFC_EXPL_PART2_V (YDVARS%FSD%LCDERS, YDVARS%FSD%DM, YDVARS%FSD%DL)
DO JFLD = 1, SIZE (YDVARS%EXT)
  CALL GPMPFC_EXPL_PART2_V (YDVARS%EXT(JFLD)%LCDERS, YDVARS%EXT(JFLD)%DM, YDVARS%EXT(JFLD)%DL)
ENDDO

IF (LHOOK) CALL DR_HOOK("GPMPFC_EXPL_PART2",1,ZHOOK)

CONTAINS

SUBROUTINE GPMPFC_EXPL_PART2_V (LDCDERS, PDM, PDL)

LOGICAL, INTENT (IN) :: LDCDERS
REAL (KIND=JPRB), INTENT (INOUT) :: PDM (KPROMA,KFLEV)
REAL (KIND=JPRB), INTENT (INOUT) :: PDL (KPROMA,KFLEV)

IF (LDCDERS) THEN
  DO JLEV=1,KFLEV
    DO JROF=KST,KEN
      PDM (JROF,JLEV) = PDM (JROF,JLEV) * PGM (JROF)
      PDL (JROF,JLEV) = PDL (JROF,JLEV) * PGM (JROF)
    ENDDO
  ENDDO
ENDIF

END SUBROUTINE GPMPFC_EXPL_PART2_V

END SUBROUTINE
