
SUBROUTINE GPRCP_EXPL (YDCST,KPROMA,KST,KPROF,KFLEV,PCP,PR,PKAP,YDVARS,KGFLTYP)

!**** *GPRCP_EXPL* - Computes Cp, R and R/Cp from Q

!     Purpose.
!     --------
!        Computes Cp, R and R/Cp from Q

!**   Interface.
!     ----------
!        *CALL* *GPRCP_EXPL(...)

!        Explicit arguments :
!        --------------------

!        INPUT:
!          KPROMA               - dimensioning.
!          KSTART               - start of work.
!          KPROF                - depth of work.
!          KFLEV                - number of layers.

!        OUTPUT:
!          PCP(KPROMA,KFLEV)    - CP
!          PR(KPROMA,KFLEV)     - R
!          PKAP(KPROMA,KFLEV)   - KAPPA

!        Implicit arguments :  Physical constants from YOMCST
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.  None.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud and Philippe Courtier  *ECMWF*
!      Original : 88-02-04

!     Modifications.
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      Y.Seity  04-02-13 (Rain, Snow and Graupel)
!      M.Hamrud  15-Jan-2006  Revised GPRCP
!      K. Yessad (Jan 2011): more compact rewriting.
!      R. El Khatib 28-Aug-2014 Optimizations :
!       - compute R or CP only if required
!       - loop collapsing whenever possible, through pure array syntax
!      A. Geer      01-Oct-2015    For independence of observation operator in OOPS, 
!                                  allow calls without YGFL initialised. Removal
!                                  of all YGFL references will have to wait.
!      H Petithomme (Dec 2020): general rewrite for optimization
!     ------------------------------------------------------------------

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK

USE YOMCST,              ONLY: TCST
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES

IMPLICIT NONE

TYPE(TCST),                     INTENT(IN)    :: YDCST
INTEGER(KIND=JPIM),             INTENT(IN)    :: KPROMA,KFLEV,KST,KPROF
INTEGER(KIND=JPIM),OPTIONAL,    INTENT(IN)    :: KGFLTYP
TYPE(FIELD_VARIABLES),          INTENT(INOUT) :: YDVARS
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT)   :: PCP(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT)   :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,       INTENT(OUT)   :: PKAP(KPROMA,KFLEV)

#include "abor1.intfb.h"

REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZR(:,:)
REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZCP(:,:)
LOGICAL :: LLCP

REAL(KIND=JPRB),TARGET :: ZCP0(KPROMA,KFLEV),ZR0(KPROMA,KFLEV)
INTEGER(KIND=JPIM) :: IGFLTYP,JLON,JLEV

REAL(KIND=JPRB) :: ZHOOK

IF (LHOOK) CALL DR_HOOK("GPRCP_EXPL",0,ZHOOK)

IF (PRESENT(PR)) THEN
  ZR => PR(:,:)
ELSEIF (PRESENT(PKAP)) THEN
  ZR => ZR0(:,:)
ENDIF

LLCP = .TRUE.

IF (PRESENT(PCP)) THEN
  ZCP => PCP(:,:)
ELSEIF (PRESENT(PKAP)) THEN
  ZCP => ZCP0(:,:)
ELSE
  ZCP => NULL()
  LLCP = .FALSE.
ENDIF

IF (LLCP) THEN
  ZCP = 0._JPRB
ENDIF

ZR = 0._JPRB

IGFLTYP = 0
IF (PRESENT (KGFLTYP)) IGFLTYP = KGFLTYP 



SELECT CASE (IGFLTYP)
  CASE (0)
  IF (YDVARS%Q%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%Q%R - YDCST%RD) * YDVARS%Q%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%Q%RCP - YDCST%RCPD) * YDVARS%Q%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%I%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%I%R - YDCST%RD) * YDVARS%I%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%I%RCP - YDCST%RCPD) * YDVARS%I%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%L%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%L%R - YDCST%RD) * YDVARS%L%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%L%RCP - YDCST%RCPD) * YDVARS%L%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LCONV%R - YDCST%RD) * YDVARS%LCONV%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LCONV%RCP - YDCST%RCPD) * YDVARS%LCONV%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%ICONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ICONV%R - YDCST%RD) * YDVARS%ICONV%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ICONV%RCP - YDCST%RCPD) * YDVARS%ICONV%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RCONV%R - YDCST%RD) * YDVARS%RCONV%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RCONV%RCP - YDCST%RCPD) * YDVARS%RCONV%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SCONV%R - YDCST%RD) * YDVARS%SCONV%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SCONV%RCP - YDCST%RCPD) * YDVARS%SCONV%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%IRAD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%IRAD%R - YDCST%RD) * YDVARS%IRAD%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%IRAD%RCP - YDCST%RCPD) * YDVARS%IRAD%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LRAD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRAD%R - YDCST%RD) * YDVARS%LRAD%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRAD%RCP - YDCST%RCPD) * YDVARS%LRAD%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%S%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%S%R - YDCST%RD) * YDVARS%S%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%S%RCP - YDCST%RCPD) * YDVARS%S%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%R%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%R%R - YDCST%RD) * YDVARS%R%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%R%RCP - YDCST%RCPD) * YDVARS%R%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%G%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%G%R - YDCST%RD) * YDVARS%G%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%G%RCP - YDCST%RCPD) * YDVARS%G%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%H%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%H%R - YDCST%RD) * YDVARS%H%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%H%RCP - YDCST%RCPD) * YDVARS%H%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%TKE%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TKE%R - YDCST%RD) * YDVARS%TKE%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TKE%RCP - YDCST%RCPD) * YDVARS%TKE%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%TTE%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TTE%R - YDCST%RD) * YDVARS%TTE%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TTE%RCP - YDCST%RCPD) * YDVARS%TTE%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB1%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB1%R - YDCST%RD) * YDVARS%EFB1%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB1%RCP - YDCST%RCPD) * YDVARS%EFB1%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB2%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB2%R - YDCST%RD) * YDVARS%EFB2%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB2%RCP - YDCST%RCPD) * YDVARS%EFB2%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB3%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB3%R - YDCST%RD) * YDVARS%EFB3%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB3%RCP - YDCST%RCPD) * YDVARS%EFB3%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%A%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%A%R - YDCST%RD) * YDVARS%A%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%A%RCP - YDCST%RCPD) * YDVARS%A%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%O3%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%O3%R - YDCST%RD) * YDVARS%O3%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%O3%RCP - YDCST%RCPD) * YDVARS%O3%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SRC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SRC%R - YDCST%RD) * YDVARS%SRC%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SRC%RCP - YDCST%RCPD) * YDVARS%SRC%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%MXL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%MXL%R - YDCST%RD) * YDVARS%MXL%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%MXL%RCP - YDCST%RCPD) * YDVARS%MXL%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SHTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SHTUR%R - YDCST%RD) * YDVARS%SHTUR%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SHTUR%RCP - YDCST%RCPD) * YDVARS%SHTUR%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FQTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FQTUR%R - YDCST%RD) * YDVARS%FQTUR%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FQTUR%RCP - YDCST%RCPD) * YDVARS%FQTUR%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FSTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSTUR%R - YDCST%RD) * YDVARS%FSTUR%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSTUR%RCP - YDCST%RCPD) * YDVARS%FSTUR%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CPF%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CPF%R - YDCST%RD) * YDVARS%CPF%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CPF%RCP - YDCST%RCPD) * YDVARS%CPF%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SPF%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SPF%R - YDCST%RD) * YDVARS%SPF%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SPF%RCP - YDCST%RCPD) * YDVARS%SPF%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CVGQ%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVGQ%R - YDCST%RD) * YDVARS%CVGQ%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVGQ%RCP - YDCST%RCPD) * YDVARS%CVGQ%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%QVA%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%QVA%R - YDCST%RD) * YDVARS%QVA%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%QVA%RCP - YDCST%RCPD) * YDVARS%QVA%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LRCH4%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRCH4%R - YDCST%RD) * YDVARS%LRCH4%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRCH4%RCP - YDCST%RCPD) * YDVARS%LRCH4%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%PHYCTY%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYCTY%R - YDCST%RD) * YDVARS%PHYCTY%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYCTY%RCP - YDCST%RCPD) * YDVARS%PHYCTY%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RSPEC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RSPEC%R - YDCST%RD) * YDVARS%RSPEC%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RSPEC%RCP - YDCST%RCPD) * YDVARS%RSPEC%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SDSAT%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SDSAT%R - YDCST%RD) * YDVARS%SDSAT%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SDSAT%RCP - YDCST%RCPD) * YDVARS%SDSAT%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CVV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVV%R - YDCST%RD) * YDVARS%CVV%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVV%RCP - YDCST%RCPD) * YDVARS%CVV%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTH%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTH%R - YDCST%RD) * YDVARS%RKTH%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTH%RCP - YDCST%RCPD) * YDVARS%RKTH%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTQV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQV%R - YDCST%RD) * YDVARS%RKTQV%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQV%RCP - YDCST%RCPD) * YDVARS%RKTQV%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTQC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQC%R - YDCST%RD) * YDVARS%RKTQC%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQC%RCP - YDCST%RCPD) * YDVARS%RKTQC%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UOM%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UOM%R - YDCST%RD) * YDVARS%UOM%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UOM%RCP - YDCST%RCPD) * YDVARS%UOM%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UAL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UAL%R - YDCST%RD) * YDVARS%UAL%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UAL%RCP - YDCST%RCPD) * YDVARS%UAL%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%DOM%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DOM%R - YDCST%RD) * YDVARS%DOM%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DOM%RCP - YDCST%RCPD) * YDVARS%DOM%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%DAL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DAL%R - YDCST%RD) * YDVARS%DAL%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DAL%RCP - YDCST%RCPD) * YDVARS%DAL%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UEN%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UEN%R - YDCST%RD) * YDVARS%UEN%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UEN%RCP - YDCST%RCPD) * YDVARS%UEN%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UNEBH%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UNEBH%R - YDCST%RD) * YDVARS%UNEBH%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UNEBH%RCP - YDCST%RCPD) * YDVARS%UNEBH%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FSD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSD%R - YDCST%RD) * YDVARS%FSD%T0 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSD%RCP - YDCST%RCPD) * YDVARS%FSD%T0 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  CASE (1)
  IF (YDVARS%Q%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%Q%R - YDCST%RD) * YDVARS%Q%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%Q%RCP - YDCST%RCPD) * YDVARS%Q%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%I%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%I%R - YDCST%RD) * YDVARS%I%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%I%RCP - YDCST%RCPD) * YDVARS%I%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%L%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%L%R - YDCST%RD) * YDVARS%L%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%L%RCP - YDCST%RCPD) * YDVARS%L%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LCONV%R - YDCST%RD) * YDVARS%LCONV%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LCONV%RCP - YDCST%RCPD) * YDVARS%LCONV%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%ICONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ICONV%R - YDCST%RD) * YDVARS%ICONV%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ICONV%RCP - YDCST%RCPD) * YDVARS%ICONV%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RCONV%R - YDCST%RD) * YDVARS%RCONV%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RCONV%RCP - YDCST%RCPD) * YDVARS%RCONV%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SCONV%R - YDCST%RD) * YDVARS%SCONV%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SCONV%RCP - YDCST%RCPD) * YDVARS%SCONV%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%IRAD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%IRAD%R - YDCST%RD) * YDVARS%IRAD%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%IRAD%RCP - YDCST%RCPD) * YDVARS%IRAD%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LRAD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRAD%R - YDCST%RD) * YDVARS%LRAD%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRAD%RCP - YDCST%RCPD) * YDVARS%LRAD%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%S%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%S%R - YDCST%RD) * YDVARS%S%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%S%RCP - YDCST%RCPD) * YDVARS%S%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%R%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%R%R - YDCST%RD) * YDVARS%R%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%R%RCP - YDCST%RCPD) * YDVARS%R%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%G%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%G%R - YDCST%RD) * YDVARS%G%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%G%RCP - YDCST%RCPD) * YDVARS%G%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%H%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%H%R - YDCST%RD) * YDVARS%H%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%H%RCP - YDCST%RCPD) * YDVARS%H%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%TKE%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TKE%R - YDCST%RD) * YDVARS%TKE%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TKE%RCP - YDCST%RCPD) * YDVARS%TKE%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%TTE%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TTE%R - YDCST%RD) * YDVARS%TTE%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TTE%RCP - YDCST%RCPD) * YDVARS%TTE%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB1%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB1%R - YDCST%RD) * YDVARS%EFB1%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB1%RCP - YDCST%RCPD) * YDVARS%EFB1%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB2%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB2%R - YDCST%RD) * YDVARS%EFB2%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB2%RCP - YDCST%RCPD) * YDVARS%EFB2%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB3%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB3%R - YDCST%RD) * YDVARS%EFB3%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB3%RCP - YDCST%RCPD) * YDVARS%EFB3%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%A%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%A%R - YDCST%RD) * YDVARS%A%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%A%RCP - YDCST%RCPD) * YDVARS%A%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%O3%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%O3%R - YDCST%RD) * YDVARS%O3%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%O3%RCP - YDCST%RCPD) * YDVARS%O3%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SRC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SRC%R - YDCST%RD) * YDVARS%SRC%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SRC%RCP - YDCST%RCPD) * YDVARS%SRC%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%MXL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%MXL%R - YDCST%RD) * YDVARS%MXL%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%MXL%RCP - YDCST%RCPD) * YDVARS%MXL%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SHTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SHTUR%R - YDCST%RD) * YDVARS%SHTUR%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SHTUR%RCP - YDCST%RCPD) * YDVARS%SHTUR%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FQTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FQTUR%R - YDCST%RD) * YDVARS%FQTUR%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FQTUR%RCP - YDCST%RCPD) * YDVARS%FQTUR%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FSTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSTUR%R - YDCST%RD) * YDVARS%FSTUR%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSTUR%RCP - YDCST%RCPD) * YDVARS%FSTUR%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CPF%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CPF%R - YDCST%RD) * YDVARS%CPF%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CPF%RCP - YDCST%RCPD) * YDVARS%CPF%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SPF%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SPF%R - YDCST%RD) * YDVARS%SPF%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SPF%RCP - YDCST%RCPD) * YDVARS%SPF%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CVGQ%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVGQ%R - YDCST%RD) * YDVARS%CVGQ%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVGQ%RCP - YDCST%RCPD) * YDVARS%CVGQ%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%QVA%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%QVA%R - YDCST%RD) * YDVARS%QVA%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%QVA%RCP - YDCST%RCPD) * YDVARS%QVA%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LRCH4%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRCH4%R - YDCST%RD) * YDVARS%LRCH4%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRCH4%RCP - YDCST%RCPD) * YDVARS%LRCH4%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%PHYCTY%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYCTY%R - YDCST%RD) * YDVARS%PHYCTY%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYCTY%RCP - YDCST%RCPD) * YDVARS%PHYCTY%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RSPEC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RSPEC%R - YDCST%RD) * YDVARS%RSPEC%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RSPEC%RCP - YDCST%RCPD) * YDVARS%RSPEC%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SDSAT%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SDSAT%R - YDCST%RD) * YDVARS%SDSAT%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SDSAT%RCP - YDCST%RCPD) * YDVARS%SDSAT%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CVV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVV%R - YDCST%RD) * YDVARS%CVV%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVV%RCP - YDCST%RCPD) * YDVARS%CVV%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTH%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTH%R - YDCST%RD) * YDVARS%RKTH%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTH%RCP - YDCST%RCPD) * YDVARS%RKTH%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTQV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQV%R - YDCST%RD) * YDVARS%RKTQV%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQV%RCP - YDCST%RCPD) * YDVARS%RKTQV%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTQC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQC%R - YDCST%RD) * YDVARS%RKTQC%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQC%RCP - YDCST%RCPD) * YDVARS%RKTQC%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UOM%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UOM%R - YDCST%RD) * YDVARS%UOM%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UOM%RCP - YDCST%RCPD) * YDVARS%UOM%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UAL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UAL%R - YDCST%RD) * YDVARS%UAL%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UAL%RCP - YDCST%RCPD) * YDVARS%UAL%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%DOM%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DOM%R - YDCST%RD) * YDVARS%DOM%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DOM%RCP - YDCST%RCPD) * YDVARS%DOM%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%DAL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DAL%R - YDCST%RD) * YDVARS%DAL%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DAL%RCP - YDCST%RCPD) * YDVARS%DAL%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UEN%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UEN%R - YDCST%RD) * YDVARS%UEN%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UEN%RCP - YDCST%RCPD) * YDVARS%UEN%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UNEBH%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UNEBH%R - YDCST%RD) * YDVARS%UNEBH%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UNEBH%RCP - YDCST%RCPD) * YDVARS%UNEBH%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FSD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSD%R - YDCST%RD) * YDVARS%FSD%T1 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSD%RCP - YDCST%RCPD) * YDVARS%FSD%T1 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  CASE (9)
  IF (YDVARS%Q%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%Q%R - YDCST%RD) * YDVARS%Q%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%Q%RCP - YDCST%RCPD) * YDVARS%Q%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%I%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%I%R - YDCST%RD) * YDVARS%I%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%I%RCP - YDCST%RCPD) * YDVARS%I%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%L%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%L%R - YDCST%RD) * YDVARS%L%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%L%RCP - YDCST%RCPD) * YDVARS%L%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LCONV%R - YDCST%RD) * YDVARS%LCONV%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LCONV%RCP - YDCST%RCPD) * YDVARS%LCONV%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%ICONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ICONV%R - YDCST%RD) * YDVARS%ICONV%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ICONV%RCP - YDCST%RCPD) * YDVARS%ICONV%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RCONV%R - YDCST%RD) * YDVARS%RCONV%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RCONV%RCP - YDCST%RCPD) * YDVARS%RCONV%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SCONV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SCONV%R - YDCST%RD) * YDVARS%SCONV%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SCONV%RCP - YDCST%RCPD) * YDVARS%SCONV%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%IRAD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%IRAD%R - YDCST%RD) * YDVARS%IRAD%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%IRAD%RCP - YDCST%RCPD) * YDVARS%IRAD%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LRAD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRAD%R - YDCST%RD) * YDVARS%LRAD%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRAD%RCP - YDCST%RCPD) * YDVARS%LRAD%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%S%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%S%R - YDCST%RD) * YDVARS%S%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%S%RCP - YDCST%RCPD) * YDVARS%S%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%R%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%R%R - YDCST%RD) * YDVARS%R%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%R%RCP - YDCST%RCPD) * YDVARS%R%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%G%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%G%R - YDCST%RD) * YDVARS%G%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%G%RCP - YDCST%RCPD) * YDVARS%G%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%H%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%H%R - YDCST%RD) * YDVARS%H%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%H%RCP - YDCST%RCPD) * YDVARS%H%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%TKE%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TKE%R - YDCST%RD) * YDVARS%TKE%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TKE%RCP - YDCST%RCPD) * YDVARS%TKE%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%TTE%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TTE%R - YDCST%RD) * YDVARS%TTE%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TTE%RCP - YDCST%RCPD) * YDVARS%TTE%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB1%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB1%R - YDCST%RD) * YDVARS%EFB1%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB1%RCP - YDCST%RCPD) * YDVARS%EFB1%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB2%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB2%R - YDCST%RD) * YDVARS%EFB2%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB2%RCP - YDCST%RCPD) * YDVARS%EFB2%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%EFB3%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB3%R - YDCST%RD) * YDVARS%EFB3%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB3%RCP - YDCST%RCPD) * YDVARS%EFB3%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%A%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%A%R - YDCST%RD) * YDVARS%A%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%A%RCP - YDCST%RCPD) * YDVARS%A%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%O3%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%O3%R - YDCST%RD) * YDVARS%O3%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%O3%RCP - YDCST%RCPD) * YDVARS%O3%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SRC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SRC%R - YDCST%RD) * YDVARS%SRC%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SRC%RCP - YDCST%RCPD) * YDVARS%SRC%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%MXL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%MXL%R - YDCST%RD) * YDVARS%MXL%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%MXL%RCP - YDCST%RCPD) * YDVARS%MXL%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SHTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SHTUR%R - YDCST%RD) * YDVARS%SHTUR%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SHTUR%RCP - YDCST%RCPD) * YDVARS%SHTUR%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FQTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FQTUR%R - YDCST%RD) * YDVARS%FQTUR%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FQTUR%RCP - YDCST%RCPD) * YDVARS%FQTUR%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FSTUR%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSTUR%R - YDCST%RD) * YDVARS%FSTUR%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSTUR%RCP - YDCST%RCPD) * YDVARS%FSTUR%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CPF%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CPF%R - YDCST%RD) * YDVARS%CPF%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CPF%RCP - YDCST%RCPD) * YDVARS%CPF%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SPF%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SPF%R - YDCST%RD) * YDVARS%SPF%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SPF%RCP - YDCST%RCPD) * YDVARS%SPF%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CVGQ%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVGQ%R - YDCST%RD) * YDVARS%CVGQ%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVGQ%RCP - YDCST%RCPD) * YDVARS%CVGQ%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%QVA%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%QVA%R - YDCST%RD) * YDVARS%QVA%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%QVA%RCP - YDCST%RCPD) * YDVARS%QVA%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%LRCH4%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRCH4%R - YDCST%RD) * YDVARS%LRCH4%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRCH4%RCP - YDCST%RCPD) * YDVARS%LRCH4%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%PHYCTY%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYCTY%R - YDCST%RD) * YDVARS%PHYCTY%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYCTY%RCP - YDCST%RCPD) * YDVARS%PHYCTY%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RSPEC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RSPEC%R - YDCST%RD) * YDVARS%RSPEC%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RSPEC%RCP - YDCST%RCPD) * YDVARS%RSPEC%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%SDSAT%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SDSAT%R - YDCST%RD) * YDVARS%SDSAT%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SDSAT%RCP - YDCST%RCPD) * YDVARS%SDSAT%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%CVV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVV%R - YDCST%RD) * YDVARS%CVV%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVV%RCP - YDCST%RCPD) * YDVARS%CVV%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTH%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTH%R - YDCST%RD) * YDVARS%RKTH%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTH%RCP - YDCST%RCPD) * YDVARS%RKTH%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTQV%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQV%R - YDCST%RD) * YDVARS%RKTQV%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQV%RCP - YDCST%RCPD) * YDVARS%RKTQV%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%RKTQC%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQC%R - YDCST%RD) * YDVARS%RKTQC%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQC%RCP - YDCST%RCPD) * YDVARS%RKTQC%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UOM%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UOM%R - YDCST%RD) * YDVARS%UOM%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UOM%RCP - YDCST%RCPD) * YDVARS%UOM%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UAL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UAL%R - YDCST%RD) * YDVARS%UAL%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UAL%RCP - YDCST%RCPD) * YDVARS%UAL%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%DOM%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DOM%R - YDCST%RD) * YDVARS%DOM%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DOM%RCP - YDCST%RCPD) * YDVARS%DOM%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%DAL%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DAL%R - YDCST%RD) * YDVARS%DAL%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DAL%RCP - YDCST%RCPD) * YDVARS%DAL%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UEN%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UEN%R - YDCST%RD) * YDVARS%UEN%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UEN%RCP - YDCST%RCPD) * YDVARS%UEN%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%UNEBH%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UNEBH%R - YDCST%RD) * YDVARS%UNEBH%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UNEBH%RCP - YDCST%RCPD) * YDVARS%UNEBH%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  IF (YDVARS%FSD%LTHERMACT) THEN
    DO JLEV = 1, KFLEV
      DO JLON = KST, KPROF
        ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSD%R - YDCST%RD) * YDVARS%FSD%T9 (JLON, JLEV)
        IF (LLCP) THEN
          ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSD%RCP - YDCST%RCPD) * YDVARS%FSD%T9 (JLON, JLEV)
        ENDIF
      ENDDO
    ENDDO
  ENDIF
  CASE DEFAULT
    CALL ABOR1 ('UNEXPECTED IGFLTYP')
END SELECT 

DO JLEV = 1, KFLEV
  DO JLON = KST, KPROF
    ZR (JLON,JLEV) = YDCST%RD + ZR (JLON,JLEV)
    IF (LLCP) THEN
      ZCP (JLON,JLEV) = YDCST%RCPD + ZCP (JLON,JLEV)
    ENDIF
  ENDDO
ENDDO

IF (PRESENT(PKAP)) THEN
  PKAP(KST:KPROF,1:KFLEV)=ZR(KST:KPROF,1:KFLEV)/ZCP(KST:KPROF,1:KFLEV)
ENDIF

IF (LHOOK) CALL DR_HOOK("GPRCP_EXPL",1,ZHOOK)

END SUBROUTINE GPRCP_EXPL

