
SUBROUTINE GPRCP_EXPL (YDCST,KPROMA,KST,KPROF,KFLEV,PCP,PR,PKAP,YDVARS,KGFLTYP)

!**** *GPRCP_EXPL* - Computes Cp, R and R/Cp from Q

!     Purpose.
!     --------
!        Computes Cp, R and R/Cp from Q

!**   Interface.
!     ----------
!        *CALL* *GPRCP_EXPL(...)

!        Explicit arguments :
!        --------------------

!        INPUT:
!          KPROMA               - dimensioning.
!          KSTART               - start of work.
!          KPROF                - depth of work.
!          KFLEV                - number of layers.

!        OUTPUT:
!          PCP(KPROMA,KFLEV)    - CP
!          PR(KPROMA,KFLEV)     - R
!          PKAP(KPROMA,KFLEV)   - KAPPA

!        Implicit arguments :  Physical constants from YOMCST
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.  None.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud and Philippe Courtier  *ECMWF*
!      Original : 88-02-04

!     Modifications.
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      Y.Seity  04-02-13 (Rain, Snow and Graupel)
!      M.Hamrud  15-Jan-2006  Revised GPRCP
!      K. Yessad (Jan 2011): more compact rewriting.
!      R. El Khatib 28-Aug-2014 Optimizations :
!       - compute R or CP only if required
!       - loop collapsing whenever possible, through pure array syntax
!      A. Geer      01-Oct-2015    For independence of observation operator in OOPS, 
!                                  allow calls without YGFL initialised. Removal
!                                  of all YGFL references will have to wait.
!      H Petithomme (Dec 2020): general rewrite for optimization
!     ------------------------------------------------------------------

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK

USE YOMCST,              ONLY: TCST
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES

IMPLICIT NONE

TYPE(TCST),                     INTENT(IN)    :: YDCST
INTEGER(KIND=JPIM),             INTENT(IN)    :: KPROMA,KFLEV,KST,KPROF
INTEGER(KIND=JPIM),OPTIONAL,    INTENT(IN)    :: KGFLTYP
TYPE(FIELD_VARIABLES),          INTENT(INOUT) :: YDVARS
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT)   :: PCP(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,TARGET,INTENT(OUT)   :: PR(KPROMA,KFLEV)
REAL(KIND=JPRB),OPTIONAL,       INTENT(OUT)   :: PKAP(KPROMA,KFLEV)

#include "abor1.intfb.h"

REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZR(:,:)
REAL(KIND=JPRB),CONTIGUOUS,POINTER :: ZCP(:,:)
LOGICAL :: LLCP

REAL(KIND=JPRB),TARGET :: ZCP0(KPROMA,KFLEV),ZR0(KPROMA,KFLEV)
INTEGER(KIND=JPIM) :: IGFLTYP, JLON, JLEV, JFLD

REAL(KIND=JPRB) :: ZHOOK

IF (LHOOK) CALL DR_HOOK("GPRCP_EXPL",0,ZHOOK)

IF (PRESENT(PR)) THEN
  ZR => PR(:,:)
ELSEIF (PRESENT(PKAP)) THEN
  ZR => ZR0(:,:)
ENDIF

LLCP = .TRUE.

IF (PRESENT(PCP)) THEN
  ZCP => PCP(:,:)
ELSEIF (PRESENT(PKAP)) THEN
  ZCP => ZCP0(:,:)
ELSE
  ZCP => NULL()
  LLCP = .FALSE.
ENDIF

IF (LLCP) THEN
  ZCP = 0._JPRB
ENDIF

ZR = 0._JPRB

IGFLTYP = 0
IF (PRESENT (KGFLTYP)) IGFLTYP = KGFLTYP 



SELECT CASE (IGFLTYP)
  CASE (0)
  CALL GPRCP_EXPL1 (YDVARS%Q%LTHERMACT, YDVARS%Q%R, YDVARS%Q%RCP, YDVARS%Q%T0)
! IF (YDVARS%Q%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%Q%R - YDCST%RD) * YDVARS%Q%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%Q%RCP - YDCST%RCPD) * YDVARS%Q%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%I%LTHERMACT, YDVARS%I%R, YDVARS%I%RCP, YDVARS%I%T0)
! IF (YDVARS%I%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%I%R - YDCST%RD) * YDVARS%I%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%I%RCP - YDCST%RCPD) * YDVARS%I%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%L%LTHERMACT, YDVARS%L%R, YDVARS%L%RCP, YDVARS%L%T0)
! IF (YDVARS%L%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%L%R - YDCST%RD) * YDVARS%L%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%L%RCP - YDCST%RCPD) * YDVARS%L%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%LCONV%LTHERMACT, YDVARS%LCONV%R, YDVARS%LCONV%RCP, YDVARS%LCONV%T0)
! IF (YDVARS%LCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LCONV%R - YDCST%RD) * YDVARS%LCONV%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LCONV%RCP - YDCST%RCPD) * YDVARS%LCONV%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%ICONV%LTHERMACT, YDVARS%ICONV%R, YDVARS%ICONV%RCP, YDVARS%ICONV%T0)
! IF (YDVARS%ICONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ICONV%R - YDCST%RD) * YDVARS%ICONV%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ICONV%RCP - YDCST%RCPD) * YDVARS%ICONV%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RCONV%LTHERMACT, YDVARS%RCONV%R, YDVARS%RCONV%RCP, YDVARS%RCONV%T0)
! IF (YDVARS%RCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RCONV%R - YDCST%RD) * YDVARS%RCONV%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RCONV%RCP - YDCST%RCPD) * YDVARS%RCONV%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SCONV%LTHERMACT, YDVARS%SCONV%R, YDVARS%SCONV%RCP, YDVARS%SCONV%T0)
! IF (YDVARS%SCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SCONV%R - YDCST%RD) * YDVARS%SCONV%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SCONV%RCP - YDCST%RCPD) * YDVARS%SCONV%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%IRAD%LTHERMACT, YDVARS%IRAD%R, YDVARS%IRAD%RCP, YDVARS%IRAD%T0)
! IF (YDVARS%IRAD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%IRAD%R - YDCST%RD) * YDVARS%IRAD%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%IRAD%RCP - YDCST%RCPD) * YDVARS%IRAD%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%LRAD%LTHERMACT, YDVARS%LRAD%R, YDVARS%LRAD%RCP, YDVARS%LRAD%T0)
! IF (YDVARS%LRAD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRAD%R - YDCST%RD) * YDVARS%LRAD%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRAD%RCP - YDCST%RCPD) * YDVARS%LRAD%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%S%LTHERMACT, YDVARS%S%R, YDVARS%S%RCP, YDVARS%S%T0)
! IF (YDVARS%S%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%S%R - YDCST%RD) * YDVARS%S%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%S%RCP - YDCST%RCPD) * YDVARS%S%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%R%LTHERMACT, YDVARS%R%R, YDVARS%R%RCP, YDVARS%R%T0)
! IF (YDVARS%R%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%R%R - YDCST%RD) * YDVARS%R%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%R%RCP - YDCST%RCPD) * YDVARS%R%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%G%LTHERMACT, YDVARS%G%R, YDVARS%G%RCP, YDVARS%G%T0)
! IF (YDVARS%G%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%G%R - YDCST%RD) * YDVARS%G%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%G%RCP - YDCST%RCPD) * YDVARS%G%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%H%LTHERMACT, YDVARS%H%R, YDVARS%H%RCP, YDVARS%H%T0)
! IF (YDVARS%H%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%H%R - YDCST%RD) * YDVARS%H%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%H%RCP - YDCST%RCPD) * YDVARS%H%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%TKE%LTHERMACT, YDVARS%TKE%R, YDVARS%TKE%RCP, YDVARS%TKE%T0)
! IF (YDVARS%TKE%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TKE%R - YDCST%RD) * YDVARS%TKE%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TKE%RCP - YDCST%RCPD) * YDVARS%TKE%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%TTE%LTHERMACT, YDVARS%TTE%R, YDVARS%TTE%RCP, YDVARS%TTE%T0)
! IF (YDVARS%TTE%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TTE%R - YDCST%RD) * YDVARS%TTE%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TTE%RCP - YDCST%RCPD) * YDVARS%TTE%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB1%LTHERMACT, YDVARS%EFB1%R, YDVARS%EFB1%RCP, YDVARS%EFB1%T0)
! IF (YDVARS%EFB1%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB1%R - YDCST%RD) * YDVARS%EFB1%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB1%RCP - YDCST%RCPD) * YDVARS%EFB1%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB2%LTHERMACT, YDVARS%EFB2%R, YDVARS%EFB2%RCP, YDVARS%EFB2%T0)
! IF (YDVARS%EFB2%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB2%R - YDCST%RD) * YDVARS%EFB2%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB2%RCP - YDCST%RCPD) * YDVARS%EFB2%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB3%LTHERMACT, YDVARS%EFB3%R, YDVARS%EFB3%RCP, YDVARS%EFB3%T0)
! IF (YDVARS%EFB3%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB3%R - YDCST%RD) * YDVARS%EFB3%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB3%RCP - YDCST%RCPD) * YDVARS%EFB3%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%A%LTHERMACT, YDVARS%A%R, YDVARS%A%RCP, YDVARS%A%T0)
! IF (YDVARS%A%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%A%R - YDCST%RD) * YDVARS%A%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%A%RCP - YDCST%RCPD) * YDVARS%A%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%O3%LTHERMACT, YDVARS%O3%R, YDVARS%O3%RCP, YDVARS%O3%T0)
! IF (YDVARS%O3%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%O3%R - YDCST%RD) * YDVARS%O3%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%O3%RCP - YDCST%RCPD) * YDVARS%O3%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SRC%LTHERMACT, YDVARS%SRC%R, YDVARS%SRC%RCP, YDVARS%SRC%T0)
! IF (YDVARS%SRC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SRC%R - YDCST%RD) * YDVARS%SRC%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SRC%RCP - YDCST%RCPD) * YDVARS%SRC%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%MXL%LTHERMACT, YDVARS%MXL%R, YDVARS%MXL%RCP, YDVARS%MXL%T0)
! IF (YDVARS%MXL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%MXL%R - YDCST%RD) * YDVARS%MXL%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%MXL%RCP - YDCST%RCPD) * YDVARS%MXL%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SHTUR%LTHERMACT, YDVARS%SHTUR%R, YDVARS%SHTUR%RCP, YDVARS%SHTUR%T0)
! IF (YDVARS%SHTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SHTUR%R - YDCST%RD) * YDVARS%SHTUR%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SHTUR%RCP - YDCST%RCPD) * YDVARS%SHTUR%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%FQTUR%LTHERMACT, YDVARS%FQTUR%R, YDVARS%FQTUR%RCP, YDVARS%FQTUR%T0)
! IF (YDVARS%FQTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FQTUR%R - YDCST%RD) * YDVARS%FQTUR%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FQTUR%RCP - YDCST%RCPD) * YDVARS%FQTUR%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%FSTUR%LTHERMACT, YDVARS%FSTUR%R, YDVARS%FSTUR%RCP, YDVARS%FSTUR%T0)
! IF (YDVARS%FSTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSTUR%R - YDCST%RD) * YDVARS%FSTUR%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSTUR%RCP - YDCST%RCPD) * YDVARS%FSTUR%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CPF%LTHERMACT, YDVARS%CPF%R, YDVARS%CPF%RCP, YDVARS%CPF%T0)
! IF (YDVARS%CPF%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CPF%R - YDCST%RD) * YDVARS%CPF%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CPF%RCP - YDCST%RCPD) * YDVARS%CPF%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SPF%LTHERMACT, YDVARS%SPF%R, YDVARS%SPF%RCP, YDVARS%SPF%T0)
! IF (YDVARS%SPF%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SPF%R - YDCST%RD) * YDVARS%SPF%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SPF%RCP - YDCST%RCPD) * YDVARS%SPF%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CVGQ%LTHERMACT, YDVARS%CVGQ%R, YDVARS%CVGQ%RCP, YDVARS%CVGQ%T0)
! IF (YDVARS%CVGQ%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVGQ%R - YDCST%RD) * YDVARS%CVGQ%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVGQ%RCP - YDCST%RCPD) * YDVARS%CVGQ%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%QVA%LTHERMACT, YDVARS%QVA%R, YDVARS%QVA%RCP, YDVARS%QVA%T0)
! IF (YDVARS%QVA%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%QVA%R - YDCST%RD) * YDVARS%QVA%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%QVA%RCP - YDCST%RCPD) * YDVARS%QVA%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%GHG)
    IF (YDVARS%GHG(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%GHG(JFLD)%R - YDCST%RD) * YDVARS%GHG(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%GHG(JFLD)%RCP - YDCST%RCPD) * YDVARS%GHG(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%CHEM)
    IF (YDVARS%CHEM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CHEM(JFLD)%R - YDCST%RD) * YDVARS%CHEM(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CHEM(JFLD)%RCP - YDCST%RCPD) * YDVARS%CHEM(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERO)
    IF (YDVARS%AERO(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERO(JFLD)%R - YDCST%RD) * YDVARS%AERO(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERO(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERO(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%LRCH4%LTHERMACT, YDVARS%LRCH4%R, YDVARS%LRCH4%RCP, YDVARS%LRCH4%T0)
! IF (YDVARS%LRCH4%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRCH4%R - YDCST%RD) * YDVARS%LRCH4%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRCH4%RCP - YDCST%RCPD) * YDVARS%LRCH4%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%FORC)
    IF (YDVARS%FORC(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FORC(JFLD)%R - YDCST%RD) * YDVARS%FORC(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FORC(JFLD)%RCP - YDCST%RCPD) * YDVARS%FORC(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EZDIAG)
    IF (YDVARS%EZDIAG(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EZDIAG(JFLD)%R - YDCST%RD) * YDVARS%EZDIAG(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EZDIAG(JFLD)%RCP - YDCST%RCPD) * YDVARS%EZDIAG(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%ERA40)
    IF (YDVARS%ERA40(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ERA40(JFLD)%R - YDCST%RD) * YDVARS%ERA40(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ERA40(JFLD)%RCP - YDCST%RCPD) * YDVARS%ERA40(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%NOGW)
    IF (YDVARS%NOGW(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%NOGW(JFLD)%R - YDCST%RD) * YDVARS%NOGW(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%NOGW(JFLD)%RCP - YDCST%RCPD) * YDVARS%NOGW(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EDRP)
    IF (YDVARS%EDRP(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EDRP(JFLD)%R - YDCST%RD) * YDVARS%EDRP(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EDRP(JFLD)%RCP - YDCST%RCPD) * YDVARS%EDRP(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%SLDIA)
    IF (YDVARS%SLDIA(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SLDIA(JFLD)%R - YDCST%RD) * YDVARS%SLDIA(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SLDIA(JFLD)%RCP - YDCST%RCPD) * YDVARS%SLDIA(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERAOT)
    IF (YDVARS%AERAOT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERAOT(JFLD)%R - YDCST%RD) * YDVARS%AERAOT(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERAOT(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERAOT(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERLISI)
    IF (YDVARS%AERLISI(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERLISI(JFLD)%R - YDCST%RD) * YDVARS%AERLISI(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERLISI(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERLISI(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROUT)
    IF (YDVARS%AEROUT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AEROUT(JFLD)%R - YDCST%RD) * YDVARS%AEROUT(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AEROUT(JFLD)%RCP - YDCST%RCPD) * YDVARS%AEROUT(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
    IF (YDVARS%AEROCLIM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AEROCLIM(JFLD)%R - YDCST%RD) * YDVARS%AEROCLIM(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AEROCLIM(JFLD)%RCP - YDCST%RCPD) * YDVARS%AEROCLIM(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%UVP)
    IF (YDVARS%UVP(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UVP(JFLD)%R - YDCST%RD) * YDVARS%UVP(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UVP(JFLD)%RCP - YDCST%RCPD) * YDVARS%UVP(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%PHYS)
    IF (YDVARS%PHYS(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYS(JFLD)%R - YDCST%RD) * YDVARS%PHYS(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYS(JFLD)%RCP - YDCST%RCPD) * YDVARS%PHYS(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%PHYCTY%LTHERMACT, YDVARS%PHYCTY%R, YDVARS%PHYCTY%RCP, YDVARS%PHYCTY%T0)
! IF (YDVARS%PHYCTY%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYCTY%R - YDCST%RD) * YDVARS%PHYCTY%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYCTY%RCP - YDCST%RCPD) * YDVARS%PHYCTY%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RSPEC%LTHERMACT, YDVARS%RSPEC%R, YDVARS%RSPEC%RCP, YDVARS%RSPEC%T0)
! IF (YDVARS%RSPEC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RSPEC%R - YDCST%RD) * YDVARS%RSPEC%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RSPEC%RCP - YDCST%RCPD) * YDVARS%RSPEC%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SDSAT%LTHERMACT, YDVARS%SDSAT%R, YDVARS%SDSAT%RCP, YDVARS%SDSAT%T0)
! IF (YDVARS%SDSAT%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SDSAT%R - YDCST%RD) * YDVARS%SDSAT%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SDSAT%RCP - YDCST%RCPD) * YDVARS%SDSAT%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CVV%LTHERMACT, YDVARS%CVV%R, YDVARS%CVV%RCP, YDVARS%CVV%T0)
! IF (YDVARS%CVV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVV%R - YDCST%RD) * YDVARS%CVV%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVV%RCP - YDCST%RCPD) * YDVARS%CVV%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTH%LTHERMACT, YDVARS%RKTH%R, YDVARS%RKTH%RCP, YDVARS%RKTH%T0)
! IF (YDVARS%RKTH%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTH%R - YDCST%RD) * YDVARS%RKTH%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTH%RCP - YDCST%RCPD) * YDVARS%RKTH%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTQV%LTHERMACT, YDVARS%RKTQV%R, YDVARS%RKTQV%RCP, YDVARS%RKTQV%T0)
! IF (YDVARS%RKTQV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQV%R - YDCST%RD) * YDVARS%RKTQV%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQV%RCP - YDCST%RCPD) * YDVARS%RKTQV%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTQC%LTHERMACT, YDVARS%RKTQC%R, YDVARS%RKTQC%RCP, YDVARS%RKTQC%T0)
! IF (YDVARS%RKTQC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQC%R - YDCST%RD) * YDVARS%RKTQC%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQC%RCP - YDCST%RCPD) * YDVARS%RKTQC%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UOM%LTHERMACT, YDVARS%UOM%R, YDVARS%UOM%RCP, YDVARS%UOM%T0)
! IF (YDVARS%UOM%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UOM%R - YDCST%RD) * YDVARS%UOM%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UOM%RCP - YDCST%RCPD) * YDVARS%UOM%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UAL%LTHERMACT, YDVARS%UAL%R, YDVARS%UAL%RCP, YDVARS%UAL%T0)
! IF (YDVARS%UAL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UAL%R - YDCST%RD) * YDVARS%UAL%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UAL%RCP - YDCST%RCPD) * YDVARS%UAL%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%DOM%LTHERMACT, YDVARS%DOM%R, YDVARS%DOM%RCP, YDVARS%DOM%T0)
! IF (YDVARS%DOM%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DOM%R - YDCST%RD) * YDVARS%DOM%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DOM%RCP - YDCST%RCPD) * YDVARS%DOM%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%DAL%LTHERMACT, YDVARS%DAL%R, YDVARS%DAL%RCP, YDVARS%DAL%T0)
! IF (YDVARS%DAL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DAL%R - YDCST%RD) * YDVARS%DAL%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DAL%RCP - YDCST%RCPD) * YDVARS%DAL%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UEN%LTHERMACT, YDVARS%UEN%R, YDVARS%UEN%RCP, YDVARS%UEN%T0)
! IF (YDVARS%UEN%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UEN%R - YDCST%RD) * YDVARS%UEN%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UEN%RCP - YDCST%RCPD) * YDVARS%UEN%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UNEBH%LTHERMACT, YDVARS%UNEBH%R, YDVARS%UNEBH%RCP, YDVARS%UNEBH%T0)
! IF (YDVARS%UNEBH%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UNEBH%R - YDCST%RD) * YDVARS%UNEBH%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UNEBH%RCP - YDCST%RCPD) * YDVARS%UNEBH%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%CRM)
    IF (YDVARS%CRM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CRM(JFLD)%R - YDCST%RD) * YDVARS%CRM(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CRM(JFLD)%RCP - YDCST%RCPD) * YDVARS%CRM(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%LIMA)
    IF (YDVARS%LIMA(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LIMA(JFLD)%R - YDCST%RD) * YDVARS%LIMA(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LIMA(JFLD)%RCP - YDCST%RCPD) * YDVARS%LIMA(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%FSD%LTHERMACT, YDVARS%FSD%R, YDVARS%FSD%RCP, YDVARS%FSD%T0)
! IF (YDVARS%FSD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSD%R - YDCST%RD) * YDVARS%FSD%T0 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSD%RCP - YDCST%RCPD) * YDVARS%FSD%T0 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%EXT)
    IF (YDVARS%EXT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EXT(JFLD)%R - YDCST%RD) * YDVARS%EXT(JFLD)%T0 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EXT(JFLD)%RCP - YDCST%RCPD) * YDVARS%EXT(JFLD)%T0 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CASE (1)
  CALL GPRCP_EXPL1 (YDVARS%Q%LTHERMACT, YDVARS%Q%R, YDVARS%Q%RCP, YDVARS%Q%T1)
! IF (YDVARS%Q%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%Q%R - YDCST%RD) * YDVARS%Q%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%Q%RCP - YDCST%RCPD) * YDVARS%Q%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%I%LTHERMACT, YDVARS%I%R, YDVARS%I%RCP, YDVARS%I%T1)
! IF (YDVARS%I%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%I%R - YDCST%RD) * YDVARS%I%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%I%RCP - YDCST%RCPD) * YDVARS%I%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%L%LTHERMACT, YDVARS%L%R, YDVARS%L%RCP, YDVARS%L%T1)
! IF (YDVARS%L%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%L%R - YDCST%RD) * YDVARS%L%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%L%RCP - YDCST%RCPD) * YDVARS%L%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%LCONV%LTHERMACT, YDVARS%LCONV%R, YDVARS%LCONV%RCP, YDVARS%LCONV%T1)
! IF (YDVARS%LCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LCONV%R - YDCST%RD) * YDVARS%LCONV%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LCONV%RCP - YDCST%RCPD) * YDVARS%LCONV%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%ICONV%LTHERMACT, YDVARS%ICONV%R, YDVARS%ICONV%RCP, YDVARS%ICONV%T1)
! IF (YDVARS%ICONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ICONV%R - YDCST%RD) * YDVARS%ICONV%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ICONV%RCP - YDCST%RCPD) * YDVARS%ICONV%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RCONV%LTHERMACT, YDVARS%RCONV%R, YDVARS%RCONV%RCP, YDVARS%RCONV%T1)
! IF (YDVARS%RCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RCONV%R - YDCST%RD) * YDVARS%RCONV%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RCONV%RCP - YDCST%RCPD) * YDVARS%RCONV%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SCONV%LTHERMACT, YDVARS%SCONV%R, YDVARS%SCONV%RCP, YDVARS%SCONV%T1)
! IF (YDVARS%SCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SCONV%R - YDCST%RD) * YDVARS%SCONV%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SCONV%RCP - YDCST%RCPD) * YDVARS%SCONV%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%IRAD%LTHERMACT, YDVARS%IRAD%R, YDVARS%IRAD%RCP, YDVARS%IRAD%T1)
! IF (YDVARS%IRAD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%IRAD%R - YDCST%RD) * YDVARS%IRAD%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%IRAD%RCP - YDCST%RCPD) * YDVARS%IRAD%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%LRAD%LTHERMACT, YDVARS%LRAD%R, YDVARS%LRAD%RCP, YDVARS%LRAD%T1)
! IF (YDVARS%LRAD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRAD%R - YDCST%RD) * YDVARS%LRAD%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRAD%RCP - YDCST%RCPD) * YDVARS%LRAD%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%S%LTHERMACT, YDVARS%S%R, YDVARS%S%RCP, YDVARS%S%T1)
! IF (YDVARS%S%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%S%R - YDCST%RD) * YDVARS%S%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%S%RCP - YDCST%RCPD) * YDVARS%S%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%R%LTHERMACT, YDVARS%R%R, YDVARS%R%RCP, YDVARS%R%T1)
! IF (YDVARS%R%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%R%R - YDCST%RD) * YDVARS%R%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%R%RCP - YDCST%RCPD) * YDVARS%R%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%G%LTHERMACT, YDVARS%G%R, YDVARS%G%RCP, YDVARS%G%T1)
! IF (YDVARS%G%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%G%R - YDCST%RD) * YDVARS%G%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%G%RCP - YDCST%RCPD) * YDVARS%G%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%H%LTHERMACT, YDVARS%H%R, YDVARS%H%RCP, YDVARS%H%T1)
! IF (YDVARS%H%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%H%R - YDCST%RD) * YDVARS%H%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%H%RCP - YDCST%RCPD) * YDVARS%H%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%TKE%LTHERMACT, YDVARS%TKE%R, YDVARS%TKE%RCP, YDVARS%TKE%T1)
! IF (YDVARS%TKE%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TKE%R - YDCST%RD) * YDVARS%TKE%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TKE%RCP - YDCST%RCPD) * YDVARS%TKE%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%TTE%LTHERMACT, YDVARS%TTE%R, YDVARS%TTE%RCP, YDVARS%TTE%T1)
! IF (YDVARS%TTE%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TTE%R - YDCST%RD) * YDVARS%TTE%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TTE%RCP - YDCST%RCPD) * YDVARS%TTE%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB1%LTHERMACT, YDVARS%EFB1%R, YDVARS%EFB1%RCP, YDVARS%EFB1%T1)
! IF (YDVARS%EFB1%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB1%R - YDCST%RD) * YDVARS%EFB1%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB1%RCP - YDCST%RCPD) * YDVARS%EFB1%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB2%LTHERMACT, YDVARS%EFB2%R, YDVARS%EFB2%RCP, YDVARS%EFB2%T1)
! IF (YDVARS%EFB2%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB2%R - YDCST%RD) * YDVARS%EFB2%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB2%RCP - YDCST%RCPD) * YDVARS%EFB2%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB3%LTHERMACT, YDVARS%EFB3%R, YDVARS%EFB3%RCP, YDVARS%EFB3%T1)
! IF (YDVARS%EFB3%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB3%R - YDCST%RD) * YDVARS%EFB3%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB3%RCP - YDCST%RCPD) * YDVARS%EFB3%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%A%LTHERMACT, YDVARS%A%R, YDVARS%A%RCP, YDVARS%A%T1)
! IF (YDVARS%A%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%A%R - YDCST%RD) * YDVARS%A%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%A%RCP - YDCST%RCPD) * YDVARS%A%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%O3%LTHERMACT, YDVARS%O3%R, YDVARS%O3%RCP, YDVARS%O3%T1)
! IF (YDVARS%O3%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%O3%R - YDCST%RD) * YDVARS%O3%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%O3%RCP - YDCST%RCPD) * YDVARS%O3%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SRC%LTHERMACT, YDVARS%SRC%R, YDVARS%SRC%RCP, YDVARS%SRC%T1)
! IF (YDVARS%SRC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SRC%R - YDCST%RD) * YDVARS%SRC%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SRC%RCP - YDCST%RCPD) * YDVARS%SRC%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%MXL%LTHERMACT, YDVARS%MXL%R, YDVARS%MXL%RCP, YDVARS%MXL%T1)
! IF (YDVARS%MXL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%MXL%R - YDCST%RD) * YDVARS%MXL%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%MXL%RCP - YDCST%RCPD) * YDVARS%MXL%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SHTUR%LTHERMACT, YDVARS%SHTUR%R, YDVARS%SHTUR%RCP, YDVARS%SHTUR%T1)
! IF (YDVARS%SHTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SHTUR%R - YDCST%RD) * YDVARS%SHTUR%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SHTUR%RCP - YDCST%RCPD) * YDVARS%SHTUR%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%FQTUR%LTHERMACT, YDVARS%FQTUR%R, YDVARS%FQTUR%RCP, YDVARS%FQTUR%T1)
! IF (YDVARS%FQTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FQTUR%R - YDCST%RD) * YDVARS%FQTUR%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FQTUR%RCP - YDCST%RCPD) * YDVARS%FQTUR%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%FSTUR%LTHERMACT, YDVARS%FSTUR%R, YDVARS%FSTUR%RCP, YDVARS%FSTUR%T1)
! IF (YDVARS%FSTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSTUR%R - YDCST%RD) * YDVARS%FSTUR%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSTUR%RCP - YDCST%RCPD) * YDVARS%FSTUR%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CPF%LTHERMACT, YDVARS%CPF%R, YDVARS%CPF%RCP, YDVARS%CPF%T1)
! IF (YDVARS%CPF%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CPF%R - YDCST%RD) * YDVARS%CPF%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CPF%RCP - YDCST%RCPD) * YDVARS%CPF%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SPF%LTHERMACT, YDVARS%SPF%R, YDVARS%SPF%RCP, YDVARS%SPF%T1)
! IF (YDVARS%SPF%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SPF%R - YDCST%RD) * YDVARS%SPF%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SPF%RCP - YDCST%RCPD) * YDVARS%SPF%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CVGQ%LTHERMACT, YDVARS%CVGQ%R, YDVARS%CVGQ%RCP, YDVARS%CVGQ%T1)
! IF (YDVARS%CVGQ%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVGQ%R - YDCST%RD) * YDVARS%CVGQ%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVGQ%RCP - YDCST%RCPD) * YDVARS%CVGQ%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%QVA%LTHERMACT, YDVARS%QVA%R, YDVARS%QVA%RCP, YDVARS%QVA%T1)
! IF (YDVARS%QVA%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%QVA%R - YDCST%RD) * YDVARS%QVA%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%QVA%RCP - YDCST%RCPD) * YDVARS%QVA%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%GHG)
    IF (YDVARS%GHG(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%GHG(JFLD)%R - YDCST%RD) * YDVARS%GHG(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%GHG(JFLD)%RCP - YDCST%RCPD) * YDVARS%GHG(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%CHEM)
    IF (YDVARS%CHEM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CHEM(JFLD)%R - YDCST%RD) * YDVARS%CHEM(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CHEM(JFLD)%RCP - YDCST%RCPD) * YDVARS%CHEM(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERO)
    IF (YDVARS%AERO(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERO(JFLD)%R - YDCST%RD) * YDVARS%AERO(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERO(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERO(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%LRCH4%LTHERMACT, YDVARS%LRCH4%R, YDVARS%LRCH4%RCP, YDVARS%LRCH4%T1)
! IF (YDVARS%LRCH4%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRCH4%R - YDCST%RD) * YDVARS%LRCH4%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRCH4%RCP - YDCST%RCPD) * YDVARS%LRCH4%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%FORC)
    IF (YDVARS%FORC(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FORC(JFLD)%R - YDCST%RD) * YDVARS%FORC(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FORC(JFLD)%RCP - YDCST%RCPD) * YDVARS%FORC(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EZDIAG)
    IF (YDVARS%EZDIAG(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EZDIAG(JFLD)%R - YDCST%RD) * YDVARS%EZDIAG(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EZDIAG(JFLD)%RCP - YDCST%RCPD) * YDVARS%EZDIAG(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%ERA40)
    IF (YDVARS%ERA40(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ERA40(JFLD)%R - YDCST%RD) * YDVARS%ERA40(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ERA40(JFLD)%RCP - YDCST%RCPD) * YDVARS%ERA40(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%NOGW)
    IF (YDVARS%NOGW(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%NOGW(JFLD)%R - YDCST%RD) * YDVARS%NOGW(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%NOGW(JFLD)%RCP - YDCST%RCPD) * YDVARS%NOGW(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EDRP)
    IF (YDVARS%EDRP(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EDRP(JFLD)%R - YDCST%RD) * YDVARS%EDRP(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EDRP(JFLD)%RCP - YDCST%RCPD) * YDVARS%EDRP(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%SLDIA)
    IF (YDVARS%SLDIA(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SLDIA(JFLD)%R - YDCST%RD) * YDVARS%SLDIA(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SLDIA(JFLD)%RCP - YDCST%RCPD) * YDVARS%SLDIA(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERAOT)
    IF (YDVARS%AERAOT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERAOT(JFLD)%R - YDCST%RD) * YDVARS%AERAOT(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERAOT(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERAOT(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERLISI)
    IF (YDVARS%AERLISI(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERLISI(JFLD)%R - YDCST%RD) * YDVARS%AERLISI(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERLISI(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERLISI(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROUT)
    IF (YDVARS%AEROUT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AEROUT(JFLD)%R - YDCST%RD) * YDVARS%AEROUT(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AEROUT(JFLD)%RCP - YDCST%RCPD) * YDVARS%AEROUT(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
    IF (YDVARS%AEROCLIM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AEROCLIM(JFLD)%R - YDCST%RD) * YDVARS%AEROCLIM(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AEROCLIM(JFLD)%RCP - YDCST%RCPD) * YDVARS%AEROCLIM(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%UVP)
    IF (YDVARS%UVP(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UVP(JFLD)%R - YDCST%RD) * YDVARS%UVP(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UVP(JFLD)%RCP - YDCST%RCPD) * YDVARS%UVP(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%PHYS)
    IF (YDVARS%PHYS(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYS(JFLD)%R - YDCST%RD) * YDVARS%PHYS(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYS(JFLD)%RCP - YDCST%RCPD) * YDVARS%PHYS(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%PHYCTY%LTHERMACT, YDVARS%PHYCTY%R, YDVARS%PHYCTY%RCP, YDVARS%PHYCTY%T1)
! IF (YDVARS%PHYCTY%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYCTY%R - YDCST%RD) * YDVARS%PHYCTY%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYCTY%RCP - YDCST%RCPD) * YDVARS%PHYCTY%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RSPEC%LTHERMACT, YDVARS%RSPEC%R, YDVARS%RSPEC%RCP, YDVARS%RSPEC%T1)
! IF (YDVARS%RSPEC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RSPEC%R - YDCST%RD) * YDVARS%RSPEC%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RSPEC%RCP - YDCST%RCPD) * YDVARS%RSPEC%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SDSAT%LTHERMACT, YDVARS%SDSAT%R, YDVARS%SDSAT%RCP, YDVARS%SDSAT%T1)
! IF (YDVARS%SDSAT%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SDSAT%R - YDCST%RD) * YDVARS%SDSAT%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SDSAT%RCP - YDCST%RCPD) * YDVARS%SDSAT%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CVV%LTHERMACT, YDVARS%CVV%R, YDVARS%CVV%RCP, YDVARS%CVV%T1)
! IF (YDVARS%CVV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVV%R - YDCST%RD) * YDVARS%CVV%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVV%RCP - YDCST%RCPD) * YDVARS%CVV%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTH%LTHERMACT, YDVARS%RKTH%R, YDVARS%RKTH%RCP, YDVARS%RKTH%T1)
! IF (YDVARS%RKTH%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTH%R - YDCST%RD) * YDVARS%RKTH%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTH%RCP - YDCST%RCPD) * YDVARS%RKTH%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTQV%LTHERMACT, YDVARS%RKTQV%R, YDVARS%RKTQV%RCP, YDVARS%RKTQV%T1)
! IF (YDVARS%RKTQV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQV%R - YDCST%RD) * YDVARS%RKTQV%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQV%RCP - YDCST%RCPD) * YDVARS%RKTQV%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTQC%LTHERMACT, YDVARS%RKTQC%R, YDVARS%RKTQC%RCP, YDVARS%RKTQC%T1)
! IF (YDVARS%RKTQC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQC%R - YDCST%RD) * YDVARS%RKTQC%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQC%RCP - YDCST%RCPD) * YDVARS%RKTQC%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UOM%LTHERMACT, YDVARS%UOM%R, YDVARS%UOM%RCP, YDVARS%UOM%T1)
! IF (YDVARS%UOM%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UOM%R - YDCST%RD) * YDVARS%UOM%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UOM%RCP - YDCST%RCPD) * YDVARS%UOM%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UAL%LTHERMACT, YDVARS%UAL%R, YDVARS%UAL%RCP, YDVARS%UAL%T1)
! IF (YDVARS%UAL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UAL%R - YDCST%RD) * YDVARS%UAL%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UAL%RCP - YDCST%RCPD) * YDVARS%UAL%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%DOM%LTHERMACT, YDVARS%DOM%R, YDVARS%DOM%RCP, YDVARS%DOM%T1)
! IF (YDVARS%DOM%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DOM%R - YDCST%RD) * YDVARS%DOM%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DOM%RCP - YDCST%RCPD) * YDVARS%DOM%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%DAL%LTHERMACT, YDVARS%DAL%R, YDVARS%DAL%RCP, YDVARS%DAL%T1)
! IF (YDVARS%DAL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DAL%R - YDCST%RD) * YDVARS%DAL%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DAL%RCP - YDCST%RCPD) * YDVARS%DAL%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UEN%LTHERMACT, YDVARS%UEN%R, YDVARS%UEN%RCP, YDVARS%UEN%T1)
! IF (YDVARS%UEN%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UEN%R - YDCST%RD) * YDVARS%UEN%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UEN%RCP - YDCST%RCPD) * YDVARS%UEN%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UNEBH%LTHERMACT, YDVARS%UNEBH%R, YDVARS%UNEBH%RCP, YDVARS%UNEBH%T1)
! IF (YDVARS%UNEBH%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UNEBH%R - YDCST%RD) * YDVARS%UNEBH%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UNEBH%RCP - YDCST%RCPD) * YDVARS%UNEBH%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%CRM)
    IF (YDVARS%CRM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CRM(JFLD)%R - YDCST%RD) * YDVARS%CRM(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CRM(JFLD)%RCP - YDCST%RCPD) * YDVARS%CRM(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%LIMA)
    IF (YDVARS%LIMA(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LIMA(JFLD)%R - YDCST%RD) * YDVARS%LIMA(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LIMA(JFLD)%RCP - YDCST%RCPD) * YDVARS%LIMA(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%FSD%LTHERMACT, YDVARS%FSD%R, YDVARS%FSD%RCP, YDVARS%FSD%T1)
! IF (YDVARS%FSD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSD%R - YDCST%RD) * YDVARS%FSD%T1 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSD%RCP - YDCST%RCPD) * YDVARS%FSD%T1 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%EXT)
    IF (YDVARS%EXT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EXT(JFLD)%R - YDCST%RD) * YDVARS%EXT(JFLD)%T1 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EXT(JFLD)%RCP - YDCST%RCPD) * YDVARS%EXT(JFLD)%T1 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CASE (9)
  CALL GPRCP_EXPL1 (YDVARS%Q%LTHERMACT, YDVARS%Q%R, YDVARS%Q%RCP, YDVARS%Q%T9)
! IF (YDVARS%Q%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%Q%R - YDCST%RD) * YDVARS%Q%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%Q%RCP - YDCST%RCPD) * YDVARS%Q%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%I%LTHERMACT, YDVARS%I%R, YDVARS%I%RCP, YDVARS%I%T9)
! IF (YDVARS%I%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%I%R - YDCST%RD) * YDVARS%I%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%I%RCP - YDCST%RCPD) * YDVARS%I%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%L%LTHERMACT, YDVARS%L%R, YDVARS%L%RCP, YDVARS%L%T9)
! IF (YDVARS%L%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%L%R - YDCST%RD) * YDVARS%L%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%L%RCP - YDCST%RCPD) * YDVARS%L%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%LCONV%LTHERMACT, YDVARS%LCONV%R, YDVARS%LCONV%RCP, YDVARS%LCONV%T9)
! IF (YDVARS%LCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LCONV%R - YDCST%RD) * YDVARS%LCONV%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LCONV%RCP - YDCST%RCPD) * YDVARS%LCONV%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%ICONV%LTHERMACT, YDVARS%ICONV%R, YDVARS%ICONV%RCP, YDVARS%ICONV%T9)
! IF (YDVARS%ICONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ICONV%R - YDCST%RD) * YDVARS%ICONV%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ICONV%RCP - YDCST%RCPD) * YDVARS%ICONV%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RCONV%LTHERMACT, YDVARS%RCONV%R, YDVARS%RCONV%RCP, YDVARS%RCONV%T9)
! IF (YDVARS%RCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RCONV%R - YDCST%RD) * YDVARS%RCONV%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RCONV%RCP - YDCST%RCPD) * YDVARS%RCONV%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SCONV%LTHERMACT, YDVARS%SCONV%R, YDVARS%SCONV%RCP, YDVARS%SCONV%T9)
! IF (YDVARS%SCONV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SCONV%R - YDCST%RD) * YDVARS%SCONV%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SCONV%RCP - YDCST%RCPD) * YDVARS%SCONV%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%IRAD%LTHERMACT, YDVARS%IRAD%R, YDVARS%IRAD%RCP, YDVARS%IRAD%T9)
! IF (YDVARS%IRAD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%IRAD%R - YDCST%RD) * YDVARS%IRAD%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%IRAD%RCP - YDCST%RCPD) * YDVARS%IRAD%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%LRAD%LTHERMACT, YDVARS%LRAD%R, YDVARS%LRAD%RCP, YDVARS%LRAD%T9)
! IF (YDVARS%LRAD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRAD%R - YDCST%RD) * YDVARS%LRAD%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRAD%RCP - YDCST%RCPD) * YDVARS%LRAD%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%S%LTHERMACT, YDVARS%S%R, YDVARS%S%RCP, YDVARS%S%T9)
! IF (YDVARS%S%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%S%R - YDCST%RD) * YDVARS%S%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%S%RCP - YDCST%RCPD) * YDVARS%S%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%R%LTHERMACT, YDVARS%R%R, YDVARS%R%RCP, YDVARS%R%T9)
! IF (YDVARS%R%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%R%R - YDCST%RD) * YDVARS%R%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%R%RCP - YDCST%RCPD) * YDVARS%R%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%G%LTHERMACT, YDVARS%G%R, YDVARS%G%RCP, YDVARS%G%T9)
! IF (YDVARS%G%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%G%R - YDCST%RD) * YDVARS%G%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%G%RCP - YDCST%RCPD) * YDVARS%G%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%H%LTHERMACT, YDVARS%H%R, YDVARS%H%RCP, YDVARS%H%T9)
! IF (YDVARS%H%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%H%R - YDCST%RD) * YDVARS%H%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%H%RCP - YDCST%RCPD) * YDVARS%H%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%TKE%LTHERMACT, YDVARS%TKE%R, YDVARS%TKE%RCP, YDVARS%TKE%T9)
! IF (YDVARS%TKE%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TKE%R - YDCST%RD) * YDVARS%TKE%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TKE%RCP - YDCST%RCPD) * YDVARS%TKE%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%TTE%LTHERMACT, YDVARS%TTE%R, YDVARS%TTE%RCP, YDVARS%TTE%T9)
! IF (YDVARS%TTE%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%TTE%R - YDCST%RD) * YDVARS%TTE%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%TTE%RCP - YDCST%RCPD) * YDVARS%TTE%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB1%LTHERMACT, YDVARS%EFB1%R, YDVARS%EFB1%RCP, YDVARS%EFB1%T9)
! IF (YDVARS%EFB1%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB1%R - YDCST%RD) * YDVARS%EFB1%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB1%RCP - YDCST%RCPD) * YDVARS%EFB1%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB2%LTHERMACT, YDVARS%EFB2%R, YDVARS%EFB2%RCP, YDVARS%EFB2%T9)
! IF (YDVARS%EFB2%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB2%R - YDCST%RD) * YDVARS%EFB2%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB2%RCP - YDCST%RCPD) * YDVARS%EFB2%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%EFB3%LTHERMACT, YDVARS%EFB3%R, YDVARS%EFB3%RCP, YDVARS%EFB3%T9)
! IF (YDVARS%EFB3%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EFB3%R - YDCST%RD) * YDVARS%EFB3%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EFB3%RCP - YDCST%RCPD) * YDVARS%EFB3%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%A%LTHERMACT, YDVARS%A%R, YDVARS%A%RCP, YDVARS%A%T9)
! IF (YDVARS%A%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%A%R - YDCST%RD) * YDVARS%A%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%A%RCP - YDCST%RCPD) * YDVARS%A%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%O3%LTHERMACT, YDVARS%O3%R, YDVARS%O3%RCP, YDVARS%O3%T9)
! IF (YDVARS%O3%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%O3%R - YDCST%RD) * YDVARS%O3%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%O3%RCP - YDCST%RCPD) * YDVARS%O3%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SRC%LTHERMACT, YDVARS%SRC%R, YDVARS%SRC%RCP, YDVARS%SRC%T9)
! IF (YDVARS%SRC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SRC%R - YDCST%RD) * YDVARS%SRC%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SRC%RCP - YDCST%RCPD) * YDVARS%SRC%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%MXL%LTHERMACT, YDVARS%MXL%R, YDVARS%MXL%RCP, YDVARS%MXL%T9)
! IF (YDVARS%MXL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%MXL%R - YDCST%RD) * YDVARS%MXL%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%MXL%RCP - YDCST%RCPD) * YDVARS%MXL%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SHTUR%LTHERMACT, YDVARS%SHTUR%R, YDVARS%SHTUR%RCP, YDVARS%SHTUR%T9)
! IF (YDVARS%SHTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SHTUR%R - YDCST%RD) * YDVARS%SHTUR%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SHTUR%RCP - YDCST%RCPD) * YDVARS%SHTUR%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%FQTUR%LTHERMACT, YDVARS%FQTUR%R, YDVARS%FQTUR%RCP, YDVARS%FQTUR%T9)
! IF (YDVARS%FQTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FQTUR%R - YDCST%RD) * YDVARS%FQTUR%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FQTUR%RCP - YDCST%RCPD) * YDVARS%FQTUR%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%FSTUR%LTHERMACT, YDVARS%FSTUR%R, YDVARS%FSTUR%RCP, YDVARS%FSTUR%T9)
! IF (YDVARS%FSTUR%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSTUR%R - YDCST%RD) * YDVARS%FSTUR%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSTUR%RCP - YDCST%RCPD) * YDVARS%FSTUR%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CPF%LTHERMACT, YDVARS%CPF%R, YDVARS%CPF%RCP, YDVARS%CPF%T9)
! IF (YDVARS%CPF%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CPF%R - YDCST%RD) * YDVARS%CPF%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CPF%RCP - YDCST%RCPD) * YDVARS%CPF%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SPF%LTHERMACT, YDVARS%SPF%R, YDVARS%SPF%RCP, YDVARS%SPF%T9)
! IF (YDVARS%SPF%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SPF%R - YDCST%RD) * YDVARS%SPF%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SPF%RCP - YDCST%RCPD) * YDVARS%SPF%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CVGQ%LTHERMACT, YDVARS%CVGQ%R, YDVARS%CVGQ%RCP, YDVARS%CVGQ%T9)
! IF (YDVARS%CVGQ%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVGQ%R - YDCST%RD) * YDVARS%CVGQ%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVGQ%RCP - YDCST%RCPD) * YDVARS%CVGQ%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%QVA%LTHERMACT, YDVARS%QVA%R, YDVARS%QVA%RCP, YDVARS%QVA%T9)
! IF (YDVARS%QVA%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%QVA%R - YDCST%RD) * YDVARS%QVA%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%QVA%RCP - YDCST%RCPD) * YDVARS%QVA%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%GHG)
    IF (YDVARS%GHG(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%GHG(JFLD)%R - YDCST%RD) * YDVARS%GHG(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%GHG(JFLD)%RCP - YDCST%RCPD) * YDVARS%GHG(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%CHEM)
    IF (YDVARS%CHEM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CHEM(JFLD)%R - YDCST%RD) * YDVARS%CHEM(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CHEM(JFLD)%RCP - YDCST%RCPD) * YDVARS%CHEM(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERO)
    IF (YDVARS%AERO(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERO(JFLD)%R - YDCST%RD) * YDVARS%AERO(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERO(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERO(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%LRCH4%LTHERMACT, YDVARS%LRCH4%R, YDVARS%LRCH4%RCP, YDVARS%LRCH4%T9)
! IF (YDVARS%LRCH4%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LRCH4%R - YDCST%RD) * YDVARS%LRCH4%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LRCH4%RCP - YDCST%RCPD) * YDVARS%LRCH4%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%FORC)
    IF (YDVARS%FORC(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FORC(JFLD)%R - YDCST%RD) * YDVARS%FORC(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FORC(JFLD)%RCP - YDCST%RCPD) * YDVARS%FORC(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EZDIAG)
    IF (YDVARS%EZDIAG(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EZDIAG(JFLD)%R - YDCST%RD) * YDVARS%EZDIAG(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EZDIAG(JFLD)%RCP - YDCST%RCPD) * YDVARS%EZDIAG(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%ERA40)
    IF (YDVARS%ERA40(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%ERA40(JFLD)%R - YDCST%RD) * YDVARS%ERA40(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%ERA40(JFLD)%RCP - YDCST%RCPD) * YDVARS%ERA40(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%NOGW)
    IF (YDVARS%NOGW(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%NOGW(JFLD)%R - YDCST%RD) * YDVARS%NOGW(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%NOGW(JFLD)%RCP - YDCST%RCPD) * YDVARS%NOGW(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EDRP)
    IF (YDVARS%EDRP(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EDRP(JFLD)%R - YDCST%RD) * YDVARS%EDRP(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EDRP(JFLD)%RCP - YDCST%RCPD) * YDVARS%EDRP(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%SLDIA)
    IF (YDVARS%SLDIA(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SLDIA(JFLD)%R - YDCST%RD) * YDVARS%SLDIA(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SLDIA(JFLD)%RCP - YDCST%RCPD) * YDVARS%SLDIA(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERAOT)
    IF (YDVARS%AERAOT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERAOT(JFLD)%R - YDCST%RD) * YDVARS%AERAOT(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERAOT(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERAOT(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERLISI)
    IF (YDVARS%AERLISI(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AERLISI(JFLD)%R - YDCST%RD) * YDVARS%AERLISI(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AERLISI(JFLD)%RCP - YDCST%RCPD) * YDVARS%AERLISI(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROUT)
    IF (YDVARS%AEROUT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AEROUT(JFLD)%R - YDCST%RD) * YDVARS%AEROUT(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AEROUT(JFLD)%RCP - YDCST%RCPD) * YDVARS%AEROUT(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
    IF (YDVARS%AEROCLIM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%AEROCLIM(JFLD)%R - YDCST%RD) * YDVARS%AEROCLIM(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%AEROCLIM(JFLD)%RCP - YDCST%RCPD) * YDVARS%AEROCLIM(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%UVP)
    IF (YDVARS%UVP(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UVP(JFLD)%R - YDCST%RD) * YDVARS%UVP(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UVP(JFLD)%RCP - YDCST%RCPD) * YDVARS%UVP(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%PHYS)
    IF (YDVARS%PHYS(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYS(JFLD)%R - YDCST%RD) * YDVARS%PHYS(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYS(JFLD)%RCP - YDCST%RCPD) * YDVARS%PHYS(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%PHYCTY%LTHERMACT, YDVARS%PHYCTY%R, YDVARS%PHYCTY%RCP, YDVARS%PHYCTY%T9)
! IF (YDVARS%PHYCTY%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%PHYCTY%R - YDCST%RD) * YDVARS%PHYCTY%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%PHYCTY%RCP - YDCST%RCPD) * YDVARS%PHYCTY%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RSPEC%LTHERMACT, YDVARS%RSPEC%R, YDVARS%RSPEC%RCP, YDVARS%RSPEC%T9)
! IF (YDVARS%RSPEC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RSPEC%R - YDCST%RD) * YDVARS%RSPEC%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RSPEC%RCP - YDCST%RCPD) * YDVARS%RSPEC%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%SDSAT%LTHERMACT, YDVARS%SDSAT%R, YDVARS%SDSAT%RCP, YDVARS%SDSAT%T9)
! IF (YDVARS%SDSAT%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%SDSAT%R - YDCST%RD) * YDVARS%SDSAT%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%SDSAT%RCP - YDCST%RCPD) * YDVARS%SDSAT%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%CVV%LTHERMACT, YDVARS%CVV%R, YDVARS%CVV%RCP, YDVARS%CVV%T9)
! IF (YDVARS%CVV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CVV%R - YDCST%RD) * YDVARS%CVV%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CVV%RCP - YDCST%RCPD) * YDVARS%CVV%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTH%LTHERMACT, YDVARS%RKTH%R, YDVARS%RKTH%RCP, YDVARS%RKTH%T9)
! IF (YDVARS%RKTH%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTH%R - YDCST%RD) * YDVARS%RKTH%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTH%RCP - YDCST%RCPD) * YDVARS%RKTH%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTQV%LTHERMACT, YDVARS%RKTQV%R, YDVARS%RKTQV%RCP, YDVARS%RKTQV%T9)
! IF (YDVARS%RKTQV%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQV%R - YDCST%RD) * YDVARS%RKTQV%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQV%RCP - YDCST%RCPD) * YDVARS%RKTQV%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%RKTQC%LTHERMACT, YDVARS%RKTQC%R, YDVARS%RKTQC%RCP, YDVARS%RKTQC%T9)
! IF (YDVARS%RKTQC%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%RKTQC%R - YDCST%RD) * YDVARS%RKTQC%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%RKTQC%RCP - YDCST%RCPD) * YDVARS%RKTQC%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UOM%LTHERMACT, YDVARS%UOM%R, YDVARS%UOM%RCP, YDVARS%UOM%T9)
! IF (YDVARS%UOM%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UOM%R - YDCST%RD) * YDVARS%UOM%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UOM%RCP - YDCST%RCPD) * YDVARS%UOM%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UAL%LTHERMACT, YDVARS%UAL%R, YDVARS%UAL%RCP, YDVARS%UAL%T9)
! IF (YDVARS%UAL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UAL%R - YDCST%RD) * YDVARS%UAL%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UAL%RCP - YDCST%RCPD) * YDVARS%UAL%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%DOM%LTHERMACT, YDVARS%DOM%R, YDVARS%DOM%RCP, YDVARS%DOM%T9)
! IF (YDVARS%DOM%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DOM%R - YDCST%RD) * YDVARS%DOM%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DOM%RCP - YDCST%RCPD) * YDVARS%DOM%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%DAL%LTHERMACT, YDVARS%DAL%R, YDVARS%DAL%RCP, YDVARS%DAL%T9)
! IF (YDVARS%DAL%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%DAL%R - YDCST%RD) * YDVARS%DAL%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%DAL%RCP - YDCST%RCPD) * YDVARS%DAL%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UEN%LTHERMACT, YDVARS%UEN%R, YDVARS%UEN%RCP, YDVARS%UEN%T9)
! IF (YDVARS%UEN%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UEN%R - YDCST%RD) * YDVARS%UEN%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UEN%RCP - YDCST%RCPD) * YDVARS%UEN%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  CALL GPRCP_EXPL1 (YDVARS%UNEBH%LTHERMACT, YDVARS%UNEBH%R, YDVARS%UNEBH%RCP, YDVARS%UNEBH%T9)
! IF (YDVARS%UNEBH%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%UNEBH%R - YDCST%RD) * YDVARS%UNEBH%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%UNEBH%RCP - YDCST%RCPD) * YDVARS%UNEBH%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%CRM)
    IF (YDVARS%CRM(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%CRM(JFLD)%R - YDCST%RD) * YDVARS%CRM(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%CRM(JFLD)%RCP - YDCST%RCPD) * YDVARS%CRM(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%LIMA)
    IF (YDVARS%LIMA(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%LIMA(JFLD)%R - YDCST%RD) * YDVARS%LIMA(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%LIMA(JFLD)%RCP - YDCST%RCPD) * YDVARS%LIMA(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CALL GPRCP_EXPL1 (YDVARS%FSD%LTHERMACT, YDVARS%FSD%R, YDVARS%FSD%RCP, YDVARS%FSD%T9)
! IF (YDVARS%FSD%LTHERMACT) THEN
!   DO JLEV = 1, KFLEV
!     DO JLON = KST, KPROF
!       ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%FSD%R - YDCST%RD) * YDVARS%FSD%T9 (JLON, JLEV)
!       IF (LLCP) THEN
!         ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%FSD%RCP - YDCST%RCPD) * YDVARS%FSD%T9 (JLON, JLEV)
!       ENDIF
!     ENDDO
!   ENDDO
! ENDIF
  DO JFLD = 1, SIZE (YDVARS%EXT)
    IF (YDVARS%EXT(JFLD)%LTHERMACT) THEN
      DO JLEV = 1, KFLEV
        DO JLON = KST, KPROF
          ZR (JLON,JLEV) = ZR (JLON,JLEV) + (YDVARS%EXT(JFLD)%R - YDCST%RD) * YDVARS%EXT(JFLD)%T9 (JLON, JLEV)
          IF (LLCP) THEN
            ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (YDVARS%EXT(JFLD)%RCP - YDCST%RCPD) * YDVARS%EXT(JFLD)%T9 (JLON, JLEV)
          ENDIF
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  CASE DEFAULT
    CALL ABOR1 ('UNEXPECTED IGFLTYP')
END SELECT 

DO JLEV = 1, KFLEV
  DO JLON = KST, KPROF
    ZR (JLON,JLEV) = YDCST%RD + ZR (JLON,JLEV)
    IF (LLCP) THEN
      ZCP (JLON,JLEV) = YDCST%RCPD + ZCP (JLON,JLEV)
    ENDIF
  ENDDO
ENDDO

IF (PRESENT(PKAP)) THEN
  PKAP(KST:KPROF,1:KFLEV)=ZR(KST:KPROF,1:KFLEV)/ZCP(KST:KPROF,1:KFLEV)
ENDIF

IF (LHOOK) CALL DR_HOOK("GPRCP_EXPL",1,ZHOOK)

CONTAINS

SUBROUTINE GPRCP_EXPL1 (LDTHERMACT, P_R, P_RCP, P_T)

LOGICAL, INTENT (IN) :: LDTHERMACT
REAL (KIND=JPRB), INTENT (IN) :: P_R
REAL (KIND=JPRB), INTENT (IN) :: P_RCP
REAL (KIND=JPRB), INTENT (IN) :: P_T (KPROMA,KFLEV)

IF (LDTHERMACT) THEN
  DO JLEV = 1, KFLEV
    DO JLON = KST, KPROF
      ZR (JLON,JLEV) = ZR (JLON,JLEV) + (P_R - YDCST%RD) * P_T (JLON, JLEV)
      IF (LLCP) THEN
        ZCP (JLON,JLEV) = ZCP (JLON,JLEV) + (P_RCP - YDCST%RCPD) * P_T (JLON, JLEV)
      ENDIF
    ENDDO
  ENDDO
ENDIF

END SUBROUTINE GPRCP_EXPL1

END SUBROUTINE GPRCP_EXPL

