
SUBROUTINE GPTF2_EXPL_3TL_PART2 (YDGEOMETRY, YDDYN, KST, KEN, LDFSTEP, YDVARS)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE FIELD_VARIABLES_MOD    , ONLY : FIELD_VARIABLES
USE YOMDYN       , ONLY : TDYN


IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDYN)        ,INTENT(IN)    :: YDDYN
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KEN
LOGICAL           ,INTENT(IN)    :: LDFSTEP
TYPE(FIELD_VARIABLES),INTENT(INOUT) :: YDVARS

INTEGER (KIND=JPIM) :: JLEV, JFLD, JLON

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK("GPTF2_EXPL_3TL_PART2",0,ZHOOK_HANDLE)

IF (LDFSTEP) THEN

  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%Q%LT9, YDVARS%Q%T9, YDVARS%Q%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%I%LT9, YDVARS%I%T9, YDVARS%I%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%L%LT9, YDVARS%L%T9, YDVARS%L%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%LCONV%LT9, YDVARS%LCONV%T9, YDVARS%LCONV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%ICONV%LT9, YDVARS%ICONV%T9, YDVARS%ICONV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%RCONV%LT9, YDVARS%RCONV%T9, YDVARS%RCONV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%SCONV%LT9, YDVARS%SCONV%T9, YDVARS%SCONV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%IRAD%LT9, YDVARS%IRAD%T9, YDVARS%IRAD%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%LRAD%LT9, YDVARS%LRAD%T9, YDVARS%LRAD%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%S%LT9, YDVARS%S%T9, YDVARS%S%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%R%LT9, YDVARS%R%T9, YDVARS%R%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%G%LT9, YDVARS%G%T9, YDVARS%G%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%H%LT9, YDVARS%H%T9, YDVARS%H%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%TKE%LT9, YDVARS%TKE%T9, YDVARS%TKE%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%TTE%LT9, YDVARS%TTE%T9, YDVARS%TTE%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%EFB1%LT9, YDVARS%EFB1%T9, YDVARS%EFB1%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%EFB2%LT9, YDVARS%EFB2%T9, YDVARS%EFB2%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%EFB3%LT9, YDVARS%EFB3%T9, YDVARS%EFB3%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%A%LT9, YDVARS%A%T9, YDVARS%A%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%O3%LT9, YDVARS%O3%T9, YDVARS%O3%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%SRC%LT9, YDVARS%SRC%T9, YDVARS%SRC%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%MXL%LT9, YDVARS%MXL%T9, YDVARS%MXL%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%SHTUR%LT9, YDVARS%SHTUR%T9, YDVARS%SHTUR%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%FQTUR%LT9, YDVARS%FQTUR%T9, YDVARS%FQTUR%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%FSTUR%LT9, YDVARS%FSTUR%T9, YDVARS%FSTUR%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%CPF%LT9, YDVARS%CPF%T9, YDVARS%CPF%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%SPF%LT9, YDVARS%SPF%T9, YDVARS%SPF%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%CVGQ%LT9, YDVARS%CVGQ%T9, YDVARS%CVGQ%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%QVA%LT9, YDVARS%QVA%T9, YDVARS%QVA%T0)
  DO JFLD = 1, SIZE (YDVARS%GHG)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%GHG(JFLD)%LT9, YDVARS%GHG(JFLD)%T9, YDVARS%GHG(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%CHEM)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%CHEM(JFLD)%LT9, YDVARS%CHEM(JFLD)%T9, YDVARS%CHEM(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERO)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%AERO(JFLD)%LT9, YDVARS%AERO(JFLD)%T9, YDVARS%AERO(JFLD)%T0)
  ENDDO
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%LRCH4%LT9, YDVARS%LRCH4%T9, YDVARS%LRCH4%T0)
  DO JFLD = 1, SIZE (YDVARS%FORC)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%FORC(JFLD)%LT9, YDVARS%FORC(JFLD)%T9, YDVARS%FORC(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EZDIAG)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%EZDIAG(JFLD)%LT9, YDVARS%EZDIAG(JFLD)%T9, YDVARS%EZDIAG(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%ERA40)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%ERA40(JFLD)%LT9, YDVARS%ERA40(JFLD)%T9, YDVARS%ERA40(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%NOGW)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%NOGW(JFLD)%LT9, YDVARS%NOGW(JFLD)%T9, YDVARS%NOGW(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EDRP)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%EDRP(JFLD)%LT9, YDVARS%EDRP(JFLD)%T9, YDVARS%EDRP(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%SLDIA)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%SLDIA(JFLD)%LT9, YDVARS%SLDIA(JFLD)%T9, YDVARS%SLDIA(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERAOT)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%AERAOT(JFLD)%LT9, YDVARS%AERAOT(JFLD)%T9, YDVARS%AERAOT(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERLISI)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%AERLISI(JFLD)%LT9, YDVARS%AERLISI(JFLD)%T9, YDVARS%AERLISI(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROUT)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%AEROUT(JFLD)%LT9, YDVARS%AEROUT(JFLD)%T9, YDVARS%AEROUT(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%AEROCLIM(JFLD)%LT9, YDVARS%AEROCLIM(JFLD)%T9, YDVARS%AEROCLIM(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%UVP)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%UVP(JFLD)%LT9, YDVARS%UVP(JFLD)%T9, YDVARS%UVP(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%PHYS)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%PHYS(JFLD)%LT9, YDVARS%PHYS(JFLD)%T9, YDVARS%PHYS(JFLD)%T0)
  ENDDO
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%PHYCTY%LT9, YDVARS%PHYCTY%T9, YDVARS%PHYCTY%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%RSPEC%LT9, YDVARS%RSPEC%T9, YDVARS%RSPEC%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%SDSAT%LT9, YDVARS%SDSAT%T9, YDVARS%SDSAT%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%CVV%LT9, YDVARS%CVV%T9, YDVARS%CVV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%RKTH%LT9, YDVARS%RKTH%T9, YDVARS%RKTH%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%RKTQV%LT9, YDVARS%RKTQV%T9, YDVARS%RKTQV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%RKTQC%LT9, YDVARS%RKTQC%T9, YDVARS%RKTQC%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%UOM%LT9, YDVARS%UOM%T9, YDVARS%UOM%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%UAL%LT9, YDVARS%UAL%T9, YDVARS%UAL%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%DOM%LT9, YDVARS%DOM%T9, YDVARS%DOM%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%DAL%LT9, YDVARS%DAL%T9, YDVARS%DAL%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%UEN%LT9, YDVARS%UEN%T9, YDVARS%UEN%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%UNEBH%LT9, YDVARS%UNEBH%T9, YDVARS%UNEBH%T0)
  DO JFLD = 1, SIZE (YDVARS%CRM)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%CRM(JFLD)%LT9, YDVARS%CRM(JFLD)%T9, YDVARS%CRM(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%LIMA)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%LIMA(JFLD)%LT9, YDVARS%LIMA(JFLD)%T9, YDVARS%LIMA(JFLD)%T0)
  ENDDO
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%FSD%LT9, YDVARS%FSD%T9, YDVARS%FSD%T0)
  DO JFLD = 1, SIZE (YDVARS%EXT)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_T (YDVARS%EXT(JFLD)%LT9, YDVARS%EXT(JFLD)%T9, YDVARS%EXT(JFLD)%T0)
  ENDDO

ELSE

  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%Q%LT9, YDVARS%Q%T9, YDVARS%Q%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%I%LT9, YDVARS%I%T9, YDVARS%I%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%L%LT9, YDVARS%L%T9, YDVARS%L%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%LCONV%LT9, YDVARS%LCONV%T9, YDVARS%LCONV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%ICONV%LT9, YDVARS%ICONV%T9, YDVARS%ICONV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%RCONV%LT9, YDVARS%RCONV%T9, YDVARS%RCONV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%SCONV%LT9, YDVARS%SCONV%T9, YDVARS%SCONV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%IRAD%LT9, YDVARS%IRAD%T9, YDVARS%IRAD%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%LRAD%LT9, YDVARS%LRAD%T9, YDVARS%LRAD%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%S%LT9, YDVARS%S%T9, YDVARS%S%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%R%LT9, YDVARS%R%T9, YDVARS%R%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%G%LT9, YDVARS%G%T9, YDVARS%G%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%H%LT9, YDVARS%H%T9, YDVARS%H%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%TKE%LT9, YDVARS%TKE%T9, YDVARS%TKE%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%TTE%LT9, YDVARS%TTE%T9, YDVARS%TTE%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%EFB1%LT9, YDVARS%EFB1%T9, YDVARS%EFB1%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%EFB2%LT9, YDVARS%EFB2%T9, YDVARS%EFB2%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%EFB3%LT9, YDVARS%EFB3%T9, YDVARS%EFB3%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%A%LT9, YDVARS%A%T9, YDVARS%A%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%O3%LT9, YDVARS%O3%T9, YDVARS%O3%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%SRC%LT9, YDVARS%SRC%T9, YDVARS%SRC%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%MXL%LT9, YDVARS%MXL%T9, YDVARS%MXL%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%SHTUR%LT9, YDVARS%SHTUR%T9, YDVARS%SHTUR%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%FQTUR%LT9, YDVARS%FQTUR%T9, YDVARS%FQTUR%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%FSTUR%LT9, YDVARS%FSTUR%T9, YDVARS%FSTUR%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%CPF%LT9, YDVARS%CPF%T9, YDVARS%CPF%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%SPF%LT9, YDVARS%SPF%T9, YDVARS%SPF%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%CVGQ%LT9, YDVARS%CVGQ%T9, YDVARS%CVGQ%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%QVA%LT9, YDVARS%QVA%T9, YDVARS%QVA%T0)
  DO JFLD = 1, SIZE (YDVARS%GHG)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%GHG(JFLD)%LT9, YDVARS%GHG(JFLD)%T9, YDVARS%GHG(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%CHEM)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%CHEM(JFLD)%LT9, YDVARS%CHEM(JFLD)%T9, YDVARS%CHEM(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERO)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%AERO(JFLD)%LT9, YDVARS%AERO(JFLD)%T9, YDVARS%AERO(JFLD)%T0)
  ENDDO
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%LRCH4%LT9, YDVARS%LRCH4%T9, YDVARS%LRCH4%T0)
  DO JFLD = 1, SIZE (YDVARS%FORC)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%FORC(JFLD)%LT9, YDVARS%FORC(JFLD)%T9, YDVARS%FORC(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EZDIAG)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%EZDIAG(JFLD)%LT9, YDVARS%EZDIAG(JFLD)%T9, YDVARS%EZDIAG(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%ERA40)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%ERA40(JFLD)%LT9, YDVARS%ERA40(JFLD)%T9, YDVARS%ERA40(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%NOGW)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%NOGW(JFLD)%LT9, YDVARS%NOGW(JFLD)%T9, YDVARS%NOGW(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%EDRP)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%EDRP(JFLD)%LT9, YDVARS%EDRP(JFLD)%T9, YDVARS%EDRP(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%SLDIA)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%SLDIA(JFLD)%LT9, YDVARS%SLDIA(JFLD)%T9, YDVARS%SLDIA(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERAOT)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%AERAOT(JFLD)%LT9, YDVARS%AERAOT(JFLD)%T9, YDVARS%AERAOT(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AERLISI)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%AERLISI(JFLD)%LT9, YDVARS%AERLISI(JFLD)%T9, YDVARS%AERLISI(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROUT)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%AEROUT(JFLD)%LT9, YDVARS%AEROUT(JFLD)%T9, YDVARS%AEROUT(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%AEROCLIM)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%AEROCLIM(JFLD)%LT9, YDVARS%AEROCLIM(JFLD)%T9, YDVARS%AEROCLIM(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%UVP)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%UVP(JFLD)%LT9, YDVARS%UVP(JFLD)%T9, YDVARS%UVP(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%PHYS)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%PHYS(JFLD)%LT9, YDVARS%PHYS(JFLD)%T9, YDVARS%PHYS(JFLD)%T0)
  ENDDO
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%PHYCTY%LT9, YDVARS%PHYCTY%T9, YDVARS%PHYCTY%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%RSPEC%LT9, YDVARS%RSPEC%T9, YDVARS%RSPEC%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%SDSAT%LT9, YDVARS%SDSAT%T9, YDVARS%SDSAT%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%CVV%LT9, YDVARS%CVV%T9, YDVARS%CVV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%RKTH%LT9, YDVARS%RKTH%T9, YDVARS%RKTH%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%RKTQV%LT9, YDVARS%RKTQV%T9, YDVARS%RKTQV%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%RKTQC%LT9, YDVARS%RKTQC%T9, YDVARS%RKTQC%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%UOM%LT9, YDVARS%UOM%T9, YDVARS%UOM%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%UAL%LT9, YDVARS%UAL%T9, YDVARS%UAL%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%DOM%LT9, YDVARS%DOM%T9, YDVARS%DOM%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%DAL%LT9, YDVARS%DAL%T9, YDVARS%DAL%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%UEN%LT9, YDVARS%UEN%T9, YDVARS%UEN%T0)
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%UNEBH%LT9, YDVARS%UNEBH%T9, YDVARS%UNEBH%T0)
  DO JFLD = 1, SIZE (YDVARS%CRM)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%CRM(JFLD)%LT9, YDVARS%CRM(JFLD)%T9, YDVARS%CRM(JFLD)%T0)
  ENDDO
  DO JFLD = 1, SIZE (YDVARS%LIMA)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%LIMA(JFLD)%LT9, YDVARS%LIMA(JFLD)%T9, YDVARS%LIMA(JFLD)%T0)
  ENDDO
  CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%FSD%LT9, YDVARS%FSD%T9, YDVARS%FSD%T0)
  DO JFLD = 1, SIZE (YDVARS%EXT)
    CALL GPTF2_EXPL_3TL_PART2_FSTEP_F (YDVARS%EXT(JFLD)%LT9, YDVARS%EXT(JFLD)%T9, YDVARS%EXT(JFLD)%T0)
  ENDDO

ENDIF

IF (LHOOK) CALL DR_HOOK("GPTF2_EXPL_3TL_PART2",1,ZHOOK_HANDLE)

CONTAINS 

SUBROUTINE GPTF2_EXPL_3TL_PART2_FSTEP_T (LDT9, PT9, PT0)

LOGICAL, INTENT (IN) :: LDT9
REAL (KIND=JPRB), INTENT (INOUT) :: PT9 (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)    :: PT0 (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)

IF (LDT9) THEN
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JLON=KST,KEN
      PT9 (JLON,JLEV) = PT0 (JLON,JLEV)
    ENDDO
  ENDDO
ENDIF

END SUBROUTINE GPTF2_EXPL_3TL_PART2_FSTEP_T

SUBROUTINE GPTF2_EXPL_3TL_PART2_FSTEP_F (LDT9, PT9, PT0)

LOGICAL, INTENT (IN) :: LDT9
REAL (KIND=JPRB), INTENT (INOUT) :: PT9 (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL (KIND=JPRB), INTENT (IN)    :: PT0 (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)

IF (LDT9) THEN
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JLON=KST,KEN
      PT9 (JLON,JLEV) = PT9 (JLON,JLEV) + YDDYN%REPSM2 * PT0 (JLON,JLEV)
    ENDDO
  ENDDO
ENDIF


END SUBROUTINE GPTF2_EXPL_3TL_PART2_FSTEP_F

END SUBROUTINE
