
SUBROUTINE LATTEX_EXPL_VSPLTRANS (YDGEOMETRY, YDCPG_BNDS, YDML_GCONF, YDML_DYN, YDCPG_SL1)

! **  NEVER TESTED **

USE PARKIND1              , ONLY : JPIM, JPRB
USE YOMHOOK               , ONLY : DR_HOOK, LHOOK
USE GEOMETRY_MOD          , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD     , ONLY : CPG_BNDS_TYPE
USE MODEL_GENERAL_CONF_MOD, ONLY : MODEL_GENERAL_CONF_TYPE
USE MODEL_DYNAMICS_MOD    , ONLY : MODEL_DYNAMICS_TYPE
USE CPG_TYPE_MOD          , ONLY : CPG_SL1_TYPE


IMPLICIT NONE

TYPE(GEOMETRY)                ,INTENT(IN)     :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)           ,INTENT(IN)     :: YDCPG_BNDS
TYPE(MODEL_GENERAL_CONF_TYPE) ,INTENT(IN)     :: YDML_GCONF
TYPE(MODEL_DYNAMICS_TYPE)     ,INTENT(IN)     :: YDML_DYN
TYPE(CPG_SL1_TYPE)            ,INTENT(INOUT)  :: YDCPG_SL1

#include "vspltrans.intfb.h"

LOGICAL :: LLTDIABLIN
INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF
INTEGER (KIND=JPIM) :: JGFL

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('LATTEX_EXPL_VSPLTRANS',0,ZHOOK_HANDLE)

CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YQ%LADV, YDML_GCONF%YGFL%YQ%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YQ%CSLINT, YDCPG_SL1%Q, YDCPG_SL1%Q_F, &
                            & YDCPG_SL1%Q_SP, YDCPG_SL1%Q_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YI%LADV, YDML_GCONF%YGFL%YI%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YI%CSLINT, YDCPG_SL1%I, YDCPG_SL1%I_F, &
                            & YDCPG_SL1%I_SP, YDCPG_SL1%I_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YL%LADV, YDML_GCONF%YGFL%YL%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YL%CSLINT, YDCPG_SL1%L, YDCPG_SL1%L_F, &
                            & YDCPG_SL1%L_SP, YDCPG_SL1%L_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YLCONV%LADV, YDML_GCONF%YGFL%YLCONV%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YLCONV%CSLINT, YDCPG_SL1%LCONV, YDCPG_SL1%LCONV_F, &
                            & YDCPG_SL1%LCONV_SP, YDCPG_SL1%LCONV_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YICONV%LADV, YDML_GCONF%YGFL%YICONV%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YICONV%CSLINT, YDCPG_SL1%ICONV, YDCPG_SL1%ICONV_F, &
                            & YDCPG_SL1%ICONV_SP, YDCPG_SL1%ICONV_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YRCONV%LADV, YDML_GCONF%YGFL%YRCONV%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YRCONV%CSLINT, YDCPG_SL1%RCONV, YDCPG_SL1%RCONV_F, &
                            & YDCPG_SL1%RCONV_SP, YDCPG_SL1%RCONV_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YSCONV%LADV, YDML_GCONF%YGFL%YSCONV%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YSCONV%CSLINT, YDCPG_SL1%SCONV, YDCPG_SL1%SCONV_F, &
                            & YDCPG_SL1%SCONV_SP, YDCPG_SL1%SCONV_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YIRAD%LADV, YDML_GCONF%YGFL%YIRAD%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YIRAD%CSLINT, YDCPG_SL1%IRAD, YDCPG_SL1%IRAD_F, &
                            & YDCPG_SL1%IRAD_SP, YDCPG_SL1%IRAD_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YLRAD%LADV, YDML_GCONF%YGFL%YLRAD%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YLRAD%CSLINT, YDCPG_SL1%LRAD, YDCPG_SL1%LRAD_F, &
                            & YDCPG_SL1%LRAD_SP, YDCPG_SL1%LRAD_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YS%LADV, YDML_GCONF%YGFL%YS%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YS%CSLINT, YDCPG_SL1%S, YDCPG_SL1%S_F, &
                            & YDCPG_SL1%S_SP, YDCPG_SL1%S_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YR%LADV, YDML_GCONF%YGFL%YR%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YR%CSLINT, YDCPG_SL1%R, YDCPG_SL1%R_F, &
                            & YDCPG_SL1%R_SP, YDCPG_SL1%R_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YG%LADV, YDML_GCONF%YGFL%YG%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YG%CSLINT, YDCPG_SL1%G, YDCPG_SL1%G_F, &
                            & YDCPG_SL1%G_SP, YDCPG_SL1%G_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YH%LADV, YDML_GCONF%YGFL%YH%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YH%CSLINT, YDCPG_SL1%H, YDCPG_SL1%H_F, &
                            & YDCPG_SL1%H_SP, YDCPG_SL1%H_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YTKE%LADV, YDML_GCONF%YGFL%YTKE%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YTKE%CSLINT, YDCPG_SL1%TKE, YDCPG_SL1%TKE_F, &
                            & YDCPG_SL1%TKE_SP, YDCPG_SL1%TKE_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YTTE%LADV, YDML_GCONF%YGFL%YTTE%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YTTE%CSLINT, YDCPG_SL1%TTE, YDCPG_SL1%TTE_F, &
                            & YDCPG_SL1%TTE_SP, YDCPG_SL1%TTE_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YEFB1%LADV, YDML_GCONF%YGFL%YEFB1%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YEFB1%CSLINT, YDCPG_SL1%EFB1, YDCPG_SL1%EFB1_F, &
                            & YDCPG_SL1%EFB1_SP, YDCPG_SL1%EFB1_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YEFB2%LADV, YDML_GCONF%YGFL%YEFB2%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YEFB2%CSLINT, YDCPG_SL1%EFB2, YDCPG_SL1%EFB2_F, &
                            & YDCPG_SL1%EFB2_SP, YDCPG_SL1%EFB2_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YEFB3%LADV, YDML_GCONF%YGFL%YEFB3%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YEFB3%CSLINT, YDCPG_SL1%EFB3, YDCPG_SL1%EFB3_F, &
                            & YDCPG_SL1%EFB3_SP, YDCPG_SL1%EFB3_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YA%LADV, YDML_GCONF%YGFL%YA%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YA%CSLINT, YDCPG_SL1%A, YDCPG_SL1%A_F, &
                            & YDCPG_SL1%A_SP, YDCPG_SL1%A_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YO3%LADV, YDML_GCONF%YGFL%YO3%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YO3%CSLINT, YDCPG_SL1%O3, YDCPG_SL1%O3_F, &
                            & YDCPG_SL1%O3_SP, YDCPG_SL1%O3_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YSRC%LADV, YDML_GCONF%YGFL%YSRC%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YSRC%CSLINT, YDCPG_SL1%SRC, YDCPG_SL1%SRC_F, &
                            & YDCPG_SL1%SRC_SP, YDCPG_SL1%SRC_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YMXL%LADV, YDML_GCONF%YGFL%YMXL%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YMXL%CSLINT, YDCPG_SL1%MXL, YDCPG_SL1%MXL_F, &
                            & YDCPG_SL1%MXL_SP, YDCPG_SL1%MXL_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YSHTUR%LADV, YDML_GCONF%YGFL%YSHTUR%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YSHTUR%CSLINT, YDCPG_SL1%SHTUR, YDCPG_SL1%SHTUR_F, &
                            & YDCPG_SL1%SHTUR_SP, YDCPG_SL1%SHTUR_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YFQTUR%LADV, YDML_GCONF%YGFL%YFQTUR%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YFQTUR%CSLINT, YDCPG_SL1%FQTUR, YDCPG_SL1%FQTUR_F, &
                            & YDCPG_SL1%FQTUR_SP, YDCPG_SL1%FQTUR_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YFSTUR%LADV, YDML_GCONF%YGFL%YFSTUR%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YFSTUR%CSLINT, YDCPG_SL1%FSTUR, YDCPG_SL1%FSTUR_F, &
                            & YDCPG_SL1%FSTUR_SP, YDCPG_SL1%FSTUR_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YCPF%LADV, YDML_GCONF%YGFL%YCPF%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YCPF%CSLINT, YDCPG_SL1%CPF, YDCPG_SL1%CPF_F, &
                            & YDCPG_SL1%CPF_SP, YDCPG_SL1%CPF_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YSPF%LADV, YDML_GCONF%YGFL%YSPF%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YSPF%CSLINT, YDCPG_SL1%SPF, YDCPG_SL1%SPF_F, &
                            & YDCPG_SL1%SPF_SP, YDCPG_SL1%SPF_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YCVGQ%LADV, YDML_GCONF%YGFL%YCVGQ%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YCVGQ%CSLINT, YDCPG_SL1%CVGQ, YDCPG_SL1%CVGQ_F, &
                            & YDCPG_SL1%CVGQ_SP, YDCPG_SL1%CVGQ_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YQVA%LADV, YDML_GCONF%YGFL%YQVA%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YQVA%CSLINT, YDCPG_SL1%QVA, YDCPG_SL1%QVA_F, &
                            & YDCPG_SL1%QVA_SP, YDCPG_SL1%QVA_SPF)
DO JGFL = 1, SIZE (YDCPG_SL1%GHG)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YGHG(JGFL)%LADV, YDML_GCONF%YGFL%YGHG(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YGHG(JGFL)%CSLINT, YDCPG_SL1%GHG(JGFL)%P, YDCPG_SL1%GHG(JGFL)%P_F, &
                              & YDCPG_SL1%GHG(JGFL)%P_SP, YDCPG_SL1%GHG(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%CHEM)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YCHEM(JGFL)%LADV, YDML_GCONF%YGFL%YCHEM(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YCHEM(JGFL)%CSLINT, YDCPG_SL1%CHEM(JGFL)%P, YDCPG_SL1%CHEM(JGFL)%P_F, &
                              & YDCPG_SL1%CHEM(JGFL)%P_SP, YDCPG_SL1%CHEM(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERO)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YAERO(JGFL)%LADV, YDML_GCONF%YGFL%YAERO(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YAERO(JGFL)%CSLINT, YDCPG_SL1%AERO(JGFL)%P, YDCPG_SL1%AERO(JGFL)%P_F, &
                              & YDCPG_SL1%AERO(JGFL)%P_SP, YDCPG_SL1%AERO(JGFL)%P_SPF)
ENDDO
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YLRCH4%LADV, YDML_GCONF%YGFL%YLRCH4%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YLRCH4%CSLINT, YDCPG_SL1%LRCH4, YDCPG_SL1%LRCH4_F, &
                            & YDCPG_SL1%LRCH4_SP, YDCPG_SL1%LRCH4_SPF)
DO JGFL = 1, SIZE (YDCPG_SL1%FORC)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YFORC(JGFL)%LADV, YDML_GCONF%YGFL%YFORC(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YFORC(JGFL)%CSLINT, YDCPG_SL1%FORC(JGFL)%P, YDCPG_SL1%FORC(JGFL)%P_F, &
                              & YDCPG_SL1%FORC(JGFL)%P_SP, YDCPG_SL1%FORC(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%EZDIAG)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YEZDIAG(JGFL)%LADV, YDML_GCONF%YGFL%YEZDIAG(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YEZDIAG(JGFL)%CSLINT, YDCPG_SL1%EZDIAG(JGFL)%P, YDCPG_SL1%EZDIAG(JGFL)%P_F, &
                              & YDCPG_SL1%EZDIAG(JGFL)%P_SP, YDCPG_SL1%EZDIAG(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%ERA40)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YERA40(JGFL)%LADV, YDML_GCONF%YGFL%YERA40(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YERA40(JGFL)%CSLINT, YDCPG_SL1%ERA40(JGFL)%P, YDCPG_SL1%ERA40(JGFL)%P_F, &
                              & YDCPG_SL1%ERA40(JGFL)%P_SP, YDCPG_SL1%ERA40(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%NOGW)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YNOGW(JGFL)%LADV, YDML_GCONF%YGFL%YNOGW(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YNOGW(JGFL)%CSLINT, YDCPG_SL1%NOGW(JGFL)%P, YDCPG_SL1%NOGW(JGFL)%P_F, &
                              & YDCPG_SL1%NOGW(JGFL)%P_SP, YDCPG_SL1%NOGW(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%EDRP)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YEDRP(JGFL)%LADV, YDML_GCONF%YGFL%YEDRP(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YEDRP(JGFL)%CSLINT, YDCPG_SL1%EDRP(JGFL)%P, YDCPG_SL1%EDRP(JGFL)%P_F, &
                              & YDCPG_SL1%EDRP(JGFL)%P_SP, YDCPG_SL1%EDRP(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%SLDIA)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YSLDIA(JGFL)%LADV, YDML_GCONF%YGFL%YSLDIA(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YSLDIA(JGFL)%CSLINT, YDCPG_SL1%SLDIA(JGFL)%P, YDCPG_SL1%SLDIA(JGFL)%P_F, &
                              & YDCPG_SL1%SLDIA(JGFL)%P_SP, YDCPG_SL1%SLDIA(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERAOT)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YAERAOT(JGFL)%LADV, YDML_GCONF%YGFL%YAERAOT(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YAERAOT(JGFL)%CSLINT, YDCPG_SL1%AERAOT(JGFL)%P, YDCPG_SL1%AERAOT(JGFL)%P_F, &
                              & YDCPG_SL1%AERAOT(JGFL)%P_SP, YDCPG_SL1%AERAOT(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AERLISI)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YAERLISI(JGFL)%LADV, YDML_GCONF%YGFL%YAERLISI(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YAERLISI(JGFL)%CSLINT, YDCPG_SL1%AERLISI(JGFL)%P, YDCPG_SL1%AERLISI(JGFL)%P_F, &
                              & YDCPG_SL1%AERLISI(JGFL)%P_SP, YDCPG_SL1%AERLISI(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AEROUT)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YAEROUT(JGFL)%LADV, YDML_GCONF%YGFL%YAEROUT(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YAEROUT(JGFL)%CSLINT, YDCPG_SL1%AEROUT(JGFL)%P, YDCPG_SL1%AEROUT(JGFL)%P_F, &
                              & YDCPG_SL1%AEROUT(JGFL)%P_SP, YDCPG_SL1%AEROUT(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%AEROCLIM)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YAEROCLIM(JGFL)%LADV, YDML_GCONF%YGFL%YAEROCLIM(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YAEROCLIM(JGFL)%CSLINT, YDCPG_SL1%AEROCLIM(JGFL)%P, YDCPG_SL1%AEROCLIM(JGFL)%P_F, &
                              & YDCPG_SL1%AEROCLIM(JGFL)%P_SP, YDCPG_SL1%AEROCLIM(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%UVP)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YUVP(JGFL)%LADV, YDML_GCONF%YGFL%YUVP(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YUVP(JGFL)%CSLINT, YDCPG_SL1%UVP(JGFL)%P, YDCPG_SL1%UVP(JGFL)%P_F, &
                              & YDCPG_SL1%UVP(JGFL)%P_SP, YDCPG_SL1%UVP(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%PHYS)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YPHYS(JGFL)%LADV, YDML_GCONF%YGFL%YPHYS(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YPHYS(JGFL)%CSLINT, YDCPG_SL1%PHYS(JGFL)%P, YDCPG_SL1%PHYS(JGFL)%P_F, &
                              & YDCPG_SL1%PHYS(JGFL)%P_SP, YDCPG_SL1%PHYS(JGFL)%P_SPF)
ENDDO
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YPHYCTY%LADV, YDML_GCONF%YGFL%YPHYCTY%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YPHYCTY%CSLINT, YDCPG_SL1%PHYCTY, YDCPG_SL1%PHYCTY_F, &
                            & YDCPG_SL1%PHYCTY_SP, YDCPG_SL1%PHYCTY_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YRSPEC%LADV, YDML_GCONF%YGFL%YRSPEC%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YRSPEC%CSLINT, YDCPG_SL1%RSPEC, YDCPG_SL1%RSPEC_F, &
                            & YDCPG_SL1%RSPEC_SP, YDCPG_SL1%RSPEC_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YSDSAT%LADV, YDML_GCONF%YGFL%YSDSAT%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YSDSAT%CSLINT, YDCPG_SL1%SDSAT, YDCPG_SL1%SDSAT_F, &
                            & YDCPG_SL1%SDSAT_SP, YDCPG_SL1%SDSAT_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YCVV%LADV, YDML_GCONF%YGFL%YCVV%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YCVV%CSLINT, YDCPG_SL1%CVV, YDCPG_SL1%CVV_F, &
                            & YDCPG_SL1%CVV_SP, YDCPG_SL1%CVV_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YRKTH%LADV, YDML_GCONF%YGFL%YRKTH%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YRKTH%CSLINT, YDCPG_SL1%RKTH, YDCPG_SL1%RKTH_F, &
                            & YDCPG_SL1%RKTH_SP, YDCPG_SL1%RKTH_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YRKTQV%LADV, YDML_GCONF%YGFL%YRKTQV%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YRKTQV%CSLINT, YDCPG_SL1%RKTQV, YDCPG_SL1%RKTQV_F, &
                            & YDCPG_SL1%RKTQV_SP, YDCPG_SL1%RKTQV_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YRKTQC%LADV, YDML_GCONF%YGFL%YRKTQC%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YRKTQC%CSLINT, YDCPG_SL1%RKTQC, YDCPG_SL1%RKTQC_F, &
                            & YDCPG_SL1%RKTQC_SP, YDCPG_SL1%RKTQC_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YUOM%LADV, YDML_GCONF%YGFL%YUOM%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YUOM%CSLINT, YDCPG_SL1%UOM, YDCPG_SL1%UOM_F, &
                            & YDCPG_SL1%UOM_SP, YDCPG_SL1%UOM_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YUAL%LADV, YDML_GCONF%YGFL%YUAL%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YUAL%CSLINT, YDCPG_SL1%UAL, YDCPG_SL1%UAL_F, &
                            & YDCPG_SL1%UAL_SP, YDCPG_SL1%UAL_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YDOM%LADV, YDML_GCONF%YGFL%YDOM%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YDOM%CSLINT, YDCPG_SL1%DOM, YDCPG_SL1%DOM_F, &
                            & YDCPG_SL1%DOM_SP, YDCPG_SL1%DOM_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YDAL%LADV, YDML_GCONF%YGFL%YDAL%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YDAL%CSLINT, YDCPG_SL1%DAL, YDCPG_SL1%DAL_F, &
                            & YDCPG_SL1%DAL_SP, YDCPG_SL1%DAL_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YUEN%LADV, YDML_GCONF%YGFL%YUEN%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YUEN%CSLINT, YDCPG_SL1%UEN, YDCPG_SL1%UEN_F, &
                            & YDCPG_SL1%UEN_SP, YDCPG_SL1%UEN_SPF)
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YUNEBH%LADV, YDML_GCONF%YGFL%YUNEBH%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YUNEBH%CSLINT, YDCPG_SL1%UNEBH, YDCPG_SL1%UNEBH_F, &
                            & YDCPG_SL1%UNEBH_SP, YDCPG_SL1%UNEBH_SPF)
DO JGFL = 1, SIZE (YDCPG_SL1%CRM)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YCRM(JGFL)%LADV, YDML_GCONF%YGFL%YCRM(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YCRM(JGFL)%CSLINT, YDCPG_SL1%CRM(JGFL)%P, YDCPG_SL1%CRM(JGFL)%P_F, &
                              & YDCPG_SL1%CRM(JGFL)%P_SP, YDCPG_SL1%CRM(JGFL)%P_SPF)
ENDDO
DO JGFL = 1, SIZE (YDCPG_SL1%LIMA)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YLIMA(JGFL)%LADV, YDML_GCONF%YGFL%YLIMA(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YLIMA(JGFL)%CSLINT, YDCPG_SL1%LIMA(JGFL)%P, YDCPG_SL1%LIMA(JGFL)%P_F, &
                              & YDCPG_SL1%LIMA(JGFL)%P_SP, YDCPG_SL1%LIMA(JGFL)%P_SPF)
ENDDO
CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YFSD%LADV, YDML_GCONF%YGFL%YFSD%LTDIABLIN,          &
                            & YDML_GCONF%YGFL%YFSD%CSLINT, YDCPG_SL1%FSD, YDCPG_SL1%FSD_F, &
                            & YDCPG_SL1%FSD_SP, YDCPG_SL1%FSD_SPF)
DO JGFL = 1, SIZE (YDCPG_SL1%EXT)
  CALL LATTEX_EXPL_VSPLTRANS_V (YDML_GCONF%YGFL%YEXT(JGFL)%LADV, YDML_GCONF%YGFL%YEXT(JGFL)%LTDIABLIN,          &
                              & YDML_GCONF%YGFL%YEXT(JGFL)%CSLINT, YDCPG_SL1%EXT(JGFL)%P, YDCPG_SL1%EXT(JGFL)%P_F, &
                              & YDCPG_SL1%EXT(JGFL)%P_SP, YDCPG_SL1%EXT(JGFL)%P_SPF)
ENDDO

!  DO JGFL=1,YDML_GCONF%YGFL%NUMFLDS
!    IF(YDML_GCONF%YGFL%YCOMP(JGFL)%LADV .AND. YDML_GCONF%YGFL%YCOMP(JGFL)%CSLINT=='LAITVSPCQM  ' ) THEN
!      IPX  =(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SL1-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
!      IPXSP=(YDML_GCONF%YGFL%YCOMP(JGFL)%MP_SPL-1)*(YDGEOMETRY%YRDIMV%NFLEN-YDGEOMETRY%YRDIMV%NFLSA+1)
!      LLTDIABLIN=YDML_GCONF%YGFL%YCOMP(JGFL)%LTDIABLIN
!      IF ((YDML_DYN%YRDYN%NSPLTHOI /= 0).OR.LLTDIABLIN) THEN
!        DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!          DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!            YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLSPF9+IPXSP+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!          & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLF9  +IPX  +JLEV-YDGEOMETRY%YRDIMV%NFLSA)
!          ENDDO
!        ENDDO
!        CALL VSPLTRANS(YDGEOMETRY%YRVSPLIP,YDGEOMETRY%YRDIM%NPROMA,YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA,
!                     & YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLSA,YDGEOMETRY%YRDIMV%NFLEN,
!                     & YDCPG_SL1%ZVIEW(:,YDML_DYN%YRPTRSLB1%MSLB1GFLSPF9+IPXSP))
!      ENDIF
!      DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!        DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!          YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFLSP9+IPXSP+JLEV-YDGEOMETRY%YRDIMV%NFLSA)=&
!        & YDCPG_SL1%ZVIEW(JROF,YDML_DYN%YRPTRSLB1%MSLB1GFL9  +IPX  +JLEV-YDGEOMETRY%YRDIMV%NFLSA)
!        ENDDO
!      ENDDO
!      CALL VSPLTRANS(YDGEOMETRY%YRVSPLIP,YDGEOMETRY%YRDIM%NPROMA,YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA,&
!                   & YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLSA,YDGEOMETRY%YRDIMV%NFLEN,&
!                   & YDCPG_SL1%ZVIEW(:,YDML_DYN%YRPTRSLB1%MSLB1GFLSP9+IPXSP))
!    ENDIF
!  ENDDO

IF (LHOOK) CALL DR_HOOK('LATTEX_EXPL_VSPLTRANS',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE LATTEX_EXPL_VSPLTRANS_V (LDADV, LDTDIABLIN, CDSLINT, PSL1, PSL1_F, PSL1_SPF, PSL1_SP)

LOGICAL            , INTENT (IN)    :: LDADV
LOGICAL            , INTENT (IN)    :: LDTDIABLIN
CHARACTER (LEN=*)  , INTENT (IN)    :: CDSLINT
REAL (KIND=JPRB)   , INTENT (IN)    :: PSL1     (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB)   , INTENT (IN)    :: PSL1_F   (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB)   , INTENT (INOUT) :: PSL1_SP  (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB)   , INTENT (INOUT) :: PSL1_SPF (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)

IF (LDADV .AND. CDSLINT=='LAITVSPCQM  ') THEN
  LLTDIABLIN=LDTDIABLIN
  IF ((YDML_DYN%YRDYN%NSPLTHOI /= 0).OR.LLTDIABLIN) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        PSL1_SPF(JROF,JLEV)=PSL1_F(JROF,JLEV)
      ENDDO
    ENDDO
    CALL VSPLTRANS(YDGEOMETRY%YRVSPLIP,YDGEOMETRY%YRDIM%NPROMA,YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA,&
                 & YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLSA,YDGEOMETRY%YRDIMV%NFLEN,PSL1_SPF)
  ENDIF
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      PSL1_SP(JROF,JLEV)=PSL1(JROF,JLEV)
    ENDDO
  ENDDO
  CALL VSPLTRANS(YDGEOMETRY%YRVSPLIP,YDGEOMETRY%YRDIM%NPROMA,YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA,&
               & YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLSA,YDGEOMETRY%YRDIMV%NFLEN,PSL1_SP)
ENDIF

END SUBROUTINE LATTEX_EXPL_VSPLTRANS_V

END SUBROUTINE
