
SUBROUTINE LATTEX_EXPL_2TL (YDGEOMETRY, YDCPG_BNDS, YDML_GCONF, YDML_DYN, YDCPG_SL1, YDVARS, LDCT, LDCTC)

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK

USE GEOMETRY_MOD           , ONLY : GEOMETRY
USE CPG_OPTS_TYPE_MOD, ONLY : CPG_BNDS_TYPE, CPG_OPTS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE MODEL_DYNAMICS_MOD     , ONLY : MODEL_DYNAMICS_TYPE
USE CPG_TYPE_MOD           , ONLY : CPG_SL1_TYPE
USE FIELD_VARIABLES_MOD,ONLY : FIELD_VARIABLES


IMPLICIT NONE

TYPE(GEOMETRY)                ,INTENT (IN)    :: YDGEOMETRY
TYPE(CPG_BNDS_TYPE)           ,INTENT (IN)    :: YDCPG_BNDS
TYPE(MODEL_GENERAL_CONF_TYPE) ,INTENT (IN)    :: YDML_GCONF
TYPE(MODEL_DYNAMICS_TYPE)     ,INTENT (IN)    :: YDML_DYN
TYPE(CPG_SL1_TYPE)            ,INTENT (INOUT) :: YDCPG_SL1
TYPE(FIELD_VARIABLES)         ,INTENT (INOUT) :: YDVARS
LOGICAL                       ,INTENT (IN)    :: LDCT
LOGICAL                       ,INTENT (IN)    :: LDCTC

LOGICAL :: LLTDIABLIN
INTEGER (KIND=JPIM) :: JLEV
INTEGER (KIND=JPIM) :: JROF

REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('LATTEX_EXPL_2TL',0,ZHOOK_HANDLE)

IF(LDCT.AND.(.NOT.LDCTC))THEN
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YQ%LADV, YDML_GCONF%YGFL%YQ%LTDIABLIN, &
                                     & YDCPG_SL1%Q, YDCPG_SL1%Q_F, YDVARS%Q%T9)
! IF(YDML_GCONF%YGFL%YQ%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YQ%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%Q(JROF,JLEV)=YDCPG_SL1%Q(JROF,JLEV)&
!       &+YDCPG_SL1%Q_F(JROF,JLEV)+YDVARS%Q%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%Q(JROF,JLEV)=YDCPG_SL1%Q(JROF,JLEV)+YDVARS%Q%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YI%LADV, YDML_GCONF%YGFL%YI%LTDIABLIN, &
                                     & YDCPG_SL1%I, YDCPG_SL1%I_F, YDVARS%I%T9)
! IF(YDML_GCONF%YGFL%YI%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YI%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%I(JROF,JLEV)=YDCPG_SL1%I(JROF,JLEV)&
!       &+YDCPG_SL1%I_F(JROF,JLEV)+YDVARS%I%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%I(JROF,JLEV)=YDCPG_SL1%I(JROF,JLEV)+YDVARS%I%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YL%LADV, YDML_GCONF%YGFL%YL%LTDIABLIN, &
                                     & YDCPG_SL1%L, YDCPG_SL1%L_F, YDVARS%L%T9)
! IF(YDML_GCONF%YGFL%YL%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YL%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%L(JROF,JLEV)=YDCPG_SL1%L(JROF,JLEV)&
!       &+YDCPG_SL1%L_F(JROF,JLEV)+YDVARS%L%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%L(JROF,JLEV)=YDCPG_SL1%L(JROF,JLEV)+YDVARS%L%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YLCONV%LADV, YDML_GCONF%YGFL%YLCONV%LTDIABLIN, &
                                     & YDCPG_SL1%LCONV, YDCPG_SL1%LCONV_F, YDVARS%LCONV%T9)
! IF(YDML_GCONF%YGFL%YLCONV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YLCONV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LCONV(JROF,JLEV)=YDCPG_SL1%LCONV(JROF,JLEV)&
!       &+YDCPG_SL1%LCONV_F(JROF,JLEV)+YDVARS%LCONV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LCONV(JROF,JLEV)=YDCPG_SL1%LCONV(JROF,JLEV)+YDVARS%LCONV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YICONV%LADV, YDML_GCONF%YGFL%YICONV%LTDIABLIN, &
                                     & YDCPG_SL1%ICONV, YDCPG_SL1%ICONV_F, YDVARS%ICONV%T9)
! IF(YDML_GCONF%YGFL%YICONV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YICONV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%ICONV(JROF,JLEV)=YDCPG_SL1%ICONV(JROF,JLEV)&
!       &+YDCPG_SL1%ICONV_F(JROF,JLEV)+YDVARS%ICONV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%ICONV(JROF,JLEV)=YDCPG_SL1%ICONV(JROF,JLEV)+YDVARS%ICONV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YRCONV%LADV, YDML_GCONF%YGFL%YRCONV%LTDIABLIN, &
                                     & YDCPG_SL1%RCONV, YDCPG_SL1%RCONV_F, YDVARS%RCONV%T9)
! IF(YDML_GCONF%YGFL%YRCONV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRCONV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RCONV(JROF,JLEV)=YDCPG_SL1%RCONV(JROF,JLEV)&
!       &+YDCPG_SL1%RCONV_F(JROF,JLEV)+YDVARS%RCONV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RCONV(JROF,JLEV)=YDCPG_SL1%RCONV(JROF,JLEV)+YDVARS%RCONV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YSCONV%LADV, YDML_GCONF%YGFL%YSCONV%LTDIABLIN, &
                                     & YDCPG_SL1%SCONV, YDCPG_SL1%SCONV_F, YDVARS%SCONV%T9)
! IF(YDML_GCONF%YGFL%YSCONV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSCONV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SCONV(JROF,JLEV)=YDCPG_SL1%SCONV(JROF,JLEV)&
!       &+YDCPG_SL1%SCONV_F(JROF,JLEV)+YDVARS%SCONV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SCONV(JROF,JLEV)=YDCPG_SL1%SCONV(JROF,JLEV)+YDVARS%SCONV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YIRAD%LADV, YDML_GCONF%YGFL%YIRAD%LTDIABLIN, &
                                     & YDCPG_SL1%IRAD, YDCPG_SL1%IRAD_F, YDVARS%IRAD%T9)
! IF(YDML_GCONF%YGFL%YIRAD%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YIRAD%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%IRAD(JROF,JLEV)=YDCPG_SL1%IRAD(JROF,JLEV)&
!       &+YDCPG_SL1%IRAD_F(JROF,JLEV)+YDVARS%IRAD%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%IRAD(JROF,JLEV)=YDCPG_SL1%IRAD(JROF,JLEV)+YDVARS%IRAD%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YLRAD%LADV, YDML_GCONF%YGFL%YLRAD%LTDIABLIN, &
                                     & YDCPG_SL1%LRAD, YDCPG_SL1%LRAD_F, YDVARS%LRAD%T9)
! IF(YDML_GCONF%YGFL%YLRAD%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YLRAD%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LRAD(JROF,JLEV)=YDCPG_SL1%LRAD(JROF,JLEV)&
!       &+YDCPG_SL1%LRAD_F(JROF,JLEV)+YDVARS%LRAD%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LRAD(JROF,JLEV)=YDCPG_SL1%LRAD(JROF,JLEV)+YDVARS%LRAD%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YS%LADV, YDML_GCONF%YGFL%YS%LTDIABLIN, &
                                     & YDCPG_SL1%S, YDCPG_SL1%S_F, YDVARS%S%T9)
! IF(YDML_GCONF%YGFL%YS%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YS%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%S(JROF,JLEV)=YDCPG_SL1%S(JROF,JLEV)&
!       &+YDCPG_SL1%S_F(JROF,JLEV)+YDVARS%S%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%S(JROF,JLEV)=YDCPG_SL1%S(JROF,JLEV)+YDVARS%S%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YR%LADV, YDML_GCONF%YGFL%YR%LTDIABLIN, &
                                     & YDCPG_SL1%R, YDCPG_SL1%R_F, YDVARS%R%T9)
! IF(YDML_GCONF%YGFL%YR%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YR%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%R(JROF,JLEV)=YDCPG_SL1%R(JROF,JLEV)&
!       &+YDCPG_SL1%R_F(JROF,JLEV)+YDVARS%R%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%R(JROF,JLEV)=YDCPG_SL1%R(JROF,JLEV)+YDVARS%R%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YG%LADV, YDML_GCONF%YGFL%YG%LTDIABLIN, &
                                     & YDCPG_SL1%G, YDCPG_SL1%G_F, YDVARS%G%T9)
! IF(YDML_GCONF%YGFL%YG%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YG%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%G(JROF,JLEV)=YDCPG_SL1%G(JROF,JLEV)&
!       &+YDCPG_SL1%G_F(JROF,JLEV)+YDVARS%G%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%G(JROF,JLEV)=YDCPG_SL1%G(JROF,JLEV)+YDVARS%G%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YH%LADV, YDML_GCONF%YGFL%YH%LTDIABLIN, &
                                     & YDCPG_SL1%H, YDCPG_SL1%H_F, YDVARS%H%T9)
! IF(YDML_GCONF%YGFL%YH%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YH%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%H(JROF,JLEV)=YDCPG_SL1%H(JROF,JLEV)&
!       &+YDCPG_SL1%H_F(JROF,JLEV)+YDVARS%H%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%H(JROF,JLEV)=YDCPG_SL1%H(JROF,JLEV)+YDVARS%H%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YTKE%LADV, YDML_GCONF%YGFL%YTKE%LTDIABLIN, &
                                     & YDCPG_SL1%TKE, YDCPG_SL1%TKE_F, YDVARS%TKE%T9)
! IF(YDML_GCONF%YGFL%YTKE%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YTKE%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%TKE(JROF,JLEV)=YDCPG_SL1%TKE(JROF,JLEV)&
!       &+YDCPG_SL1%TKE_F(JROF,JLEV)+YDVARS%TKE%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%TKE(JROF,JLEV)=YDCPG_SL1%TKE(JROF,JLEV)+YDVARS%TKE%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YTTE%LADV, YDML_GCONF%YGFL%YTTE%LTDIABLIN, &
                                     & YDCPG_SL1%TTE, YDCPG_SL1%TTE_F, YDVARS%TTE%T9)
! IF(YDML_GCONF%YGFL%YTTE%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YTTE%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%TTE(JROF,JLEV)=YDCPG_SL1%TTE(JROF,JLEV)&
!       &+YDCPG_SL1%TTE_F(JROF,JLEV)+YDVARS%TTE%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%TTE(JROF,JLEV)=YDCPG_SL1%TTE(JROF,JLEV)+YDVARS%TTE%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YEFB1%LADV, YDML_GCONF%YGFL%YEFB1%LTDIABLIN, &
                                     & YDCPG_SL1%EFB1, YDCPG_SL1%EFB1_F, YDVARS%EFB1%T9)
! IF(YDML_GCONF%YGFL%YEFB1%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YEFB1%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB1(JROF,JLEV)=YDCPG_SL1%EFB1(JROF,JLEV)&
!       &+YDCPG_SL1%EFB1_F(JROF,JLEV)+YDVARS%EFB1%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB1(JROF,JLEV)=YDCPG_SL1%EFB1(JROF,JLEV)+YDVARS%EFB1%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YEFB2%LADV, YDML_GCONF%YGFL%YEFB2%LTDIABLIN, &
                                     & YDCPG_SL1%EFB2, YDCPG_SL1%EFB2_F, YDVARS%EFB2%T9)
! IF(YDML_GCONF%YGFL%YEFB2%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YEFB2%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB2(JROF,JLEV)=YDCPG_SL1%EFB2(JROF,JLEV)&
!       &+YDCPG_SL1%EFB2_F(JROF,JLEV)+YDVARS%EFB2%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB2(JROF,JLEV)=YDCPG_SL1%EFB2(JROF,JLEV)+YDVARS%EFB2%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YEFB3%LADV, YDML_GCONF%YGFL%YEFB3%LTDIABLIN, &
                                     & YDCPG_SL1%EFB3, YDCPG_SL1%EFB3_F, YDVARS%EFB3%T9)
! IF(YDML_GCONF%YGFL%YEFB3%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YEFB3%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB3(JROF,JLEV)=YDCPG_SL1%EFB3(JROF,JLEV)&
!       &+YDCPG_SL1%EFB3_F(JROF,JLEV)+YDVARS%EFB3%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB3(JROF,JLEV)=YDCPG_SL1%EFB3(JROF,JLEV)+YDVARS%EFB3%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YA%LADV, YDML_GCONF%YGFL%YA%LTDIABLIN, &
                                     & YDCPG_SL1%A, YDCPG_SL1%A_F, YDVARS%A%T9)
! IF(YDML_GCONF%YGFL%YA%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YA%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%A(JROF,JLEV)=YDCPG_SL1%A(JROF,JLEV)&
!       &+YDCPG_SL1%A_F(JROF,JLEV)+YDVARS%A%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%A(JROF,JLEV)=YDCPG_SL1%A(JROF,JLEV)+YDVARS%A%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YO3%LADV, YDML_GCONF%YGFL%YO3%LTDIABLIN, &
                                     & YDCPG_SL1%O3, YDCPG_SL1%O3_F, YDVARS%O3%T9)
! IF(YDML_GCONF%YGFL%YO3%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YO3%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%O3(JROF,JLEV)=YDCPG_SL1%O3(JROF,JLEV)&
!       &+YDCPG_SL1%O3_F(JROF,JLEV)+YDVARS%O3%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%O3(JROF,JLEV)=YDCPG_SL1%O3(JROF,JLEV)+YDVARS%O3%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YSRC%LADV, YDML_GCONF%YGFL%YSRC%LTDIABLIN, &
                                     & YDCPG_SL1%SRC, YDCPG_SL1%SRC_F, YDVARS%SRC%T9)
! IF(YDML_GCONF%YGFL%YSRC%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSRC%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SRC(JROF,JLEV)=YDCPG_SL1%SRC(JROF,JLEV)&
!       &+YDCPG_SL1%SRC_F(JROF,JLEV)+YDVARS%SRC%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SRC(JROF,JLEV)=YDCPG_SL1%SRC(JROF,JLEV)+YDVARS%SRC%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YMXL%LADV, YDML_GCONF%YGFL%YMXL%LTDIABLIN, &
                                     & YDCPG_SL1%MXL, YDCPG_SL1%MXL_F, YDVARS%MXL%T9)
! IF(YDML_GCONF%YGFL%YMXL%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YMXL%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%MXL(JROF,JLEV)=YDCPG_SL1%MXL(JROF,JLEV)&
!       &+YDCPG_SL1%MXL_F(JROF,JLEV)+YDVARS%MXL%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%MXL(JROF,JLEV)=YDCPG_SL1%MXL(JROF,JLEV)+YDVARS%MXL%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YSHTUR%LADV, YDML_GCONF%YGFL%YSHTUR%LTDIABLIN, &
                                     & YDCPG_SL1%SHTUR, YDCPG_SL1%SHTUR_F, YDVARS%SHTUR%T9)
! IF(YDML_GCONF%YGFL%YSHTUR%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSHTUR%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SHTUR(JROF,JLEV)=YDCPG_SL1%SHTUR(JROF,JLEV)&
!       &+YDCPG_SL1%SHTUR_F(JROF,JLEV)+YDVARS%SHTUR%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SHTUR(JROF,JLEV)=YDCPG_SL1%SHTUR(JROF,JLEV)+YDVARS%SHTUR%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YFQTUR%LADV, YDML_GCONF%YGFL%YFQTUR%LTDIABLIN, &
                                     & YDCPG_SL1%FQTUR, YDCPG_SL1%FQTUR_F, YDVARS%FQTUR%T9)
! IF(YDML_GCONF%YGFL%YFQTUR%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YFQTUR%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FQTUR(JROF,JLEV)=YDCPG_SL1%FQTUR(JROF,JLEV)&
!       &+YDCPG_SL1%FQTUR_F(JROF,JLEV)+YDVARS%FQTUR%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FQTUR(JROF,JLEV)=YDCPG_SL1%FQTUR(JROF,JLEV)+YDVARS%FQTUR%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YFSTUR%LADV, YDML_GCONF%YGFL%YFSTUR%LTDIABLIN, &
                                     & YDCPG_SL1%FSTUR, YDCPG_SL1%FSTUR_F, YDVARS%FSTUR%T9)
! IF(YDML_GCONF%YGFL%YFSTUR%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YFSTUR%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FSTUR(JROF,JLEV)=YDCPG_SL1%FSTUR(JROF,JLEV)&
!       &+YDCPG_SL1%FSTUR_F(JROF,JLEV)+YDVARS%FSTUR%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FSTUR(JROF,JLEV)=YDCPG_SL1%FSTUR(JROF,JLEV)+YDVARS%FSTUR%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YCPF%LADV, YDML_GCONF%YGFL%YCPF%LTDIABLIN, &
                                     & YDCPG_SL1%CPF, YDCPG_SL1%CPF_F, YDVARS%CPF%T9)
! IF(YDML_GCONF%YGFL%YCPF%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YCPF%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CPF(JROF,JLEV)=YDCPG_SL1%CPF(JROF,JLEV)&
!       &+YDCPG_SL1%CPF_F(JROF,JLEV)+YDVARS%CPF%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CPF(JROF,JLEV)=YDCPG_SL1%CPF(JROF,JLEV)+YDVARS%CPF%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YSPF%LADV, YDML_GCONF%YGFL%YSPF%LTDIABLIN, &
                                     & YDCPG_SL1%SPF, YDCPG_SL1%SPF_F, YDVARS%SPF%T9)
! IF(YDML_GCONF%YGFL%YSPF%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSPF%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SPF(JROF,JLEV)=YDCPG_SL1%SPF(JROF,JLEV)&
!       &+YDCPG_SL1%SPF_F(JROF,JLEV)+YDVARS%SPF%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SPF(JROF,JLEV)=YDCPG_SL1%SPF(JROF,JLEV)+YDVARS%SPF%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YCVGQ%LADV, YDML_GCONF%YGFL%YCVGQ%LTDIABLIN, &
                                     & YDCPG_SL1%CVGQ, YDCPG_SL1%CVGQ_F, YDVARS%CVGQ%T9)
! IF(YDML_GCONF%YGFL%YCVGQ%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YCVGQ%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CVGQ(JROF,JLEV)=YDCPG_SL1%CVGQ(JROF,JLEV)&
!       &+YDCPG_SL1%CVGQ_F(JROF,JLEV)+YDVARS%CVGQ%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CVGQ(JROF,JLEV)=YDCPG_SL1%CVGQ(JROF,JLEV)+YDVARS%CVGQ%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YQVA%LADV, YDML_GCONF%YGFL%YQVA%LTDIABLIN, &
                                     & YDCPG_SL1%QVA, YDCPG_SL1%QVA_F, YDVARS%QVA%T9)
! IF(YDML_GCONF%YGFL%YQVA%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YQVA%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%QVA(JROF,JLEV)=YDCPG_SL1%QVA(JROF,JLEV)&
!       &+YDCPG_SL1%QVA_F(JROF,JLEV)+YDVARS%QVA%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%QVA(JROF,JLEV)=YDCPG_SL1%QVA(JROF,JLEV)+YDVARS%QVA%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YLRCH4%LADV, YDML_GCONF%YGFL%YLRCH4%LTDIABLIN, &
                                     & YDCPG_SL1%LRCH4, YDCPG_SL1%LRCH4_F, YDVARS%LRCH4%T9)
! IF(YDML_GCONF%YGFL%YLRCH4%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YLRCH4%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LRCH4(JROF,JLEV)=YDCPG_SL1%LRCH4(JROF,JLEV)&
!       &+YDCPG_SL1%LRCH4_F(JROF,JLEV)+YDVARS%LRCH4%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LRCH4(JROF,JLEV)=YDCPG_SL1%LRCH4(JROF,JLEV)+YDVARS%LRCH4%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YPHYCTY%LADV, YDML_GCONF%YGFL%YPHYCTY%LTDIABLIN, &
                                     & YDCPG_SL1%PHYCTY, YDCPG_SL1%PHYCTY_F, YDVARS%PHYCTY%T9)
! IF(YDML_GCONF%YGFL%YPHYCTY%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YPHYCTY%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%PHYCTY(JROF,JLEV)=YDCPG_SL1%PHYCTY(JROF,JLEV)&
!       &+YDCPG_SL1%PHYCTY_F(JROF,JLEV)+YDVARS%PHYCTY%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%PHYCTY(JROF,JLEV)=YDCPG_SL1%PHYCTY(JROF,JLEV)+YDVARS%PHYCTY%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YRSPEC%LADV, YDML_GCONF%YGFL%YRSPEC%LTDIABLIN, &
                                     & YDCPG_SL1%RSPEC, YDCPG_SL1%RSPEC_F, YDVARS%RSPEC%T9)
! IF(YDML_GCONF%YGFL%YRSPEC%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRSPEC%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RSPEC(JROF,JLEV)=YDCPG_SL1%RSPEC(JROF,JLEV)&
!       &+YDCPG_SL1%RSPEC_F(JROF,JLEV)+YDVARS%RSPEC%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RSPEC(JROF,JLEV)=YDCPG_SL1%RSPEC(JROF,JLEV)+YDVARS%RSPEC%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YSDSAT%LADV, YDML_GCONF%YGFL%YSDSAT%LTDIABLIN, &
                                     & YDCPG_SL1%SDSAT, YDCPG_SL1%SDSAT_F, YDVARS%SDSAT%T9)
! IF(YDML_GCONF%YGFL%YSDSAT%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSDSAT%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SDSAT(JROF,JLEV)=YDCPG_SL1%SDSAT(JROF,JLEV)&
!       &+YDCPG_SL1%SDSAT_F(JROF,JLEV)+YDVARS%SDSAT%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SDSAT(JROF,JLEV)=YDCPG_SL1%SDSAT(JROF,JLEV)+YDVARS%SDSAT%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YCVV%LADV, YDML_GCONF%YGFL%YCVV%LTDIABLIN, &
                                     & YDCPG_SL1%CVV, YDCPG_SL1%CVV_F, YDVARS%CVV%T9)
! IF(YDML_GCONF%YGFL%YCVV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YCVV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CVV(JROF,JLEV)=YDCPG_SL1%CVV(JROF,JLEV)&
!       &+YDCPG_SL1%CVV_F(JROF,JLEV)+YDVARS%CVV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CVV(JROF,JLEV)=YDCPG_SL1%CVV(JROF,JLEV)+YDVARS%CVV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YRKTH%LADV, YDML_GCONF%YGFL%YRKTH%LTDIABLIN, &
                                     & YDCPG_SL1%RKTH, YDCPG_SL1%RKTH_F, YDVARS%RKTH%T9)
! IF(YDML_GCONF%YGFL%YRKTH%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRKTH%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTH(JROF,JLEV)=YDCPG_SL1%RKTH(JROF,JLEV)&
!       &+YDCPG_SL1%RKTH_F(JROF,JLEV)+YDVARS%RKTH%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTH(JROF,JLEV)=YDCPG_SL1%RKTH(JROF,JLEV)+YDVARS%RKTH%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YRKTQV%LADV, YDML_GCONF%YGFL%YRKTQV%LTDIABLIN, &
                                     & YDCPG_SL1%RKTQV, YDCPG_SL1%RKTQV_F, YDVARS%RKTQV%T9)
! IF(YDML_GCONF%YGFL%YRKTQV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRKTQV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTQV(JROF,JLEV)=YDCPG_SL1%RKTQV(JROF,JLEV)&
!       &+YDCPG_SL1%RKTQV_F(JROF,JLEV)+YDVARS%RKTQV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTQV(JROF,JLEV)=YDCPG_SL1%RKTQV(JROF,JLEV)+YDVARS%RKTQV%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YRKTQC%LADV, YDML_GCONF%YGFL%YRKTQC%LTDIABLIN, &
                                     & YDCPG_SL1%RKTQC, YDCPG_SL1%RKTQC_F, YDVARS%RKTQC%T9)
! IF(YDML_GCONF%YGFL%YRKTQC%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRKTQC%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTQC(JROF,JLEV)=YDCPG_SL1%RKTQC(JROF,JLEV)&
!       &+YDCPG_SL1%RKTQC_F(JROF,JLEV)+YDVARS%RKTQC%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTQC(JROF,JLEV)=YDCPG_SL1%RKTQC(JROF,JLEV)+YDVARS%RKTQC%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YUOM%LADV, YDML_GCONF%YGFL%YUOM%LTDIABLIN, &
                                     & YDCPG_SL1%UOM, YDCPG_SL1%UOM_F, YDVARS%UOM%T9)
! IF(YDML_GCONF%YGFL%YUOM%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YUOM%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UOM(JROF,JLEV)=YDCPG_SL1%UOM(JROF,JLEV)&
!       &+YDCPG_SL1%UOM_F(JROF,JLEV)+YDVARS%UOM%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UOM(JROF,JLEV)=YDCPG_SL1%UOM(JROF,JLEV)+YDVARS%UOM%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YUAL%LADV, YDML_GCONF%YGFL%YUAL%LTDIABLIN, &
                                     & YDCPG_SL1%UAL, YDCPG_SL1%UAL_F, YDVARS%UAL%T9)
! IF(YDML_GCONF%YGFL%YUAL%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YUAL%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UAL(JROF,JLEV)=YDCPG_SL1%UAL(JROF,JLEV)&
!       &+YDCPG_SL1%UAL_F(JROF,JLEV)+YDVARS%UAL%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UAL(JROF,JLEV)=YDCPG_SL1%UAL(JROF,JLEV)+YDVARS%UAL%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YDOM%LADV, YDML_GCONF%YGFL%YDOM%LTDIABLIN, &
                                     & YDCPG_SL1%DOM, YDCPG_SL1%DOM_F, YDVARS%DOM%T9)
! IF(YDML_GCONF%YGFL%YDOM%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YDOM%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%DOM(JROF,JLEV)=YDCPG_SL1%DOM(JROF,JLEV)&
!       &+YDCPG_SL1%DOM_F(JROF,JLEV)+YDVARS%DOM%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%DOM(JROF,JLEV)=YDCPG_SL1%DOM(JROF,JLEV)+YDVARS%DOM%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YDAL%LADV, YDML_GCONF%YGFL%YDAL%LTDIABLIN, &
                                     & YDCPG_SL1%DAL, YDCPG_SL1%DAL_F, YDVARS%DAL%T9)
! IF(YDML_GCONF%YGFL%YDAL%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YDAL%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%DAL(JROF,JLEV)=YDCPG_SL1%DAL(JROF,JLEV)&
!       &+YDCPG_SL1%DAL_F(JROF,JLEV)+YDVARS%DAL%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%DAL(JROF,JLEV)=YDCPG_SL1%DAL(JROF,JLEV)+YDVARS%DAL%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YUEN%LADV, YDML_GCONF%YGFL%YUEN%LTDIABLIN, &
                                     & YDCPG_SL1%UEN, YDCPG_SL1%UEN_F, YDVARS%UEN%T9)
! IF(YDML_GCONF%YGFL%YUEN%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YUEN%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UEN(JROF,JLEV)=YDCPG_SL1%UEN(JROF,JLEV)&
!       &+YDCPG_SL1%UEN_F(JROF,JLEV)+YDVARS%UEN%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UEN(JROF,JLEV)=YDCPG_SL1%UEN(JROF,JLEV)+YDVARS%UEN%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YUNEBH%LADV, YDML_GCONF%YGFL%YUNEBH%LTDIABLIN, &
                                     & YDCPG_SL1%UNEBH, YDCPG_SL1%UNEBH_F, YDVARS%UNEBH%T9)
! IF(YDML_GCONF%YGFL%YUNEBH%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YUNEBH%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UNEBH(JROF,JLEV)=YDCPG_SL1%UNEBH(JROF,JLEV)&
!       &+YDCPG_SL1%UNEBH_F(JROF,JLEV)+YDVARS%UNEBH%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UNEBH(JROF,JLEV)=YDCPG_SL1%UNEBH(JROF,JLEV)+YDVARS%UNEBH%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (YDML_GCONF%YGFL%YFSD%LADV, YDML_GCONF%YGFL%YFSD%LTDIABLIN, &
                                     & YDCPG_SL1%FSD, YDCPG_SL1%FSD_F, YDVARS%FSD%T9)
! IF(YDML_GCONF%YGFL%YFSD%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YFSD%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FSD(JROF,JLEV)=YDCPG_SL1%FSD(JROF,JLEV)&
!       &+YDCPG_SL1%FSD_F(JROF,JLEV)+YDVARS%FSD%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FSD(JROF,JLEV)=YDCPG_SL1%FSD(JROF,JLEV)+YDVARS%FSD%T9(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF

ELSEIF (.NOT.LDCT) THEN

  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YQ%LADV, YDML_GCONF%YGFL%YQ%LTDIABLIN, &
                              & YDCPG_SL1%Q, YDCPG_SL1%Q_F, YDVARS%Q%T0)
! IF(YDML_GCONF%YGFL%YQ%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YQ%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%Q(JROF,JLEV)=YDCPG_SL1%Q(JROF,JLEV)&
!       &+YDCPG_SL1%Q_F(JROF,JLEV)+YDVARS%Q%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%Q(JROF,JLEV)=YDCPG_SL1%Q(JROF,JLEV)+YDVARS%Q%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YI%LADV, YDML_GCONF%YGFL%YI%LTDIABLIN, &
                              & YDCPG_SL1%I, YDCPG_SL1%I_F, YDVARS%I%T0)
! IF(YDML_GCONF%YGFL%YI%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YI%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%I(JROF,JLEV)=YDCPG_SL1%I(JROF,JLEV)&
!       &+YDCPG_SL1%I_F(JROF,JLEV)+YDVARS%I%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%I(JROF,JLEV)=YDCPG_SL1%I(JROF,JLEV)+YDVARS%I%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YL%LADV, YDML_GCONF%YGFL%YL%LTDIABLIN, &
                              & YDCPG_SL1%L, YDCPG_SL1%L_F, YDVARS%L%T0)
! IF(YDML_GCONF%YGFL%YL%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YL%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%L(JROF,JLEV)=YDCPG_SL1%L(JROF,JLEV)&
!       &+YDCPG_SL1%L_F(JROF,JLEV)+YDVARS%L%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%L(JROF,JLEV)=YDCPG_SL1%L(JROF,JLEV)+YDVARS%L%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YLCONV%LADV, YDML_GCONF%YGFL%YLCONV%LTDIABLIN, &
                              & YDCPG_SL1%LCONV, YDCPG_SL1%LCONV_F, YDVARS%LCONV%T0)
! IF(YDML_GCONF%YGFL%YLCONV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YLCONV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LCONV(JROF,JLEV)=YDCPG_SL1%LCONV(JROF,JLEV)&
!       &+YDCPG_SL1%LCONV_F(JROF,JLEV)+YDVARS%LCONV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LCONV(JROF,JLEV)=YDCPG_SL1%LCONV(JROF,JLEV)+YDVARS%LCONV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YICONV%LADV, YDML_GCONF%YGFL%YICONV%LTDIABLIN, &
                              & YDCPG_SL1%ICONV, YDCPG_SL1%ICONV_F, YDVARS%ICONV%T0)
! IF(YDML_GCONF%YGFL%YICONV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YICONV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%ICONV(JROF,JLEV)=YDCPG_SL1%ICONV(JROF,JLEV)&
!       &+YDCPG_SL1%ICONV_F(JROF,JLEV)+YDVARS%ICONV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%ICONV(JROF,JLEV)=YDCPG_SL1%ICONV(JROF,JLEV)+YDVARS%ICONV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YRCONV%LADV, YDML_GCONF%YGFL%YRCONV%LTDIABLIN, &
                              & YDCPG_SL1%RCONV, YDCPG_SL1%RCONV_F, YDVARS%RCONV%T0)
! IF(YDML_GCONF%YGFL%YRCONV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRCONV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RCONV(JROF,JLEV)=YDCPG_SL1%RCONV(JROF,JLEV)&
!       &+YDCPG_SL1%RCONV_F(JROF,JLEV)+YDVARS%RCONV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RCONV(JROF,JLEV)=YDCPG_SL1%RCONV(JROF,JLEV)+YDVARS%RCONV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YSCONV%LADV, YDML_GCONF%YGFL%YSCONV%LTDIABLIN, &
                              & YDCPG_SL1%SCONV, YDCPG_SL1%SCONV_F, YDVARS%SCONV%T0)
! IF(YDML_GCONF%YGFL%YSCONV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSCONV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SCONV(JROF,JLEV)=YDCPG_SL1%SCONV(JROF,JLEV)&
!       &+YDCPG_SL1%SCONV_F(JROF,JLEV)+YDVARS%SCONV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SCONV(JROF,JLEV)=YDCPG_SL1%SCONV(JROF,JLEV)+YDVARS%SCONV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YIRAD%LADV, YDML_GCONF%YGFL%YIRAD%LTDIABLIN, &
                              & YDCPG_SL1%IRAD, YDCPG_SL1%IRAD_F, YDVARS%IRAD%T0)
! IF(YDML_GCONF%YGFL%YIRAD%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YIRAD%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%IRAD(JROF,JLEV)=YDCPG_SL1%IRAD(JROF,JLEV)&
!       &+YDCPG_SL1%IRAD_F(JROF,JLEV)+YDVARS%IRAD%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%IRAD(JROF,JLEV)=YDCPG_SL1%IRAD(JROF,JLEV)+YDVARS%IRAD%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YLRAD%LADV, YDML_GCONF%YGFL%YLRAD%LTDIABLIN, &
                              & YDCPG_SL1%LRAD, YDCPG_SL1%LRAD_F, YDVARS%LRAD%T0)
! IF(YDML_GCONF%YGFL%YLRAD%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YLRAD%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LRAD(JROF,JLEV)=YDCPG_SL1%LRAD(JROF,JLEV)&
!       &+YDCPG_SL1%LRAD_F(JROF,JLEV)+YDVARS%LRAD%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LRAD(JROF,JLEV)=YDCPG_SL1%LRAD(JROF,JLEV)+YDVARS%LRAD%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YS%LADV, YDML_GCONF%YGFL%YS%LTDIABLIN, &
                              & YDCPG_SL1%S, YDCPG_SL1%S_F, YDVARS%S%T0)
! IF(YDML_GCONF%YGFL%YS%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YS%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%S(JROF,JLEV)=YDCPG_SL1%S(JROF,JLEV)&
!       &+YDCPG_SL1%S_F(JROF,JLEV)+YDVARS%S%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%S(JROF,JLEV)=YDCPG_SL1%S(JROF,JLEV)+YDVARS%S%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YR%LADV, YDML_GCONF%YGFL%YR%LTDIABLIN, &
                              & YDCPG_SL1%R, YDCPG_SL1%R_F, YDVARS%R%T0)
! IF(YDML_GCONF%YGFL%YR%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YR%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%R(JROF,JLEV)=YDCPG_SL1%R(JROF,JLEV)&
!       &+YDCPG_SL1%R_F(JROF,JLEV)+YDVARS%R%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%R(JROF,JLEV)=YDCPG_SL1%R(JROF,JLEV)+YDVARS%R%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YG%LADV, YDML_GCONF%YGFL%YG%LTDIABLIN, &
                              & YDCPG_SL1%G, YDCPG_SL1%G_F, YDVARS%G%T0)
! IF(YDML_GCONF%YGFL%YG%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YG%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%G(JROF,JLEV)=YDCPG_SL1%G(JROF,JLEV)&
!       &+YDCPG_SL1%G_F(JROF,JLEV)+YDVARS%G%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%G(JROF,JLEV)=YDCPG_SL1%G(JROF,JLEV)+YDVARS%G%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YH%LADV, YDML_GCONF%YGFL%YH%LTDIABLIN, &
                              & YDCPG_SL1%H, YDCPG_SL1%H_F, YDVARS%H%T0)
! IF(YDML_GCONF%YGFL%YH%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YH%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%H(JROF,JLEV)=YDCPG_SL1%H(JROF,JLEV)&
!       &+YDCPG_SL1%H_F(JROF,JLEV)+YDVARS%H%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%H(JROF,JLEV)=YDCPG_SL1%H(JROF,JLEV)+YDVARS%H%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YTKE%LADV, YDML_GCONF%YGFL%YTKE%LTDIABLIN, &
                              & YDCPG_SL1%TKE, YDCPG_SL1%TKE_F, YDVARS%TKE%T0)
! IF(YDML_GCONF%YGFL%YTKE%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YTKE%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%TKE(JROF,JLEV)=YDCPG_SL1%TKE(JROF,JLEV)&
!       &+YDCPG_SL1%TKE_F(JROF,JLEV)+YDVARS%TKE%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%TKE(JROF,JLEV)=YDCPG_SL1%TKE(JROF,JLEV)+YDVARS%TKE%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YTTE%LADV, YDML_GCONF%YGFL%YTTE%LTDIABLIN, &
                              & YDCPG_SL1%TTE, YDCPG_SL1%TTE_F, YDVARS%TTE%T0)
! IF(YDML_GCONF%YGFL%YTTE%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YTTE%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%TTE(JROF,JLEV)=YDCPG_SL1%TTE(JROF,JLEV)&
!       &+YDCPG_SL1%TTE_F(JROF,JLEV)+YDVARS%TTE%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%TTE(JROF,JLEV)=YDCPG_SL1%TTE(JROF,JLEV)+YDVARS%TTE%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YEFB1%LADV, YDML_GCONF%YGFL%YEFB1%LTDIABLIN, &
                              & YDCPG_SL1%EFB1, YDCPG_SL1%EFB1_F, YDVARS%EFB1%T0)
! IF(YDML_GCONF%YGFL%YEFB1%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YEFB1%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB1(JROF,JLEV)=YDCPG_SL1%EFB1(JROF,JLEV)&
!       &+YDCPG_SL1%EFB1_F(JROF,JLEV)+YDVARS%EFB1%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB1(JROF,JLEV)=YDCPG_SL1%EFB1(JROF,JLEV)+YDVARS%EFB1%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YEFB2%LADV, YDML_GCONF%YGFL%YEFB2%LTDIABLIN, &
                              & YDCPG_SL1%EFB2, YDCPG_SL1%EFB2_F, YDVARS%EFB2%T0)
! IF(YDML_GCONF%YGFL%YEFB2%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YEFB2%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB2(JROF,JLEV)=YDCPG_SL1%EFB2(JROF,JLEV)&
!       &+YDCPG_SL1%EFB2_F(JROF,JLEV)+YDVARS%EFB2%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB2(JROF,JLEV)=YDCPG_SL1%EFB2(JROF,JLEV)+YDVARS%EFB2%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YEFB3%LADV, YDML_GCONF%YGFL%YEFB3%LTDIABLIN, &
                              & YDCPG_SL1%EFB3, YDCPG_SL1%EFB3_F, YDVARS%EFB3%T0)
! IF(YDML_GCONF%YGFL%YEFB3%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YEFB3%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB3(JROF,JLEV)=YDCPG_SL1%EFB3(JROF,JLEV)&
!       &+YDCPG_SL1%EFB3_F(JROF,JLEV)+YDVARS%EFB3%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%EFB3(JROF,JLEV)=YDCPG_SL1%EFB3(JROF,JLEV)+YDVARS%EFB3%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YA%LADV, YDML_GCONF%YGFL%YA%LTDIABLIN, &
                              & YDCPG_SL1%A, YDCPG_SL1%A_F, YDVARS%A%T0)
! IF(YDML_GCONF%YGFL%YA%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YA%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%A(JROF,JLEV)=YDCPG_SL1%A(JROF,JLEV)&
!       &+YDCPG_SL1%A_F(JROF,JLEV)+YDVARS%A%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%A(JROF,JLEV)=YDCPG_SL1%A(JROF,JLEV)+YDVARS%A%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YO3%LADV, YDML_GCONF%YGFL%YO3%LTDIABLIN, &
                              & YDCPG_SL1%O3, YDCPG_SL1%O3_F, YDVARS%O3%T0)
! IF(YDML_GCONF%YGFL%YO3%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YO3%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%O3(JROF,JLEV)=YDCPG_SL1%O3(JROF,JLEV)&
!       &+YDCPG_SL1%O3_F(JROF,JLEV)+YDVARS%O3%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%O3(JROF,JLEV)=YDCPG_SL1%O3(JROF,JLEV)+YDVARS%O3%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YSRC%LADV, YDML_GCONF%YGFL%YSRC%LTDIABLIN, &
                              & YDCPG_SL1%SRC, YDCPG_SL1%SRC_F, YDVARS%SRC%T0)
! IF(YDML_GCONF%YGFL%YSRC%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSRC%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SRC(JROF,JLEV)=YDCPG_SL1%SRC(JROF,JLEV)&
!       &+YDCPG_SL1%SRC_F(JROF,JLEV)+YDVARS%SRC%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SRC(JROF,JLEV)=YDCPG_SL1%SRC(JROF,JLEV)+YDVARS%SRC%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YMXL%LADV, YDML_GCONF%YGFL%YMXL%LTDIABLIN, &
                              & YDCPG_SL1%MXL, YDCPG_SL1%MXL_F, YDVARS%MXL%T0)
! IF(YDML_GCONF%YGFL%YMXL%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YMXL%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%MXL(JROF,JLEV)=YDCPG_SL1%MXL(JROF,JLEV)&
!       &+YDCPG_SL1%MXL_F(JROF,JLEV)+YDVARS%MXL%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%MXL(JROF,JLEV)=YDCPG_SL1%MXL(JROF,JLEV)+YDVARS%MXL%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YSHTUR%LADV, YDML_GCONF%YGFL%YSHTUR%LTDIABLIN, &
                              & YDCPG_SL1%SHTUR, YDCPG_SL1%SHTUR_F, YDVARS%SHTUR%T0)
! IF(YDML_GCONF%YGFL%YSHTUR%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSHTUR%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SHTUR(JROF,JLEV)=YDCPG_SL1%SHTUR(JROF,JLEV)&
!       &+YDCPG_SL1%SHTUR_F(JROF,JLEV)+YDVARS%SHTUR%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SHTUR(JROF,JLEV)=YDCPG_SL1%SHTUR(JROF,JLEV)+YDVARS%SHTUR%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YFQTUR%LADV, YDML_GCONF%YGFL%YFQTUR%LTDIABLIN, &
                              & YDCPG_SL1%FQTUR, YDCPG_SL1%FQTUR_F, YDVARS%FQTUR%T0)
! IF(YDML_GCONF%YGFL%YFQTUR%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YFQTUR%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FQTUR(JROF,JLEV)=YDCPG_SL1%FQTUR(JROF,JLEV)&
!       &+YDCPG_SL1%FQTUR_F(JROF,JLEV)+YDVARS%FQTUR%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FQTUR(JROF,JLEV)=YDCPG_SL1%FQTUR(JROF,JLEV)+YDVARS%FQTUR%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YFSTUR%LADV, YDML_GCONF%YGFL%YFSTUR%LTDIABLIN, &
                              & YDCPG_SL1%FSTUR, YDCPG_SL1%FSTUR_F, YDVARS%FSTUR%T0)
! IF(YDML_GCONF%YGFL%YFSTUR%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YFSTUR%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FSTUR(JROF,JLEV)=YDCPG_SL1%FSTUR(JROF,JLEV)&
!       &+YDCPG_SL1%FSTUR_F(JROF,JLEV)+YDVARS%FSTUR%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FSTUR(JROF,JLEV)=YDCPG_SL1%FSTUR(JROF,JLEV)+YDVARS%FSTUR%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YCPF%LADV, YDML_GCONF%YGFL%YCPF%LTDIABLIN, &
                              & YDCPG_SL1%CPF, YDCPG_SL1%CPF_F, YDVARS%CPF%T0)
! IF(YDML_GCONF%YGFL%YCPF%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YCPF%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CPF(JROF,JLEV)=YDCPG_SL1%CPF(JROF,JLEV)&
!       &+YDCPG_SL1%CPF_F(JROF,JLEV)+YDVARS%CPF%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CPF(JROF,JLEV)=YDCPG_SL1%CPF(JROF,JLEV)+YDVARS%CPF%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YSPF%LADV, YDML_GCONF%YGFL%YSPF%LTDIABLIN, &
                              & YDCPG_SL1%SPF, YDCPG_SL1%SPF_F, YDVARS%SPF%T0)
! IF(YDML_GCONF%YGFL%YSPF%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSPF%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SPF(JROF,JLEV)=YDCPG_SL1%SPF(JROF,JLEV)&
!       &+YDCPG_SL1%SPF_F(JROF,JLEV)+YDVARS%SPF%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SPF(JROF,JLEV)=YDCPG_SL1%SPF(JROF,JLEV)+YDVARS%SPF%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YCVGQ%LADV, YDML_GCONF%YGFL%YCVGQ%LTDIABLIN, &
                              & YDCPG_SL1%CVGQ, YDCPG_SL1%CVGQ_F, YDVARS%CVGQ%T0)
! IF(YDML_GCONF%YGFL%YCVGQ%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YCVGQ%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CVGQ(JROF,JLEV)=YDCPG_SL1%CVGQ(JROF,JLEV)&
!       &+YDCPG_SL1%CVGQ_F(JROF,JLEV)+YDVARS%CVGQ%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CVGQ(JROF,JLEV)=YDCPG_SL1%CVGQ(JROF,JLEV)+YDVARS%CVGQ%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YQVA%LADV, YDML_GCONF%YGFL%YQVA%LTDIABLIN, &
                              & YDCPG_SL1%QVA, YDCPG_SL1%QVA_F, YDVARS%QVA%T0)
! IF(YDML_GCONF%YGFL%YQVA%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YQVA%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%QVA(JROF,JLEV)=YDCPG_SL1%QVA(JROF,JLEV)&
!       &+YDCPG_SL1%QVA_F(JROF,JLEV)+YDVARS%QVA%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%QVA(JROF,JLEV)=YDCPG_SL1%QVA(JROF,JLEV)+YDVARS%QVA%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YLRCH4%LADV, YDML_GCONF%YGFL%YLRCH4%LTDIABLIN, &
                              & YDCPG_SL1%LRCH4, YDCPG_SL1%LRCH4_F, YDVARS%LRCH4%T0)
! IF(YDML_GCONF%YGFL%YLRCH4%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YLRCH4%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LRCH4(JROF,JLEV)=YDCPG_SL1%LRCH4(JROF,JLEV)&
!       &+YDCPG_SL1%LRCH4_F(JROF,JLEV)+YDVARS%LRCH4%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%LRCH4(JROF,JLEV)=YDCPG_SL1%LRCH4(JROF,JLEV)+YDVARS%LRCH4%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YPHYCTY%LADV, YDML_GCONF%YGFL%YPHYCTY%LTDIABLIN, &
                              & YDCPG_SL1%PHYCTY, YDCPG_SL1%PHYCTY_F, YDVARS%PHYCTY%T0)
! IF(YDML_GCONF%YGFL%YPHYCTY%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YPHYCTY%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%PHYCTY(JROF,JLEV)=YDCPG_SL1%PHYCTY(JROF,JLEV)&
!       &+YDCPG_SL1%PHYCTY_F(JROF,JLEV)+YDVARS%PHYCTY%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%PHYCTY(JROF,JLEV)=YDCPG_SL1%PHYCTY(JROF,JLEV)+YDVARS%PHYCTY%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YRSPEC%LADV, YDML_GCONF%YGFL%YRSPEC%LTDIABLIN, &
                              & YDCPG_SL1%RSPEC, YDCPG_SL1%RSPEC_F, YDVARS%RSPEC%T0)
! IF(YDML_GCONF%YGFL%YRSPEC%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRSPEC%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RSPEC(JROF,JLEV)=YDCPG_SL1%RSPEC(JROF,JLEV)&
!       &+YDCPG_SL1%RSPEC_F(JROF,JLEV)+YDVARS%RSPEC%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RSPEC(JROF,JLEV)=YDCPG_SL1%RSPEC(JROF,JLEV)+YDVARS%RSPEC%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YSDSAT%LADV, YDML_GCONF%YGFL%YSDSAT%LTDIABLIN, &
                              & YDCPG_SL1%SDSAT, YDCPG_SL1%SDSAT_F, YDVARS%SDSAT%T0)
! IF(YDML_GCONF%YGFL%YSDSAT%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YSDSAT%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SDSAT(JROF,JLEV)=YDCPG_SL1%SDSAT(JROF,JLEV)&
!       &+YDCPG_SL1%SDSAT_F(JROF,JLEV)+YDVARS%SDSAT%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%SDSAT(JROF,JLEV)=YDCPG_SL1%SDSAT(JROF,JLEV)+YDVARS%SDSAT%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YCVV%LADV, YDML_GCONF%YGFL%YCVV%LTDIABLIN, &
                              & YDCPG_SL1%CVV, YDCPG_SL1%CVV_F, YDVARS%CVV%T0)
! IF(YDML_GCONF%YGFL%YCVV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YCVV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CVV(JROF,JLEV)=YDCPG_SL1%CVV(JROF,JLEV)&
!       &+YDCPG_SL1%CVV_F(JROF,JLEV)+YDVARS%CVV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%CVV(JROF,JLEV)=YDCPG_SL1%CVV(JROF,JLEV)+YDVARS%CVV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YRKTH%LADV, YDML_GCONF%YGFL%YRKTH%LTDIABLIN, &
                              & YDCPG_SL1%RKTH, YDCPG_SL1%RKTH_F, YDVARS%RKTH%T0)
! IF(YDML_GCONF%YGFL%YRKTH%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRKTH%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTH(JROF,JLEV)=YDCPG_SL1%RKTH(JROF,JLEV)&
!       &+YDCPG_SL1%RKTH_F(JROF,JLEV)+YDVARS%RKTH%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTH(JROF,JLEV)=YDCPG_SL1%RKTH(JROF,JLEV)+YDVARS%RKTH%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YRKTQV%LADV, YDML_GCONF%YGFL%YRKTQV%LTDIABLIN, &
                              & YDCPG_SL1%RKTQV, YDCPG_SL1%RKTQV_F, YDVARS%RKTQV%T0)
! IF(YDML_GCONF%YGFL%YRKTQV%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRKTQV%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTQV(JROF,JLEV)=YDCPG_SL1%RKTQV(JROF,JLEV)&
!       &+YDCPG_SL1%RKTQV_F(JROF,JLEV)+YDVARS%RKTQV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTQV(JROF,JLEV)=YDCPG_SL1%RKTQV(JROF,JLEV)+YDVARS%RKTQV%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YRKTQC%LADV, YDML_GCONF%YGFL%YRKTQC%LTDIABLIN, &
                              & YDCPG_SL1%RKTQC, YDCPG_SL1%RKTQC_F, YDVARS%RKTQC%T0)
! IF(YDML_GCONF%YGFL%YRKTQC%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YRKTQC%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTQC(JROF,JLEV)=YDCPG_SL1%RKTQC(JROF,JLEV)&
!       &+YDCPG_SL1%RKTQC_F(JROF,JLEV)+YDVARS%RKTQC%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%RKTQC(JROF,JLEV)=YDCPG_SL1%RKTQC(JROF,JLEV)+YDVARS%RKTQC%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YUOM%LADV, YDML_GCONF%YGFL%YUOM%LTDIABLIN, &
                              & YDCPG_SL1%UOM, YDCPG_SL1%UOM_F, YDVARS%UOM%T0)
! IF(YDML_GCONF%YGFL%YUOM%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YUOM%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UOM(JROF,JLEV)=YDCPG_SL1%UOM(JROF,JLEV)&
!       &+YDCPG_SL1%UOM_F(JROF,JLEV)+YDVARS%UOM%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UOM(JROF,JLEV)=YDCPG_SL1%UOM(JROF,JLEV)+YDVARS%UOM%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YUAL%LADV, YDML_GCONF%YGFL%YUAL%LTDIABLIN, &
                              & YDCPG_SL1%UAL, YDCPG_SL1%UAL_F, YDVARS%UAL%T0)
! IF(YDML_GCONF%YGFL%YUAL%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YUAL%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UAL(JROF,JLEV)=YDCPG_SL1%UAL(JROF,JLEV)&
!       &+YDCPG_SL1%UAL_F(JROF,JLEV)+YDVARS%UAL%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UAL(JROF,JLEV)=YDCPG_SL1%UAL(JROF,JLEV)+YDVARS%UAL%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YDOM%LADV, YDML_GCONF%YGFL%YDOM%LTDIABLIN, &
                              & YDCPG_SL1%DOM, YDCPG_SL1%DOM_F, YDVARS%DOM%T0)
! IF(YDML_GCONF%YGFL%YDOM%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YDOM%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%DOM(JROF,JLEV)=YDCPG_SL1%DOM(JROF,JLEV)&
!       &+YDCPG_SL1%DOM_F(JROF,JLEV)+YDVARS%DOM%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%DOM(JROF,JLEV)=YDCPG_SL1%DOM(JROF,JLEV)+YDVARS%DOM%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YDAL%LADV, YDML_GCONF%YGFL%YDAL%LTDIABLIN, &
                              & YDCPG_SL1%DAL, YDCPG_SL1%DAL_F, YDVARS%DAL%T0)
! IF(YDML_GCONF%YGFL%YDAL%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YDAL%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%DAL(JROF,JLEV)=YDCPG_SL1%DAL(JROF,JLEV)&
!       &+YDCPG_SL1%DAL_F(JROF,JLEV)+YDVARS%DAL%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%DAL(JROF,JLEV)=YDCPG_SL1%DAL(JROF,JLEV)+YDVARS%DAL%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YUEN%LADV, YDML_GCONF%YGFL%YUEN%LTDIABLIN, &
                              & YDCPG_SL1%UEN, YDCPG_SL1%UEN_F, YDVARS%UEN%T0)
! IF(YDML_GCONF%YGFL%YUEN%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YUEN%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UEN(JROF,JLEV)=YDCPG_SL1%UEN(JROF,JLEV)&
!       &+YDCPG_SL1%UEN_F(JROF,JLEV)+YDVARS%UEN%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UEN(JROF,JLEV)=YDCPG_SL1%UEN(JROF,JLEV)+YDVARS%UEN%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YUNEBH%LADV, YDML_GCONF%YGFL%YUNEBH%LTDIABLIN, &
                              & YDCPG_SL1%UNEBH, YDCPG_SL1%UNEBH_F, YDVARS%UNEBH%T0)
! IF(YDML_GCONF%YGFL%YUNEBH%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YUNEBH%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UNEBH(JROF,JLEV)=YDCPG_SL1%UNEBH(JROF,JLEV)&
!       &+YDCPG_SL1%UNEBH_F(JROF,JLEV)+YDVARS%UNEBH%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%UNEBH(JROF,JLEV)=YDCPG_SL1%UNEBH(JROF,JLEV)+YDVARS%UNEBH%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF
  CALL LATTEX_EXPL_2TL_V_DCT_F (YDML_GCONF%YGFL%YFSD%LADV, YDML_GCONF%YGFL%YFSD%LTDIABLIN, &
                              & YDCPG_SL1%FSD, YDCPG_SL1%FSD_F, YDVARS%FSD%T0)
! IF(YDML_GCONF%YGFL%YFSD%LADV) THEN
!   LLTDIABLIN=YDML_GCONF%YGFL%YFSD%LTDIABLIN
!   IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FSD(JROF,JLEV)=YDCPG_SL1%FSD(JROF,JLEV)&
!       &+YDCPG_SL1%FSD_F(JROF,JLEV)+YDVARS%FSD%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ELSE
!     DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
!       DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
!         YDCPG_SL1%FSD(JROF,JLEV)=YDCPG_SL1%FSD(JROF,JLEV)+YDVARS%FSD%T0(JROF,JLEV)
!       ENDDO
!     ENDDO
!   ENDIF
! ENDIF

ENDIF


!  Qv in YCVGQ for computation of SL Moisture Convergence for French physics

IF (YDML_GCONF%YGFL%YCVGQ%LGP .AND. (.NOT.LDCTC)) THEN  
  LLTDIABLIN=YDML_GCONF%YGFL%YCVGQ%LTDIABLIN
  IF ((YDML_DYN%YRDYN%NSPLTHOI /= 0).OR.LLTDIABLIN) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%CVGQ_F(JROF,JLEV)=YDCPG_SL1%Q_F(JROF,JLEV)
      ENDDO
    ENDDO
  ENDIF
  DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
    DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
      YDCPG_SL1%CVGQ(JROF,JLEV)=YDCPG_SL1%Q(JROF,JLEV)
    ENDDO
  ENDDO
  LLTDIABLIN=YDML_GCONF%YGFL%YCVGQ%LTDIABLIN.AND.YDML_GCONF%YGFL%YQ%LTDIABLIN
  IF ((YDML_DYN%YRDYN%NSPLTHOI == 0).AND.LLTDIABLIN) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        YDCPG_SL1%CVGQ(JROF,JLEV)=YDCPG_SL1%CVGQ(JROF,JLEV)+YDCPG_SL1%Q_F(JROF,JLEV)
      ENDDO
    ENDDO
  ENDIF
ENDIF   

IF (LHOOK) CALL DR_HOOK('LATTEX_EXPL_2TL',1,ZHOOK_HANDLE)

CONTAINS 

SUBROUTINE LATTEX_EXPL_2TL_V_DCT_T_DCTC_F (LDADV, LDTDIABLIN, PSL1, PSL1_F, PT9)

LOGICAL         , INTENT (IN)    :: LDADV
LOGICAL         , INTENT (IN)    :: LDTDIABLIN
REAL (KIND=JPRB), INTENT (INOUT) :: PSL1   (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB), INTENT (IN)    :: PSL1_F (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB), INTENT (IN)    :: PT9    (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)

IF (LDADV) THEN
  LLTDIABLIN = LDTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        PSL1(JROF,JLEV)=PSL1(JROF,JLEV)+PSL1_F(JROF,JLEV)+PT9(JROF,JLEV)
      ENDDO
    ENDDO
  ELSE
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        PSL1(JROF,JLEV)=PSL1(JROF,JLEV)+PT9(JROF,JLEV)
      ENDDO
    ENDDO
  ENDIF
ENDIF

END SUBROUTINE LATTEX_EXPL_2TL_V_DCT_T_DCTC_F

SUBROUTINE LATTEX_EXPL_2TL_V_DCT_F (LDADV, LDTDIABLIN, PSL1, PSL1_F, PT0)

LOGICAL         , INTENT (IN)    :: LDADV
LOGICAL         , INTENT (IN)    :: LDTDIABLIN
REAL (KIND=JPRB), INTENT (INOUT) :: PSL1   (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB), INTENT (IN)    :: PSL1_F (YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL (KIND=JPRB), INTENT (IN)    :: PT0    (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)

IF (LDADV) THEN
  LLTDIABLIN = LDTDIABLIN
  IF (YDML_DYN%YRDYN%LSPLTHOIGFL.AND.(YDML_DYN%YRDYN%NSPLTHOI==0).AND.(.NOT.LLTDIABLIN)) THEN
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        PSL1(JROF,JLEV)=PSL1(JROF,JLEV)+PSL1_F(JROF,JLEV)+PT0(JROF,JLEV)
      ENDDO
    ENDDO
  ELSE
    DO JLEV=1,YDGEOMETRY%YRDIMV%NFLEVG
      DO JROF=YDCPG_BNDS%KIDIA,YDCPG_BNDS%KFDIA
        PSL1(JROF,JLEV)=PSL1(JROF,JLEV)+PT0(JROF,JLEV)
      ENDDO
    ENDDO
  ENDIF
ENDIF

END SUBROUTINE LATTEX_EXPL_2TL_V_DCT_F

END SUBROUTINE LATTEX_EXPL_2TL
